
// This file was auto-generated by aiecc.py --aie-generate-hsa

#ifndef MLIR_AIE_QUIET
#define __mlir_aie_verbose(x) x
#else
#define __mlir_aie_verbose(x)
#endif

void invoke_data_movement(hsa_queue_t *q, hsa_agent_t *a, void *buf2, void *buf0) {
	uint64_t wr_idx = 0;
	uint64_t packet_id = 0;
	hsa_agent_dispatch_packet_t pkt;
	wr_idx  = hsa_queue_add_write_index_relaxed(q, 1);
	packet_id  = wr_idx % q->size;
	mlir_aie_packet_nd_memcpy(&pkt, 0 /* herd_id */, 6 /* col */, 0 /* dir */, 0/* channel */, 4 /* Burst length */, 2 /* Memory space */, (uint64_t)buf2 + 0 /* Address */, 256 /* 1d_length */, 1 /* 2d_length */, 0 /* 2d_stride */, 1 /* 3d_length */, 0 /* 3d_stride */ , 1 /* 4d_length */, 0 /* 4d_stride */);
	mlir_aie_queue_dispatch_and_wait(a, q, packet_id, wr_idx, &pkt);

	wr_idx  = hsa_queue_add_write_index_relaxed(q, 1);
	packet_id  = wr_idx % q->size;
	mlir_aie_packet_nd_memcpy(&pkt, 0 /* herd_id */, 6 /* col */, 1 /* dir */, 0/* channel */, 4 /* Burst length */, 2 /* Memory space */, (uint64_t)buf0 + 0 /* Address */, 256 /* 1d_length */, 1 /* 2d_length */, 0 /* 2d_stride */, 1 /* 3d_length */, 0 /* 3d_stride */ , 1 /* 4d_length */, 0 /* 4d_stride */);
	mlir_aie_queue_dispatch_and_wait(a, q, packet_id, wr_idx, &pkt);

}
