//===- test_place_core_groups.mlir ----------------------------*- MLIR -*-===//
//
// Copyright (C) 2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --split-input-file --aie-place-tiles %s | FileCheck %s

// A 4x4 grid of cores. Each logical column c has a MemTile that broadcasts
// to the column's cores and collects one output from each, fed by its own
// shim; MemTile r also broadcasts along logical row r. A core shares two
// flows with its column's MemTile and one with its row's, so the cores of
// a logical column are grouped and placed in one physical column, with the
// MemTile and shim under them. The cores are created row-major here, and
// column-major in the next module: the placement is the same.
// CHECK-LABEL: @core_groups_row_major
module @core_groups_row_major {
  aie.device(npu2) {
    // CHECK-DAG: %[[S0:.*]] = aie.tile(0, 0)
    %s0 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M0:.*]] = aie.tile(0, 1)
    %m0 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S1:.*]] = aie.tile(1, 0)
    %s1 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M1:.*]] = aie.tile(1, 1)
    %m1 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S2:.*]] = aie.tile(2, 0)
    %s2 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M2:.*]] = aie.tile(2, 1)
    %m2 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S3:.*]] = aie.tile(3, 0)
    %s3 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M3:.*]] = aie.tile(3, 1)
    %m3 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[C00:.*]] = aie.tile(0, 2)
    %c00 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C01:.*]] = aie.tile(1, 2)
    %c01 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C02:.*]] = aie.tile(2, 2)
    %c02 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C03:.*]] = aie.tile(3, 2)
    %c03 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C10:.*]] = aie.tile(0, 3)
    %c10 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C11:.*]] = aie.tile(1, 3)
    %c11 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C12:.*]] = aie.tile(2, 3)
    %c12 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C13:.*]] = aie.tile(3, 3)
    %c13 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C20:.*]] = aie.tile(0, 4)
    %c20 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C21:.*]] = aie.tile(1, 4)
    %c21 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C22:.*]] = aie.tile(2, 4)
    %c22 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C23:.*]] = aie.tile(3, 4)
    %c23 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C30:.*]] = aie.tile(0, 5)
    %c30 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C31:.*]] = aie.tile(1, 5)
    %c31 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C32:.*]] = aie.tile(2, 5)
    %c32 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C33:.*]] = aie.tile(3, 5)
    %c33 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: aie.flow(%[[S0]], DMA : 0, %[[M0]], DMA : 4)
    aie.flow(%s0, DMA : 0, %m0, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S1]], DMA : 0, %[[M1]], DMA : 4)
    aie.flow(%s1, DMA : 0, %m1, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S2]], DMA : 0, %[[M2]], DMA : 4)
    aie.flow(%s2, DMA : 0, %m2, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S3]], DMA : 0, %[[M3]], DMA : 4)
    aie.flow(%s3, DMA : 0, %m3, DMA : 4)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C00]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c00, DMA : 0)
    aie.flow(%c00, DMA : 0, %m0, DMA : 0)
    aie.flow(%m0, DMA : 1, %c00, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C01]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c01, DMA : 0)
    aie.flow(%c01, DMA : 0, %m1, DMA : 0)
    aie.flow(%m0, DMA : 1, %c01, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C02]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c02, DMA : 0)
    aie.flow(%c02, DMA : 0, %m2, DMA : 0)
    aie.flow(%m0, DMA : 1, %c02, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C03]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c03, DMA : 0)
    aie.flow(%c03, DMA : 0, %m3, DMA : 0)
    aie.flow(%m0, DMA : 1, %c03, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C10]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c10, DMA : 0)
    aie.flow(%c10, DMA : 0, %m0, DMA : 1)
    aie.flow(%m1, DMA : 1, %c10, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C11]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c11, DMA : 0)
    aie.flow(%c11, DMA : 0, %m1, DMA : 1)
    aie.flow(%m1, DMA : 1, %c11, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C12]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c12, DMA : 0)
    aie.flow(%c12, DMA : 0, %m2, DMA : 1)
    aie.flow(%m1, DMA : 1, %c12, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C13]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c13, DMA : 0)
    aie.flow(%c13, DMA : 0, %m3, DMA : 1)
    aie.flow(%m1, DMA : 1, %c13, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C20]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c20, DMA : 0)
    aie.flow(%c20, DMA : 0, %m0, DMA : 2)
    aie.flow(%m2, DMA : 1, %c20, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C21]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c21, DMA : 0)
    aie.flow(%c21, DMA : 0, %m1, DMA : 2)
    aie.flow(%m2, DMA : 1, %c21, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C22]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c22, DMA : 0)
    aie.flow(%c22, DMA : 0, %m2, DMA : 2)
    aie.flow(%m2, DMA : 1, %c22, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C23]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c23, DMA : 0)
    aie.flow(%c23, DMA : 0, %m3, DMA : 2)
    aie.flow(%m2, DMA : 1, %c23, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C30]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c30, DMA : 0)
    aie.flow(%c30, DMA : 0, %m0, DMA : 3)
    aie.flow(%m3, DMA : 1, %c30, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C31]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c31, DMA : 0)
    aie.flow(%c31, DMA : 0, %m1, DMA : 3)
    aie.flow(%m3, DMA : 1, %c31, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C32]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c32, DMA : 0)
    aie.flow(%c32, DMA : 0, %m2, DMA : 3)
    aie.flow(%m3, DMA : 1, %c32, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C33]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c33, DMA : 0)
    aie.flow(%c33, DMA : 0, %m3, DMA : 3)
    aie.flow(%m3, DMA : 1, %c33, DMA : 1)
    // CHECK-NOT: aie.logical_tile
  }
}

// -----

// CHECK-LABEL: @core_groups_col_major
module @core_groups_col_major {
  aie.device(npu2) {
    // CHECK-DAG: %[[S0:.*]] = aie.tile(0, 0)
    %s0 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M0:.*]] = aie.tile(0, 1)
    %m0 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S1:.*]] = aie.tile(1, 0)
    %s1 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M1:.*]] = aie.tile(1, 1)
    %m1 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S2:.*]] = aie.tile(2, 0)
    %s2 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M2:.*]] = aie.tile(2, 1)
    %m2 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[S3:.*]] = aie.tile(3, 0)
    %s3 = aie.logical_tile<ShimNOCTile>(?, ?)
    // CHECK-DAG: %[[M3:.*]] = aie.tile(3, 1)
    %m3 = aie.logical_tile<MemTile>(?, ?)
    // CHECK-DAG: %[[C00:.*]] = aie.tile(0, 2)
    %c00 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C10:.*]] = aie.tile(0, 3)
    %c10 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C20:.*]] = aie.tile(0, 4)
    %c20 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C30:.*]] = aie.tile(0, 5)
    %c30 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C01:.*]] = aie.tile(1, 2)
    %c01 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C11:.*]] = aie.tile(1, 3)
    %c11 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C21:.*]] = aie.tile(1, 4)
    %c21 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C31:.*]] = aie.tile(1, 5)
    %c31 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C02:.*]] = aie.tile(2, 2)
    %c02 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C12:.*]] = aie.tile(2, 3)
    %c12 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C22:.*]] = aie.tile(2, 4)
    %c22 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C32:.*]] = aie.tile(2, 5)
    %c32 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C03:.*]] = aie.tile(3, 2)
    %c03 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C13:.*]] = aie.tile(3, 3)
    %c13 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C23:.*]] = aie.tile(3, 4)
    %c23 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: %[[C33:.*]] = aie.tile(3, 5)
    %c33 = aie.logical_tile<CoreTile>(?, ?)
    // CHECK-DAG: aie.flow(%[[S0]], DMA : 0, %[[M0]], DMA : 4)
    aie.flow(%s0, DMA : 0, %m0, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S1]], DMA : 0, %[[M1]], DMA : 4)
    aie.flow(%s1, DMA : 0, %m1, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S2]], DMA : 0, %[[M2]], DMA : 4)
    aie.flow(%s2, DMA : 0, %m2, DMA : 4)
    // CHECK-DAG: aie.flow(%[[S3]], DMA : 0, %[[M3]], DMA : 4)
    aie.flow(%s3, DMA : 0, %m3, DMA : 4)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C00]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c00, DMA : 0)
    aie.flow(%c00, DMA : 0, %m0, DMA : 0)
    aie.flow(%m0, DMA : 1, %c00, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C10]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c10, DMA : 0)
    aie.flow(%c10, DMA : 0, %m0, DMA : 1)
    aie.flow(%m1, DMA : 1, %c10, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C20]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c20, DMA : 0)
    aie.flow(%c20, DMA : 0, %m0, DMA : 2)
    aie.flow(%m2, DMA : 1, %c20, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M0]], DMA : 0, %[[C30]], DMA : 0)
    aie.flow(%m0, DMA : 0, %c30, DMA : 0)
    aie.flow(%c30, DMA : 0, %m0, DMA : 3)
    aie.flow(%m3, DMA : 1, %c30, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C01]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c01, DMA : 0)
    aie.flow(%c01, DMA : 0, %m1, DMA : 0)
    aie.flow(%m0, DMA : 1, %c01, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C11]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c11, DMA : 0)
    aie.flow(%c11, DMA : 0, %m1, DMA : 1)
    aie.flow(%m1, DMA : 1, %c11, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C21]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c21, DMA : 0)
    aie.flow(%c21, DMA : 0, %m1, DMA : 2)
    aie.flow(%m2, DMA : 1, %c21, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M1]], DMA : 0, %[[C31]], DMA : 0)
    aie.flow(%m1, DMA : 0, %c31, DMA : 0)
    aie.flow(%c31, DMA : 0, %m1, DMA : 3)
    aie.flow(%m3, DMA : 1, %c31, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C02]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c02, DMA : 0)
    aie.flow(%c02, DMA : 0, %m2, DMA : 0)
    aie.flow(%m0, DMA : 1, %c02, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C12]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c12, DMA : 0)
    aie.flow(%c12, DMA : 0, %m2, DMA : 1)
    aie.flow(%m1, DMA : 1, %c12, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C22]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c22, DMA : 0)
    aie.flow(%c22, DMA : 0, %m2, DMA : 2)
    aie.flow(%m2, DMA : 1, %c22, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M2]], DMA : 0, %[[C32]], DMA : 0)
    aie.flow(%m2, DMA : 0, %c32, DMA : 0)
    aie.flow(%c32, DMA : 0, %m2, DMA : 3)
    aie.flow(%m3, DMA : 1, %c32, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C03]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c03, DMA : 0)
    aie.flow(%c03, DMA : 0, %m3, DMA : 0)
    aie.flow(%m0, DMA : 1, %c03, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C13]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c13, DMA : 0)
    aie.flow(%c13, DMA : 0, %m3, DMA : 1)
    aie.flow(%m1, DMA : 1, %c13, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C23]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c23, DMA : 0)
    aie.flow(%c23, DMA : 0, %m3, DMA : 2)
    aie.flow(%m2, DMA : 1, %c23, DMA : 1)
    // CHECK-DAG: aie.flow(%[[M3]], DMA : 0, %[[C33]], DMA : 0)
    aie.flow(%m3, DMA : 0, %c33, DMA : 0)
    aie.flow(%c33, DMA : 0, %m3, DMA : 3)
    aie.flow(%m3, DMA : 1, %c33, DMA : 1)
    // CHECK-NOT: aie.logical_tile
  }
}
