# _bootstrap.py -*- Python -*-
#
# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""The ping-pong bootstrap park: internal, not part of the public API surface.

Ping-pong needs somewhere for the core to be, other than the resident, while
the *resident's own* granule is being written -- a core that returned to the
resident at address 0 would be executing the very granule being overwritten.
This is mechanically an ordinary overlay (linked at a fixed address against
the resident's symbols) that is written once during setup and never again;
what differs is its lifetime and its handshake, which cannot use the same
hardware-lock `WorkerRuntimeBarrier` the normal, in-resident
`ProgramMemorySlot.wait()` uses, because it is compiled C++ linked in
separately, not part of the core's own Python-emitted MLIR body. It uses the
same plain-buffer poll `test/npu-xrt/program_memory_overlay/stub.cc` already
proves correct on hardware, adapted so the symbol names are internal instead
of test fixtures.
"""

import numpy as np

from ... import ir  # pyright: ignore[reportMissingImports, reportAttributeAccessIssue]
from ...dialects import memref  # pyright: ignore[reportAttributeAccessIssue]
from ...dialects.aie import external_func  # pyright: ignore[reportAttributeAccessIssue]
from ...dialects.aiex import npu_blockwrite  # pyright: ignore[reportAttributeAccessIssue]
from ...dialects.aiex import npu_maskpoll  # pyright: ignore[reportAttributeAccessIssue]
from ...extras.dialects.arith import constant  # pyright: ignore[reportMissingImports]
from ...helpers.dialects.func import call  # pyright: ignore[reportMissingImports]
from ..buffer import Buffer


def emit_payload_global(sym: str, memref_ty, words: list) -> None:
    """Emit a module-scope constant `memref.global` holding `words`.

    Placed at the enclosing `aie.device`'s block start, mirroring
    `pmlib/design.py:_payload_global` -- `Program` verifies the module before
    returning it, so the global must exist by the time the sequence body
    finishes being built, and inserting at block start keeps every payload
    declared before anything that references it. Shared by `slot.py` and
    this module rather than defined twice.
    """
    device = ir.InsertionPoint.current.block.owner.operation.parent
    with ir.InsertionPoint.at_block_begin(device.regions[0].blocks[0]):
        memref.global_(
            sym,
            ir.TypeAttr.get(memref_ty),
            sym_visibility="private",
            constant=True,
            initial_value=ir.DenseElementsAttr.get(
                np.array(words, dtype=np.uint32).view(np.int32)
            ),
        )

_STUB_SOURCE = """\
// Generated by iron.overlay._bootstrap. The ping-pong park: announces arrival
// on `{parked}`, then spins on `{flag}` exactly like the normal in-resident
// wait -- the host releases both the same way, just at different addresses.
#include <cstdint>

extern "C" int32_t {flag}[];
extern "C" int32_t {parked}[];

extern "C" void {entry}(void) {{
  volatile int32_t *parked = {parked};
  volatile int32_t *f = {flag};
  *parked = 1;
  while (*f == 0)
    ;
  *f = 0;
  *parked = 0;
}}
"""


class Bootstrap:
    """One ping-pong pair's shared park state.

    Not constructed directly by users -- `ProgramMemorySlot.pingpong()`
    creates one per pair and attaches it to whichever slot shares the
    resident's granule.
    """

    def __init__(self, name: str, tile, base: int, size: int):
        self.name = name
        self.tile = tile
        self.base = base
        self.size = size
        self.entry_symbol = f"overlay_stub_{name}"
        word_ty = np.ndarray[(1,), np.dtype[np.int32]]
        self.flag = Buffer(
            word_ty,
            initial_value=np.array([0], dtype=np.int32),
            name=f"{name}_flag",
            tile=tile,
            use_write_rtp=True,
        )
        self.parked = Buffer(
            word_ty,
            initial_value=np.array([0], dtype=np.int32),
            name=f"{name}_parked",
            tile=tile,
        )
        self._op = None
        self._ld_path: str | None = None
        # Resolved from the pass-1 resident ELF by ProgramMemoryOverlayDesign
        # and injected into the pass-2 build's fresh Bootstrap instance before
        # its Program is resolved -- a Buffer's address is compiler-assigned,
        # so there is no way to know it before pass 1 has actually run.
        self.parked_addr: int | None = None
        # Words for the *current* build pass, exactly as ProgramMemorySlot's
        # own _pass2_words: None (pass 1) -> zero-filled placeholder, so the
        # resident's layout does not depend on the stub's real content. Set by
        # ProgramMemoryOverlayDesign after linking the compiled stub, before
        # pass 2's Program is resolved.
        self.pass2_words: list | None = None
        self._installed = False

    def source(self) -> str:
        return _STUB_SOURCE.format(
            flag=self.flag.name, parked=self.parked.name, entry=self.entry_symbol
        )

    def install(self) -> None:
        """Emit the one-time write of the park's own code, from a Runtime
        sequence. Idempotent per instance -- safe to call from `load()` on
        every phase; only the first call emits anything.
        """
        if self._installed:
            return
        self._installed = True
        words = self.pass2_words if self.pass2_words is not None else [0] * (
            self.size // 4
        )
        memref_ty = ir.MemRefType.get([len(words)], ir.IntegerType.get_signless(32))
        sym = f"{self.name}_stub_payload"
        emit_payload_global(sym, memref_ty, words)
        npu_blockwrite(
            self._host_offset() + self.base,
            memref.get_global(memref_ty, sym),
            column=self.tile.col,
            row=self.tile.row,
        )

    def _host_offset(self) -> int:
        # Deferred import: iron.overlay.slot imports this module, so a
        # module-level import back would be circular. Only needed here, at
        # install() time (inside an active MLIR context), not at import time.
        from ...utils import get_current_device

        return get_current_device().target_model.get_program_memory_host_offset()

    def resolve(self) -> None:
        if self._op is not None:
            return
        self._ld_path = f"{self.name}_stub_slot.ld"
        with open(self._ld_path, "w") as f:
            f.write(
                "/* Generated by iron.overlay._bootstrap.Bootstrap. */\n"
                f"{self.entry_symbol} = 0x{self.base:x};\n"
            )
        self._op = external_func(
            self.entry_symbol, inputs=[], link_with=self._ld_path
        )

    def enter(self) -> None:
        """Call from inside the owning Worker's core_fn: park here."""
        if self._op is None:
            raise RuntimeError("Bootstrap must be resolved before enter() is called.")
        call(self._op, [])

    def release(self) -> None:
        """Call from inside a Runtime sequence: signal the park to return."""
        self.flag[0] = 1

    def wait_parked(self, column: int, row: int) -> None:
        """Block the runtime sequence until the core has reached the park.

        `parked_addr` is only knowable after pass 1 has actually compiled
        (a Buffer's address is compiler-assigned) -- pass 1 itself, which
        needs *a* value here to have the right instruction-stream shape,
        uses a placeholder 0 instead. That pass-1 xclbin is discarded after
        its resident ELF is read, never run on hardware, so the placeholder
        never needs to be correct.
        """
        i32 = ir.IntegerType.get_signless(32)
        npu_maskpoll(
            constant(self.parked_addr or 0, i32),
            constant(1, i32),
            constant(0xFFFFFFFF, i32),
            column=column,
            row=row,
        )
