//===- ADFOps.cpp -------------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2021, Xilinx, Inc. All rights reserved.
// Copyright (C) 2022-2023, Advanced Micro Devices, Inc. All rights reserved.
//
//===----------------------------------------------------------------------===//
//

#include "aie/Dialect/ADF/ADFOps.h"

using namespace mlir;
using namespace xilinx;
using namespace ADF;

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "aie/Dialect/ADF/ADF.cpp.inc"