"""Codegen: emit a static const float[256] exp LUT header.

Used by llama_flowkv_qk to compute softmax without aie::exp2 (which
isn't bit-exact vs numpy). After subtract-max all scores are <= 0;
the kernel quantizes them to int8 with a fixed `exp_quant_scale` and
looks up the LUT:

  q[i]   = clamp(round((shifted[i]) * (1/exp_quant_scale)), -128, 0)
  exp_v  = exp_lut[q[i] + 128]   # = exp(q[i] * exp_quant_scale)

The LUT is generated here with the same arithmetic the test reference
replays, so both compute identical exp values.
"""

import argparse
import sys

import numpy as np


def exp_lut(exp_quant_scale: float) -> np.ndarray:
    """256 fp32 entries: lut[k] = exp((k - 128) * exp_quant_scale).

    With exp_quant_scale negative (we expect shifted scores in (-inf, 0]
    so q[i] in [-128, 0]; we want exp(negative) = small positive), the
    LUT covers values from exp(-128 * |scale|) to exp(127 * |scale|).

    Convention here: pass exp_quant_scale > 0, the kernel uses the
    inverse to quantize; lut[k] = exp((k - 128) * exp_quant_scale)
    interpreting k - 128 as a signed offset.
    """
    out = np.zeros(256, dtype=np.float32)
    for k in range(256):
        out[k] = np.exp((k - 128) * exp_quant_scale).astype(np.float32)
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--exp-quant-scale", type=float, required=True,
                   help="resolution of the LUT in score-units per index step")
    p.add_argument("-o", required=True)
    args = p.parse_args(sys.argv[1:])

    lut = exp_lut(args.exp_quant_scale)
    raw = lut.view(np.uint32)

    with open(args.o, "w") as f:
        f.write("// auto-generated by gen_exp_lut.py; do not edit\n")
        f.write(f"// exp_quant_scale = {args.exp_quant_scale}\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const uint32_t llama_exp_lut_raw[256] = {\n")
        for i in range(0, 256, 4):
            row = ", ".join(f"0x{raw[j]:08x}" for j in range(i, i + 4))
            f.write(f"    {row},\n")
        f.write("};\n")
        f.write("\n// Convenience: float view via memcpy in the kernel.\n")


if __name__ == "__main__":
    main()
