# kernels/__init__.py -*- Python -*-
#
# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""Factory functions for AIE kernel ExternalFunctions.

Submodules:
- `eltwise` — passthrough, scale, add, mul, relu
- `datamovement` — axpy, convert_copy, expand, transpose
- `reduce` — reduce_add, reduce_min, reduce_max, compute_max
- `vision` — rgba2hue, threshold, bitwise_or, bitwise_and, gray2rgba, rgba2gray, filter2d, add_weighted
- `activation` — softmax, gelu, silu, swiglu, bf16_exp, exp2f_vec, tanh, sigmoid, leaky_relu
- `transformer` — rms_norm, layer_norm, layer_norm_f32, layer_norm_affine_cast, rope, mm_activation_epilogue
- `linalg` — mm, mv, cascade_mm  (mm/mv expose ``.zero`` for the companion zero-fill kernel,
  ``.mac_dims`` and ``.stream_dims`` / ``.a_dims_from_stream`` for the DMA layout)

Most factories attach a [`KernelContract`][iron.kernels.KernelContract] as
``.contract``: argument roles, a numpy reference and a tolerance. It is what
``aie.utils.kernel_harness`` uses to build, run and check any kernel, and the
``*_ref`` functions exported here are those references.
- `conv` — conv2dk1, conv2dk3, conv2dk1_skip, conv2dk1_i8, conv2dk14, conv2dk1_skip_init, bn_*
"""

from ._common import NONFINITE, OVERFLOW, ROLES, ROUNDING, SUBNORMALS, KernelContract
from .activation import (
    bf16_exp,
    bf16_exp_ref,
    exp2f_vec,
    exp2f_vec_ref,
    gelu,
    gelu_ref,
    leaky_relu,
    leaky_relu_ref,
    relu_ref,
    sigmoid,
    sigmoid_ref,
    silu,
    silu_ref,
    softmax,
    softmax_ref,
    swiglu,
    swiglu_ref,
    tanh,
    tanh_ref,
)
from .conv import (
    DWCONV1D_TAIL,
    bn_conv2dk1_i8,
    bn_conv2dk1_i8_ref,
    bn_conv2dk1_input_split_partial_put_ui8,
    bn_conv2dk1_input_split_partial_skip_get,
    bn_conv2dk1_partial_get_relu_i8,
    bn_conv2dk1_partial_put_i8,
    bn_conv2dk1_relu,
    bn_conv2dk1_relu_ref,
    bn_conv2dk1_relu_xy_pool_padded,
    bn_conv2dk1_relu_xy_pool_padded_ref,
    bn_conv2dk1_skip,
    bn_conv2dk1_skip_ref,
    bn_conv2dk3,
    bn_conv2dk3_dw,
    bn_conv2dk3_dw_out_split,
    bn_conv2dk3_dw_ref,
    bn_conv2dk3_ref,
    bn_fc_relu_ui16_pad,
    bn_fc_relu_ui16_pad_ref,
    conv2dk1,
    conv2dk1_i8,
    conv2dk1_i8_ref,
    conv2dk1_ref,
    conv2dk1_skip,
    conv2dk1_skip_init,
    conv2dk1_skip_init_ref,
    conv2dk1_skip_ref,
    conv2dk3,
    conv2dk3_ref,
    conv2dk14,
    conv2dk14_ref,
    dwconv1d,
    dwconv1d_ref,
)
from .datamovement import (
    axpy,
    axpy_ref,
    convert_copy,
    convert_copy_ref,
    expand,
    expand_ref,
    transpose,
    transpose_ref,
)
from .eltwise import (
    add,
    add_ref,
    mul,
    mul_add,
    mul_add_ref,
    mul_ref,
    passthrough,
    relu,
    scale,
    scale_ref,
)
from .linalg import (
    cascade_mm,
    mha,
    mm,
    mm_acc_dtype,
    mm_bfp,
    mm_bfp_mixed_ref,
    mm_bfp_ref,
    mm_bfp_shuffle,
    mm_bfp_shuffle_ref,
    mm_ref,
    mm_stream_dims,
    mv,
    mv_bf16_ref,
    mv_ref,
)
from .reduce import (
    compute_max,
    compute_max_ref,
    reduce_add,
    reduce_add_ref,
    reduce_max,
    reduce_max_ref,
    reduce_min,
    reduce_min_ref,
)
from .transformer import (
    layer_norm,
    layer_norm_affine_cast,
    layer_norm_affine_cast_ref,
    layer_norm_f32,
    layer_norm_f32_ref,
    layer_norm_ref,
    mm_activation_epilogue,
    mm_activation_epilogue_ref,
    rms_norm,
    rms_norm_ref,
    rope,
    rope_ref,
)
from .vision import (
    add_weighted,
    add_weighted_ref,
    bitwise_and,
    bitwise_and_ref,
    bitwise_or,
    bitwise_or_ref,
    filter2d,
    filter2d_ref,
    gray2rgba,
    gray2rgba_ref,
    rgba2gray,
    rgba2gray_ref,
    rgba2hue,
    rgba2hue_ref,
    threshold,
    threshold_ref,
)

__all__ = [
    "KernelContract",
    "NONFINITE",
    "OVERFLOW",
    "SUBNORMALS",
    "ROUNDING",
    "ROLES",
    "passthrough",
    "scale",
    "add",
    "mul",
    "mul_add",
    "mul_add_ref",
    "rms_norm",
    "rms_norm_ref",
    "layer_norm",
    "layer_norm_ref",
    "layer_norm_f32",
    "layer_norm_f32_ref",
    "layer_norm_affine_cast",
    "layer_norm_affine_cast_ref",
    "rope",
    "rope_ref",
    "mm_activation_epilogue",
    "mm_activation_epilogue_ref",
    "reduce_add",
    "reduce_min",
    "reduce_max",
    "compute_max",
    "compute_max_ref",
    "relu",
    "rgba2hue",
    "rgba2hue_ref",
    "threshold",
    "threshold_ref",
    "bitwise_or",
    "bitwise_or_ref",
    "bitwise_and",
    "bitwise_and_ref",
    "gray2rgba",
    "gray2rgba_ref",
    "rgba2gray",
    "rgba2gray_ref",
    "filter2d",
    "filter2d_ref",
    "add_weighted",
    "add_weighted_ref",
    "softmax",
    "gelu",
    "silu",
    "swiglu",
    "swiglu_ref",
    "bf16_exp",
    "exp2f_vec",
    "tanh",
    "sigmoid",
    "leaky_relu",
    "axpy",
    "convert_copy",
    "expand",
    "transpose",
    "add_ref",
    "mul_ref",
    "scale_ref",
    "reduce_add_ref",
    "reduce_min_ref",
    "reduce_max_ref",
    "axpy_ref",
    "convert_copy_ref",
    "expand_ref",
    "transpose_ref",
    "mm_ref",
    "mv_ref",
    "mv_bf16_ref",
    "mm_stream_dims",
    "relu_ref",
    "silu_ref",
    "gelu_ref",
    "bf16_exp_ref",
    "exp2f_vec_ref",
    "softmax_ref",
    "tanh_ref",
    "sigmoid_ref",
    "leaky_relu_ref",
    "mm",
    "mm_acc_dtype",
    "mha",
    "mm_bfp",
    "mm_bfp_ref",
    "mm_bfp_mixed_ref",
    "mm_bfp_shuffle_ref",
    "mm_bfp_shuffle",
    "mv",
    "cascade_mm",
    "conv2dk1",
    "conv2dk1_ref",
    "conv2dk3",
    "dwconv1d",
    "dwconv1d_ref",
    "DWCONV1D_TAIL",
    "conv2dk3_ref",
    "conv2dk1_skip",
    "conv2dk1_skip_ref",
    "conv2dk1_i8",
    "conv2dk1_i8_ref",
    "conv2dk14",
    "conv2dk14_ref",
    "conv2dk1_skip_init",
    "conv2dk1_skip_init_ref",
    "bn_conv2dk1_relu",
    "bn_conv2dk1_relu_ref",
    "bn_conv2dk3",
    "bn_conv2dk3_ref",
    "bn_conv2dk1_i8",
    "bn_conv2dk1_i8_ref",
    "bn_conv2dk1_skip",
    "bn_conv2dk1_skip_ref",
    "bn_conv2dk3_dw",
    "bn_conv2dk3_dw_ref",
    "bn_conv2dk1_relu_xy_pool_padded",
    "bn_conv2dk1_relu_xy_pool_padded_ref",
    "bn_fc_relu_ui16_pad",
    "bn_fc_relu_ui16_pad_ref",
    "bn_conv2dk1_partial_put_i8",
    "bn_conv2dk1_partial_get_relu_i8",
    "bn_conv2dk3_dw_out_split",
    "bn_conv2dk1_input_split_partial_put_ui8",
    "bn_conv2dk1_input_split_partial_skip_get",
]
