version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/utils/mlir_aie_wheels"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/utils/mlir_wheels"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      pre-commit-minor-patch:
        update-types: ["minor", "patch"]
