# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 8,22 * *"
    groups:
      github-actions-minor-patch:
        update-types: ["minor", "patch"]
      github-actions-major:
        update-types: ["major"]

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "cron"
      cronjob: "0 6 8,22 * *"
    groups:
      python-minor-patch:
        update-types: ["minor", "patch"]
      python-major:
        update-types: ["major"]

  - package-ecosystem: "pip"
    directory: "/utils/mlir_aie_wheels"
    schedule:
      interval: "cron"
      cronjob: "0 6 8,22 * *"
    groups:
      mlir-aie-wheels-minor-patch:
        update-types: ["minor", "patch"]
      mlir-aie-wheels-major:
        update-types: ["major"]

  - package-ecosystem: "pip"
    directory: "/utils/mlir_wheels"
    schedule:
      interval: "cron"
      cronjob: "0 6 8,22 * *"
    groups:
      mlir-wheels-minor-patch:
        update-types: ["minor", "patch"]
      mlir-wheels-major:
        update-types: ["major"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 8,22 * *"
    groups:
      pre-commit-minor-patch:
        update-types: ["minor", "patch"]
      pre-commit-major:
        update-types: ["major"]
