#loc9 = loc("test/aiecc/cpp_basic.mlir":60:26)
#loc10 = loc("test/aiecc/cpp_basic.mlir":60:48)
module {
  aie.device(npu1_1col) {
    %c16_i64 = arith.constant 16 : i64 loc(#loc2)
    %c1_i64 = arith.constant 1 : i64 loc(#loc2)
    %c0_i64 = arith.constant 0 : i64 loc(#loc2)
    %shim_noc_tile_0_0 = aie.tile(0, 0) {controller_id = #aie.packet_info<pkt_type = 0, pkt_id = 15>} loc(#loc3)
    %tile_0_2 = aie.tile(0, 2) {controller_id = #aie.packet_info<pkt_type = 0, pkt_id = 27>} loc(#loc4)
    %of_out_cons_prod_lock_0 = aie.lock(%shim_noc_tile_0_0, 2) {init = 0 : i32, sym_name = "of_out_cons_prod_lock_0"} loc(#loc5)
    %of_out_cons_cons_lock_0 = aie.lock(%shim_noc_tile_0_0, 3) {init = 0 : i32, sym_name = "of_out_cons_cons_lock_0"} loc(#loc5)
    %of_out_buff_0 = aie.buffer(%tile_0_2) {address = 1024 : i32, mem_bank = 0 : i32, sym_name = "of_out_buff_0"} : memref<16xi32>  loc(#loc5)
    %of_out_buff_1 = aie.buffer(%tile_0_2) {address = 16384 : i32, mem_bank = 1 : i32, sym_name = "of_out_buff_1"} : memref<16xi32>  loc(#loc5)
    %of_out_prod_lock_0 = aie.lock(%tile_0_2, 2) {init = 2 : i32, sym_name = "of_out_prod_lock_0"} loc(#loc5)
    %of_out_cons_lock_0 = aie.lock(%tile_0_2, 3) {init = 0 : i32, sym_name = "of_out_cons_lock_0"} loc(#loc5)
    %of_in_cons_buff_0 = aie.buffer(%tile_0_2) {address = 32768 : i32, mem_bank = 2 : i32, sym_name = "of_in_cons_buff_0"} : memref<16xi32>  loc(#loc6)
    %of_in_cons_buff_1 = aie.buffer(%tile_0_2) {address = 49152 : i32, mem_bank = 3 : i32, sym_name = "of_in_cons_buff_1"} : memref<16xi32>  loc(#loc6)
    %of_in_cons_prod_lock_0 = aie.lock(%tile_0_2, 0) {init = 2 : i32, sym_name = "of_in_cons_prod_lock_0"} loc(#loc6)
    %of_in_cons_cons_lock_0 = aie.lock(%tile_0_2, 1) {init = 0 : i32, sym_name = "of_in_cons_cons_lock_0"} loc(#loc6)
    %of_in_prod_lock_0 = aie.lock(%shim_noc_tile_0_0, 0) {init = 0 : i32, sym_name = "of_in_prod_lock_0"} loc(#loc6)
    %of_in_cons_lock_0 = aie.lock(%shim_noc_tile_0_0, 1) {init = 0 : i32, sym_name = "of_in_cons_lock_0"} loc(#loc6)
    %_anonymous0 = aie.buffer(%tile_0_2) {address = 1088 : i32, mem_bank = 0 : i32, sym_name = "_anonymous0"} : memref<2xi32>  loc(#loc7)
    %core_0_2 = aie.core(%tile_0_2) {
      aie.end loc(#loc7)
    } {elf_file = "/tmp/cp2/elfs_main_core_0_2.elf"} loc(#loc7)
    aie.runtime_sequence(%arg0: memref<16xi32> loc("test/aiecc/cpp_basic.mlir":60:26), %arg1: memref<16xi32> loc("test/aiecc/cpp_basic.mlir":60:48)) {
      aiex.npu.dma_memcpy_nd(%arg1[%c0_i64, %c0_i64, %c0_i64, %c0_i64][%c1_i64, %c1_i64, %c1_i64, %c16_i64][%c0_i64, %c0_i64, %c0_i64, %c1_i64]) {id = 1 : i64, metadata = @of_out_shim_alloc} : memref<16xi32> loc(#loc11)
      aiex.npu.dma_memcpy_nd(%arg0[%c0_i64, %c0_i64, %c0_i64, %c0_i64][%c1_i64, %c1_i64, %c1_i64, %c16_i64][%c0_i64, %c0_i64, %c0_i64, %c1_i64]) {id = 0 : i64, issue_token = true, metadata = @of_in_shim_alloc} : memref<16xi32> loc(#loc12)
      aiex.npu.dma_wait {symbol = @of_out_shim_alloc} loc(#loc13)
    } loc(#loc8)
    aie.shim_dma_allocation @of_in_shim_alloc(%shim_noc_tile_0_0, MM2S, 0) loc(#loc6)
    %mem_0_2 = aie.mem(%tile_0_2) {
      %0 = aie.dma_start(S2MM, 0, ^bb1, ^bb3) loc(#loc6)
    ^bb1:  // 2 preds: ^bb0, ^bb2
      aie.use_lock(%of_in_cons_prod_lock_0, AcquireGreaterEqual, 1) loc(#loc6)
      aie.dma_bd(%of_in_cons_buff_0 : memref<16xi32>, 0, 16) {bd_id = 0 : i32, next_bd_id = 1 : i32} loc(#loc6)
      aie.use_lock(%of_in_cons_cons_lock_0, Release, 1) loc(#loc6)
      aie.next_bd ^bb2 loc(#loc6)
    ^bb2:  // pred: ^bb1
      aie.use_lock(%of_in_cons_prod_lock_0, AcquireGreaterEqual, 1) loc(#loc6)
      aie.dma_bd(%of_in_cons_buff_1 : memref<16xi32>, 0, 16) {bd_id = 1 : i32, next_bd_id = 0 : i32} loc(#loc6)
      aie.use_lock(%of_in_cons_cons_lock_0, Release, 1) loc(#loc6)
      aie.next_bd ^bb1 loc(#loc6)
    ^bb3:  // pred: ^bb0
      %1 = aie.dma_start(MM2S, 0, ^bb4, ^bb6) loc(#loc5)
    ^bb4:  // 2 preds: ^bb3, ^bb5
      aie.use_lock(%of_out_cons_lock_0, AcquireGreaterEqual, 1) loc(#loc5)
      aie.dma_bd(%of_out_buff_0 : memref<16xi32>, 0, 16) {bd_id = 2 : i32, next_bd_id = 3 : i32} loc(#loc5)
      aie.use_lock(%of_out_prod_lock_0, Release, 1) loc(#loc5)
      aie.next_bd ^bb5 loc(#loc5)
    ^bb5:  // pred: ^bb4
      aie.use_lock(%of_out_cons_lock_0, AcquireGreaterEqual, 1) loc(#loc5)
      aie.dma_bd(%of_out_buff_1 : memref<16xi32>, 0, 16) {bd_id = 3 : i32, next_bd_id = 2 : i32} loc(#loc5)
      aie.use_lock(%of_out_prod_lock_0, Release, 1) loc(#loc5)
      aie.next_bd ^bb4 loc(#loc5)
    ^bb6:  // pred: ^bb3
      aie.end loc(#loc6)
    } loc(#loc6)
    aie.shim_dma_allocation @of_out_shim_alloc(%shim_noc_tile_0_0, S2MM, 0) loc(#loc5)
    aie.packet_flow(15) {
      aie.packet_source<%shim_noc_tile_0_0, TileControl : 0> loc(#loc3)
      aie.packet_dest<%shim_noc_tile_0_0, South : 0> loc(#loc3)
    } {keep_pkt_header = true, priority_route = true} loc(#loc3)
    %switchbox_0_0 = aie.switchbox(%shim_noc_tile_0_0) {
      aie.connect<South : 3, North : 1> loc(#loc6)
      aie.connect<North : 1, South : 2> loc(#loc5)
      %0 = aie.amsel<5> (3) loc(#loc3)
      %1 = aie.masterset(South : 0, %0) {keep_pkt_header = true} loc(#loc3)
      aie.packet_rules(TileControl : 0) {
        aie.rule(31, 15, %0) loc(#loc3)
      } loc(#loc3)
    } loc(#loc2)
    %shim_mux_0_0 = aie.shim_mux(%shim_noc_tile_0_0) {
      aie.connect<DMA : 0, North : 3> loc(#loc6)
      aie.connect<North : 2, DMA : 0> loc(#loc5)
    } loc(#loc2)
    %mem_tile_0_1 = aie.tile(0, 1) loc(#loc2)
    %switchbox_0_1 = aie.switchbox(%mem_tile_0_1) {
      aie.connect<South : 1, North : 1> loc(#loc6)
      aie.connect<North : 1, South : 1> loc(#loc5)
    } loc(#loc2)
    %switchbox_0_2 = aie.switchbox(%tile_0_2) {
      aie.connect<South : 1, DMA : 0> loc(#loc6)
      aie.connect<DMA : 0, South : 1> loc(#loc5)
    } loc(#loc2)
    aie.wire(%shim_mux_0_0 : North, %switchbox_0_0 : South) loc(#loc3)
    aie.wire(%shim_noc_tile_0_0 : DMA, %shim_mux_0_0 : DMA) loc(#loc3)
    aie.wire(%mem_tile_0_1 : Core, %switchbox_0_1 : Core) loc(#loc2)
    aie.wire(%mem_tile_0_1 : DMA, %switchbox_0_1 : DMA) loc(#loc2)
    aie.wire(%switchbox_0_0 : North, %switchbox_0_1 : South) loc(#loc2)
    aie.wire(%tile_0_2 : Core, %switchbox_0_2 : Core) loc(#loc4)
    aie.wire(%tile_0_2 : DMA, %switchbox_0_2 : DMA) loc(#loc4)
    aie.wire(%switchbox_0_1 : North, %switchbox_0_2 : South) loc(#loc4)
  } {aiecc.pdi_id = 1 : i32} loc(#loc1)
} loc(#loc)
#loc = loc("test/aiecc/cpp_basic.mlir":29:1)
#loc1 = loc("test/aiecc/cpp_basic.mlir":30:3)
#loc2 = loc(unknown)
#loc3 = loc("test/aiecc/cpp_basic.mlir":31:17)
#loc4 = loc("test/aiecc/cpp_basic.mlir":32:17)
#loc5 = loc("test/aiecc/cpp_basic.mlir":35:5)
#loc6 = loc("test/aiecc/cpp_basic.mlir":34:5)
#loc7 = loc("test/aiecc/cpp_basic.mlir":37:17)
#loc8 = loc("test/aiecc/cpp_basic.mlir":60:5)
#loc11 = loc("test/aiecc/cpp_basic.mlir":64:7)
#loc12 = loc("test/aiecc/cpp_basic.mlir":65:7)
#loc13 = loc("test/aiecc/cpp_basic.mlir":66:7)
