//===- cpp_partition_json.mlir -----------------------------------*- MLIR -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2026, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

// Tests that the aie_partition.json generated by C++ aiecc has correct
// column_width and start_columns for different device types.

// REQUIRES: peano

// --- npu1_1col: column_width=1, start_columns=[1,2,3,4] ---
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin -n %S/cpp_partition_npu1_1col.mlir
// RUN: FileCheck %s --input-file=cpp_partition_npu1_1col.mlir.prj/main_aie_partition.json --check-prefix=NPU1_1COL

// NPU1_1COL: "column_width": 1
// NPU1_1COL: "start_columns": [
// NPU1_1COL: 1

// --- npu1 (full 4-col): column_width=4, start_columns=[0] ---
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin -n %S/cpp_partition_npu1.mlir
// RUN: FileCheck %s --input-file=cpp_partition_npu1.mlir.prj/main_aie_partition.json --check-prefix=NPU1

// NPU1: "column_width": 4
// NPU1: "start_columns": [
// NPU1: 0

// --- npu2 (full 8-col): column_width=8, start_columns=[0] ---
// RUN: aiecc --no-xchesscc --no-xbridge --aie-generate-xclbin -n %S/cpp_partition_npu2.mlir
// RUN: FileCheck %s --input-file=cpp_partition_npu2.mlir.prj/main_aie_partition.json --check-prefix=NPU2

// NPU2: "column_width": 8
// NPU2: "start_columns": [
// NPU2: 0
