//===- cpp_expand_load_pdis_config.mlir ------------------------*- MLIR -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2026, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

// Test that the config.json generated by --generate-full-elf --expand-load-pdis
// contains the correct PDI entries for all devices including empties.
// This validates that the config.json structure matches the old Python
// FlowRunner output: empty devices get their own PDI entries with unique IDs.

// REQUIRES: peano

// RUN: rm -rf %t && mkdir -p %t
// RUN: cd %t && aiecc --no-xchesscc --no-xbridge --generate-full-elf --expand-load-pdis --tmpdir=%t %S/cpp_expand_load_pdis.mlir 2>&1
// RUN: cat %t/full_elf_config.json | FileCheck %s

// Verify config.json has xrt-kernels entry (only devices with runtime sequences)
// CHECK: "xrt-kernels"

// Verify PDI entries include empty device (2 original + 1 empty = 3 PDIs)
// The single aiex.configure creates one empty device for reset
// CHECK: "PDIs"
// CHECK-DAG: "PDI_file":{{.*}}empty_0.pdi
// CHECK-DAG: "PDI_file":{{.*}}main.pdi
// CHECK-DAG: "PDI_file":{{.*}}add_one.pdi

// Verify PDI IDs are present (sequential from 1: empty_0=1, main=2, add_one=3)
// CHECK-DAG: "id": 1
// CHECK-DAG: "id": 2
// CHECK-DAG: "id": 3

module {

    aie.device(npu2) @main {
        aie.runtime_sequence @sequence(%arg : memref<16xi32>) {
            aiex.configure @add_one {
                aiex.run @add_one_seq (%arg) : (memref<16xi32>)
            }
        }
    }

    aie.device(npu2) @add_one {
        %t00 = aie.tile(0, 0)
        %t02 = aie.tile(0, 2)

        aie.objectfifo @of_in (%t00, {%t02}, 1 : i32) : !aie.objectfifo<memref<16xi32>>
        aie.objectfifo @of_out(%t02, {%t00}, 1 : i32) : !aie.objectfifo<memref<16xi32>>

        aie.core(%t02) {
            %c0 = arith.constant 0 : index
            %c1 = arith.constant 1 : index
            %c16 = arith.constant 16 : index
            %c1_i32 = arith.constant 1 : i32
            %c_intmax = arith.constant 0xFFFFFE : index

            scf.for %niter = %c0 to %c_intmax step %c1 {
                %subview_in  = aie.objectfifo.acquire @of_in (Consume, 1) : !aie.objectfifosubview<memref<16xi32>>
                %subview_out = aie.objectfifo.acquire @of_out(Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
                %elem_in  = aie.objectfifo.subview.access %subview_in [0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                %elem_out = aie.objectfifo.subview.access %subview_out[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                scf.for %i = %c0 to %c16 step %c1 {
                    %0 = memref.load %elem_in[%i] : memref<16xi32>
                    %1 = arith.addi %0, %c1_i32 : i32
                    memref.store %1, %elem_out[%i] : memref<16xi32>
                }
                aie.objectfifo.release @of_in (Consume, 1)
                aie.objectfifo.release @of_out(Produce, 1)
            }
            aie.end
        }

        aie.runtime_sequence @add_one_seq(%a : memref<16xi32>) {
            %t_in = aiex.dma_configure_task_for @of_in {
                aie.dma_bd(%a : memref<16xi32>, 0, 16)
                aie.end
            }
            %t_out = aiex.dma_configure_task_for @of_out {
                aie.dma_bd(%a : memref<16xi32>, 0, 16)
                aie.end
            } {issue_token = true}
            aiex.dma_start_task(%t_in)
            aiex.dma_start_task(%t_out)
            aiex.dma_await_task(%t_out)
        }
    }
}
