//===- AIE2_delayed_release.mlir -------------------------------*- MLIR -*-===//
//
// Copyright (C) 2023 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// The expected semantics of objectFIFO aquire/releases are such that the most
// recent acquire will always name the _total_ number of elements available
// to the core. For example, an acquire(2) followed by an acquire(1) means that
// after the second acquire, the core can only read one object (not three!),
// even though none of the previously acquired elements haven't been freed.
// Essentially, the smaller-numbered acquire will reduce the set of legally
// accessible objects. (The remaining accessible element will be the same as
// the most recent one of the previously acquired two elements.)

//  objectFifo   (capacity 4)
//  [ | | | | ]
//   x x           after acquire(2)     x = consumable data
//   . x           after acquire(1)     . = produced, not yet freed
//                 after release(2)     (all slots empty, ready for produce)

// You always want to release(max(acquire no. since last release))

// This tests ensures that locks are acquired correctly to preserve these
// semantics.

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-assign-lock-ids --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcve2302) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(2, 2)
// CHECK:           %[[VAL_1:.*]] = aie.tile(2, 3)
// CHECK:           %[[VAL_2:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_0"} : memref<i32>
// CHECK:           %[[VAL_3:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_1"} : memref<i32>
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_2"} : memref<i32>
// CHECK:           %[[VAL_5:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_3"} : memref<i32>
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_0]], 0) {init = 4 : i32, sym_name = "fifo_prod_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "fifo_cons_lock_0"}
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "buf23"} : memref<4xi32>
// CHECK:           %[[VAL_9:.*]] = aie.core(%[[VAL_0]]) {
// CHECK:             %[[VAL_10:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_11:.*]] = arith.constant 99 : i32
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_10]])
// CHECK:             memref.store %[[VAL_11]], %[[VAL_2]][] : memref<i32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_10]])
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_10]])
// CHECK:             memref.store %[[VAL_11]], %[[VAL_3]][] : memref<i32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_10]])
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_10]])
// CHECK:             memref.store %[[VAL_11]], %[[VAL_4]][] : memref<i32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_10]])
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_10]])
// CHECK:             memref.store %[[VAL_11]], %[[VAL_5]][] : memref<i32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_10]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_12:.*]] = aie.core(%[[VAL_1]]) {
// CHECK:             %[[VAL_13:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_14:.*]] = arith.constant 3 : index
// CHECK:             %[[VAL_15:.*]] = arith.constant 2 : index
// CHECK:             %[[VAL_16:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_17:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_18:.*]] = arith.constant 3 : i32
// CHECK:             %[[VAL_19:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_20:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:             %[[VAL_21:.*]] = memref.load %[[VAL_2]][] : memref<i32>
// CHECK:             memref.store %[[VAL_21]], %[[VAL_8]]{{\[}}%[[VAL_17]]] : memref<4xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_19]])
// CHECK:             %[[VAL_22:.*]] = memref.load %[[VAL_2]][] : memref<i32>
// CHECK:             memref.store %[[VAL_22]], %[[VAL_8]]{{\[}}%[[VAL_16]]] : memref<4xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_20]])
// CHECK:             %[[VAL_23:.*]] = memref.load %[[VAL_2]][] : memref<i32>
// CHECK:             memref.store %[[VAL_23]], %[[VAL_8]]{{\[}}%[[VAL_15]]] : memref<4xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_19]])
// CHECK:             %[[VAL_24:.*]] = memref.load %[[VAL_2]][] : memref<i32>
// CHECK:             memref.store %[[VAL_24]], %[[VAL_8]]{{\[}}%[[VAL_14]]] : memref<4xi32>
// CHECK:             aie.use_lock(%[[VAL_6]], Release, %[[VAL_18]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module @AIE2_delayed_release {
    aie.device(xcve2302) {
        %tile22 = aie.tile(2, 2)
        %tile23 = aie.tile(2, 3)
        %buf23 = aie.buffer(%tile23) {sym_name = "buf23"} : memref<4xi32>

        aie.objectfifo @fifo (%tile22, {%tile23}, 4 : i32) : !aie.objectfifo<memref<i32>>

        // Producer -- produces one element at a time
        %core22 = aie.core(%tile22) {
            %c99 = arith.constant 99 : i32
            %i0 = arith.constant 0 : index
            %i1 = arith.constant 1 : index
            %i4 = arith.constant 4 : index
            scf.for %it = %i0 to %i4 step %i1 {
                // Produce one 1 element (acquire producer lock) ...
                %subview = aie.objectfifo.acquire @fifo (Produce, 1) : !aie.objectfifosubview<memref<i32>>
                %subview_obj = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
                memref.store %c99, %subview_obj[] : memref<i32>
                aie.objectfifo.release @fifo (Produce, 1)
                // ... done producing (release consumer lock)
            }
            aie.end
        }

        // Consumer -- consumes {2, 1, 3, 1}; releases {0, 0, 0, 2}
        %core23 = aie.core(%tile23) {
            %i0 = arith.constant 0 : index
            %i1 = arith.constant 1 : index
            %i2 = arith.constant 2 : index
            %i3 = arith.constant 3 : index

            // Begin consuming 2 elements (acquire consumer lock with value 2)
            %subview0 = aie.objectfifo.acquire @fifo (Consume, 2) : !aie.objectfifosubview<memref<i32>>
            %subview0_obj = aie.objectfifo.subview.access %subview0[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
            %v0 = memref.load %subview0_obj[] : memref<i32>
            memref.store %v0, %buf23[%i0] : memref<4xi32>

            // For the next step, we only need one element (this could be a subroutine that acquires 1, not knowing that we already acquired 2)
            %subview1 = aie.objectfifo.acquire @fifo (Consume, 1) : !aie.objectfifosubview<memref<i32>>
            %subview1_obj = aie.objectfifo.subview.access %subview1[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
            %v1 = memref.load %subview1_obj[] : memref<i32>
            memref.store %v1, %buf23[%i1] : memref<4xi32>

            // Actually, give us the two from before and one more for three objects total (consumer lock should increase by one)
            %subview2 = aie.objectfifo.acquire @fifo (Consume, 3) : !aie.objectfifosubview<memref<i32>>
            %subview2_obj = aie.objectfifo.subview.access %subview2[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
            %v2 = memref.load %subview2_obj[] : memref<i32>
            memref.store %v2, %buf23[%i2] : memref<4xi32>

            // Now let's just work on one element (consumer lock should not change value)
            %subview3 = aie.objectfifo.acquire @fifo (Consume, 1) : !aie.objectfifosubview<memref<i32>>
            %subview3_obj = aie.objectfifo.subview.access %subview3[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
            %v3 = memref.load %subview3_obj[] : memref<i32>
            memref.store %v3, %buf23[%i3] : memref<4xi32>

            // Done, let's release everything we hold (we hold 3 objects from our max acquire)
            aie.objectfifo.release @fifo (Consume, 3)

            aie.end
        }
    }
}
