//===- AIE2_cyclostatic_L2.mlir --------------------------------*- MLIR -*-===//
//
// Copyright (C) 2023 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// In this example, an AIE core pushes data into a memtile, in a one-by-one
// fashion. The memtile forwards this one-by-one to a consumer tile. The
// consumer tile cyclostatically consumes {1, 2, 1} elements at a time.

// The way this gets lowered is as follows:
//
// - On the producer tile, two buffers get allocated. Each time the producer
//   wishes to push onto the objectFifo, the implementation alternates between
//   the two buffers (ping-pong). This way, the previous buffer remains
//   untouched while it is being pushed onto the stream. The other one can
//   meanwhile be filled with the next object.
//
// - On the memory tile, objects are read in from the stream one-by-one. Since
//   the objectFifo is allocated to hold _up to_ 4 elements, four buffers are
//   provisioned on the memory tile, into which data from the stream is
//   received. The "_cons" locks are used to notify the memory tile whenever
//   a single new object is ready on the stream. As the objects get pushed
//   from memory back out onto the stream, backpressure makes sure that no more
//   elements are written to the stream than are read on the receiving end.
//   Therefore, this boils down to forwarding objects one-by-one through the
//   memory tile (irrespective of what chunk size the consumer consumes).
//
// - On the receiving consumer end, four buffers are also preallocated, into
//   which the DMA copies objects arriving from the stream. This again is done
//   object-by-object. If the consumer needs more than one object at once, it
//   acquires the consumer locks multiple times.

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcve2302) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(2, 2)
// CHECK:           %[[VAL_1:.*]] = aie.tile(2, 1)
// CHECK:           %[[VAL_2:.*]] = aie.tile(8, 3)
// CHECK:           %[[VAL_3:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "fifo1_cons_buff_0"} : memref<1xi32>
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "fifo1_cons_buff_1"} : memref<1xi32>
// CHECK:           %[[VAL_5:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "fifo1_cons_buff_2"} : memref<1xi32>
// CHECK:           %[[VAL_6:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "fifo1_cons_buff_3"} : memref<1xi32>
// CHECK:           %[[VAL_7:.*]] = aie.lock(%[[VAL_2]], 0) {init = 4 : i32, sym_name = "fifo1_cons_prod_lock_0"}
// CHECK:           %[[VAL_8:.*]] = aie.lock(%[[VAL_2]], 1) {init = 0 : i32, sym_name = "fifo1_cons_cons_lock_0"}
// CHECK:           %[[VAL_9:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo0_cons_buff_0"} : memref<1xi32>
// CHECK:           %[[VAL_10:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo0_cons_buff_1"} : memref<1xi32>
// CHECK:           %[[VAL_11:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo0_cons_buff_2"} : memref<1xi32>
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo0_cons_buff_3"} : memref<1xi32>
// CHECK:           %[[VAL_13:.*]] = aie.lock(%[[VAL_1]], 0) {init = 4 : i32, sym_name = "fifo0_cons_prod_lock_0"}
// CHECK:           %[[VAL_14:.*]] = aie.lock(%[[VAL_1]], 1) {init = 0 : i32, sym_name = "fifo0_cons_cons_lock_0"}
// CHECK:           %[[VAL_15:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_0"} : memref<1xi32>
// CHECK:           %[[VAL_16:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_1"} : memref<1xi32>
// CHECK:           %[[VAL_17:.*]] = aie.lock(%[[VAL_0]], 0) {init = 2 : i32, sym_name = "fifo0_prod_lock_0"}
// CHECK:           %[[VAL_18:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "fifo0_cons_lock_0"}
// CHECK:           %[[VAL_19:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "buf83"} : memref<1xi32>
// CHECK:           aie.flow(%[[VAL_0]], DMA : 0, %[[VAL_1]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_1]], DMA : 0, %[[VAL_2]], DMA : 0)
// CHECK:           %[[VAL_20:.*]] = aie.core(%[[VAL_0]]) {
// CHECK:             %[[VAL_21:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_22:.*]] = arith.constant 88 : i32
// CHECK:             %[[VAL_23:.*]] = arith.constant 77 : i32
// CHECK:             %[[VAL_24:.*]] = arith.constant 66 : i32
// CHECK:             %[[VAL_25:.*]] = arith.constant 55 : i32
// CHECK:             %[[VAL_26:.*]] = arith.constant 0 : index
// CHECK:             aie.use_lock(%[[VAL_17]], AcquireGreaterEqual, %[[VAL_21]])
// CHECK:             memref.store %[[VAL_25]], %[[VAL_15]]{{\[}}%[[VAL_26]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_18]], Release, %[[VAL_21]])
// CHECK:             aie.use_lock(%[[VAL_17]], AcquireGreaterEqual, %[[VAL_21]])
// CHECK:             memref.store %[[VAL_24]], %[[VAL_16]]{{\[}}%[[VAL_26]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_18]], Release, %[[VAL_21]])
// CHECK:             aie.use_lock(%[[VAL_17]], AcquireGreaterEqual, %[[VAL_21]])
// CHECK:             memref.store %[[VAL_23]], %[[VAL_15]]{{\[}}%[[VAL_26]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_18]], Release, %[[VAL_21]])
// CHECK:             aie.use_lock(%[[VAL_17]], AcquireGreaterEqual, %[[VAL_21]])
// CHECK:             memref.store %[[VAL_22]], %[[VAL_16]]{{\[}}%[[VAL_26]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_18]], Release, %[[VAL_21]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_27:.*]] = aie.core(%[[VAL_2]]) {
// CHECK:             %[[VAL_28:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_29:.*]] = arith.constant 3 : index
// CHECK:             %[[VAL_30:.*]] = arith.constant 2 : index
// CHECK:             %[[VAL_31:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_32:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_33:.*]] = arith.constant 2 : i32
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:             %[[VAL_34:.*]] = memref.load %[[VAL_3]]{{\[}}%[[VAL_32]]] : memref<1xi32>
// CHECK:             memref.store %[[VAL_34]], %[[VAL_19]]{{\[}}%[[VAL_32]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_28]])
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_33]])
// CHECK:             %[[VAL_35:.*]] = memref.load %[[VAL_4]]{{\[}}%[[VAL_32]]] : memref<1xi32>
// CHECK:             %[[VAL_36:.*]] = memref.load %[[VAL_5]]{{\[}}%[[VAL_32]]] : memref<1xi32>
// CHECK:             memref.store %[[VAL_35]], %[[VAL_19]]{{\[}}%[[VAL_31]]] : memref<1xi32>
// CHECK:             memref.store %[[VAL_36]], %[[VAL_19]]{{\[}}%[[VAL_30]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_33]])
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:             %[[VAL_37:.*]] = memref.load %[[VAL_6]]{{\[}}%[[VAL_32]]] : memref<1xi32>
// CHECK:             memref.store %[[VAL_37]], %[[VAL_19]]{{\[}}%[[VAL_29]]] : memref<1xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_28]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_38:.*]] = aie.mem(%[[VAL_0]]) {
// CHECK:             %[[VAL_39:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_40:.*]] = aie.dma_start(MM2S, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_18]], AcquireGreaterEqual, %[[VAL_39]])
// CHECK:             aie.dma_bd(%[[VAL_15]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_17]], Release, %[[VAL_39]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_18]], AcquireGreaterEqual, %[[VAL_39]])
// CHECK:             aie.dma_bd(%[[VAL_16]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_17]], Release, %[[VAL_39]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_41:.*]] = aie.memtile_dma(%[[VAL_1]]) {
// CHECK:             %[[VAL_42:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_43:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb5)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_9]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_10]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb4:
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb5:
// CHECK:             %[[VAL_44:.*]] = aie.dma_start(MM2S, 0, ^bb6, ^bb10)
// CHECK:           ^bb6:
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_9]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb7
// CHECK:           ^bb7:
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_10]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb8
// CHECK:           ^bb8:
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb9
// CHECK:           ^bb9:
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_42]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_42]])
// CHECK:             aie.next_bd ^bb6
// CHECK:           ^bb10:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_45:.*]] = aie.mem(%[[VAL_2]]) {
// CHECK:             %[[VAL_46:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_47:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb5)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_3]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_8]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_4]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_8]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_5]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_8]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb4:
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_6]] : memref<1xi32>, 0, 1)
// CHECK:             aie.use_lock(%[[VAL_8]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb5:
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module @aie2_cyclostatic_L2 {
    aie.device(xcve2302) {

        %tile22 = aie.tile(2, 2)  // producer tile
        %memtile = aie.tile(2, 1) // mem tile
        %tile83 = aie.tile(8, 3)  // consumer tile
        %buf83  = aie.buffer(%tile83) {sym_name = "buf83"} : memref<1xi32>

        // ObjectFifo that can hold 4 memref<1xi32>s, populated by tile22 and
        // consumed by tile23
        aie.objectfifo @fifo0 (%tile22, {%memtile}, 4 : i32) : !aie.objectfifo<memref<1xi32>>
        aie.objectfifo @fifo1 (%memtile, {%tile83}, [4, 4]) : !aie.objectfifo<memref<1xi32>>
        aie.objectfifo.link [@fifo0] -> [@fifo1] ([] [])

        // Producer core
        %core22 = aie.core(%tile22) {
            %i0 = arith.constant 0 : index
            %c55 = arith.constant 55 : i32
            %c66 = arith.constant 66 : i32
            %c77 = arith.constant 77 : i32
            %c88 = arith.constant 88 : i32

            // Push 55
            %subview0 = aie.objectfifo.acquire @fifo0 (Produce, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview0_obj = aie.objectfifo.subview.access %subview0[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            memref.store %c55, %subview0_obj[%i0] : memref<1xi32>
            aie.objectfifo.release @fifo0 (Produce, 1)

            // Push 66
            %subview1 = aie.objectfifo.acquire @fifo0 (Produce, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview1_obj = aie.objectfifo.subview.access %subview1[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            memref.store %c66, %subview1_obj[%i0] : memref<1xi32>
            aie.objectfifo.release @fifo0 (Produce, 1)

            // Push 77
            %subview2 = aie.objectfifo.acquire @fifo0 (Produce, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview2_obj = aie.objectfifo.subview.access %subview2[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            memref.store %c77, %subview2_obj[%i0] : memref<1xi32>
            aie.objectfifo.release @fifo0 (Produce, 1)

            // Push 88
            %subview3 = aie.objectfifo.acquire @fifo0 (Produce, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview3_obj = aie.objectfifo.subview.access %subview3[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            memref.store %c88, %subview3_obj[%i0] : memref<1xi32>
            aie.objectfifo.release @fifo0 (Produce, 1)

            aie.end
        }

        // Consumer core
        %core28 = aie.core(%tile83) {
            // Consumer pattern: {1, 2, 1}
            %i0 = arith.constant 0 : index
            %i1 = arith.constant 1 : index
            %i2 = arith.constant 2 : index
            %i3 = arith.constant 3 : index

            // Pop 1 object off queue
            %subview0 = aie.objectfifo.acquire @fifo1 (Consume, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview0_obj = aie.objectfifo.subview.access %subview0[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            %v55 = memref.load %subview0_obj[%i0] : memref<1xi32>
            memref.store %v55, %buf83[%i0] : memref<1xi32>
            aie.objectfifo.release @fifo1 (Consume, 1)

            // Pop 2 objects off queue
            %subview1 = aie.objectfifo.acquire @fifo1 (Consume, 2) : !aie.objectfifosubview<memref<1xi32>>
            %subview1_obj0 = aie.objectfifo.subview.access %subview1[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            %subview1_obj1 = aie.objectfifo.subview.access %subview1[1] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            %v66 = memref.load %subview1_obj0[%i0] : memref<1xi32>
            %v77 = memref.load %subview1_obj1[%i0] : memref<1xi32>
            memref.store %v66, %buf83[%i1] : memref<1xi32>
            memref.store %v77, %buf83[%i2] : memref<1xi32>
            aie.objectfifo.release @fifo1 (Consume, 2)

            // Pop 1 object off queue
            %subview2 = aie.objectfifo.acquire @fifo1 (Consume, 1) : !aie.objectfifosubview<memref<1xi32>>
            %subview2_obj = aie.objectfifo.subview.access %subview2[0] : !aie.objectfifosubview<memref<1xi32>> -> memref<1xi32>
            %v88 = memref.load %subview2_obj[%i0] : memref<1xi32>
            memref.store %v88, %buf83[%i3] : memref<1xi32>
            aie.objectfifo.release @fifo1 (Consume, 1)

            aie.end
        }

    }
}
