//===- AIE2_static_L1.mlir -------------------------------------*- MLIR -*-===//
//
// Copyright (C) 2023 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// This tests a static pattern where a producer writes one element and a
// consumer consumes two elements at a time. The cores are adjacent to
// one another and should use shared memory.
// In this case, "objects" really are just simple i32s.
// The producer simply counts up from 0, step size 1.
// The consumer copies what it sees into %dstbuf23.
// In the end, %dstbuf23 should hold [0, 1, 2, 3, 4, 5, ... 15]

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-assign-lock-ids --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcve2302) {
// CHECK:           %[[VAL_0:.*]] = arith.constant 16 : index
// CHECK:           %[[VAL_1:.*]] = arith.constant 2 : index
// CHECK:           %[[VAL_2:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_3:.*]] = aie.tile(2, 2)
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "srcbuf22"} : memref<i32>
// CHECK:           %[[VAL_5:.*]] = aie.tile(2, 3)
// CHECK:           %[[VAL_6:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "fifo_buff_0"} : memref<i32>
// CHECK:           %[[VAL_7:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "fifo_buff_1"} : memref<i32>
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "fifo_buff_2"} : memref<i32>
// CHECK:           %[[VAL_9:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "fifo_buff_3"} : memref<i32>
// CHECK:           %[[VAL_10:.*]] = aie.lock(%[[VAL_3]], 0) {init = 4 : i32, sym_name = "fifo_prod_lock_0"}
// CHECK:           %[[VAL_11:.*]] = aie.lock(%[[VAL_3]], 1) {init = 0 : i32, sym_name = "fifo_cons_lock_0"}
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_5]]) {sym_name = "dstbuf22"} : memref<16xi32>
// CHECK:           %[[VAL_13:.*]] = aie.core(%[[VAL_3]]) {
// CHECK:             %[[VAL_14:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_15:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_16:.*]] = arith.constant 4 : index
// CHECK:             memref.store %[[VAL_15]], %[[VAL_4]][] : memref<i32>
// CHECK:             scf.for %[[VAL_17:.*]] = %[[VAL_2]] to %[[VAL_0]] step %[[VAL_16]] {
// CHECK:               %[[VAL_18:.*]] = memref.load %[[VAL_4]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_14]])
// CHECK:               memref.store %[[VAL_18]], %[[VAL_6]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_11]], Release, %[[VAL_14]])
// CHECK:               %[[VAL_19:.*]] = arith.addi %[[VAL_18]], %[[VAL_14]] : i32
// CHECK:               memref.store %[[VAL_19]], %[[VAL_4]][] : memref<i32>
// CHECK:               %[[VAL_20:.*]] = memref.load %[[VAL_4]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_14]])
// CHECK:               memref.store %[[VAL_20]], %[[VAL_7]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_11]], Release, %[[VAL_14]])
// CHECK:               %[[VAL_21:.*]] = arith.addi %[[VAL_20]], %[[VAL_14]] : i32
// CHECK:               memref.store %[[VAL_21]], %[[VAL_4]][] : memref<i32>
// CHECK:               %[[VAL_22:.*]] = memref.load %[[VAL_4]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_14]])
// CHECK:               memref.store %[[VAL_22]], %[[VAL_8]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_11]], Release, %[[VAL_14]])
// CHECK:               %[[VAL_23:.*]] = arith.addi %[[VAL_22]], %[[VAL_14]] : i32
// CHECK:               memref.store %[[VAL_23]], %[[VAL_4]][] : memref<i32>
// CHECK:               %[[VAL_24:.*]] = memref.load %[[VAL_4]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_14]])
// CHECK:               memref.store %[[VAL_24]], %[[VAL_9]][] : memref<i32>
// CHECK:               aie.use_lock(%[[VAL_11]], Release, %[[VAL_14]])
// CHECK:               %[[VAL_25:.*]] = arith.addi %[[VAL_24]], %[[VAL_14]] : i32
// CHECK:               memref.store %[[VAL_25]], %[[VAL_4]][] : memref<i32>
// CHECK:             }
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_26:.*]] = aie.core(%[[VAL_5]]) {
// CHECK:             %[[VAL_27:.*]] = arith.constant 8 : index
// CHECK:             %[[VAL_28:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_29:.*]] = arith.constant 4 : index
// CHECK:             %[[VAL_30:.*]] = arith.constant 6 : index
// CHECK:             scf.for %[[VAL_31:.*]] = %[[VAL_2]] to %[[VAL_0]] step %[[VAL_27]] {
// CHECK:               aie.use_lock(%[[VAL_11]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:               %[[VAL_32:.*]] = memref.load %[[VAL_6]][] : memref<i32>
// CHECK:               %[[VAL_33:.*]] = memref.load %[[VAL_7]][] : memref<i32>
// CHECK:               func.call @store2(%[[VAL_32]], %[[VAL_33]], %[[VAL_31]], %[[VAL_12]]) : (i32, i32, index, memref<16xi32>) -> ()
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_28]])
// CHECK:               %[[VAL_34:.*]] = arith.addi %[[VAL_31]], %[[VAL_1]] : index
// CHECK:               aie.use_lock(%[[VAL_11]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:               %[[VAL_35:.*]] = memref.load %[[VAL_8]][] : memref<i32>
// CHECK:               %[[VAL_36:.*]] = memref.load %[[VAL_9]][] : memref<i32>
// CHECK:               func.call @store2(%[[VAL_35]], %[[VAL_36]], %[[VAL_34]], %[[VAL_12]]) : (i32, i32, index, memref<16xi32>) -> ()
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_28]])
// CHECK:               %[[VAL_37:.*]] = arith.addi %[[VAL_31]], %[[VAL_29]] : index
// CHECK:               aie.use_lock(%[[VAL_11]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:               %[[VAL_38:.*]] = memref.load %[[VAL_6]][] : memref<i32>
// CHECK:               %[[VAL_39:.*]] = memref.load %[[VAL_7]][] : memref<i32>
// CHECK:               func.call @store2(%[[VAL_38]], %[[VAL_39]], %[[VAL_37]], %[[VAL_12]]) : (i32, i32, index, memref<16xi32>) -> ()
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_28]])
// CHECK:               %[[VAL_40:.*]] = arith.addi %[[VAL_31]], %[[VAL_30]] : index
// CHECK:               aie.use_lock(%[[VAL_11]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:               %[[VAL_41:.*]] = memref.load %[[VAL_8]][] : memref<i32>
// CHECK:               %[[VAL_42:.*]] = memref.load %[[VAL_9]][] : memref<i32>
// CHECK:               func.call @store2(%[[VAL_41]], %[[VAL_42]], %[[VAL_40]], %[[VAL_12]]) : (i32, i32, index, memref<16xi32>) -> ()
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_28]])
// CHECK:             }
// CHECK:             aie.end
// CHECK:           }
// CHECK:           func.func @store2(%[[VAL_43:.*]]: i32, %[[VAL_44:.*]]: i32, %[[VAL_45:.*]]: index, %[[VAL_46:.*]]: memref<16xi32>) {
// CHECK:             %[[VAL_47:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_48:.*]] = index.add %[[VAL_45]], %[[VAL_47]]
// CHECK:             memref.store %[[VAL_43]], %[[VAL_46]]{{\[}}%[[VAL_45]]] : memref<16xi32>
// CHECK:             memref.store %[[VAL_44]], %[[VAL_46]]{{\[}}%[[VAL_48]]] : memref<16xi32>
// CHECK:             return
// CHECK:           }
// CHECK:         }

module @aie2_static_L1 {
    aie.device(xcve2302) {
        %i_c0 = arith.constant 0 : index
        %i_c1 = arith.constant 1 : index
        %i_c2 = arith.constant 2 : index
        %i_c16 = arith.constant 16 : index

        %tile22 = aie.tile(2, 2)  // producer tile
        %srcbuf22 = aie.buffer(%tile22) { sym_name = "srcbuf22" } : memref<i32>

        %tile23 = aie.tile(2, 3)  // consumer tile
        %dstbuf23 = aie.buffer(%tile23) { sym_name = "dstbuf22" } : memref<16xi32>

        // ObjectFifo that can hold 4 memref<i32>s, populated by tile22 and
        // consumed by tile23
        aie.objectfifo @fifo (%tile22, {%tile23}, 4 : i32) : !aie.objectfifo<memref<i32>>

        // Producer core
        %core22 = aie.core(%tile22) {
            // Initialize value to zero
            %c0 = arith.constant 0 : i32
            %c1 = arith.constant 1 : i32
            memref.store %c0, %srcbuf22[] : memref<i32>

            // Count up, with each iteration pushing a new element on to the fifo
            scf.for %idx = %i_c0 to %i_c16 step %i_c1 {
                %val0 = memref.load %srcbuf22[] : memref<i32>
                // Produce 1 elements, so acquire 1 element
                %subview = aie.objectfifo.acquire @fifo (Produce, 1) : !aie.objectfifosubview<memref<i32>>
                %elem = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
                memref.store %val0, %elem[] : memref<i32>
                aie.objectfifo.release @fifo (Produce, 1)
                // Increment
                %val1 = arith.addi %c1, %val0 : i32
                memref.store %val1, %srcbuf22[] : memref<i32>
            }

            aie.end
        }

        // Consumer core
        %core23 = aie.core(%tile23) {
            scf.for %idx = %i_c0 to %i_c16 step %i_c2 {
                // Consume _two_ elements at once (cyclo static)
                %subview = aie.objectfifo.acquire @fifo (Consume, 2) : !aie.objectfifosubview<memref<i32>>
                %elem0 = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
                %elem1 = aie.objectfifo.subview.access %subview[1] : !aie.objectfifosubview<memref<i32>> -> memref<i32>
                %val0 = memref.load %elem0[] : memref<i32>
                %val1 = memref.load %elem1[] : memref<i32>
                // Pass through to destination buffer
                func.call @store2(%val0, %val1, %idx, %dstbuf23) : (i32, i32, index, memref<16xi32>) -> ()
                // Release consumed objects
                aie.objectfifo.release @fifo (Consume, 2)
            }

            aie.end
        }

        func.func @store2(%val0: i32, %val1: i32, %base : index, %buf : memref<16xi32>) -> () {
                %ic0 = arith.constant 0 : index
                %ic1 = arith.constant 1 : index
                %idx0 = index.add %ic0, %base
                %idx1 = index.add %ic1, %base
                memref.store %val0, %buf[%idx0] : memref<16xi32>
                memref.store %val1, %buf[%idx1] : memref<16xi32>
                return
        }
    }
}
