//===- cyclostatic_AIE2.mlir ------------------------------------------------*- MLIR -*-===//
//
// Copyright (C) 2023 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Date: July 10th 2023
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcve2302) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(1, 2)
// CHECK:           %[[VAL_1:.*]] = aie.tile(2, 2)
// CHECK:           %[[VAL_2:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_3:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_1"} : memref<16xi32>
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_2"} : memref<16xi32>
// CHECK:           %[[VAL_5:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo0_buff_3"} : memref<16xi32>
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_0]], 0) {init = 4 : i32, sym_name = "fifo0_prod_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "fifo0_cons_lock_0"}
// CHECK:           %[[VAL_8:.*]] = aie.core(%[[VAL_0]]) {
// CHECK:             %[[VAL_9:.*]] = arith.constant 4 : index
// CHECK:             %[[VAL_10:.*]] = arith.constant 8 : index
// CHECK:             %[[VAL_11:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_12:.*]] = arith.constant 11 : i32
// CHECK:             %[[VAL_13:.*]] = arith.constant 1 : i32
// CHECK:             scf.for %[[VAL_14:.*]] = %[[VAL_11]] to %[[VAL_10]] step %[[VAL_9]] {
// CHECK:               aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:               memref.store %[[VAL_12]], %[[VAL_2]]{{\[}}%[[VAL_11]]] : memref<16xi32>
// CHECK:               aie.use_lock(%[[VAL_7]], Release, %[[VAL_13]])
// CHECK:               aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:               memref.store %[[VAL_12]], %[[VAL_3]]{{\[}}%[[VAL_11]]] : memref<16xi32>
// CHECK:               aie.use_lock(%[[VAL_7]], Release, %[[VAL_13]])
// CHECK:               aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:               memref.store %[[VAL_12]], %[[VAL_4]]{{\[}}%[[VAL_11]]] : memref<16xi32>
// CHECK:               aie.use_lock(%[[VAL_7]], Release, %[[VAL_13]])
// CHECK:               aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:               memref.store %[[VAL_12]], %[[VAL_5]]{{\[}}%[[VAL_11]]] : memref<16xi32>
// CHECK:               aie.use_lock(%[[VAL_7]], Release, %[[VAL_13]])
// CHECK:             }
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_13]])
// CHECK:             memref.store %[[VAL_12]], %[[VAL_2]]{{\[}}%[[VAL_11]]] : memref<16xi32>
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_13]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_15:.*]] = aie.core(%[[VAL_1]]) {
// CHECK:             %[[VAL_16:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_17:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_18:.*]] = arith.constant 4 : i32
// CHECK:             %[[VAL_19:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_20:.*]] = arith.constant 8 : index
// CHECK:             %[[VAL_21:.*]] = arith.constant 4 : index
// CHECK:             %[[VAL_22:.*]] = arith.constant 3 : i32
// CHECK:             %[[VAL_23:.*]] = arith.constant 2 : i32
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_16]])
// CHECK:             aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:             %[[VAL_24:.*]] = scf.for %[[VAL_25:.*]] = %[[VAL_17]] to %[[VAL_20]] step %[[VAL_21]] iter_args(%[[VAL_26:.*]] = %[[VAL_19]]) -> (i32) {
// CHECK:               %[[VAL_27:.*]] = arith.subi %[[VAL_22]], %[[VAL_26]] : i32
// CHECK:               %[[VAL_28:.*]] = arith.maxsi %[[VAL_27]], %[[VAL_19]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_28]])
// CHECK:               %[[VAL_29:.*]] = arith.addi %[[VAL_26]], %[[VAL_28]] : i32
// CHECK:               aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:               %[[VAL_30:.*]] = arith.subi %[[VAL_29]], %[[VAL_16]] : i32
// CHECK:               %[[VAL_31:.*]] = arith.subi %[[VAL_18]], %[[VAL_29]] : i32
// CHECK:               %[[VAL_32:.*]] = arith.maxsi %[[VAL_31]], %[[VAL_19]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_32]])
// CHECK:               %[[VAL_33:.*]] = arith.addi %[[VAL_30]], %[[VAL_32]] : i32
// CHECK:               aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:               %[[VAL_34:.*]] = arith.subi %[[VAL_33]], %[[VAL_16]] : i32
// CHECK:               %[[VAL_35:.*]] = arith.subi %[[VAL_18]], %[[VAL_33]] : i32
// CHECK:               %[[VAL_36:.*]] = arith.maxsi %[[VAL_35]], %[[VAL_19]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_36]])
// CHECK:               %[[VAL_37:.*]] = arith.addi %[[VAL_34]], %[[VAL_36]] : i32
// CHECK:               aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:               %[[VAL_38:.*]] = arith.subi %[[VAL_37]], %[[VAL_16]] : i32
// CHECK:               %[[VAL_39:.*]] = arith.subi %[[VAL_18]], %[[VAL_37]] : i32
// CHECK:               %[[VAL_40:.*]] = arith.maxsi %[[VAL_39]], %[[VAL_19]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_40]])
// CHECK:               %[[VAL_41:.*]] = arith.addi %[[VAL_38]], %[[VAL_40]] : i32
// CHECK:               aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:               %[[VAL_42:.*]] = arith.subi %[[VAL_41]], %[[VAL_16]] : i32
// CHECK:               scf.yield %[[VAL_42]] : i32
// CHECK:             }
// CHECK:             %[[VAL_43:.*]] = arith.subi %[[VAL_22]], %[[VAL_24]] : i32
// CHECK:             %[[VAL_44:.*]] = arith.maxsi %[[VAL_43]], %[[VAL_19]] : i32
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_44]])
// CHECK:             %[[VAL_45:.*]] = arith.addi %[[VAL_24]], %[[VAL_44]] : i32
// CHECK:             aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:             %[[VAL_46:.*]] = arith.subi %[[VAL_22]], %[[VAL_45]] : i32
// CHECK:             %[[VAL_47:.*]] = arith.maxsi %[[VAL_46]], %[[VAL_19]] : i32
// CHECK:             aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_47]])
// CHECK:             aie.use_lock(%[[VAL_6]], Release, %[[VAL_23]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module @cyclostatic {
    aie.device(xcve2302) {
        %tile12 = aie.tile(1, 2)
        %tile23 = aie.tile(2, 2)

        aie.objectfifo @fifo0 (%tile12, {%tile23}, 4 : i32) : !aie.objectfifo<memref<16xi32>>

        %core12 = aie.core(%tile12) {
            %v11 = arith.constant 11 : i32
            %c0 = arith.constant 0 : index
            %c1 = arith.constant 1 : index
            %c9 = arith.constant 9 : index

            scf.for %indexInHeight = %c0 to %c9 step %c1 {
                %subview1 = aie.objectfifo.acquire @fifo0 (Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
                %subview1_obj = aie.objectfifo.subview.access %subview1[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                memref.store %v11, %subview1_obj[%c0] : memref<16xi32>
                aie.objectfifo.release @fifo0 (Produce, 1)
            }

            aie.end
        }

        %core23 = aie.core(%tile23) {
            %c0 = arith.constant 0 : index
            %c1 = arith.constant 1 : index
            %c9 = arith.constant 9 : index

            %subview0 = aie.objectfifo.acquire @fifo0 (Consume, 1) : !aie.objectfifosubview<memref<16xi32>>
            %subview0_obj = aie.objectfifo.subview.access %subview0[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
            %v0 = memref.load %subview0_obj[%c0] : memref<16xi32>
            aie.objectfifo.release @fifo0 (Consume, 1)

            scf.for %indexInHeight = %c0 to %c9 step %c1 {
                %subview1 = aie.objectfifo.acquire @fifo0 (Consume, 3) : !aie.objectfifosubview<memref<16xi32>>
                %subview1_obj = aie.objectfifo.subview.access %subview1[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                %subview1_obj1 = aie.objectfifo.subview.access %subview1[1] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                %subview1_obj2 = aie.objectfifo.subview.access %subview1[2] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
                %v1 = memref.load %subview1_obj[%c0] : memref<16xi32>
                %v2 = memref.load %subview1_obj1[%c0] : memref<16xi32>
                %v3 = memref.load %subview1_obj2[%c0] : memref<16xi32>
                aie.objectfifo.release @fifo0 (Consume, 1)
            }

            %subview2 = aie.objectfifo.acquire @fifo0 (Consume, 2) : !aie.objectfifosubview<memref<16xi32>>
            %subview2_obj = aie.objectfifo.subview.access %subview2[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
            %subview2_obj1 = aie.objectfifo.subview.access %subview2[1] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
            %v4 = memref.load %subview2_obj[%c0] : memref<16xi32>
            %v5 = memref.load %subview2_obj1[%c0] : memref<16xi32>
            aie.objectfifo.release @fifo0 (Consume, 2)

            aie.end
        }
    }
}
