# dmatask.py -*- Python -*-
#
# Copyright (C) 2024 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""DMATask: a RuntimeTask that generates a shim DMA transfer operation."""

from ... import ir  # pyright: ignore[reportMissingImports, reportAttributeAccessIssue]

from ...dialects._aiex_ops_gen import (  # pyright: ignore[reportMissingImports]
    dma_start_task,
)
from ...dialects.aiex import shim_dma_single_bd_task
from ..dataflow import ObjectFifoHandle
from .data import RuntimeData
from ...helpers.taplib import TensorAccessPattern
from .task import RuntimeTask
from .taskgroup import TaskGroup


class DMATask(RuntimeTask):
    def __init__(
        self,
        object_fifo: ObjectFifoHandle,
        rt_data: RuntimeData,
        tap: TensorAccessPattern,
        task_group: TaskGroup | None = None,
        wait: bool = False,
        offset_parameter: str | None = None,
        packet: tuple[int, int] | None = None,
    ):
        """A RuntimeTask that will resolve to a DMA Operation.

        Args:
            object_fifo (ObjectFifoHandle): The ObjectFifoHandle associated with the operation
            rt_data (RuntimeData): The Runtime buffer associated with the operation.
            tap (TensorAccessPattern): The access pattern associated with the operation.
            task_group (TaskGroup | None, optional): The task group associated with the operation. Defaults to None.
            wait (bool, optional): Whether this task should conclude with a call to await or a call to free. Defaults to False.
            offset_parameter (str | None, optional): Name of a ScratchpadParameter whose value is used as the element offset for this DMA transfer. Defaults to None.
            packet (tuple[int, int] | None, optional): Stamp the shim DMA's
                BD with a packet header `(pkt_type, pkt_id)`. Pairs with
                downstream packet-switched routing (e.g. ObjectFifos
                lowered with `--packet-sw-objFifos` or an explicit
                [`PacketFlow`][iron.PacketFlow]). Defaults to None.
        """
        self._object_fifo = object_fifo
        self._rt_data = rt_data
        self._tap = tap
        self._wait = wait
        self._offset_parameter = offset_parameter
        self._packet = packet
        self._task = None
        RuntimeTask.__init__(self, task_group)

    def will_wait(self) -> bool:
        """Whether this task should conclude with an await operation."""
        return self._wait

    @property
    def fifo(self) -> ObjectFifoHandle:
        """The ObjectFifoHandle associated with this task."""
        return self._object_fifo

    @property
    def task(self):
        """The MLIR op generated by resolve(). This handle is used after resolution for await or free operations as
        dictated by a TaskGroup Finish operation"""
        if not self._task:
            raise ValueError("Cannot get task before it is created (during resolve())")
        return self._task

    def resolve(
        self,
        loc: ir.Location | None = None,
        ip: ir.InsertionPoint | None = None,
    ) -> None:
        # Reference the ObjectFifo by symbol name, not its resolved op: the DMA
        # only needs the metadata symbol (shim_dma_single_bd_task reduces an op
        # to its sym_name anyway), and a name is a legal MLIR forward reference.
        # This lets the runtime sequence body emit before fifos are resolved, so
        # the body runs exactly once.
        self._task = shim_dma_single_bd_task(
            self._object_fifo.name,
            self._rt_data.op,
            tap=self._tap,
            issue_token=self._wait,
            offset_parameter=self._offset_parameter,
            packet=self._packet,  # pyright: ignore[reportArgumentType]
        )
        dma_start_task(self._task)
