# dmatask.py -*- Python -*-
#
# Copyright (C) 2024 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""DMATask: a RuntimeTask that generates a shim DMA transfer operation."""

from ... import ir  # pyright: ignore[reportMissingImports, reportAttributeAccessIssue]
from ...dialects._aiex_ops_gen import (  # pyright: ignore[reportMissingImports]
    dma_start_task,
)
from ...dialects.aiex import shim_dma_single_bd_task
from ...helpers.taplib import TensorAccessPattern
from .data import RuntimeData
from .dmataskhandle import Task
from .task import RuntimeTask
from .taskgroup import TaskGroup


class DMATask(RuntimeTask):
    def __init__(
        self,
        alloc: str,
        rt_data: RuntimeData,
        tap: TensorAccessPattern | None = None,
        task_group: TaskGroup | None = None,
        wait: bool = False,
        offset_parameter: str | None = None,
        packet: tuple[int, int] | None = None,
        sizes=None,
        strides=None,
        offset=None,
        transfer_len=None,
    ):
        """Construct a RuntimeTask that will resolve to a DMA Operation.

        Provide the access pattern either as a static ``tap``
        (TensorAccessPattern) or as explicit ``sizes``/``strides``/``offset``/
        ``transfer_len`` lists whose entries may be runtime SSA values (for the
        dynamic lowering). The two forms are mutually exclusive.

        Args:
            alloc (str): Name of the shim DMA allocation this transfer drives,
                i.e. the symbol naming the shim channel. An
                [`ObjectFifo`][iron.ObjectFifo] with a shim endpoint generates an
                allocation of its own name; a [`Flow`][iron.Flow] generates one
                for its ``shim_symbol``.
            rt_data (RuntimeData): The Runtime buffer associated with the operation.
            tap (TensorAccessPattern | None, optional): The static access pattern. Mutually exclusive with sizes/strides/offset/transfer_len.
            task_group (TaskGroup | None, optional): The task group associated with the operation. Defaults to None.
            wait (bool, optional): Whether this task should conclude with a call to await or a call to free. Defaults to False.
            offset_parameter (str | None, optional): Name of a ScratchpadParameter whose
                value is used as the element offset for this DMA transfer. Defaults to None.
            packet (tuple[int, int] | None, optional): Stamp the shim DMA's
                BD with a packet header `(pkt_type, pkt_id)`. Pairs with
                downstream packet-switched routing (e.g. an
                [`ObjectFifo`][iron.ObjectFifo] built with ``packet=True`` or
                an explicit [`PacketFlow`][iron.PacketFlow]). Defaults to None.
            sizes (optional): Explicit access-pattern sizes whose entries may be
                runtime SSA values. Used instead of ``tap`` for the dynamic path.
            strides (optional): Explicit access-pattern strides, paired with
                ``sizes``. Used instead of ``tap`` for the dynamic path.
            offset (optional): Explicit access-pattern offset. Used instead of
                ``tap`` for the dynamic path.
            transfer_len (optional): Explicit access-pattern transfer length.
                Used instead of ``tap`` for the dynamic path.
        """
        if tap is not None and any(
            v is not None for v in (sizes, strides, offset, transfer_len)
        ):
            raise ValueError(
                "DMATask: tap and sizes/strides/offset/transfer_len are mutually "
                "exclusive access-pattern specifications; pass only one."
            )
        self._alloc = alloc
        self._rt_data = rt_data
        self._tap = tap
        self._wait = wait
        self._offset_parameter = offset_parameter
        self._packet = packet
        self._sizes = sizes
        self._strides = strides
        self._offset = offset
        self._transfer_len = transfer_len
        self._task = None
        RuntimeTask.__init__(self, task_group)

    def will_wait(self) -> bool:
        """Whether this task should conclude with an await operation."""
        return self._wait

    @property
    def task(self):
        """Return the MLIR op generated by resolve().

        This handle is used after resolution for await or free operations as
        dictated by a TaskGroup Finish operation.
        """
        if not self._task:
            raise ValueError("Cannot get task before it is created (during resolve())")
        return self._task

    def resolve(
        self,
        loc: ir.Location | None = None,
        ip: ir.InsertionPoint | None = None,
    ) -> None:
        # Reference the shim allocation by symbol name, not by a resolved op:
        # the DMA only needs the metadata symbol (shim_dma_single_bd_task
        # reduces an op to its sym_name anyway). That keeps building the task
        # independent of the op that declares the allocation, so this code does
        # not have to hold or thread one.
        if self._tap is not None:
            self._task = shim_dma_single_bd_task(
                self._alloc,
                self._rt_data.op,
                tap=self._tap,
                issue_token=self._wait,
                offset_parameter=self._offset_parameter,
                packet=self._packet,  # pyright: ignore[reportArgumentType]
            )
        else:
            # Explicit (possibly runtime-valued) access pattern for the dynamic path.
            self._task = shim_dma_single_bd_task(
                self._alloc,
                self._rt_data.op,
                offset=self._offset,
                sizes=self._sizes,
                strides=self._strides,
                transfer_len=self._transfer_len,
                issue_token=self._wait,
                offset_parameter=self._offset_parameter,
                packet=self._packet,  # pyright: ignore[reportArgumentType]
            )
        dma_start_task(self._task)


def emit_shim_transfer(
    alloc: str,
    rt_data,
    tap=None,
    wait: bool = False,
    packet: tuple[int, int] | None = None,
    offset_parameter=None,
    group=None,
    sizes=None,
    strides=None,
    offset=None,
    transfer_len=None,
    managed: bool = True,
) -> Task:
    """Emit one shim DMA transfer on the ``alloc`` channel, inside the active sequence.

    The body shared by the runtime's data-movement verbs --
    ``ObjectFifoHandle.fill``/``drain`` and ``Flow.fill``/``drain`` -- which
    differ only in how they name the shim channel and in the endpoint
    bookkeeping they do first.

    The access pattern is given either as a static ``tap`` or as explicit
    ``sizes``/``strides``/``offset``/``transfer_len`` whose entries may be
    runtime SSA values (the dynamic path). The two forms are mutually exclusive;
    when neither is given, a linear transfer of the whole buffer is used.

    When ``managed`` is True (default), the transfer is enrolled in a TaskGroup
    (explicit ``group`` or the sequence's implicit one), which awaits/frees it at
    group close. When False, the caller owns the transfer's lifetime via the
    returned Task's ``.free()``/``.await_()`` -- used for hand-rolled software
    pipelines that carry the task across ``scf.for`` iterations.

    Returns:
        Task: A handle to the transfer.

    Lazy imports break the runtime<->scratchpad import cycle.
    """
    from ..scratchpad_parameter import ScratchpadParameter
    from ._context import active_sequence

    active = active_sequence()
    rt = active._runtime

    if not isinstance(rt_data, RuntimeData):
        raise ValueError(f"Expected a RuntimeData source/dest, got {rt_data}")
    if rt_data not in rt._rt_data:
        raise ValueError(
            f"{rt_data} is not a RuntimeData object declared by sequence()"
        )

    explicit = any(v is not None for v in (sizes, strides, offset, transfer_len))
    if tap is not None and explicit:
        raise ValueError(
            "Pass either tap or sizes/strides/offset/transfer_len, not both."
        )
    if tap is None and not explicit:
        tap = rt_data.default_tap()

    if not managed and group is not None:
        raise ValueError(
            "An unmanaged transfer (managed=False) is not part of a TaskGroup; "
            "do not also pass group=."
        )

    offset_param_name = None
    if offset_parameter is not None:
        if isinstance(offset_parameter, ScratchpadParameter):
            offset_param_name = offset_parameter.name
            if offset_parameter not in rt._scratchpad_parameters:
                rt._scratchpad_parameters.append(offset_parameter)
        else:
            offset_param_name = offset_parameter

    task = DMATask(
        alloc,
        rt_data,
        tap=tap,
        task_group=group,
        wait=wait,
        offset_parameter=offset_param_name,
        packet=packet,
        sizes=sizes,
        strides=strides,
        offset=offset,
        transfer_len=transfer_len,
    )
    if managed:
        active.emit_transfer(task, group)
    else:
        # Emit the BD only; the caller owns await/free via the Task.
        task.resolve()
    # Wrap the transfer's !index result: it is both the scf iter_arg payload
    # and the operand dma_await_task/dma_free_task accept.
    return Task(task.task.result)
