MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x20000, LENGTH = 0x0020000
}
ENTRY(_main_init)
SECTIONS
{
  . = 0x0;
  .text : { 
     // the _main_init symbol from me_basic.o has to come at address zero.
     *me_basic.o(.text)
     . = 0x200;
     *(.text)
  } > program
  .data : { *(.data) } > data
  . = 0x20000;
  _sp_start_value_DM_stack = .;
  . = 0x24000;
  a = .;
  . += 1024;
  .bss : { *(.bss) } > data
}
