// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
//===- simple.mlir ---------------------------------------------*- MLIR -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// (c) Copyright 2021 Xilinx Inc.
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-canonicalize-device %s | FileCheck %s
// CHECK: aie.device(xcvc1902) {
// CHECK:   %[[T0:.*]] = aie.tile(0, 1)
// CHECK:   %[[T1:.*]] = aie.tile(1, 2)
// CHECK:   %[[T2:.*]] = aie.tile(0, 2)
// CHECK:   aie.flow(%[[T0]], DMA : 0, %[[T1]], Core : 1)
// CHECK:   aie.packet_flow(16) {
// CHECK:     aie.packet_source<%[[T0]], Core : 0>
// CHECK:     aie.packet_dest<%[[T1]], Core : 0>
// CHECK:     aie.packet_dest<%[[T2]], DMA : 1>
// CHECK:   }
// CHECK: }

module {
  %01 = aie.tile(0, 1)
  %12 = aie.tile(1, 2)
  %02 = aie.tile(0, 2)
  aie.flow(%01, DMA : 0, %12, Core : 1)
  aie.packet_flow(0x10) {
    aie.packet_source < %01, Core : 0>
    aie.packet_dest < %12, Core : 0>
    aie.packet_dest < %02, DMA : 1>
  }
}
