//===- yolo_conv2dk3_stride2_silu_bias_oiyxi8o8.h ------------------*- C++
//-*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2026, Advanced Micro Devices, Inc.
//
// 3x3 stride-2 INT8 conv with INT32 bias accumulator-init + INT8 SiLU LUT.
// Weights are OIYXI8O8 packed (shared by yolo26n m1/m3/m5/m7 — every
// conv_stride block except m0 whose in_c=3 isn't 8-aligned).
//
// Activation layout: (in_w, 1, in_c) int8.
// Weight layout:     (O/8, I/8, kH, kW, 8 [I-inner], 8 [O-inner]) int8 flat.
// Output layout:     (out_w=in_w/2, 1, out_c) int8.
// Border:  0 = skip top, 1 = all 3 rows, 2 = skip bot (matches sim).
// SiLU LUT: 256-entry int8 indexed by pre_silu+128, generated by
// gen_yolo_silu_luts.py.
//
//===----------------------------------------------------------------------===//

#ifndef _YOLO_CONV2DK3_STRIDE2_SILU_BIAS_OIYXI8O8_H
#define _YOLO_CONV2DK3_STRIDE2_SILU_BIAS_OIYXI8O8_H

#include <stdint.h>

extern "C" {

void yolo_conv2dk3_stride2_silu_bias_oiyxi8o8_i8_i8(
    int8_t *line0, int8_t *line1, int8_t *line2, int8_t *wts, int32_t *bias,
    int8_t *silu_lut, int8_t *output, const int32_t input_width,
    const int32_t input_channels, const int32_t output_channels,
    const int32_t kernel_width, const int32_t kernel_height,
    const int32_t border, const int32_t right_shift, const int32_t padding);

} // extern "C"

#endif
