//===- yolo_m0_conv2dk3_silu_bias.h -------------------------------*- C++ -*-===//
//
// 3x3 stride-2 INT8 conv kernel for yolo26n-cls m0 stem (512x512x8 -> 256x256x16).
//
// Forked from mlir-aie/aie_kernels/aie2/bottleneck/bn_conv2dk3.cc with patches:
//   - output type uint8 -> int8 (SiLU output is signed; clamp [-128, 127])
//   - int32 bias added as accumulator-init (replaces sum=0)
//   - weight layout: OIYX raw (m0's in_c=3 isn't 8-aligned, can't pack to OIYXI8O8;
//                    matches iron_sim_kernels._m0_conv3x3_stride2)
//   - border arg: 0 = skip top row, 1 = all 3, 2 = skip bot row (matches sim)
//   - SiLU LUT applied via runtime int8 lookup (LUT generated by
//                    gen_yolo_silu_luts.py from the Quark XINT8 ONNX scales)
//   - target: aie2p (Strix)
//
//===----------------------------------------------------------------------===//

#ifndef _YOLO_M0_CONV2DK3_SILU_BIAS_H
#define _YOLO_M0_CONV2DK3_SILU_BIAS_H

#include <stdint.h>

extern "C" {

// Compute one output row of a 3x3 stride-2 INT8 conv with INT32 bias init.
//
// Inputs: three input rows (top neighbor, current, bottom neighbor), each
// shape (input_width, 1, input_channels) i8. For the first output row m0's
// builder passes line0 == line1 (= input row 0) so top-row replication falls
// out naturally without special-casing.
//
// Output: one row (output_width = input_width/2, 1, output_channels) i8.
//
// Args mirror the per-block builder's Kernel signature
// (aie2_yolo_per_block.py, _build_m0).
void yolo_m0_conv2dk3_stride2_silu_bias_i8_i8(
    int8_t *line0, int8_t *line1, int8_t *line2,
    int8_t *wts,
    int32_t *bias,
    int8_t *silu_lut,           // 256-entry int8 LUT, indexed by pre_silu+128
    int8_t *output,
    const int32_t input_width,
    const int32_t input_channels,
    const int32_t output_channels,
    const int32_t kernel_width,
    const int32_t kernel_height,
    const int32_t border,       // 0 = skip top, 1 = all 3 rows, 2 = skip bot
    const int32_t right_shift,
    const int32_t padding);     // unused for stride-2 stem; reserved for future use

} // extern "C"

#endif // _YOLO_M0_CONV2DK3_SILU_BIAS_H
