//===- fully_divisible_loop_iter_dynamic.mlir -------------------*- MLIR -*-===//
//
// Copyright (C) 2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// Dynamic counterpart of fully_divisible_loop_iter.mlir. Under dynamic lowering
// (the aiecc driver default) the loop is preserved (step 1, single body) with a
// runtime buffer-index switch, instead of being unrolled by the buffer depth.

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=true" --aie-assign-lock-ids --canonicalize %s | FileCheck %s

// The loop is NOT unrolled: original step of 1 is kept (static lowering would
// rewrite this to step 2 and emit two acquire/release bodies).
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcvc1902) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(1, 2)
// CHECK:           %[[VAL_1:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "loop_of_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_2:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "loop_of_buff_1"} : memref<16xi32>
// CHECK:           %[[VAL_3:.*]] = aie.lock(%[[VAL_0]], 0) {init = 0 : i32, sym_name = "loop_of_lock_0"}
// CHECK:           %[[VAL_4:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "loop_of_lock_1"}
// CHECK:           func.func @some_work(%[[VAL_5:.*]]: memref<16xi32>, %[[VAL_6:.*]]: index) {
// CHECK:             return
// CHECK:           }
// CHECK:           %[[VAL_7:.*]] = aie.core(%[[VAL_0]]) {
// CHECK:             %[[VAL_8:.*]] = arith.constant -1 : i32
// CHECK:             %[[VAL_9:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_10:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_11:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_12:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_13:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_14:.*]] = arith.constant 4 : index
// CHECK:             %[[VAL_15:.*]] = scf.for %[[VAL_16:.*]] = %[[VAL_12]] to %[[VAL_14]] step %[[VAL_13]] iter_args(%[[VAL_17:.*]] = %[[VAL_10]]) -> (i32) {
// CHECK:               %[[VAL_18:.*]] = arith.index_cast %[[VAL_17]] : i32 to index
// CHECK:               %[[VAL_19:.*]] = scf.index_switch %[[VAL_18]] -> index
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_3]] : index
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_4]] : index
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_3]] : index
// CHECK:               }
// CHECK:               aie.use_lock(%[[VAL_19]], Acquire, %[[VAL_10]])
// CHECK:               %[[VAL_20:.*]] = arith.index_cast %[[VAL_17]] : i32 to index
// CHECK:               %[[VAL_21:.*]] = scf.index_switch %[[VAL_20]] -> memref<16xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_1]] : memref<16xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_2]] : memref<16xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_1]] : memref<16xi32>
// CHECK:               }
// CHECK:               func.call @some_work(%[[VAL_21]], %[[VAL_16]]) : (memref<16xi32>, index) -> ()
// CHECK:               %[[VAL_22:.*]] = arith.index_cast %[[VAL_17]] : i32 to index
// CHECK:               %[[VAL_23:.*]] = scf.index_switch %[[VAL_22]] -> index
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_3]] : index
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_4]] : index
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_3]] : index
// CHECK:               }
// CHECK:               aie.use_lock(%[[VAL_23]], Release, %[[VAL_9]])
// CHECK:               %[[VAL_24:.*]] = arith.addi %[[VAL_17]], %[[VAL_9]] : i32
// CHECK:               %[[VAL_25:.*]] = arith.cmpi sge, %[[VAL_24]], %[[VAL_11]] : i32
// CHECK:               %[[VAL_26:.*]] = arith.addi %[[VAL_17]], %[[VAL_8]] : i32
// CHECK:               %[[VAL_27:.*]] = arith.select %[[VAL_25]], %[[VAL_26]], %[[VAL_24]] : i32
// CHECK:               scf.yield %[[VAL_27]] : i32
// CHECK:             }
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module {
  aie.device(xcvc1902) {
    %tile12 = aie.tile(1, 2)
    %tile13 = aie.tile(1, 3)
    aie.objectfifo @loop_of (%tile12, {%tile13}, 2 : i32) : !aie.objectfifo<memref<16xi32>>
    func.func @some_work(%line_in:memref<16xi32>, %index:index) -> () {
      return
    }
    %core12 = aie.core(%tile12) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c4 = arith.constant 4 : index
      scf.for %indexInHeight = %c0 to %c4 step %c1 {
        %subview = aie.objectfifo.acquire @loop_of (Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
        %elem0 = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
        func.call @some_work(%elem0,%indexInHeight) : (memref<16xi32>,index) -> ()
        aie.objectfifo.release @loop_of (Produce, 1)
      }
      aie.end
    }
  }
}
