//===- fully_divisible_loop_iter.mlir ---------------------------*- MLIR -*-===//
//
// Copyright (C) 2025 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-assign-lock-ids --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcvc1902) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(1, 2)
// CHECK:           %[[VAL_1:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "loop_of_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_2:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "loop_of_buff_1"} : memref<16xi32>
// CHECK:           %[[VAL_3:.*]] = aie.lock(%[[VAL_0]], 0) {init = 0 : i32, sym_name = "loop_of_lock_0"}
// CHECK:           %[[VAL_4:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "loop_of_lock_1"}
// CHECK:           func.func @some_work(%[[VAL_5:.*]]: memref<16xi32>, %[[VAL_6:.*]]: index) {
// CHECK:             return
// CHECK:           }
// CHECK:           %[[VAL_7:.*]] = aie.core(%[[VAL_0]]) {
// CHECK:             %[[VAL_8:.*]] = arith.constant 2 : index
// CHECK:             %[[VAL_9:.*]] = arith.constant 4 : index
// CHECK:             %[[VAL_10:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_11:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_12:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_13:.*]] = arith.constant 1 : i32
// CHECK:             scf.for %[[VAL_14:.*]] = %[[VAL_11]] to %[[VAL_9]] step %[[VAL_8]] {
// CHECK:               aie.use_lock(%[[VAL_3]], Acquire, %[[VAL_12]])
// CHECK:               func.call @some_work(%[[VAL_1]], %[[VAL_14]]) : (memref<16xi32>, index) -> ()
// CHECK:               aie.use_lock(%[[VAL_3]], Release, %[[VAL_13]])
// CHECK:               %[[VAL_15:.*]] = arith.addi %[[VAL_14]], %[[VAL_10]] : index
// CHECK:               aie.use_lock(%[[VAL_4]], Acquire, %[[VAL_12]])
// CHECK:               func.call @some_work(%[[VAL_2]], %[[VAL_15]]) : (memref<16xi32>, index) -> ()
// CHECK:               aie.use_lock(%[[VAL_4]], Release, %[[VAL_13]])
// CHECK:             }
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module {
  aie.device(xcvc1902) {
    %tile12 = aie.tile(1, 2)
    %tile13 = aie.tile(1, 3)
    aie.objectfifo @loop_of (%tile12, {%tile13}, 2 : i32) : !aie.objectfifo<memref<16xi32>>
    func.func @some_work(%line_in:memref<16xi32>, %index:index) -> () {
      return
    }
    %core12 = aie.core(%tile12) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c4 = arith.constant 4 : index
      scf.for %indexInHeight = %c0 to %c4 step %c1 {
        %subview = aie.objectfifo.acquire @loop_of (Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
        %elem0 = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<16xi32>> -> memref<16xi32>
        func.call @some_work(%elem0,%indexInHeight) : (memref<16xi32>,index) -> ()
        aie.objectfifo.release @loop_of (Produce, 1)
      }
      aie.end
    }
  }
}
