//===- npu_dma_memcpy.mlir -------------------------------------*- MLIR -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2024 Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-dma-to-npu %s | FileCheck %s

// CHECK: memref.global "private" constant {{.*}} : memref<8xi32> = dense<[2048, 0, 0, 33554432, -2113929153, 33556479, 0, 33554432]>
// CHECK: aie.runtime_sequence
// CHECK:   %[[VALUE:.*]] = memref.get_global {{.*}} : memref<8xi32>
// CHECK:   aiex.npu.blockwrite(%[[VALUE]]) {address = 118784 : ui32} : memref<8xi32>
// CHECK:   %[[ARGPLUS:.*]] = arith.constant 16384 : i32
// CHECK:   aiex.npu.address_patch(%[[ARGPLUS]] : i32) {addr = 118788 : ui32, arg_idx = 0 : i32}
// CHECK-DAG:   %[[WVAL:.*]] = arith.constant 0 : i32
// CHECK-DAG:   %[[WADDR:.*]] = arith.constant 119316 : i32
// CHECK:   aiex.npu.write32(%[[WADDR]], %[[WVAL]]) : i32, i32
// CHECK: }

module {
 aie.device(npu1_1col) {
  %t00 = aie.tile(0, 0)
  %tile_0_0 = aie.tile(0, 0)
  aie.shim_dma_allocation @airMemcpyId12 (%tile_0_0, MM2S, 0)
  aie.runtime_sequence (%arg0: memref<2x64x64xi32>, %arg1: memref<2x64x64xi32>, %arg2: memref<2x64x64xi32>) {
    aiex.npu.dma_memcpy_nd(%arg0[1, 0, 0, 0][1, 2, 32, 32][4096, 2048, 64, 1]) {id = 0 : i64, metadata = @airMemcpyId12} : memref<2x64x64xi32>
  }
 }
}
