//===- llama_silu_mul_int8.cc -------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Llama silu_mul: fused SiLU(gate) * up. Production dataflow shape:
// int8 in, int8 out; bf16-internal for the SiLU lookup.
//
//   silu_g = silu_lut[gate_i8 + 128]            (precomputed bf16)
//   out_f  = silu_g * (up_i8 * up_scale)
//   out_i8 = clamp(round(out_f * inv_out_scale), -128, 127)
//
// SiLU is implemented as a precomputed 256-entry bf16 LUT keyed by the
// int8 gate input. The LUT is generated at build time by gen_silu_lut.py
// using the same gate_scale, then included as a const uint16 array (raw
// bf16 bit patterns). This way the kernel and the numpy reference look
// up bit-identical SiLU values -- no HW tanh approximation in the loop.
// Pattern mirrors yolo_m9_ffn_0_silu_row_vec.cc.
//
//===----------------------------------------------------------------------===//

#include <aie_api/aie.hpp>
#include <stdint.h>
#include <string.h>

#include "build/silu_lut.h"   // generated by gen_silu_lut.py

#ifndef LLAMA_SILU_MUL_COLS
#define LLAMA_SILU_MUL_COLS 8192   // HIDDEN_DIM
#endif

static constexpr int32_t I8_MAX = 127;
static constexpr int32_t I8_MIN = -128;

static inline int8_t round_to_i8(float v) {
  int32_t r = (int32_t)(v + (v >= 0.0f ? 0.5f : -0.5f));
  if (r > I8_MAX) r = I8_MAX;
  if (r < I8_MIN) r = I8_MIN;
  return (int8_t)r;
}

static inline bfloat16 silu_lookup(int8_t g) {
  uint16_t raw = llama_silu_lut_raw[(int)g + 128];
  bfloat16 bf;
  memcpy(&bf, &raw, 2);
  return bf;
}

extern "C" {

void llama_silu_mul_int8(int8_t *restrict gate, int8_t *restrict up,
                         int8_t *restrict out,
                         float up_scale, float inv_out_scale) {
  event0();

  constexpr int kCols = LLAMA_SILU_MUL_COLS;

  for (int i = 0; i < kCols; i++) {
    bfloat16 s_bf = silu_lookup(gate[i]);
    float    s_f  = (float)s_bf;
    float    u_f  = (float)up[i] * up_scale;
    float    out_f = s_f * u_f * inv_out_scale;
    out[i] = round_to_i8(out_f);
  }

  event1();
}

// Dynamic-scale variant (Phase 6c.5b.2). The `up` buffer is sized
// kCols + 8 bytes; the last 8 bytes carry (up_scale fp32, inv_out_scale
// fp32) written by the up-gemm worker upstream. gate_scale stays baked
// into the LUT.
void llama_silu_mul_int8_dyn(int8_t *restrict gate, int8_t *restrict up,
                             int8_t *restrict out) {
  event0();

  constexpr int kCols = LLAMA_SILU_MUL_COLS;
  float up_scale, inv_out_scale;
  memcpy(&up_scale,      up + kCols,     4);
  memcpy(&inv_out_scale, up + kCols + 4, 4);

  for (int i = 0; i < kCols; i++) {
    bfloat16 s_bf = silu_lookup(gate[i]);
    float    s_f  = (float)s_bf;
    float    u_f  = (float)up[i] * up_scale;
    float    out_f = s_f * u_f * inv_out_scale;
    out[i] = round_to_i8(out_f);
  }

  event1();
}

} // extern "C"
