//===- llama_flowkv.cc --------------------------------------*- C++ -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Llama attention pair v0.1: non-chunked full-softmax split across two
// CTs, with bit-exact-against-numpy arithmetic:
//
//   - int32 dot products (exact), scaled by ONE combined qk_scale
//     (q_scale * k_scale / sqrt(head_dim)) so ordering matches numpy
//   - exp via a 256-entry LUT generated by gen_exp_lut.py; both kernel
//     and reference index identical fp32 entries (yolo m10_softmax
//     pattern). NO aie::exp2 -- that approximation differs from numpy
//     exp.
//   - exact 1.0f / sum (NOT aie::inv) -- aie::inv is a HW reciprocal
//     approximation, not bit-exact.
//   - fp32 probs across the CT0 -> CT1 stream (NOT bf16). Eliminates
//     the bf16 truncation that the v0 design had.
//
// CT0 (llama_flowkv_qk):  Q_i8 + K_packed_i8 -> probs_fp32 (size T)
// CT1 (llama_flowkv_sv):  V_packed_i8 + probs_fp32 -> out_i8 (head_dim)
//
//===----------------------------------------------------------------------===//

#include <aie_api/aie.hpp>
#include <stdint.h>
#include <string.h>

#include "build/exp_lut.h"

#ifndef LLAMA_FLOWKV_HEAD_DIM
#define LLAMA_FLOWKV_HEAD_DIM 64
#endif
#ifndef LLAMA_FLOWKV_T
#define LLAMA_FLOWKV_T 16
#endif
#ifndef LLAMA_FLOWKV_EXP_QUANT_SCALE
// LUT step in score-units. lut[k] = exp((k - 128) * EXP_QUANT_SCALE).
// 0.05 covers shifted scores down to -128*0.05 = -6.4
// (exp(-6.4) = 1.7e-3, safely below the dominant terms).
#define LLAMA_FLOWKV_EXP_QUANT_SCALE 0.05f
#endif

static constexpr int kHD = LLAMA_FLOWKV_HEAD_DIM;
static constexpr int kT  = LLAMA_FLOWKV_T;
static constexpr float kExpQuantScale = LLAMA_FLOWKV_EXP_QUANT_SCALE;
static constexpr float kInvExpQuantScale = 1.0f / LLAMA_FLOWKV_EXP_QUANT_SCALE;

static constexpr int32_t I8_MAX = 127;
static constexpr int32_t I8_MIN = -128;

static inline int8_t round_to_i8(float v) {
  int32_t r = (int32_t)(v + (v >= 0.0f ? 0.5f : -0.5f));
  if (r > I8_MAX) r = I8_MAX;
  if (r < I8_MIN) r = I8_MIN;
  return (int8_t)r;
}

// Quantize a shifted (<=0) score to int8 with the LUT step, clamp to
// [-128, 0]; matches the test's numpy reference.
static inline int32_t quant_shifted(float shifted) {
  float v = shifted * kInvExpQuantScale;
  int32_t q = (int32_t)(v + (v >= 0.0f ? 0.5f : -0.5f));
  if (q > 0) q = 0;
  if (q < -128) q = -128;
  return q;
}

static inline float lookup_exp(int32_t q) {
  uint32_t raw = llama_exp_lut_raw[q + 128];
  float v;
  memcpy(&v, &raw, 4);
  return v;
}

extern "C" {

// CT0: compute fp32 softmax probabilities for one query against the K cache.
void llama_flowkv_qk(int8_t *restrict q_i8, int8_t *restrict k_i8,
                     float *restrict probs_out,
                     float q_scale, float k_scale) {
  event0();

  // AIE2P fp default rounding is NOT round-to-nearest-even -- explicitly
  // set conv_even (banker's rounding, matches numpy's astype semantics).
  ::aie::set_rounding(aie::rounding_mode::conv_even);

  // 1/sqrt(64) = 0.125 (Llama 3.2 1B head_dim is always 64). For other
  // head_dim, precompute in the Python build and pass as a scalar arg.
  static_assert(kHD == 64, "qk_scale hardcoded for head_dim=64");
  constexpr float kInvSqrtHD = 0.125f;
  const float qk_scale = q_scale * k_scale * kInvSqrtHD;

  // 1) Scores: int32 dot, then ONE combined float multiply.
  float scores[kT];
  float max_s = -1e30f;
  for (int i = 0; i < kT; i++) {
    int32_t dot = 0;
    for (int d = 0; d < kHD; d++) {
      dot += (int32_t)q_i8[d] * (int32_t)k_i8[i * kHD + d];
    }
    float s = (float)dot * qk_scale;
    scores[i] = s;
    if (s > max_s) max_s = s;
  }

  // 2) Shift + LUT-exp + sum.
  float exp_v[kT];
  float sum = 0.0f;
  for (int i = 0; i < kT; i++) {
    int32_t q = quant_shifted(scores[i] - max_s);
    float e = lookup_exp(q);
    exp_v[i] = e;
    sum += e;
  }

  // 3) Normalize and emit fp32 probs (no bf16 truncation).
  const float inv_sum = 1.0f / sum;
  for (int i = 0; i < kT; i++) {
    probs_out[i] = exp_v[i] * inv_sum;
  }

  event1();
}

// CT1: probs @ V_dequant, requant to int8.
void llama_flowkv_sv(int8_t *restrict v_i8, float *restrict probs_in,
                     int8_t *restrict out_i8,
                     float v_scale, float inv_out_scale) {
  event0();

  ::aie::set_rounding(aie::rounding_mode::conv_even);

  for (int j = 0; j < kHD; j++) {
    float acc = 0.0f;
    for (int i = 0; i < kT; i++) {
      acc += probs_in[i] * (float)v_i8[i * kHD + j];
    }
    out_i8[j] = round_to_i8(acc * v_scale * inv_out_scale);
  }

  event1();
}

} // extern "C"
