//===- core_flag_test.mlir --------------------------------------*- MLIR -*-===//
//
// Copyright (C) 2024 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-assign-lock-ids %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(npu1_1col) {
// CHECK:           func.func @passthrough_10_i32(%[[VAL_0:.*]]: memref<10xi32>, %[[VAL_1:.*]]: memref<10xi32>) {
// CHECK:             return
// CHECK:           }
// CHECK:           %[[VAL_2:.*]] = aie.tile(0, 0)
// CHECK:           %[[VAL_3:.*]] = aie.tile(0, 2)
// CHECK:           %[[VAL_4:.*]] = aie.tile(0, 4)
// CHECK:           %[[VAL_5:.*]] = aie.lock(%[[VAL_2]], 0) {init = 0 : i32, sym_name = "output_fifo2_cons_prod_lock_0"}
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_2]], 1) {init = 0 : i32, sym_name = "output_fifo2_cons_cons_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo2_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo2_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_9:.*]] = aie.lock(%[[VAL_4]], 0) {init = 2 : i32, sym_name = "output_fifo2_prod_lock_0"}
// CHECK:           %[[VAL_10:.*]] = aie.lock(%[[VAL_4]], 1) {init = 0 : i32, sym_name = "output_fifo2_cons_lock_0"}
// CHECK:           %[[VAL_11:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo2_cons_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo2_cons_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_13:.*]] = aie.lock(%[[VAL_4]], 2) {init = 2 : i32, sym_name = "input_fifo2_cons_prod_lock_0"}
// CHECK:           %[[VAL_14:.*]] = aie.lock(%[[VAL_4]], 3) {init = 0 : i32, sym_name = "input_fifo2_cons_cons_lock_0"}
// CHECK:           %[[VAL_15:.*]] = aie.lock(%[[VAL_2]], 2) {init = 0 : i32, sym_name = "input_fifo2_prod_lock_0"}
// CHECK:           %[[VAL_16:.*]] = aie.lock(%[[VAL_2]], 3) {init = 0 : i32, sym_name = "input_fifo2_cons_lock_0"}
// CHECK:           %[[VAL_17:.*]] = aie.lock(%[[VAL_2]], 4) {init = 0 : i32, sym_name = "output_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_18:.*]] = aie.lock(%[[VAL_2]], 5) {init = 0 : i32, sym_name = "output_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_19:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "output_fifo_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_20:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "output_fifo_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_21:.*]] = aie.lock(%[[VAL_3]], 0) {init = 2 : i32, sym_name = "output_fifo_prod_lock_0"}
// CHECK:           %[[VAL_22:.*]] = aie.lock(%[[VAL_3]], 1) {init = 0 : i32, sym_name = "output_fifo_cons_lock_0"}
// CHECK:           %[[VAL_23:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "input_fifo_cons_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_24:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "input_fifo_cons_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_25:.*]] = aie.lock(%[[VAL_3]], 2) {init = 2 : i32, sym_name = "input_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_26:.*]] = aie.lock(%[[VAL_3]], 3) {init = 0 : i32, sym_name = "input_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_27:.*]] = aie.lock(%[[VAL_2]], 6) {init = 0 : i32, sym_name = "input_fifo_prod_lock_0"}
// CHECK:           %[[VAL_28:.*]] = aie.lock(%[[VAL_2]], 7) {init = 0 : i32, sym_name = "input_fifo_cons_lock_0"}
// CHECK:           aie.flow(%[[VAL_2]], DMA : 0, %[[VAL_3]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_3]], DMA : 0, %[[VAL_2]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_2]], DMA : 1, %[[VAL_4]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_4]], DMA : 0, %[[VAL_2]], DMA : 1)
// CHECK:           %[[VAL_29:.*]] = aie.core(%[[VAL_3]]) {
// CHECK:             %[[VAL_30:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_31:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_32:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_33:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_34:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_35:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_36:.*]] = arith.constant 10 : index
// CHECK:             %[[VAL_37:.*]]:4 = scf.for %[[VAL_38:.*]] = %[[VAL_34]] to %[[VAL_36]] step %[[VAL_35]] iter_args(%[[VAL_39:.*]] = %[[VAL_30]], %[[VAL_40:.*]] = %[[VAL_30]], %[[VAL_41:.*]] = %[[VAL_31]], %[[VAL_42:.*]] = %[[VAL_31]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_43:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_44:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_45:.*]] = arith.subi %[[VAL_43]], %[[VAL_39]] : i32
// CHECK:               %[[VAL_46:.*]] = arith.maxsi %[[VAL_45]], %[[VAL_44]] : i32
// CHECK:               aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:               %[[VAL_47:.*]] = arith.addi %[[VAL_39]], %[[VAL_46]] : i32
// CHECK:               %[[VAL_48:.*]] = arith.index_cast %[[VAL_41]] : i32 to index
// CHECK:               %[[VAL_49:.*]] = scf.index_switch %[[VAL_48]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_19]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_20]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_19]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_50:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_51:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_52:.*]] = arith.subi %[[VAL_50]], %[[VAL_40]] : i32
// CHECK:               %[[VAL_53:.*]] = arith.maxsi %[[VAL_52]], %[[VAL_51]] : i32
// CHECK:               aie.use_lock(%[[VAL_26]], AcquireGreaterEqual, %[[VAL_53]])
// CHECK:               %[[VAL_54:.*]] = arith.addi %[[VAL_40]], %[[VAL_53]] : i32
// CHECK:               %[[VAL_55:.*]] = arith.index_cast %[[VAL_42]] : i32 to index
// CHECK:               %[[VAL_56:.*]] = scf.index_switch %[[VAL_55]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_23]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_24]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_23]] : memref<10xi32>
// CHECK:               }
// CHECK:               func.call @passthrough_10_i32(%[[VAL_56]], %[[VAL_49]]) : (memref<10xi32>, memref<10xi32>) -> ()
// CHECK:               %[[VAL_57:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_25]], Release, %[[VAL_57]])
// CHECK:               %[[VAL_58:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_59:.*]] = arith.subi %[[VAL_54]], %[[VAL_58]] : i32
// CHECK:               %[[VAL_60:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_61:.*]] = arith.addi %[[VAL_42]], %[[VAL_60]] : i32
// CHECK:               %[[VAL_62:.*]] = arith.cmpi sge, %[[VAL_61]], %[[VAL_33]] : i32
// CHECK:               %[[VAL_63:.*]] = arith.subi %[[VAL_61]], %[[VAL_33]] : i32
// CHECK:               %[[VAL_64:.*]] = arith.select %[[VAL_62]], %[[VAL_63]], %[[VAL_61]] : i32
// CHECK:               %[[VAL_65:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_22]], Release, %[[VAL_65]])
// CHECK:               %[[VAL_66:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_67:.*]] = arith.subi %[[VAL_47]], %[[VAL_66]] : i32
// CHECK:               %[[VAL_68:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_69:.*]] = arith.addi %[[VAL_41]], %[[VAL_68]] : i32
// CHECK:               %[[VAL_70:.*]] = arith.cmpi sge, %[[VAL_69]], %[[VAL_32]] : i32
// CHECK:               %[[VAL_71:.*]] = arith.subi %[[VAL_69]], %[[VAL_32]] : i32
// CHECK:               %[[VAL_72:.*]] = arith.select %[[VAL_70]], %[[VAL_71]], %[[VAL_69]] : i32
// CHECK:               scf.yield %[[VAL_67]], %[[VAL_59]], %[[VAL_72]], %[[VAL_64]] : i32, i32, i32, i32
// CHECK:             } {aie.unroll_hint = 2 : i64}
// CHECK:             aie.end
// CHECK:           } {dynamic_objfifo_lowering = true}
// CHECK:           %[[VAL_73:.*]] = aie.core(%[[VAL_4]]) {
// CHECK:             %[[VAL_74:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_75:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_76:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_77:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_78:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_79:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_80:.*]] = arith.constant 10 : index
// CHECK:             %[[VAL_81:.*]]:4 = scf.for %[[VAL_82:.*]] = %[[VAL_78]] to %[[VAL_80]] step %[[VAL_79]] iter_args(%[[VAL_83:.*]] = %[[VAL_74]], %[[VAL_84:.*]] = %[[VAL_74]], %[[VAL_85:.*]] = %[[VAL_75]], %[[VAL_86:.*]] = %[[VAL_75]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_87:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_88:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_89:.*]] = arith.subi %[[VAL_87]], %[[VAL_83]] : i32
// CHECK:               %[[VAL_90:.*]] = arith.maxsi %[[VAL_89]], %[[VAL_88]] : i32
// CHECK:               aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_90]])
// CHECK:               %[[VAL_91:.*]] = arith.addi %[[VAL_83]], %[[VAL_90]] : i32
// CHECK:               %[[VAL_92:.*]] = arith.index_cast %[[VAL_85]] : i32 to index
// CHECK:               %[[VAL_93:.*]] = scf.index_switch %[[VAL_92]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_8]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_94:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_95:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_96:.*]] = arith.subi %[[VAL_94]], %[[VAL_84]] : i32
// CHECK:               %[[VAL_97:.*]] = arith.maxsi %[[VAL_96]], %[[VAL_95]] : i32
// CHECK:               aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_97]])
// CHECK:               %[[VAL_98:.*]] = arith.addi %[[VAL_84]], %[[VAL_97]] : i32
// CHECK:               %[[VAL_99:.*]] = arith.index_cast %[[VAL_86]] : i32 to index
// CHECK:               %[[VAL_100:.*]] = scf.index_switch %[[VAL_99]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               func.call @passthrough_10_i32(%[[VAL_100]], %[[VAL_93]]) : (memref<10xi32>, memref<10xi32>) -> ()
// CHECK:               %[[VAL_101:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_13]], Release, %[[VAL_101]])
// CHECK:               %[[VAL_102:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_103:.*]] = arith.subi %[[VAL_98]], %[[VAL_102]] : i32
// CHECK:               %[[VAL_104:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_105:.*]] = arith.addi %[[VAL_86]], %[[VAL_104]] : i32
// CHECK:               %[[VAL_106:.*]] = arith.cmpi sge, %[[VAL_105]], %[[VAL_77]] : i32
// CHECK:               %[[VAL_107:.*]] = arith.subi %[[VAL_105]], %[[VAL_77]] : i32
// CHECK:               %[[VAL_108:.*]] = arith.select %[[VAL_106]], %[[VAL_107]], %[[VAL_105]] : i32
// CHECK:               %[[VAL_109:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_109]])
// CHECK:               %[[VAL_110:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_111:.*]] = arith.subi %[[VAL_91]], %[[VAL_110]] : i32
// CHECK:               %[[VAL_112:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_113:.*]] = arith.addi %[[VAL_85]], %[[VAL_112]] : i32
// CHECK:               %[[VAL_114:.*]] = arith.cmpi sge, %[[VAL_113]], %[[VAL_76]] : i32
// CHECK:               %[[VAL_115:.*]] = arith.subi %[[VAL_113]], %[[VAL_76]] : i32
// CHECK:               %[[VAL_116:.*]] = arith.select %[[VAL_114]], %[[VAL_115]], %[[VAL_113]] : i32
// CHECK:               scf.yield %[[VAL_111]], %[[VAL_103]], %[[VAL_116]], %[[VAL_108]] : i32, i32, i32, i32
// CHECK:             } {aie.unroll_hint = 2 : i64}
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @input_fifo_shim_alloc(%[[VAL_2]], MM2S, 0)
// CHECK:           %[[VAL_117:.*]] = aie.mem(%[[VAL_3]]) {
// CHECK:             %[[VAL_118:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_119:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_25]], AcquireGreaterEqual, %[[VAL_119]])
// CHECK:             aie.dma_bd(%[[VAL_23]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_120:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_26]], Release, %[[VAL_120]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             %[[VAL_121:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_25]], AcquireGreaterEqual, %[[VAL_121]])
// CHECK:             aie.dma_bd(%[[VAL_24]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_122:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_26]], Release, %[[VAL_122]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             %[[VAL_123:.*]] = aie.dma_start(MM2S, 0, ^bb4, ^bb6)
// CHECK:           ^bb4:
// CHECK:             %[[VAL_124:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_124]])
// CHECK:             aie.dma_bd(%[[VAL_19]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_125:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_125]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb5:
// CHECK:             %[[VAL_126:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_126]])
// CHECK:             aie.dma_bd(%[[VAL_20]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_127:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_127]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb6:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @output_fifo_shim_alloc(%[[VAL_2]], S2MM, 0)
// CHECK:           aie.shim_dma_allocation @input_fifo2_shim_alloc(%[[VAL_2]], MM2S, 1)
// CHECK:           %[[VAL_128:.*]] = aie.mem(%[[VAL_4]]) {
// CHECK:             %[[VAL_129:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_130:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_130]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_131:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_131]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             %[[VAL_132:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_132]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_133:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_133]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             %[[VAL_134:.*]] = aie.dma_start(MM2S, 0, ^bb4, ^bb6)
// CHECK:           ^bb4:
// CHECK:             %[[VAL_135:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_135]])
// CHECK:             aie.dma_bd(%[[VAL_7]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_136:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_136]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb5:
// CHECK:             %[[VAL_137:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_137]])
// CHECK:             aie.dma_bd(%[[VAL_8]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_138:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_138]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb6:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @output_fifo2_shim_alloc(%[[VAL_2]], S2MM, 1)
// CHECK:         }


module {
  aie.device(npu1_1col) {
    func.func @passthrough_10_i32(%line_in: memref<10xi32>, %line_out: memref<10xi32>) -> () {
        return
    }

    %tile_0_0 = aie.tile(0, 0)
    %tile_0_2 = aie.tile(0, 2)
    %tile_0_4 = aie.tile(0, 4)
    aie.objectfifo @input_fifo(%tile_0_0, {%tile_0_2}, 2 : i32) : !aie.objectfifo<memref<10xi32>>
    aie.objectfifo @output_fifo(%tile_0_2, {%tile_0_0}, 2 : i32) : !aie.objectfifo<memref<10xi32>>

    aie.objectfifo @input_fifo2(%tile_0_0, {%tile_0_4}, 2 : i32) : !aie.objectfifo<memref<10xi32>>
    aie.objectfifo @output_fifo2(%tile_0_4, {%tile_0_0}, 2 : i32) : !aie.objectfifo<memref<10xi32>>

    %core_0_2 = aie.core(%tile_0_2) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c10 = arith.constant 10 : index

      scf.for %arg0 = %c0 to %c10 step %c1 {
        %0 = aie.objectfifo.acquire @output_fifo(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
        %1 = aie.objectfifo.subview.access %0[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %2 = aie.objectfifo.acquire @input_fifo(Consume, 1) : !aie.objectfifosubview<memref<10xi32>>
        %3 = aie.objectfifo.subview.access %2[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        func.call @passthrough_10_i32(%3, %1) : (memref<10xi32>, memref<10xi32>) -> ()
        aie.objectfifo.release @input_fifo(Consume, 1)
        aie.objectfifo.release @output_fifo(Produce, 1)
      }

      aie.end
    } {dynamic_objfifo_lowering = true}

    %core_0_4 = aie.core(%tile_0_4) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c10 = arith.constant 10 : index

      scf.for %arg0 = %c0 to %c10 step %c1 {
        %0 = aie.objectfifo.acquire @output_fifo2(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
        %1 = aie.objectfifo.subview.access %0[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %2 = aie.objectfifo.acquire @input_fifo2(Consume, 1) : !aie.objectfifosubview<memref<10xi32>>
        %3 = aie.objectfifo.subview.access %2[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        func.call @passthrough_10_i32(%3, %1) : (memref<10xi32>, memref<10xi32>) -> ()
        aie.objectfifo.release @input_fifo2(Consume, 1)
        aie.objectfifo.release @output_fifo2(Produce, 1)
      }

      aie.end
    }
  }
}
