//===- different_depth_objectfifos_test.mlir --------------------*- MLIR -*-===//
//
// Copyright (C) 2025 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform=dynamic-objFifos --aie-assign-lock-ids %s | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(npu1_1col) {
// CHECK:           func.func @add_10_i32(%[[VAL_0:.*]]: memref<10xi32>, %[[VAL_1:.*]]: memref<10xi32>, %[[VAL_2:.*]]: memref<10xi32>) {
// CHECK:             return
// CHECK:           }
// CHECK:           %[[VAL_3:.*]] = aie.tile(0, 0)
// CHECK:           %[[VAL_4:.*]] = aie.tile(0, 2)
// CHECK:           %[[VAL_5:.*]] = aie.lock(%[[VAL_3]], 0) {init = 0 : i32, sym_name = "output_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_3]], 1) {init = 0 : i32, sym_name = "output_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_9:.*]] = aie.lock(%[[VAL_4]], 0) {init = 2 : i32, sym_name = "output_fifo_prod_lock_0"}
// CHECK:           %[[VAL_10:.*]] = aie.lock(%[[VAL_4]], 1) {init = 0 : i32, sym_name = "output_fifo_cons_lock_0"}
// CHECK:           %[[VAL_11:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo_cons_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo_cons_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_13:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo_cons_buff_2"} : memref<10xi32>
// CHECK:           %[[VAL_14:.*]] = aie.lock(%[[VAL_4]], 2) {init = 3 : i32, sym_name = "input_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_15:.*]] = aie.lock(%[[VAL_4]], 3) {init = 0 : i32, sym_name = "input_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_16:.*]] = aie.lock(%[[VAL_3]], 2) {init = 0 : i32, sym_name = "input_fifo_prod_lock_0"}
// CHECK:           %[[VAL_17:.*]] = aie.lock(%[[VAL_3]], 3) {init = 0 : i32, sym_name = "input_fifo_cons_lock_0"}
// CHECK:           aie.flow(%[[VAL_3]], DMA : 0, %[[VAL_4]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_4]], DMA : 0, %[[VAL_3]], DMA : 0)
// CHECK:           %[[VAL_18:.*]] = aie.core(%[[VAL_4]]) {
// CHECK:             %[[VAL_19:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_20:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_21:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_22:.*]] = arith.constant 3 : i32
// CHECK:             %[[VAL_23:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_24:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_25:.*]] = arith.constant 9 : index
// CHECK:             %[[VAL_26:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_27:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_28:.*]] = arith.subi %[[VAL_26]], %[[VAL_19]] : i32
// CHECK:             %[[VAL_29:.*]] = arith.maxsi %[[VAL_28]], %[[VAL_27]] : i32
// CHECK:             aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_29]])
// CHECK:             %[[VAL_30:.*]] = arith.addi %[[VAL_19]], %[[VAL_29]] : i32
// CHECK:             %[[VAL_31:.*]] = arith.index_cast %[[VAL_20]] : i32 to index
// CHECK:             %[[VAL_32:.*]] = scf.index_switch %[[VAL_31]] -> memref<10xi32>
// CHECK:             case 0 {
// CHECK:               scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 1 {
// CHECK:               scf.yield %[[VAL_8]] : memref<10xi32>
// CHECK:             }
// CHECK:             default {
// CHECK:               scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:             }
// CHECK:             %[[VAL_33:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_34:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_35:.*]] = arith.subi %[[VAL_33]], %[[VAL_19]] : i32
// CHECK:             %[[VAL_36:.*]] = arith.maxsi %[[VAL_35]], %[[VAL_34]] : i32
// CHECK:             aie.use_lock(%[[VAL_15]], AcquireGreaterEqual, %[[VAL_36]])
// CHECK:             %[[VAL_37:.*]] = arith.addi %[[VAL_19]], %[[VAL_36]] : i32
// CHECK:             %[[VAL_38:.*]] = arith.index_cast %[[VAL_20]] : i32 to index
// CHECK:             %[[VAL_39:.*]] = scf.index_switch %[[VAL_38]] -> memref<10xi32>
// CHECK:             case 0 {
// CHECK:               scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 1 {
// CHECK:               scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 2 {
// CHECK:               scf.yield %[[VAL_13]] : memref<10xi32>
// CHECK:             }
// CHECK:             default {
// CHECK:               scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:             }
// CHECK:             func.call @add_10_i32(%[[VAL_39]], %[[VAL_39]], %[[VAL_32]]) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
// CHECK:             %[[VAL_40:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], Release, %[[VAL_40]])
// CHECK:             %[[VAL_41:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_42:.*]] = arith.subi %[[VAL_30]], %[[VAL_41]] : i32
// CHECK:             %[[VAL_43:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_44:.*]] = arith.addi %[[VAL_20]], %[[VAL_43]] : i32
// CHECK:             %[[VAL_45:.*]] = arith.cmpi sge, %[[VAL_44]], %[[VAL_21]] : i32
// CHECK:             %[[VAL_46:.*]] = arith.subi %[[VAL_44]], %[[VAL_21]] : i32
// CHECK:             %[[VAL_47:.*]] = arith.select %[[VAL_45]], %[[VAL_46]], %[[VAL_44]] : i32
// CHECK:             %[[VAL_48:.*]]:4 = scf.for %[[VAL_49:.*]] = %[[VAL_23]] to %[[VAL_25]] step %[[VAL_24]] iter_args(%[[VAL_50:.*]] = %[[VAL_42]], %[[VAL_51:.*]] = %[[VAL_37]], %[[VAL_52:.*]] = %[[VAL_47]], %[[VAL_53:.*]] = %[[VAL_20]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_54:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_55:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_56:.*]] = arith.subi %[[VAL_54]], %[[VAL_50]] : i32
// CHECK:               %[[VAL_57:.*]] = arith.maxsi %[[VAL_56]], %[[VAL_55]] : i32
// CHECK:               aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_57]])
// CHECK:               %[[VAL_58:.*]] = arith.addi %[[VAL_50]], %[[VAL_57]] : i32
// CHECK:               %[[VAL_59:.*]] = arith.index_cast %[[VAL_52]] : i32 to index
// CHECK:               %[[VAL_60:.*]] = scf.index_switch %[[VAL_59]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_8]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_61:.*]] = arith.constant 2 : i32
// CHECK:               %[[VAL_62:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_63:.*]] = arith.subi %[[VAL_61]], %[[VAL_51]] : i32
// CHECK:               %[[VAL_64:.*]] = arith.maxsi %[[VAL_63]], %[[VAL_62]] : i32
// CHECK:               aie.use_lock(%[[VAL_15]], AcquireGreaterEqual, %[[VAL_64]])
// CHECK:               %[[VAL_65:.*]] = arith.addi %[[VAL_51]], %[[VAL_64]] : i32
// CHECK:               %[[VAL_66:.*]] = arith.index_cast %[[VAL_53]] : i32 to index
// CHECK:               %[[VAL_67:.*]] = scf.index_switch %[[VAL_66]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 2 {
// CHECK:                 scf.yield %[[VAL_13]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_68:.*]] = arith.index_cast %[[VAL_53]] : i32 to index
// CHECK:               %[[VAL_69:.*]] = scf.index_switch %[[VAL_68]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_13]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 2 {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:               }
// CHECK:               func.call @add_10_i32(%[[VAL_67]], %[[VAL_69]], %[[VAL_60]]) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
// CHECK:               %[[VAL_70:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_14]], Release, %[[VAL_70]])
// CHECK:               %[[VAL_71:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_72:.*]] = arith.subi %[[VAL_65]], %[[VAL_71]] : i32
// CHECK:               %[[VAL_73:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_74:.*]] = arith.addi %[[VAL_53]], %[[VAL_73]] : i32
// CHECK:               %[[VAL_75:.*]] = arith.cmpi sge, %[[VAL_74]], %[[VAL_22]] : i32
// CHECK:               %[[VAL_76:.*]] = arith.subi %[[VAL_74]], %[[VAL_22]] : i32
// CHECK:               %[[VAL_77:.*]] = arith.select %[[VAL_75]], %[[VAL_76]], %[[VAL_74]] : i32
// CHECK:               %[[VAL_78:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_78]])
// CHECK:               %[[VAL_79:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_80:.*]] = arith.subi %[[VAL_58]], %[[VAL_79]] : i32
// CHECK:               %[[VAL_81:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_82:.*]] = arith.addi %[[VAL_52]], %[[VAL_81]] : i32
// CHECK:               %[[VAL_83:.*]] = arith.cmpi sge, %[[VAL_82]], %[[VAL_21]] : i32
// CHECK:               %[[VAL_84:.*]] = arith.subi %[[VAL_82]], %[[VAL_21]] : i32
// CHECK:               %[[VAL_85:.*]] = arith.select %[[VAL_83]], %[[VAL_84]], %[[VAL_82]] : i32
// CHECK:               scf.yield %[[VAL_80]], %[[VAL_72]], %[[VAL_85]], %[[VAL_77]] : i32, i32, i32, i32
// CHECK:             }
// CHECK:             %[[VAL_86:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_87:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_88:.*]] = arith.subi %[[VAL_86]], %[[VAL_89:.*]]#0 : i32
// CHECK:             %[[VAL_90:.*]] = arith.maxsi %[[VAL_88]], %[[VAL_87]] : i32
// CHECK:             aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_90]])
// CHECK:             %[[VAL_91:.*]] = arith.addi %[[VAL_89]]#0, %[[VAL_90]] : i32
// CHECK:             %[[VAL_92:.*]] = arith.index_cast %[[VAL_89]]#2 : i32 to index
// CHECK:             %[[VAL_93:.*]] = scf.index_switch %[[VAL_92]] -> memref<10xi32>
// CHECK:             case 0 {
// CHECK:               scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 1 {
// CHECK:               scf.yield %[[VAL_8]] : memref<10xi32>
// CHECK:             }
// CHECK:             default {
// CHECK:               scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:             }
// CHECK:             %[[VAL_94:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_95:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_96:.*]] = arith.subi %[[VAL_94]], %[[VAL_89]]#1 : i32
// CHECK:             %[[VAL_97:.*]] = arith.maxsi %[[VAL_96]], %[[VAL_95]] : i32
// CHECK:             aie.use_lock(%[[VAL_15]], AcquireGreaterEqual, %[[VAL_97]])
// CHECK:             %[[VAL_98:.*]] = arith.addi %[[VAL_89]]#1, %[[VAL_97]] : i32
// CHECK:             %[[VAL_99:.*]] = arith.index_cast %[[VAL_89]]#3 : i32 to index
// CHECK:             %[[VAL_100:.*]] = scf.index_switch %[[VAL_99]] -> memref<10xi32>
// CHECK:             case 0 {
// CHECK:               scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 1 {
// CHECK:               scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 2 {
// CHECK:               scf.yield %[[VAL_13]] : memref<10xi32>
// CHECK:             }
// CHECK:             default {
// CHECK:               scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:             }
// CHECK:             %[[VAL_101:.*]] = arith.index_cast %[[VAL_89]]#3 : i32 to index
// CHECK:             %[[VAL_102:.*]] = scf.index_switch %[[VAL_101]] -> memref<10xi32>
// CHECK:             case 0 {
// CHECK:               scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 1 {
// CHECK:               scf.yield %[[VAL_13]] : memref<10xi32>
// CHECK:             }
// CHECK:             case 2 {
// CHECK:               scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:             }
// CHECK:             default {
// CHECK:               scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:             }
// CHECK:             func.call @add_10_i32(%[[VAL_100]], %[[VAL_102]], %[[VAL_93]]) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
// CHECK:             %[[VAL_103:.*]] = arith.constant 2 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_103]])
// CHECK:             %[[VAL_104:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_105:.*]] = arith.subi %[[VAL_98]], %[[VAL_104]] : i32
// CHECK:             %[[VAL_106:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_107:.*]] = arith.addi %[[VAL_89]]#3, %[[VAL_106]] : i32
// CHECK:             %[[VAL_108:.*]] = arith.cmpi sge, %[[VAL_107]], %[[VAL_22]] : i32
// CHECK:             %[[VAL_109:.*]] = arith.subi %[[VAL_107]], %[[VAL_22]] : i32
// CHECK:             %[[VAL_110:.*]] = arith.select %[[VAL_108]], %[[VAL_109]], %[[VAL_107]] : i32
// CHECK:             %[[VAL_111:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], Release, %[[VAL_111]])
// CHECK:             %[[VAL_112:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_113:.*]] = arith.subi %[[VAL_91]], %[[VAL_112]] : i32
// CHECK:             %[[VAL_114:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_115:.*]] = arith.addi %[[VAL_89]]#2, %[[VAL_114]] : i32
// CHECK:             %[[VAL_116:.*]] = arith.cmpi sge, %[[VAL_115]], %[[VAL_21]] : i32
// CHECK:             %[[VAL_117:.*]] = arith.subi %[[VAL_115]], %[[VAL_21]] : i32
// CHECK:             %[[VAL_118:.*]] = arith.select %[[VAL_116]], %[[VAL_117]], %[[VAL_115]] : i32
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @input_fifo_shim_alloc(%[[VAL_3]], MM2S, 0)
// CHECK:           %[[VAL_119:.*]] = aie.mem(%[[VAL_4]]) {
// CHECK:             %[[VAL_120:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb4)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_121:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_121]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_122:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_15]], Release, %[[VAL_122]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             %[[VAL_123:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_123]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_124:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_15]], Release, %[[VAL_124]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             %[[VAL_125:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_125]])
// CHECK:             aie.dma_bd(%[[VAL_13]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_126:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_15]], Release, %[[VAL_126]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb4:
// CHECK:             %[[VAL_127:.*]] = aie.dma_start(MM2S, 0, ^bb5, ^bb7)
// CHECK:           ^bb5:
// CHECK:             %[[VAL_128:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_128]])
// CHECK:             aie.dma_bd(%[[VAL_7]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_129:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_129]])
// CHECK:             aie.next_bd ^bb6
// CHECK:           ^bb6:
// CHECK:             %[[VAL_130:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_130]])
// CHECK:             aie.dma_bd(%[[VAL_8]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_131:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_131]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb7:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @output_fifo_shim_alloc(%[[VAL_3]], S2MM, 0)
// CHECK:         }


module {
  aie.device(npu1_1col) {
    func.func @add_10_i32(%line_in1: memref<10xi32>, %line_in2: memref<10xi32>, %line_out: memref<10xi32>) -> () {
        return
    }

    %tile_0_0 = aie.tile(0, 0)
    %tile_0_2 = aie.tile(0, 2)
    aie.objectfifo @input_fifo(%tile_0_0, {%tile_0_2}, [2, 3]) : !aie.objectfifo<memref<10xi32>>
    aie.objectfifo @output_fifo(%tile_0_2, {%tile_0_0}, [2, 2]) : !aie.objectfifo<memref<10xi32>>

    %core_0_2 = aie.core(%tile_0_2) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c8 = arith.constant 9 : index

      %0 = aie.objectfifo.acquire @output_fifo(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
      %1 = aie.objectfifo.subview.access %0[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
      %2 = aie.objectfifo.acquire @input_fifo(Consume, 1) : !aie.objectfifosubview<memref<10xi32>>
      %3 = aie.objectfifo.subview.access %2[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
      func.call @add_10_i32(%3, %3, %1) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
      aie.objectfifo.release @output_fifo(Produce, 1)

      scf.for %arg0 = %c0 to %c8 step %c1 {
        %4 = aie.objectfifo.acquire @output_fifo(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
        %5 = aie.objectfifo.subview.access %4[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %6 = aie.objectfifo.acquire @input_fifo(Consume, 2) : !aie.objectfifosubview<memref<10xi32>>
        %7 = aie.objectfifo.subview.access %6[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %8 = aie.objectfifo.subview.access %6[1] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        func.call @add_10_i32(%7, %8, %5) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
        aie.objectfifo.release @input_fifo(Consume, 1)
        aie.objectfifo.release @output_fifo(Produce, 1)
      }

      %9 = aie.objectfifo.acquire @output_fifo(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
      %10 = aie.objectfifo.subview.access %9[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
      %11 = aie.objectfifo.acquire @input_fifo(Consume, 2) : !aie.objectfifosubview<memref<10xi32>>
      %12 = aie.objectfifo.subview.access %11[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
      %13 = aie.objectfifo.subview.access %11[1] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
      func.call @add_10_i32(%12, %13, %10) : (memref<10xi32>, memref<10xi32>, memref<10xi32>) -> ()
      aie.objectfifo.release @input_fifo(Consume, 2)
      aie.objectfifo.release @output_fifo(Produce, 1)

      aie.end
    }
  }
}
