//===- pass_flag_test.mlir --------------------------------------*- MLIR -*-===//
//
// Copyright (C) 2025 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform --aie-objectFifo-unroll="dynamic-objFifos=true" %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(npu1_1col) {
// CHECK:           func.func @passthrough_10_i32(%[[VAL_0:.*]]: memref<10xi32>, %[[VAL_1:.*]]: memref<10xi32>) {
// CHECK:             return
// CHECK:           }
// CHECK:           %[[VAL_2:.*]] = aie.tile(0, 0)
// CHECK:           %[[VAL_3:.*]] = aie.tile(0, 2)
// CHECK:           %[[VAL_4:.*]] = aie.tile(0, 4)
// CHECK:           %[[VAL_5:.*]] = aie.lock(%[[VAL_2]], 6) {init = 0 : i32, sym_name = "output_fifo2_cons_prod_lock_0"}
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_2]], 7) {init = 0 : i32, sym_name = "output_fifo2_cons_cons_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo2_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "output_fifo2_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_9:.*]] = aie.lock(%[[VAL_4]], 2) {init = 2 : i32, sym_name = "output_fifo2_prod_lock_0"}
// CHECK:           %[[VAL_10:.*]] = aie.lock(%[[VAL_4]], 3) {init = 0 : i32, sym_name = "output_fifo2_cons_lock_0"}
// CHECK:           %[[VAL_11:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo2_cons_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_4]]) {sym_name = "input_fifo2_cons_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_13:.*]] = aie.lock(%[[VAL_4]], 0) {init = 2 : i32, sym_name = "input_fifo2_cons_prod_lock_0"}
// CHECK:           %[[VAL_14:.*]] = aie.lock(%[[VAL_4]], 1) {init = 0 : i32, sym_name = "input_fifo2_cons_cons_lock_0"}
// CHECK:           %[[VAL_15:.*]] = aie.lock(%[[VAL_2]], 4) {init = 0 : i32, sym_name = "input_fifo2_prod_lock_0"}
// CHECK:           %[[VAL_16:.*]] = aie.lock(%[[VAL_2]], 5) {init = 0 : i32, sym_name = "input_fifo2_cons_lock_0"}
// CHECK:           %[[VAL_17:.*]] = aie.lock(%[[VAL_2]], 2) {init = 0 : i32, sym_name = "output_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_18:.*]] = aie.lock(%[[VAL_2]], 3) {init = 0 : i32, sym_name = "output_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_19:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "output_fifo_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_20:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "output_fifo_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_21:.*]] = aie.lock(%[[VAL_3]], 2) {init = 2 : i32, sym_name = "output_fifo_prod_lock_0"}
// CHECK:           %[[VAL_22:.*]] = aie.lock(%[[VAL_3]], 3) {init = 0 : i32, sym_name = "output_fifo_cons_lock_0"}
// CHECK:           %[[VAL_23:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "input_fifo_cons_buff_0"} : memref<10xi32>
// CHECK:           %[[VAL_24:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "input_fifo_cons_buff_1"} : memref<10xi32>
// CHECK:           %[[VAL_25:.*]] = aie.lock(%[[VAL_3]], 0) {init = 2 : i32, sym_name = "input_fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_26:.*]] = aie.lock(%[[VAL_3]], 1) {init = 0 : i32, sym_name = "input_fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_27:.*]] = aie.lock(%[[VAL_2]], 0) {init = 0 : i32, sym_name = "input_fifo_prod_lock_0"}
// CHECK:           %[[VAL_28:.*]] = aie.lock(%[[VAL_2]], 1) {init = 0 : i32, sym_name = "input_fifo_cons_lock_0"}
// CHECK:           aie.flow(%[[VAL_2]], DMA : 0, %[[VAL_3]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_3]], DMA : 0, %[[VAL_2]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_2]], DMA : 1, %[[VAL_4]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_4]], DMA : 0, %[[VAL_2]], DMA : 1)
// CHECK:           %[[VAL_29:.*]] = aie.core(%[[VAL_3]]) {
// CHECK:             %[[VAL_30:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_31:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_32:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_33:.*]] = arith.constant 10 : index
// CHECK:             %[[VAL_34:.*]]:4 = scf.for %[[VAL_35:.*]] = %[[VAL_31]] to %[[VAL_33]] step %[[VAL_32]] iter_args(%[[VAL_36:.*]] = %[[VAL_30]], %[[VAL_37:.*]] = %[[VAL_30]], %[[VAL_38:.*]] = %[[VAL_30]], %[[VAL_39:.*]] = %[[VAL_30]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_40:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_41:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_42:.*]] = arith.subi %[[VAL_40]], %[[VAL_38]] : i32
// CHECK:               %[[VAL_43:.*]] = arith.maxsi %[[VAL_42]], %[[VAL_41]] : i32
// CHECK:               aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_43]])
// CHECK:               %[[VAL_44:.*]] = arith.addi %[[VAL_38]], %[[VAL_43]] : i32
// CHECK:               %[[VAL_45:.*]] = arith.index_cast %[[VAL_36]] : i32 to index
// CHECK:               %[[VAL_46:.*]] = scf.index_switch %[[VAL_45]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_19]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_20]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_19]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_47:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_48:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_49:.*]] = arith.subi %[[VAL_47]], %[[VAL_39]] : i32
// CHECK:               %[[VAL_50:.*]] = arith.maxsi %[[VAL_49]], %[[VAL_48]] : i32
// CHECK:               aie.use_lock(%[[VAL_26]], AcquireGreaterEqual, %[[VAL_50]])
// CHECK:               %[[VAL_51:.*]] = arith.addi %[[VAL_39]], %[[VAL_50]] : i32
// CHECK:               %[[VAL_52:.*]] = arith.index_cast %[[VAL_37]] : i32 to index
// CHECK:               %[[VAL_53:.*]] = scf.index_switch %[[VAL_52]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_23]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_24]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_23]] : memref<10xi32>
// CHECK:               }
// CHECK:               func.call @passthrough_10_i32(%[[VAL_53]], %[[VAL_46]]) : (memref<10xi32>, memref<10xi32>) -> ()
// CHECK:               %[[VAL_54:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_25]], Release, %[[VAL_54]])
// CHECK:               %[[VAL_55:.*]] = arith.subi %[[VAL_51]], %[[VAL_54]] : i32
// CHECK:               %[[VAL_56:.*]] = arith.constant 2 : i32
// CHECK:               %[[VAL_57:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_58:.*]] = arith.addi %[[VAL_37]], %[[VAL_57]] : i32
// CHECK:               %[[VAL_59:.*]] = arith.cmpi sge, %[[VAL_58]], %[[VAL_56]] : i32
// CHECK:               %[[VAL_60:.*]] = arith.subi %[[VAL_58]], %[[VAL_56]] : i32
// CHECK:               %[[VAL_61:.*]] = arith.select %[[VAL_59]], %[[VAL_60]], %[[VAL_58]] : i32
// CHECK:               %[[VAL_62:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_22]], Release, %[[VAL_62]])
// CHECK:               %[[VAL_63:.*]] = arith.subi %[[VAL_44]], %[[VAL_62]] : i32
// CHECK:               %[[VAL_64:.*]] = arith.constant 2 : i32
// CHECK:               %[[VAL_65:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_66:.*]] = arith.addi %[[VAL_36]], %[[VAL_65]] : i32
// CHECK:               %[[VAL_67:.*]] = arith.cmpi sge, %[[VAL_66]], %[[VAL_64]] : i32
// CHECK:               %[[VAL_68:.*]] = arith.subi %[[VAL_66]], %[[VAL_64]] : i32
// CHECK:               %[[VAL_69:.*]] = arith.select %[[VAL_67]], %[[VAL_68]], %[[VAL_66]] : i32
// CHECK:               scf.yield %[[VAL_69]], %[[VAL_61]], %[[VAL_63]], %[[VAL_55]] : i32, i32, i32, i32
// CHECK:             }
// CHECK:             aie.end
// CHECK:           } {dynamic_objfifo_lowering = false}
// CHECK:           %[[VAL_70:.*]] = aie.core(%[[VAL_4]]) {
// CHECK:             %[[VAL_71:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_72:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_73:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_74:.*]] = arith.constant 10 : index
// CHECK:             %[[VAL_75:.*]]:4 = scf.for %[[VAL_76:.*]] = %[[VAL_72]] to %[[VAL_74]] step %[[VAL_73]] iter_args(%[[VAL_77:.*]] = %[[VAL_71]], %[[VAL_78:.*]] = %[[VAL_71]], %[[VAL_79:.*]] = %[[VAL_71]], %[[VAL_80:.*]] = %[[VAL_71]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_81:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_82:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_83:.*]] = arith.subi %[[VAL_81]], %[[VAL_79]] : i32
// CHECK:               %[[VAL_84:.*]] = arith.maxsi %[[VAL_83]], %[[VAL_82]] : i32
// CHECK:               aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_84]])
// CHECK:               %[[VAL_85:.*]] = arith.addi %[[VAL_79]], %[[VAL_84]] : i32
// CHECK:               %[[VAL_86:.*]] = arith.index_cast %[[VAL_77]] : i32 to index
// CHECK:               %[[VAL_87:.*]] = scf.index_switch %[[VAL_86]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_8]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_7]] : memref<10xi32>
// CHECK:               }
// CHECK:               %[[VAL_88:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_89:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_90:.*]] = arith.subi %[[VAL_88]], %[[VAL_80]] : i32
// CHECK:               %[[VAL_91:.*]] = arith.maxsi %[[VAL_90]], %[[VAL_89]] : i32
// CHECK:               aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_91]])
// CHECK:               %[[VAL_92:.*]] = arith.addi %[[VAL_80]], %[[VAL_91]] : i32
// CHECK:               %[[VAL_93:.*]] = arith.index_cast %[[VAL_78]] : i32 to index
// CHECK:               %[[VAL_94:.*]] = scf.index_switch %[[VAL_93]] -> memref<10xi32>
// CHECK:               case 0 {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               case 1 {
// CHECK:                 scf.yield %[[VAL_12]] : memref<10xi32>
// CHECK:               }
// CHECK:               default {
// CHECK:                 scf.yield %[[VAL_11]] : memref<10xi32>
// CHECK:               }
// CHECK:               func.call @passthrough_10_i32(%[[VAL_94]], %[[VAL_87]]) : (memref<10xi32>, memref<10xi32>) -> ()
// CHECK:               %[[VAL_95:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_13]], Release, %[[VAL_95]])
// CHECK:               %[[VAL_96:.*]] = arith.subi %[[VAL_92]], %[[VAL_95]] : i32
// CHECK:               %[[VAL_97:.*]] = arith.constant 2 : i32
// CHECK:               %[[VAL_98:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_99:.*]] = arith.addi %[[VAL_78]], %[[VAL_98]] : i32
// CHECK:               %[[VAL_100:.*]] = arith.cmpi sge, %[[VAL_99]], %[[VAL_97]] : i32
// CHECK:               %[[VAL_101:.*]] = arith.subi %[[VAL_99]], %[[VAL_97]] : i32
// CHECK:               %[[VAL_102:.*]] = arith.select %[[VAL_100]], %[[VAL_101]], %[[VAL_99]] : i32
// CHECK:               %[[VAL_103:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_103]])
// CHECK:               %[[VAL_104:.*]] = arith.subi %[[VAL_85]], %[[VAL_103]] : i32
// CHECK:               %[[VAL_105:.*]] = arith.constant 2 : i32
// CHECK:               %[[VAL_106:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_107:.*]] = arith.addi %[[VAL_77]], %[[VAL_106]] : i32
// CHECK:               %[[VAL_108:.*]] = arith.cmpi sge, %[[VAL_107]], %[[VAL_105]] : i32
// CHECK:               %[[VAL_109:.*]] = arith.subi %[[VAL_107]], %[[VAL_105]] : i32
// CHECK:               %[[VAL_110:.*]] = arith.select %[[VAL_108]], %[[VAL_109]], %[[VAL_107]] : i32
// CHECK:               scf.yield %[[VAL_110]], %[[VAL_102]], %[[VAL_104]], %[[VAL_96]] : i32, i32, i32, i32
// CHECK:             }
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @input_fifo_shim_alloc(%[[VAL_2]], MM2S, 0)
// CHECK:           %[[VAL_111:.*]] = aie.mem(%[[VAL_3]]) {
// CHECK:             %[[VAL_112:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_113:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_25]], AcquireGreaterEqual, %[[VAL_113]])
// CHECK:             aie.dma_bd(%[[VAL_23]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_114:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_26]], Release, %[[VAL_114]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             %[[VAL_115:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_25]], AcquireGreaterEqual, %[[VAL_115]])
// CHECK:             aie.dma_bd(%[[VAL_24]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_116:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_26]], Release, %[[VAL_116]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             %[[VAL_117:.*]] = aie.dma_start(MM2S, 0, ^bb4, ^bb6)
// CHECK:           ^bb4:
// CHECK:             %[[VAL_118:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_118]])
// CHECK:             aie.dma_bd(%[[VAL_19]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_119:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_119]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb5:
// CHECK:             %[[VAL_120:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_120]])
// CHECK:             aie.dma_bd(%[[VAL_20]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_121:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_121]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb6:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @output_fifo_shim_alloc(%[[VAL_2]], S2MM, 0)
// CHECK:           aie.shim_dma_allocation @input_fifo2_shim_alloc(%[[VAL_2]], MM2S, 1)
// CHECK:           %[[VAL_122:.*]] = aie.mem(%[[VAL_4]]) {
// CHECK:             %[[VAL_123:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_124:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_124]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_125:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_125]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             %[[VAL_126:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_126]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_127:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], Release, %[[VAL_127]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             %[[VAL_128:.*]] = aie.dma_start(MM2S, 0, ^bb4, ^bb6)
// CHECK:           ^bb4:
// CHECK:             %[[VAL_129:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_129]])
// CHECK:             aie.dma_bd(%[[VAL_7]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_130:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_130]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb5:
// CHECK:             %[[VAL_131:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_131]])
// CHECK:             aie.dma_bd(%[[VAL_8]] : memref<10xi32> offset = 0 len = 10)
// CHECK:             %[[VAL_132:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_132]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb6:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @output_fifo2_shim_alloc(%[[VAL_2]], S2MM, 1)
// CHECK:         }


module {
  aie.device(npu1_1col) {
    func.func @passthrough_10_i32(%line_in: memref<10xi32>, %line_out: memref<10xi32>) -> () {
        return
    }

    %tile_0_0 = aie.tile(0, 0)
    %tile_0_2 = aie.tile(0, 2)
    %tile_0_4 = aie.tile(0, 4)
    aie.objectfifo @input_fifo(%tile_0_0, {%tile_0_2}, 2 : i32) : !aie.objectfifo<memref<10xi32>>
    aie.objectfifo @output_fifo(%tile_0_2, {%tile_0_0}, 2 : i32) : !aie.objectfifo<memref<10xi32>>

    aie.objectfifo @input_fifo2(%tile_0_0, {%tile_0_4}, 2 : i32) : !aie.objectfifo<memref<10xi32>>
    aie.objectfifo @output_fifo2(%tile_0_4, {%tile_0_0}, 2 : i32) : !aie.objectfifo<memref<10xi32>>

    %core_0_2 = aie.core(%tile_0_2) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c10 = arith.constant 10 : index

      scf.for %arg0 = %c0 to %c10 step %c1 {
        %0 = aie.objectfifo.acquire @output_fifo(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
        %1 = aie.objectfifo.subview.access %0[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %2 = aie.objectfifo.acquire @input_fifo(Consume, 1) : !aie.objectfifosubview<memref<10xi32>>
        %3 = aie.objectfifo.subview.access %2[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        func.call @passthrough_10_i32(%3, %1) : (memref<10xi32>, memref<10xi32>) -> ()
        aie.objectfifo.release @input_fifo(Consume, 1)
        aie.objectfifo.release @output_fifo(Produce, 1)
      }

      aie.end
    } {dynamic_objfifo_lowering = false}

    %core_0_4 = aie.core(%tile_0_4) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c10 = arith.constant 10 : index

      scf.for %arg0 = %c0 to %c10 step %c1 {
        %0 = aie.objectfifo.acquire @output_fifo2(Produce, 1) : !aie.objectfifosubview<memref<10xi32>>
        %1 = aie.objectfifo.subview.access %0[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        %2 = aie.objectfifo.acquire @input_fifo2(Consume, 1) : !aie.objectfifosubview<memref<10xi32>>
        %3 = aie.objectfifo.subview.access %2[0] : !aie.objectfifosubview<memref<10xi32>> -> memref<10xi32>
        func.call @passthrough_10_i32(%3, %1) : (memref<10xi32>, memref<10xi32>) -> ()
        aie.objectfifo.release @input_fifo2(Consume, 1)
        aie.objectfifo.release @output_fifo2(Produce, 1)
      }

      aie.end
    }
  }
}
