//===- AieBinding.td ---------------------------------------*- tablegen -*-===//
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef AIE_BINDING_TD
#define AIE_BINDING_TD

include "mlir/Bindings/Python/Attributes.td"
include "aie/Dialect/AIE/IR/AIE.td"

#endif // AIE_BINDING_TD