//===- AIEVecBinding.td --------------------------------------*- tablegen -*-===//
//
// Copyright (C) 2023, Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef AIEVEC_BINDING_TD
#define AIEVEC_BINDING_TD

include "aie/Dialect/AIEVec/IR/AIEVecOps.td"

#endif // AIEVEC_BINDING_TD
