#!/bin/bash
#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2021 Xilinx Inc.
# (c) Copyright 2022-2024 Advanced Micro Devices, Inc.

TARGET=${1^^}
shift

# check to see if the next command line argument is -aietools
if [ "$1" == "-aietools" ]
  then
    AIETOOLS=$2
    shift
    shift
fi

AIETOOLS_PATH=`realpath $(dirname $(which xchesscc))/../`
AIETOOLS="${AIETOOLS:-${AIETOOLS_PATH}}"

if [ $TARGET != "AIE" -a $TARGET != "AIE2" ]
  then
    echo "xchesscc_wrapper: first argument is expected to be the target architecture (aie or aie2)"
    exit 1
fi
if [ $TARGET == "AIE" ]
  then
    EXTRA_DEFS="-D__AIE_ARCH__=10 -D__AIEARCH__=10"
    AIEARCH=versal_prod
    AIETARGET=versal_prod
elif [ $TARGET == "AIE2" ]
  then
    EXTRA_DEFS="-D__AIE_ARCH__=20 -D__AIEARCH__=20"
    AIEARCH=aie2
    AIETARGET=aie_ml
fi
if [ -z "$AIETOOLS" ]
  then
    echo "xchesscc_wrapper needs a valid Vitis installation"
    exit 1
fi

LIBDIR=${AIETOOLS}/data/${AIETARGET}/lib
INCDIR=${AIETOOLS}/include

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
xchesscc --aiearch ${AIEARCH} -p me -C Release_LLVM -D__AIENGINE__ $EXTRA_DEFS -I $INCDIR -P $LIBDIR -d -f $@
