.nh
.TH "GH-AGENT-TASK" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-agent-task - Work with agent tasks (preview)


.SH SYNOPSIS
\fBgh agent-task <command> [flags]\fR


.SH DESCRIPTION
Working with agent tasks in the GitHub CLI is in preview and
subject to change without notice.


.SH AVAILABLE COMMANDS
.TP
\fBgh-agent-task-create(1)\fR
Create an agent task (preview)

.TP
\fBgh-agent-task-list(1)\fR
List agent tasks (preview)

.TP
\fBgh-agent-task-view(1)\fR
View an agent task session (preview)


.SH ALIASES
gh agent-tasks, gh agent, gh agents


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# List your most recent agent tasks
$ gh agent-task list

# Create a new agent task on the current repository
$ gh agent-task create "Improve the performance of the data processing pipeline"

# View details about agent tasks associated with a pull request
$ gh agent-task view 123

# View details about a specific agent task
$ gh agent-task view 12345abc-12345-12345-12345-12345abc

.EE


.SH SEE ALSO
\fBgh(1)\fR
