.nh
.TH "GH-AUTH-STATUS" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-auth-status - Display active account and authentication state on each known GitHub host


.SH SYNOPSIS
\fBgh auth status [flags]\fR


.SH DESCRIPTION
Display active account and authentication state on each known GitHub host.

.PP
For each host, the authentication state of each known account is tested and any issues are included in the output.
Each host section will indicate the active account, which will be used when targeting that host.

.PP
If an account on any host (or only the one given via \fB--hostname\fR) has authentication issues,
the command will exit with 1 and output to stderr. Note that when using the \fB--json\fR option, the command
will always exit with zero regardless of any authentication issues, unless there is a fatal error.

.PP
To change the active account for a host, see \fBgh auth switch\fR\&.


.SH OPTIONS
.TP
\fB-a\fR, \fB--active\fR
Display the active account only

.TP
\fB-h\fR, \fB--hostname\fR \fB<string>\fR
Check only a specific hostname's auth status

.TP
\fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--json\fR \fB<fields>\fR
Output JSON with the specified fields

.TP
\fB-t\fR, \fB--show-token\fR
Display the auth token

.TP
\fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"


.SH JSON FIELDS
hosts


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Display authentication status for all accounts on all hosts
$ gh auth status

# Display authentication status for the active account on a specific host
$ gh auth status --active --hostname github.example.com

# Display tokens in plain text
$ gh auth status --show-token

# Format authentication status as JSON
$ gh auth status --json hosts

# Include plain text token in JSON output
$ gh auth status --json hosts --show-token

# Format hosts as a flat JSON array
$ gh auth status --json hosts --jq '.hosts | add'

.EE


.SH SEE ALSO
\fBgh-auth(1)\fR
