.nh
.TH "GH-DISCUSSION-CREATE" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-discussion-create - Create a new discussion (preview)


.SH SYNOPSIS
\fBgh discussion create [flags]\fR


.SH DESCRIPTION
Create a new GitHub Discussion in a repository.

.PP
With \fB--title\fR, \fB--body\fR (or \fB--body-file\fR), and \fB--category\fR, a discussion is created non-interactively.
Omitting any of these flags triggers interactive prompts when connected to a terminal.


.SH OPTIONS
.TP
\fB-b\fR, \fB--body\fR \fB<string>\fR
Body for the discussion

.TP
\fB-F\fR, \fB--body-file\fR \fB<string>\fR
Read body text from file (use "-" to read from stdin)

.TP
\fB-c\fR, \fB--category\fR \fB<string>\fR
Category name or slug for the discussion

.TP
\fB-l\fR, \fB--label\fR \fB<strings>\fR
Labels to apply to the discussion

.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format

.TP
\fB-t\fR, \fB--title\fR \fB<string>\fR
Title for the discussion


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Create interactively
$ gh discussion create

# Create non-interactively
$ gh discussion create --title "My question" --category "Q&A" --body "Details here"

.EE


.SH SEE ALSO
\fBgh-discussion(1)\fR
