.nh
.TH "GH-ISSUE-CLOSE" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-issue-close - Close issue


.SH SYNOPSIS
\fBgh issue close {<number> | <url>} [flags]\fR


.SH OPTIONS
.TP
\fB-c\fR, \fB--comment\fR \fB<string>\fR
Leave a closing comment

.TP
\fB--duplicate-of\fR \fB<string>\fR
Mark as duplicate of another issue by number or URL

.TP
\fB-r\fR, \fB--reason\fR \fB<string>\fR
Reason for closing: {completed|not planned|duplicate}


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH EXAMPLE
.EX
# Close issue
$ gh issue close 123

# Close issue and add a closing comment
$ gh issue close 123 --comment "Closing this issue"

# Close issue as a duplicate of issue #456
$ gh issue close 123 --duplicate-of 456

# Close issue as not planned
$ gh issue close 123 --reason "not planned"

.EE


.SH SEE ALSO
\fBgh-issue(1)\fR
