.nh
.TH "GH-LICENSES" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-licenses - View third-party license information


.SH SYNOPSIS
\fBgh licenses [flags]\fR


.SH DESCRIPTION
View license information for third-party libraries used in this build of the GitHub CLI.


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh(1)\fR
