.nh
.TH "GH-PR-REVERT" "1" "Jul 2026" "GitHub CLI 2.96.0" "GitHub CLI manual"

.SH NAME
gh-pr-revert - Revert a pull request


.SH SYNOPSIS
\fBgh pr revert {<number> | <url> | <branch>} [flags]\fR


.SH OPTIONS
.TP
\fB-b\fR, \fB--body\fR \fB<string>\fR
Body for the revert pull request

.TP
\fB-F\fR, \fB--body-file\fR \fB<file>\fR
Read body text from file (use "-" to read from standard input)

.TP
\fB-d\fR, \fB--draft\fR
Mark revert pull request as a draft

.TP
\fB-t\fR, \fB--title\fR \fB<string>\fR
Title for the revert pull request


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-pr(1)\fR
