name: "Setup ccache"

inputs:
  MATRIX_OS:
    description: ''
    required: true
  MATRIX_ARCH:
    description: ''
    required: true
  EXTRA_KEY:
    description: ''
    required: false

outputs:
  HOST_CCACHE_DIR:
    description: ''
    value: ${{ steps.configure_ccache_dir_on_host.outputs.HOST_CCACHE_DIR }}

description: ''

runs:
  using: "composite"
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        key: ${{ inputs.MATRIX_OS }}-${{ inputs.MATRIX_ARCH }}-${{ inputs.EXTRA_KEY }}
        max-size: "1G"
        verbose: 2

    - name: Configure ccache dir on host ubuntu
      if: contains(inputs.MATRIX_OS, 'ubuntu')
      shell: bash
      id: configure_ccache_dir_on_host
      run: |
        
        HOST_CCACHE_DIR="$(ccache --get-config cache_dir)"
        mkdir -p $HOST_CCACHE_DIR
        echo "HOST_CCACHE_DIR=$HOST_CCACHE_DIR" | tee -a $GITHUB_OUTPUT

    - name: Configure ccache
      if: contains(inputs.MATRIX_OS, 'ubuntu') || contains(inputs.MATRIX_OS, 'macos')
      shell: bash
      run: |
        
        if [ x"${{ contains(inputs.MATRIX_OS, 'macos') }}" == x"true" ]; then
          echo "/usr/local/opt/ccache/libexec:/opt/homebrew/opt/ccache/libexec" >> $GITHUB_PATH
        else
          echo "/usr/lib/ccache:/usr/lib64/ccache:/usr/lib/ccache/bin" >> $GITHUB_PATH
        fi

    - name: Configure ccache
      shell: bash
      run: |
        ccache -z
        # See https://github.com/hendrikmuhs/ccache-action/issues/146
        ccache --set-config=compiler_check=content
        ccache --set-config=sloppiness=locale,time_macros
