MLIR-AIE: lib/Dialect/AIE/Transforms/AIEAssignBuffers.cpp File Reference
AIEAssignBuffers.cpp File Reference
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIE/Transforms/AIEPasses.h"
#include "mlir/IR/Attributes.h"
#include "aie/Dialect/AIE/Transforms/AIEPasses.h.inc"
Classes
struct BankLimits
struct AIEAssignBufferAddressesPass
Namespaces
namespace xilinx
namespace xilinx::AIE
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_AIEASSIGNBUFFERADDRESSES
#define DEBUG_TYPE "aie-assign-buffers"
Typedefs
typedef struct BankLimits BankLimits
Functions
bool checkAndPrintOverflow (TileOp tile, int address, int maxDataMemorySize, int stacksize, SmallVector< BufferOp > &buffers)
bool basicAllocation (TileOp tile)
void fillBankLimits (int numBanks, int bankSize, std::vector< BankLimits > &bankLimits)
void setAndUpdateAddressInBank (BufferOp buffer, int64_t start_addr, int64_t end_addr, std::vector< int64_t > &nextAddrInBanks)
FailureOr< bool > checkAndAddBufferWithAddress (BufferOp buffer, int numBanks, std::vector< int64_t > &nextAddrInBanks, std::vector< BankLimits > &bankLimits)
FailureOr< bool > checkAndAddBufferWithMemBank (BufferOp buffer, int numBanks, std::vector< int64_t > &nextAddrInBanks, std::vector< BankLimits > &bankLimits)
void printMemMap (TileOp tile, SmallVector< BufferOp > &allocatedBuffers, SmallVector< BufferOp > &preAllocatedBuffers, int numBanks, std::vector< BankLimits > &bankLimits, int stacksize)
int setBufferAddress (BufferOp buffer, int numBanks, int &startBankIndex, std::vector< int64_t > &nextAddrInBanks, std::vector< BankLimits > &bankLimits)
bool checkAndPrintOverflow (TileOp tile, int numBanks, int stacksize, SmallVector< BufferOp > &allBuffers, std::vector< int64_t > &nextAddrInBanks, std::vector< BankLimits > &bankLimits)
void deAllocationBuffers (SmallVector< BufferOp > &buffers)
bool simpleBankAwareAllocation (TileOp tile)
LogicalResult checkBufferScope (BufferOp buffer, DeviceOp device)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aie-assign-buffers"
Definition at line 21 of file AIEAssignBuffers.cpp.
GEN_PASS_DEF_AIEASSIGNBUFFERADDRESSES
#define GEN_PASS_DEF_AIEASSIGNBUFFERADDRESSES
Definition at line 17 of file AIEAssignBuffers.cpp.
Typedef Documentation
BankLimits
typedef struct BankLimits BankLimits
Function Documentation
basicAllocation()
bool basicAllocation (TileOp tile)
Definition at line 58 of file AIEAssignBuffers.cpp.
References checkAndPrintOverflow(), and xilinx::AIE::getTargetModel().
Referenced by AIEAssignBufferAddressesPass::runOnOperation().
checkAndAddBufferWithAddress()
FailureOr< bool > checkAndAddBufferWithAddress (BufferOp buffer, int numBanks, std::vector< int64_t > & nextAddrInBanks, std::vector< BankLimits > & bankLimits)
Definition at line 170 of file AIEAssignBuffers.cpp.
Referenced by simpleBankAwareAllocation().
checkAndAddBufferWithMemBank()
FailureOr< bool > checkAndAddBufferWithMemBank (BufferOp buffer, int numBanks, std::vector< int64_t > & nextAddrInBanks, std::vector< BankLimits > & bankLimits)
Definition at line 201 of file AIEAssignBuffers.cpp.
References setAndUpdateAddressInBank().
Referenced by simpleBankAwareAllocation().
checkAndPrintOverflow() [1/2]
bool checkAndPrintOverflow (TileOp tile, int address, int maxDataMemorySize, int stacksize, SmallVector< BufferOp > & buffers)
Definition at line 30 of file AIEAssignBuffers.cpp.
Referenced by basicAllocation(), and simpleBankAwareAllocation().
checkAndPrintOverflow() [2/2]
bool checkAndPrintOverflow (TileOp tile, int numBanks, int stacksize, SmallVector< BufferOp > & allBuffers, std::vector< int64_t > & nextAddrInBanks, std::vector< BankLimits > & bankLimits)
Definition at line 298 of file AIEAssignBuffers.cpp.
checkBufferScope()
LogicalResult checkBufferScope (BufferOp buffer, DeviceOp device)
Definition at line 457 of file AIEAssignBuffers.cpp.
Referenced by AIEAssignBufferAddressesPass::runOnOperation().
deAllocationBuffers()
void deAllocationBuffers (SmallVector< BufferOp > & buffers)
Definition at line 349 of file AIEAssignBuffers.cpp.
Referenced by simpleBankAwareAllocation().
fillBankLimits()
void fillBankLimits (int numBanks, int bankSize, std::vector< BankLimits > & bankLimits)
Definition at line 143 of file AIEAssignBuffers.cpp.
Referenced by simpleBankAwareAllocation().
printMemMap()
void printMemMap (TileOp tile, SmallVector< BufferOp > & allocatedBuffers, SmallVector< BufferOp > & preAllocatedBuffers, int numBanks, std::vector< BankLimits > & bankLimits, int stacksize)
Definition at line 218 of file AIEAssignBuffers.cpp.
Referenced by simpleBankAwareAllocation().
setAndUpdateAddressInBank()
void setAndUpdateAddressInBank (BufferOp buffer, int64_t start_addr, int64_t end_addr, std::vector< int64_t > & nextAddrInBanks)
Definition at line 155 of file AIEAssignBuffers.cpp.
Referenced by checkAndAddBufferWithMemBank(), and setBufferAddress().
setBufferAddress()
int setBufferAddress (BufferOp buffer, int numBanks, int & startBankIndex, std::vector< int64_t > & nextAddrInBanks, std::vector< BankLimits > & bankLimits)
Definition at line 267 of file AIEAssignBuffers.cpp.
References setAndUpdateAddressInBank().
Referenced by simpleBankAwareAllocation().
simpleBankAwareAllocation()
bool simpleBankAwareAllocation (TileOp tile)
Definition at line 356 of file AIEAssignBuffers.cpp.
References checkAndAddBufferWithAddress(), checkAndAddBufferWithMemBank(), checkAndPrintOverflow(), deAllocationBuffers(), fillBankLimits(), xilinx::AIE::getTargetModel(), printMemMap(), and setBufferAddress().
Referenced by AIEAssignBufferAddressesPass::runOnOperation().