MLIR-AIE: include/aie/Dialect/AIE/Transforms/AIEGenerateColumnControlOverlay.h File Reference
AIEGenerateColumnControlOverlay.h File Reference
#include "aie/Dialect/AIE/IR/AIEDialect.h"
Functions
void populateAIEColumnControlOverlay (DeviceOp &device)
DenseMap< int, int > getRowToShimChanMap (const AIETargetModel &targetModel, WireBundle bundle)
DenseMap< TileID, int > getTileToControllerIdMap (bool clColumnWiseUniqueIDs, const AIETargetModel &targetModel)
Function Documentation
getRowToShimChanMap()
DenseMap< int, int > getRowToShimChanMap (const AIETargetModel & targetModel, WireBundle bundle)
Definition at line 97 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::AIETargetModel::columns(), xilinx::AIE::AIETargetModel::getNumSourceShimMuxConnections(), xilinx::AIE::AIETargetModel::isShimNOCTile(), and xilinx::AIE::AIETargetModel::rows().
Referenced by AIEGenerateColumnControlOverlayPass::generatePacketFlowsForControl(), and AIECtrlPacketToDmaPass::runOnOperation().
getTileToControllerIdMap()
DenseMap< TileID, int > getTileToControllerIdMap (bool clColumnWiseUniqueIDs, const AIETargetModel & targetModel)
Definition at line 70 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::col, xilinx::AIE::AIETargetModel::columns(), getTileToControllerIdMap6RowsOrLess(), xilinx::AIE::row, and xilinx::AIE::AIETargetModel::rows().
Referenced by AIEAssignTileCtrlIDsPass::runOnOperation(), AIEGenerateColumnControlOverlayPass::runOnOperation(), and AIECtrlPacketInferTilesPass::runOnOperation().
populateAIEColumnControlOverlay()
void populateAIEColumnControlOverlay (DeviceOp & device)
Definition at line 407 of file AIEGenerateColumnControlOverlay.cpp.