MLIR-AIE: lib/Dialect/AIE/Transforms/AIEGenerateColumnControlOverlay.cpp File Reference
AIEGenerateColumnControlOverlay.cpp File Reference
#include "aie/Dialect/AIE/Transforms/AIEGenerateColumnControlOverlay.h"
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIE/Transforms/AIEPasses.h"
#include "mlir/IR/Attributes.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/SmallSet.h"
#include "aie/Dialect/AIE/Transforms/AIEPasses.h.inc"
Classes
struct AIEAssignTileCtrlIDsPass
struct AIEGenerateColumnControlOverlayPass
Namespaces
namespace xilinx
namespace xilinx::AIE
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_AIEGENERATECOLUMNCONTROLOVERLAY
#define GEN_PASS_DEF_AIEASSIGNTILECTRLIDS
#define DEBUG_TYPE "aie-generate-column-control-overlay"
Functions
int getUnusedPacketIdFrom (DeviceOp device)
DenseMap< AIE::TileID, int > getTileToControllerIdMap6RowsOrLess (bool clColumnWiseUniqueIDs, const AIETargetModel &targetModel)
DenseMap< AIE::TileID, int > getTileToControllerIdMap (bool clColumnWiseUniqueIDs, const AIETargetModel &targetModel)
DenseMap< int, int > getRowToShimChanMap (const AIETargetModel &targetModel, WireBundle bundle)
void populateAIEColumnControlOverlay (DeviceOp &device)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aie-generate-column-control-overlay"
Definition at line 26 of file AIEGenerateColumnControlOverlay.cpp.
GEN_PASS_DEF_AIEASSIGNTILECTRLIDS
#define GEN_PASS_DEF_AIEASSIGNTILECTRLIDS
Definition at line 22 of file AIEGenerateColumnControlOverlay.cpp.
GEN_PASS_DEF_AIEGENERATECOLUMNCONTROLOVERLAY
#define GEN_PASS_DEF_AIEGENERATECOLUMNCONTROLOVERLAY
Definition at line 21 of file AIEGenerateColumnControlOverlay.cpp.
Function Documentation
getRowToShimChanMap()
DenseMap< int, int > getRowToShimChanMap (const AIETargetModel & targetModel, WireBundle bundle)
Definition at line 103 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::AIETargetModel::columns(), xilinx::AIE::AIETargetModel::getNumSourceShimMuxConnections(), xilinx::AIE::AIETargetModel::isShimNOCTile(), and xilinx::AIE::AIETargetModel::rows().
Referenced by AIEGenerateColumnControlOverlayPass::generatePacketFlowsForControl(), and AIECtrlPacketToDmaPass::runOnOperation().
getTileToControllerIdMap()
DenseMap< AIE::TileID, int > getTileToControllerIdMap (bool clColumnWiseUniqueIDs, const AIETargetModel & targetModel)
Definition at line 76 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::col, xilinx::AIE::AIETargetModel::columns(), getTileToControllerIdMap6RowsOrLess(), xilinx::AIE::row, and xilinx::AIE::AIETargetModel::rows().
Referenced by AIEAssignTileCtrlIDsPass::runOnOperation(), AIEGenerateColumnControlOverlayPass::runOnOperation(), and AIECtrlPacketInferTilesPass::runOnOperation().
getTileToControllerIdMap6RowsOrLess()
DenseMap< AIE::TileID, int > getTileToControllerIdMap6RowsOrLess (bool clColumnWiseUniqueIDs, const AIETargetModel & targetModel)
Definition at line 51 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::col, xilinx::AIE::AIETargetModel::columns(), xilinx::AIE::row, and xilinx::AIE::AIETargetModel::rows().
Referenced by getTileToControllerIdMap().
getUnusedPacketIdFrom()
int getUnusedPacketIdFrom (DeviceOp device)
Definition at line 32 of file AIEGenerateColumnControlOverlay.cpp.
populateAIEColumnControlOverlay()
void populateAIEColumnControlOverlay (DeviceOp & device)
Definition at line 417 of file AIEGenerateColumnControlOverlay.cpp.