MLIR-AIE: lib/Dialect/AIEX/Transforms/AIEHerdRouting.cpp File Reference
AIEHerdRouting.cpp File Reference
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIEX/IR/AIEXDialect.h"
#include "aie/Dialect/AIEX/Transforms/AIEXPasses.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Tools/mlir-translate/MlirTranslateMain.h"
#include "mlir/Transforms/DialectConversion.h"
#include "aie/Dialect/AIEX/Transforms/AIEXPasses.h.inc"
Classes
struct AIEOpRemoval< MyAIEOp >
struct AIEHerdRoutingPass
Namespaces
namespace xilinx
namespace xilinx::AIEX
Macros
#define GEN_PASS_DEF_AIEHERDROUTING
#define DEBUG_TYPE "aie-herd-routing"
Functions
std::optional< int > getAvailableDestChannel (SmallVector< Connect, 8 > &connects, Port sourcePort, WireBundle destBundle)
void buildRoute (int xSrc, int ySrc, int xDest, int yDest, WireBundle sourceBundle, int sourceChannel, WireBundle destBundle, int destChannel, Operation *herdOp, DenseMap< std::pair< Operation *, TileID >, SmallVector< Connect, 8 > > &switchboxes)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aie-herd-routing"
Definition at line 25 of file AIEHerdRouting.cpp.
GEN_PASS_DEF_AIEHERDROUTING
#define GEN_PASS_DEF_AIEHERDROUTING
Definition at line 21 of file AIEHerdRouting.cpp.
Function Documentation
buildRoute()
void buildRoute (int xSrc, int ySrc, int xDest, int yDest, WireBundle sourceBundle, int sourceChannel, WireBundle destBundle, int destChannel, Operation * herdOp, DenseMap< std::pair< Operation *, TileID >, SmallVector< Connect, 8 > > & switchboxes)
Definition at line 89 of file AIEHerdRouting.cpp.
References getAvailableDestChannel().
Referenced by AIEHerdRoutingPass::runOnOperation().
getAvailableDestChannel()
std::optional< int > getAvailableDestChannel (SmallVector< Connect, 8 > & connects, Port sourcePort, WireBundle destBundle)
Definition at line 50 of file AIEHerdRouting.cpp.
References xilinx::AIE::dst, xilinx::AIE::port, and xilinx::AIE::src.
Referenced by buildRoute().