MLIR-AIE: lib/Targets/AIETargetBCF.cpp File Reference
AIETargetBCF.cpp File Reference
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIEX/IR/AIEXDialect.h"
#include "aie/Targets/AIETargets.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Tools/mlir-translate/MlirTranslateMain.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Module.h"
Namespaces
xilinx
xilinx::AIE
Include the generated interface declarations.
Functions
std::string utohexstr (uint32_t u)
LogicalResult xilinx::AIE::AIETranslateToBCF (ModuleOp module, raw_ostream &output, int tileCol, int tileRow)
Function Documentation
utohexstr()
std::string utohexstr (uint32_t u)
Definition at line 24 of file AIETargetBCF.cpp.
Referenced by xilinx::AIE::AIETranslateToBCF(), checkAndPrintOverflow(), printMemMap(), and xilinx::AIE::writeBufferMap().