MLIR-AIE: lib/Dialect/AIEVec/IR/AIEVecOps.cpp File Reference
AIEVecOps.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "aie/Dialect/AIEVec/AIEVecUtils.h"
#include "aie/Dialect/AIEVec/IR/AIEVecOps.h"
#include "aie/Dialect/AIEVec/IR/AIEVecEnums.cpp.inc"
#include "aie/Dialect/AIEVec/IR/AIEVecOpsDialect.cpp.inc"
#include "aie/Dialect/AIEVec/IR/AIEVecAttributes.cpp.inc"
#include "aie/Dialect/AIEVec/IR/AIEVecOps.cpp.inc"
Macros
#define GET_ATTRDEF_LIST
#define GET_OP_LIST
#define GET_ATTRDEF_CLASSES
#define GET_OP_CLASSES
Functions
template<typename T >
void printAccumulator (OpAsmPrinter &p, T op)
template<>
void printAccumulator (OpAsmPrinter &p, aievec::FMAElemOp op)
template<>
void printAccumulator (OpAsmPrinter &p, aievec::MulElemOp op)
template<typename T >
void elideFMSubAttr (T op, SmallVector< StringRef, 4 > &elidedAttrs)
template<>
void elideFMSubAttr (aievec::FMAElemOp op, SmallVector< StringRef, 4 > &elidedAttrs)
template<>
void elideFMSubAttr (aievec::MulElemOp op, SmallVector< StringRef, 4 > &elidedAttrs)
template<typename T >
LogicalResult verifyMulFMAElemOp (T op)
ParseResult parseMulFMAElemOp (OpAsmParser &parser, OperationState &result, bool isFMAElemOp=true)
template<typename T >
LogicalResult verifyPackUnpackOp (T op)
ParseResult parsePackUnpackOp (OpAsmParser &parser, OperationState &result)
template<>
void printAccumulator (OpAsmPrinter &p, aievec::FMAConvOp op)
template<>
void printAccumulator (OpAsmPrinter &p, aievec::MulConvOp op)
template<>
void elideFMSubAttr (FMAConvOp op, SmallVector< StringRef, 4 > &elidedAttrs)
template<>
void elideFMSubAttr (MulConvOp op, SmallVector< StringRef, 4 > &elidedAttrs)
template<typename T >
LogicalResult verifyMulFMAConvOp (T op)
ParseResult parseMulFMAConvOp (OpAsmParser &parser, OperationState &result, bool isFMAConvOp=true)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 1564 of file AIEVecOps.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1567 of file AIEVecOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
elideFMSubAttr() [1/5]
template<> void elideFMSubAttr (aievec::FMAElemOp op, SmallVector< StringRef, 4 > & elidedAttrs) inline
Definition at line 619 of file AIEVecOps.cpp.
elideFMSubAttr() [2/5]
template<> void elideFMSubAttr (aievec::MulElemOp op, SmallVector< StringRef, 4 > & elidedAttrs) inline
Definition at line 626 of file AIEVecOps.cpp.
elideFMSubAttr() [3/5]
template<> void elideFMSubAttr (FMAConvOp op, SmallVector< StringRef, 4 > & elidedAttrs) inline
Definition at line 1392 of file AIEVecOps.cpp.
elideFMSubAttr() [4/5]
template<> void elideFMSubAttr (MulConvOp op, SmallVector< StringRef, 4 > & elidedAttrs) inline
Definition at line 1399 of file AIEVecOps.cpp.
elideFMSubAttr() [5/5]
template<typename T > void elideFMSubAttr (T op, SmallVector< StringRef, 4 > & elidedAttrs)
parseMulFMAConvOp()
ParseResult parseMulFMAConvOp (OpAsmParser & parser, OperationState & result, bool isFMAConvOp = true)
Definition at line 1503 of file AIEVecOps.cpp.
parseMulFMAElemOp()
ParseResult parseMulFMAElemOp (OpAsmParser & parser, OperationState & result, bool isFMAElemOp = true)
Definition at line 724 of file AIEVecOps.cpp.
parsePackUnpackOp()
ParseResult parsePackUnpackOp (OpAsmParser & parser, OperationState & result)
Definition at line 1043 of file AIEVecOps.cpp.
printAccumulator() [1/5]
template<> void printAccumulator (OpAsmPrinter & p, aievec::FMAConvOp op) inline
Definition at line 1382 of file AIEVecOps.cpp.
printAccumulator() [2/5]
template<> void printAccumulator (OpAsmPrinter & p, aievec::FMAElemOp op) inline
Definition at line 609 of file AIEVecOps.cpp.
printAccumulator() [3/5]
template<> void printAccumulator (OpAsmPrinter & p, aievec::MulConvOp op) inline
Definition at line 1386 of file AIEVecOps.cpp.
printAccumulator() [4/5]
template<> void printAccumulator (OpAsmPrinter & p, aievec::MulElemOp op) inline
Definition at line 613 of file AIEVecOps.cpp.
printAccumulator() [5/5]
template<typename T > void printAccumulator (OpAsmPrinter & p, T op)
verifyMulFMAConvOp()
template<typename T > LogicalResult verifyMulFMAConvOp (T op)
Definition at line 1434 of file AIEVecOps.cpp.
References xilinx::aievec::getVectorLaneSize().
verifyMulFMAElemOp()
template<typename T > LogicalResult verifyMulFMAElemOp (T op)
Definition at line 661 of file AIEVecOps.cpp.
References xilinx::aievec::getVectorLaneSize().
verifyPackUnpackOp()
template<typename T > LogicalResult verifyPackUnpackOp (T op)
Definition at line 1003 of file AIEVecOps.cpp.
References xilinx::aievec::getVectorLaneSize().