MLIR-AIE: cxxopts::Options Class Reference
cxxopts::Options Class Reference
#include "/home/runner/work/mlir-aie/mlir-aie/runtime_lib/test_lib/cxxopts.hpp"
Public Member Functions
Options (std::string program_name, std::string help_string="")
Options & positional_help (std::string help_text)
Options & custom_help (std::string help_text)
Options & show_positional_help ()
Options & allow_unrecognised_options ()
Options & set_width (std::size_t width)
Options & set_tab_expansion (bool expansion=true)
ParseResult parse (int argc, const char *const *argv)
OptionAdder add_options (std::string group="")
void add_options (const std::string &group, std::initializer_list< Option > options)
void add_option (const std::string &group, const Option &option)
void add_option (const std::string &group, const std::string &s, const OptionNames &l, std::string desc, const std::shared_ptr< const Value > &value, std::string arg_help)
void add_option (const std::string &group, const std::string &short_name, const std::string &single_long_name, std::string desc, const std::shared_ptr< const Value > &value, std::string arg_help)
void parse_positional (std::string option)
void parse_positional (std::vector< std::string > options)
void parse_positional (std::initializer_list< std::string > options)
template<typename Iterator >
void parse_positional (Iterator begin, Iterator end)
std::string help (const std::vector< std::string > &groups={}, bool print_usage=true) const
std::vector< std::string > groups () const
const HelpGroupDetails & group_help (const std::string &group) const
const std::string & program () const
Detailed Description
Definition at line 1433 of file cxxopts.hpp.
Constructor & Destructor Documentation
Options()
cxxopts::Options::Options (std::string program_name, std::string help_string = "") inline explicit
Definition at line 1435 of file cxxopts.hpp.
Member Function Documentation
add_option() [1/3]
void cxxopts::Options::add_option (const std::string & group, const Option & option) inline
Definition at line 1993 of file cxxopts.hpp.
References add_options().
Referenced by add_option(), and cxxopts::OptionAdder::operator()().
add_option() [2/3]
void cxxopts::Options::add_option (const std::string & group, const std::string & s, const OptionNames & l, std::string desc, const std::shared_ptr< const Value > & value, std::string arg_help) inline
Definition at line 1998 of file cxxopts.hpp.
References cxxopts::HelpOptionDetails::has_default, cxxopts::toLocalString(), and cxxopts::value().
add_option() [3/3]
void cxxopts::Options::add_option (const std::string & group, const std::string & short_name, const std::string & single_long_name, std::string desc, const std::shared_ptr< const Value > & value, std::string arg_help) inline
Definition at line 1487 of file cxxopts.hpp.
References add_option(), and cxxopts::value().
add_options() [1/2]
void cxxopts::Options::add_options (const std::string & group, std::initializer_list< Option > options) inline
Definition at line 1699 of file cxxopts.hpp.
add_options() [2/2]
OptionAdder cxxopts::Options::add_options (std::string group = "") inline
Definition at line 1707 of file cxxopts.hpp.
Referenced by test_utils::add_default_options(), and add_option().
allow_unrecognised_options()
Options & cxxopts::Options::allow_unrecognised_options () inline
Definition at line 1458 of file cxxopts.hpp.
custom_help()
Options & cxxopts::Options::custom_help (std::string help_text) inline
Definition at line 1448 of file cxxopts.hpp.
group_help()
const HelpGroupDetails & cxxopts::Options::group_help (const std::string & group) const inline
Definition at line 2149 of file cxxopts.hpp.
groups()
std::vector< std::string > cxxopts::Options::groups () const inline
Definition at line 2146 of file cxxopts.hpp.
help()
std::string cxxopts::Options::help (const std::vector< std::string > & groups = {}, bool print_usage = true) const inline
Definition at line 2120 of file cxxopts.hpp.
References cxxopts::toLocalString(), and cxxopts::toUTF8String().
Referenced by test_utils::parse_options().
parse()
ParseResult cxxopts::Options::parse (int argc, const char *const * argv) inline
Definition at line 1835 of file cxxopts.hpp.
References cxxopts::OptionParser::parse().
Referenced by test_utils::parse_options().
parse_positional() [1/4]
template<typename Iterator > void cxxopts::Options::parse_positional (Iterator begin, Iterator end) inline
Definition at line 1504 of file cxxopts.hpp.
References parse_positional().
parse_positional() [2/4]
void cxxopts::Options::parse_positional (std::initializer_list< std::string > options) inline
Definition at line 1831 of file cxxopts.hpp.
References parse_positional().
parse_positional() [3/4]
void cxxopts::Options::parse_positional (std::string option) inline
Definition at line 1820 of file cxxopts.hpp.
References parse_positional().
Referenced by parse_positional(), parse_positional(), and parse_positional().
parse_positional() [4/4]
void cxxopts::Options::parse_positional (std::vector< std::string > options) inline
Definition at line 1824 of file cxxopts.hpp.
positional_help()
Options & cxxopts::Options::positional_help (std::string help_text) inline
Definition at line 1443 of file cxxopts.hpp.
program()
const std::string & cxxopts::Options::program () const inline
Definition at line 1515 of file cxxopts.hpp.
set_tab_expansion()
Options & cxxopts::Options::set_tab_expansion (bool expansion = true) inline
Definition at line 1468 of file cxxopts.hpp.
set_width()
Options & cxxopts::Options::set_width (std::size_t width) inline
Definition at line 1463 of file cxxopts.hpp.
show_positional_help()
Options & cxxopts::Options::show_positional_help () inline
Definition at line 1453 of file cxxopts.hpp.
The documentation for this class was generated from the following file:
runtime_lib/test_lib/cxxopts.hpp