MLIR-AIE: d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container > Class Template Reference
d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container > Class Template Reference
#include "Dialect/AIE/Transforms/d_ary_heap.h"
Public Types
typedef Container::size_type size_type
typedef Value value_type
Public Member Functions
d_ary_heap_indirect (DistanceMap distance, IndexInHeapPropertyMap index_in_heap, const Compare &compare=Compare(), const Container &data=Container())
size_type size () const
bool empty () const
void push (const Value &v)
Value & top ()
const Value & top () const
void pop ()
void update (const Value &v)
bool contains (const Value &v) const
void push_or_update (const Value &v)
DistanceMap keys () const
Detailed Description
template<typename Value, std::size_t Arity, typename IndexInHeapPropertyMap, typename DistanceMap, typename Compare = std::less< Value >, typename Container = std::vector< Value >>
class d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >
Definition at line 99 of file d_ary_heap.h.
Member Typedef Documentation
size_type
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> typedef Container::size_type d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::size_type
Definition at line 104 of file d_ary_heap.h.
value_type
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> typedef Value d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::value_type
Definition at line 105 of file d_ary_heap.h.
Constructor & Destructor Documentation
d_ary_heap_indirect()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::d_ary_heap_indirect (DistanceMap distance, IndexInHeapPropertyMap index_in_heap, const Compare & compare = Compare(), const Container & data = Container()) inline
Definition at line 109 of file d_ary_heap.h.
Member Function Documentation
contains()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> bool d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::contains (const Value & v) const inline
Definition at line 175 of file d_ary_heap.h.
References get().
empty()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> bool d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::empty () const inline
Definition at line 123 of file d_ary_heap.h.
keys()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> DistanceMap d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::keys () const inline
Definition at line 194 of file d_ary_heap.h.
pop()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> void d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::pop () inline
Definition at line 146 of file d_ary_heap.h.
References put().
push()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> void d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::push (const Value & v) inline
Definition at line 125 of file d_ary_heap.h.
References put().
push_or_update()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> void d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::push_or_update (const Value & v) inline
Definition at line 181 of file d_ary_heap.h.
References get(), and put().
size()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> size_type d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::size () const inline
Definition at line 121 of file d_ary_heap.h.
top() [1/2]
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> Value & d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::top () inline
Definition at line 134 of file d_ary_heap.h.
top() [2/2]
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> const Value & d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::top () const inline
Definition at line 140 of file d_ary_heap.h.
update()
template<typename Value , std::size_t Arity, typename IndexInHeapPropertyMap , typename DistanceMap , typename Compare = std::less< Value >, typename Container = std::vector< Value >> void d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::update (const Value & v) inline
Definition at line 168 of file d_ary_heap.h.
References get().
The documentation for this class was generated from the following file:
lib/Dialect/AIE/Transforms/d_ary_heap.h