MLIR-AIE: xilinx::aievec::MulElemOpAIE2pConversion Class Reference
xilinx::aievec::MulElemOpAIE2pConversion Class Reference
Classes
struct DecodedMulElemOp
Public Member Functions
LogicalResult matchAndRewrite (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static DecodedMulElemOp decodeMulElemOp (OpAdaptor op)
Detailed Description
Definition at line 1369 of file AIEVecToLLVM.cpp.
Member Function Documentation
decodeMulElemOp()
static DecodedMulElemOp xilinx::aievec::MulElemOpAIE2pConversion::decodeMulElemOp (OpAdaptor op) inline static
Definition at line 1385 of file AIEVecToLLVM.cpp.
References xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_16x1x1x1, xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_32x1x2x1, xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_64x1x2x1, xilinx::aievec::getVectorLaneSize(), and xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::UNSUPPORTED.
Referenced by matchAndRewrite().
matchAndRewrite()
LogicalResult xilinx::aievec::MulElemOpAIE2pConversion::matchAndRewrite (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 1415 of file AIEVecToLLVM.cpp.
References xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_16x1x1x1, xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_32x1x2x1, xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::BF16_BF16_FP32_64x1x2x1, decodeMulElemOp(), and xilinx::aievec::MulElemOpAIE2pConversion::DecodedMulElemOp::UNSUPPORTED.
The documentation for this class was generated from the following file:
lib/Conversion/AIEVecToLLVM/AIEVecToLLVM.cpp