MLIR-AIE: xilinx::AIE::Placer Class Reference
xilinx::AIE::Placer Class Reference abstract
#include "aie/Dialect/AIE/Transforms/AIEPlacer.h"
Classes
struct Adjacency
struct CollectedOps
Public Types
using AllocateInfo = std::pair< mlir::Operation *, TileID >
Public Member Functions
Placer ()=default
virtual ~Placer ()=default
virtual void initialize (const AIETargetModel &targetModel)
virtual mlir::LogicalResult place (DeviceOp device)=0
virtual llvm::StringRef getName () const =0
std::optional< TileID > getPlacement (mlir::Operation *logicalTile) const
llvm::SmallVector< AllocateInfo > & getAllocates ()
Static Public Member Functions
static CollectedOps collectOperations (DeviceOp device)
static bool satisfiesConstraints (mlir::Operation *tile, TileID pos)
static Adjacency buildCascadeAdjacency (llvm::ArrayRef< CascadeFlowOp > cascadeFlows)
static Adjacency buildComputePeerAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos)
static Adjacency buildObjectFifoAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos)
static Adjacency buildFlowAdjacency (llvm::ArrayRef< FlowOp > flows, llvm::ArrayRef< PacketFlowOp > pktFlows)
Protected Attributes
PlacementResult result
llvm::SmallVector< AllocateInfo > allocates
const AIETargetModel * targetModel = nullptr
TileAvailability availability
Detailed Description
Definition at line 61 of file AIEPlacer.h.
Member Typedef Documentation
AllocateInfo
using xilinx::AIE::Placer::AllocateInfo = std::pair<mlir::Operation *, TileID>
Definition at line 82 of file AIEPlacer.h.
Constructor & Destructor Documentation
Placer()
xilinx::AIE::Placer::Placer () default
~Placer()
virtual xilinx::AIE::Placer::~Placer () virtual default
Member Function Documentation
buildCascadeAdjacency()
Placer::Adjacency Placer::buildCascadeAdjacency (llvm::ArrayRef< CascadeFlowOp > cascadeFlows) static
Definition at line 763 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::Adjacency::addEdge(), xilinx::AIE::dst, and xilinx::AIE::src.
Referenced by xilinx::AIE::SequentialPlacer::place().
buildComputePeerAdjacency()
Placer::Adjacency Placer::buildComputePeerAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos) static
Definition at line 776 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::Adjacency::addEdge().
Referenced by xilinx::AIE::SequentialPlacer::place().
buildFlowAdjacency()
Placer::Adjacency Placer::buildFlowAdjacency (llvm::ArrayRef< FlowOp > flows, llvm::ArrayRef< PacketFlowOp > pktFlows) static
Definition at line 1019 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::Adjacency::addEdgeFromValues(), xilinx::AIE::dst, xilinx::AIE::dsts, xilinx::AIE::src, and xilinx::AIE::srcs.
buildObjectFifoAdjacency()
Placer::Adjacency Placer::buildObjectFifoAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos) static
Definition at line 1011 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::Adjacency::addEdgeFromValues().
collectOperations()
Placer::CollectedOps Placer::collectOperations (DeviceOp device) static
Definition at line 69 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::CollectedOps::cascadeFlows, xilinx::AIE::Placer::CollectedOps::flows, xilinx::AIE::Placer::CollectedOps::logicalTiles, xilinx::AIE::Placer::CollectedOps::objectFifoLinks, xilinx::AIE::Placer::CollectedOps::objectFifos, and xilinx::AIE::Placer::CollectedOps::pktFlows.
Referenced by xilinx::AIE::SequentialPlacer::place().
getAllocates()
llvm::SmallVector< AllocateInfo > & xilinx::AIE::Placer::getAllocates () inline
Definition at line 83 of file AIEPlacer.h.
References allocates.
getName()
virtual llvm::StringRef xilinx::AIE::Placer::getName () const pure virtual
Implemented in xilinx::AIE::SequentialPlacer, and xilinx::AIE::SAPlacer.
getPlacement()
std::optional< TileID > xilinx::AIE::Placer::getPlacement (mlir::Operation * logicalTile) const inline
Definition at line 72 of file AIEPlacer.h.
References result.
initialize()
void Placer::initialize (const AIETargetModel & targetModel) virtual
Reimplemented in xilinx::AIE::SequentialPlacer.
Definition at line 47 of file AIEPlacer.cpp.
References availability, xilinx::AIE::col, xilinx::AIE::AIETargetModel::columns(), xilinx::AIE::TileAvailability::compTiles, xilinx::AIE::AIETargetModel::getTileType(), xilinx::AIE::TileAvailability::nonCompTiles, xilinx::AIE::row, xilinx::AIE::AIETargetModel::rows(), and targetModel.
Referenced by xilinx::AIE::SequentialPlacer::initialize().
place()
virtual mlir::LogicalResult xilinx::AIE::Placer::place (DeviceOp device) pure virtual
Implemented in xilinx::AIE::SequentialPlacer, and xilinx::AIE::SAPlacer.
satisfiesConstraints()
bool Placer::satisfiesConstraints (mlir::Operation * tile, TileID pos) static
Definition at line 85 of file AIEPlacer.cpp.
Member Data Documentation
allocates
llvm::SmallVector<AllocateInfo> xilinx::AIE::Placer::allocates protected
Definition at line 141 of file AIEPlacer.h.
Referenced by getAllocates().
availability
TileAvailability xilinx::AIE::Placer::availability protected
Definition at line 143 of file AIEPlacer.h.
Referenced by initialize(), and xilinx::AIE::SequentialPlacer::initialize().
result
PlacementResult xilinx::AIE::Placer::result protected
Definition at line 140 of file AIEPlacer.h.
Referenced by getPlacement().
targetModel
const AIETargetModel* xilinx::AIE::Placer::targetModel = nullptr protected
Definition at line 142 of file AIEPlacer.h.
Referenced by initialize(), xilinx::AIE::SequentialPlacer::initialize(), and xilinx::AIE::SequentialPlacer::place().
The documentation for this class was generated from the following files:
include/aie/Dialect/AIE/Transforms/AIEPlacer.h
lib/Dialect/AIE/Transforms/AIEPlacer.cpp