MLIR-AIE: test_utils::ParameterScratchpad Class Reference
test_utils::ParameterScratchpad Class Reference
#include "/home/runner/work/mlir-aie/mlir-aie/runtime_lib/test_lib/parameter_scratchpad.h"
Public Member Functions
ParameterScratchpad (uint32_t *buffer, const std::string &paramsPath)
Construct from a raw buffer pointer (Python bindings / testing).
void writeBytes (const std::string &name, const void *data, size_t len)
Write raw bytes (up to 4) by name, interpreted as a little-endian uint32.
void writeBits (const std::string &name, uint32_t bits)
Write a raw 32-bit value by name.
template<typename T >
void write (const std::string &name, T value)
Write a typed parameter value.
uint32_t read (const std::string &name) const
Read back a parameter's current encoded value (for debugging).
Detailed Description
Definition at line 47 of file parameter_scratchpad.h.
Constructor & Destructor Documentation
ParameterScratchpad()
test_utils::ParameterScratchpad::ParameterScratchpad (uint32_t * buffer, const std::string & paramsPath) inline
Construct from a raw buffer pointer (Python bindings / testing).
Definition at line 65 of file parameter_scratchpad.h.
Member Function Documentation
read()
uint32_t test_utils::ParameterScratchpad::read (const std::string & name) const inline
Read back a parameter's current encoded value (for debugging).
Definition at line 122 of file parameter_scratchpad.h.
write()
template<typename T > void test_utils::ParameterScratchpad::write (const std::string & name, T value) inline
Write a typed parameter value.
For core-kind parameters, the raw bits are left-shifted by 2 as required by the firmware's UPDATE_REG Incr mode, and the core right-shifts (unsigned) by 2 after reading. The round trip therefore zeroes the top 2 bits of the value (the bottom 2 bits are preserved). Types that fit in 30 bits (e.g. uint16_t, int16_t, std::bfloat16_t, and uint32_t values < 2^30) round-trip losslessly. float is not supported as a core-kind parameter (the verifier in --aie-lower-scratchpad-parameters rejects it).
Definition at line 109 of file parameter_scratchpad.h.
References writeBits().
writeBits()
void test_utils::ParameterScratchpad::writeBits (const std::string & name, uint32_t bits) inline
Write a raw 32-bit value by name.
For core-kind parameters, the bits are left-shifted by 2 (firmware requirement). For addr-kind parameters, the value is written directly (no shift).
Definition at line 84 of file parameter_scratchpad.h.
Referenced by write(), and writeBytes().
writeBytes()
void test_utils::ParameterScratchpad::writeBytes (const std::string & name, const void * data, size_t len) inline
Write raw bytes (up to 4) by name, interpreted as a little-endian uint32.
For core-kind parameters, the bits are left-shifted by 2 (firmware requirement). For addr-kind parameters, the value is written raw (no shift).
Definition at line 75 of file parameter_scratchpad.h.
References writeBits().
The documentation for this class was generated from the following file:
runtime_lib/test_lib/parameter_scratchpad.h