MLIR-AIE: xilinx::aievec::MulElemOpConversion Class Reference
xilinx::aievec::MulElemOpConversion Class Reference
Classes
struct DecodedMulElemOp
Public Member Functions
MulElemOpConversion (const LLVMTypeConverter &typeConverter, Aie2Fp32Emulation aie2Fp32EmulationOption)
LogicalResult convertToEmulatedI32MulElem (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
LogicalResult convertToEmulatedFP32MulElem (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const
LogicalResult matchAndRewrite (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static DecodedMulElemOp decodeMulElemOp (OpAdaptor op)
Public Attributes
Aie2Fp32Emulation aie2Fp32EmulationOption
Detailed Description
Definition at line 903 of file AIEVecToLLVM.cpp.
Constructor & Destructor Documentation
MulElemOpConversion()
xilinx::aievec::MulElemOpConversion::MulElemOpConversion (const LLVMTypeConverter & typeConverter, Aie2Fp32Emulation aie2Fp32EmulationOption) inline
Definition at line 908 of file AIEVecToLLVM.cpp.
Member Function Documentation
convertToEmulatedFP32MulElem()
LogicalResult xilinx::aievec::MulElemOpConversion::convertToEmulatedFP32MulElem (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline
Definition at line 1134 of file AIEVecToLLVM.cpp.
References aie2Fp32EmulationOption.
Referenced by matchAndRewrite().
convertToEmulatedI32MulElem()
LogicalResult xilinx::aievec::MulElemOpConversion::convertToEmulatedI32MulElem (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline
Definition at line 1006 of file AIEVecToLLVM.cpp.
Referenced by matchAndRewrite().
decodeMulElemOp()
static DecodedMulElemOp xilinx::aievec::MulElemOpConversion::decodeMulElemOp (OpAdaptor op) inline static
Definition at line 931 of file AIEVecToLLVM.cpp.
References xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::BF16_BF16_FP32_16x1x2x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::FP32_FP32_FP32_16x1x1x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I16_I16_I32_32x1x1x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I32_I32_I64_32x1x2x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I8_I8_I32_32x1x2x1, and xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::UNSUPPORTED.
Referenced by matchAndRewrite().
matchAndRewrite()
LogicalResult xilinx::aievec::MulElemOpConversion::matchAndRewrite (aievec::MulElemOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 1284 of file AIEVecToLLVM.cpp.
References xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::BF16_BF16_FP32_16x1x2x1, convertToEmulatedFP32MulElem(), convertToEmulatedI32MulElem(), decodeMulElemOp(), xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::FP32_FP32_FP32_16x1x1x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I16_I16_I32_32x1x1x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I32_I32_I64_32x1x2x1, xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::I8_I8_I32_32x1x2x1, and xilinx::aievec::MulElemOpConversion::DecodedMulElemOp::UNSUPPORTED.
Member Data Documentation
aie2Fp32EmulationOption
Aie2Fp32Emulation xilinx::aievec::MulElemOpConversion::aie2Fp32EmulationOption
Definition at line 913 of file AIEVecToLLVM.cpp.
Referenced by convertToEmulatedFP32MulElem().
The documentation for this class was generated from the following file:
lib/Conversion/AIEVecToLLVM/AIEVecToLLVM.cpp