MLIR-AIE: xilinx::AIE::Pathfinder Class Reference
xilinx::AIE::Pathfinder Class Reference
#include "aie/Dialect/AIE/Transforms/AIEPathFinder.h"
Public Member Functions
Pathfinder ()=default
void initialize (int maxCol, int maxRow, const AIETargetModel &targetModel) override
void addFlow (TileID srcCoords, Port srcPort, TileID dstCoords, Port dstPort, bool isPacketFlow, bool isPriorityFlow) override
void sortFlows (const int maxCol, const int maxRow) override
bool addFixedConnection (SwitchboxOp switchboxOp) override
std::optional< std::map< PathEndPoint, SwitchSettings > > findPaths (int maxIterations) override
std::map< PathEndPoint, PathEndPoint > dijkstraShortestPaths (PathEndPoint src)
Public Member Functions inherited from xilinx::AIE::Router
Router ()=default
virtual ~Router ()=default
Detailed Description
Definition at line 199 of file AIEPathFinder.h.
Constructor & Destructor Documentation
Pathfinder()
xilinx::AIE::Pathfinder::Pathfinder () default
Member Function Documentation
addFixedConnection()
bool Pathfinder::addFixedConnection (SwitchboxOp switchboxOp) override virtual
Implements xilinx::AIE::Router.
Definition at line 366 of file AIEPathFinder.cpp.
References xilinx::AIE::AVAILABLE, xilinx::AIE::col, xilinx::AIE::coords, xilinx::AIE::INVALID, and xilinx::AIE::row.
addFlow()
void Pathfinder::addFlow (TileID srcCoords, Port srcPort, TileID dstCoords, Port dstPort, bool isPacketFlow, bool isPriorityFlow) override virtual
Implements xilinx::AIE::Router.
Definition at line 289 of file AIEPathFinder.cpp.
References xilinx::AIE::dst, xilinx::AIE::dstCoords, xilinx::AIE::dsts, xilinx::AIE::isPriorityFlow, xilinx::AIE::packetGroupId, xilinx::AIE::src, and xilinx::AIE::srcCoords.
dijkstraShortestPaths()
std::map< PathEndPoint, PathEndPoint > Pathfinder::dijkstraShortestPaths (PathEndPoint src)
Definition at line 394 of file AIEPathFinder.cpp.
References xilinx::AIE::AVAILABLE, xilinx::AIE::getConnectingBundle(), and xilinx::AIE::src.
Referenced by findPaths().
findPaths()
std::optional< std::map< PathEndPoint, SwitchSettings > > Pathfinder::findPaths (int maxIterations) override virtual
Implements xilinx::AIE::Router.
Definition at line 490 of file AIEPathFinder.cpp.
References xilinx::AIE::coords, dijkstraShortestPaths(), xilinx::AIE::dsts, xilinx::AIE::isPriority, MAX_CIRCUIT_STREAM_CAPACITY, MAX_PACKET_STREAM_CAPACITY, xilinx::AIE::packetGroupId, xilinx::AIE::port, and xilinx::AIE::src.
initialize()
void Pathfinder::initialize (int maxCol, int maxRow, const AIETargetModel & targetModel) override virtual
Implements xilinx::AIE::Router.
Definition at line 181 of file AIEPathFinder.cpp.
References xilinx::AIE::AVAILABLE, xilinx::AIE::channel, xilinx::AIE::col, xilinx::AIE::coords, xilinx::AIE::AIETargetModel::getNumDestShimMuxConnections(), xilinx::AIE::AIETargetModel::getNumDestSwitchboxConnections(), xilinx::AIE::AIETargetModel::getNumSourceShimMuxConnections(), xilinx::AIE::AIETargetModel::getNumSourceSwitchboxConnections(), xilinx::AIE::INVALID, xilinx::AIE::AIETargetModel::isLegalTileConnection(), xilinx::AIE::AIETargetModel::isShimNOCorPLTile(), and xilinx::AIE::row.
sortFlows()
void Pathfinder::sortFlows (const int maxCol, const int maxRow) override virtual
Implements xilinx::AIE::Router.
Definition at line 337 of file AIEPathFinder.cpp.
The documentation for this class was generated from the following files:
include/aie/Dialect/AIE/Transforms/AIEPathFinder.h
lib/Dialect/AIE/Transforms/AIEPathFinder.cpp