MLIR-AIE: cxxopts::ParseResult Class Reference
cxxopts::ParseResult Class Reference
#include "/home/runner/work/mlir-aie/mlir-aie/runtime_lib/test_lib/cxxopts.hpp"
Classes
class Iterator
Public Member Functions
ParseResult ()=default
ParseResult (const ParseResult &)=default
ParseResult (NameHashMap &&keys, ParsedHashMap &&values, std::vector< KeyValue > sequential, std::vector< KeyValue > default_opts, std::vector< std::string > &&unmatched_args)
ParseResult & operator= (ParseResult &&)=default
ParseResult & operator= (const ParseResult &)=default
Iterator begin () const
Iterator end () const
std::size_t count (const std::string &o) const
bool contains (const std::string &o) const
const OptionValue & operator[] (const std::string &option) const
const std::vector< KeyValue > & arguments () const
const std::vector< std::string > & unmatched () const
const std::vector< KeyValue > & defaults () const
const std::string arguments_string () const
Detailed Description
Definition at line 1218 of file cxxopts.hpp.
Constructor & Destructor Documentation
ParseResult() [1/3]
cxxopts::ParseResult::ParseResult () default
ParseResult() [2/3]
cxxopts::ParseResult::ParseResult (const ParseResult &) default
ParseResult() [3/3]
cxxopts::ParseResult::ParseResult (NameHashMap && keys, ParsedHashMap && values, std::vector< KeyValue > sequential, std::vector< KeyValue > default_opts, std::vector< std::string > && unmatched_args) inline
Definition at line 1286 of file cxxopts.hpp.
Member Function Documentation
arguments()
const std::vector< KeyValue > & cxxopts::ParseResult::arguments () const inline
Definition at line 1351 of file cxxopts.hpp.
arguments_string()
const std::string cxxopts::ParseResult::arguments_string () const inline
Definition at line 1357 of file cxxopts.hpp.
begin()
Iterator cxxopts::ParseResult::begin () const inline
Definition at line 1298 of file cxxopts.hpp.
contains()
bool cxxopts::ParseResult::contains (const std::string & o) const inline
Definition at line 1317 of file cxxopts.hpp.
References count().
count()
std::size_t cxxopts::ParseResult::count (const std::string & o) const inline
Definition at line 1302 of file cxxopts.hpp.
Referenced by test_utils::check_arg_file_exists(), contains(), and test_utils::parse_options().
defaults()
const std::vector< KeyValue > & cxxopts::ParseResult::defaults () const inline
Definition at line 1355 of file cxxopts.hpp.
end()
Iterator cxxopts::ParseResult::end () const inline
Definition at line 1300 of file cxxopts.hpp.
Referenced by cxxopts::ParseResult::Iterator::Iterator().
operator=() [1/2]
ParseResult & cxxopts::ParseResult::operator= (const ParseResult &) default
operator=() [2/2]
ParseResult & cxxopts::ParseResult::operator= (ParseResult &&) default
operator[]()
const OptionValue & cxxopts::ParseResult::operator[] (const std::string & option) const inline
Definition at line 1321 of file cxxopts.hpp.
unmatched()
const std::vector< std::string > & cxxopts::ParseResult::unmatched () const inline
Definition at line 1353 of file cxxopts.hpp.
The documentation for this class was generated from the following file:
runtime_lib/test_lib/cxxopts.hpp