MLIR-AIE: xilinx::aievec::SelectOpConversion Class Reference
xilinx::aievec::SelectOpConversion Class Reference
Public Member Functions
LogicalResult matchAndRewrite (aievec::aie1::SelectOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static std::string getIntrinsicName (aievec::aie1::SelectOp op)
Detailed Description
Definition at line 1430 of file AIEVecToLLVM.cpp.
Member Function Documentation
getIntrinsicName()
static std::string xilinx::aievec::SelectOpConversion::getIntrinsicName (aievec::aie1::SelectOp op) inline static
Definition at line 1435 of file AIEVecToLLVM.cpp.
References xilinx::aievec::getVectorTypeString().
matchAndRewrite()
LogicalResult xilinx::aievec::SelectOpConversion::matchAndRewrite (aievec::aie1::SelectOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 1443 of file AIEVecToLLVM.cpp.
References xilinx::aievec::encodeConf(), xilinx::aievec::encodeSquare(), xilinx::aievec::BufferParams::offsets, xilinx::aievec::BufferParams::offsets_hi, xilinx::aievec::BufferParams::square, and xilinx::aievec::BufferParams::start.
The documentation for this class was generated from the following file:
lib/Conversion/AIEVecToLLVM/AIEVecToLLVM.cpp