MLIR-AIE: xilinx::AIE::SequentialPlacer Class Reference
xilinx::AIE::SequentialPlacer Class Reference
#include "aie/Dialect/AIE/Transforms/AIEPlacer.h"
Public Member Functions
SequentialPlacer (std::optional< int > coresPerCol=std::nullopt, bool mergeLogicalTiles=true)
void initialize (const AIETargetModel &targetModel) override
mlir::LogicalResult place (DeviceOp device) override
llvm::StringRef getName () const override
Public Member Functions inherited from xilinx::AIE::Placer
Placer ()=default
virtual ~Placer ()=default
std::optional< TileID > getPlacement (mlir::Operation *logicalTile) const
llvm::SmallVector< AllocateInfo > & getAllocates ()
Additional Inherited Members
Public Types inherited from xilinx::AIE::Placer
using AllocateInfo = std::pair< mlir::Operation *, TileID >
Static Public Member Functions inherited from xilinx::AIE::Placer
static CollectedOps collectOperations (DeviceOp device)
static bool satisfiesConstraints (mlir::Operation *tile, TileID pos)
static Adjacency buildCascadeAdjacency (llvm::ArrayRef< CascadeFlowOp > cascadeFlows)
static Adjacency buildComputePeerAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos)
static Adjacency buildObjectFifoAdjacency (llvm::ArrayRef< ObjectFifoCreateOp > objectFifos)
static Adjacency buildFlowAdjacency (llvm::ArrayRef< FlowOp > flows, llvm::ArrayRef< PacketFlowOp > pktFlows)
Protected Attributes inherited from xilinx::AIE::Placer
PlacementResult result
llvm::SmallVector< AllocateInfo > allocates
const AIETargetModel * targetModel = nullptr
TileAvailability availability
Detailed Description
Definition at line 217 of file AIEPlacer.h.
Constructor & Destructor Documentation
SequentialPlacer()
xilinx::AIE::SequentialPlacer::SequentialPlacer (std::optional< int > coresPerCol = std::nullopt, bool mergeLogicalTiles = true) inline
Definition at line 219 of file AIEPlacer.h.
Member Function Documentation
getName()
llvm::StringRef xilinx::AIE::SequentialPlacer::getName () const inline override virtual
Implements xilinx::AIE::Placer.
Definition at line 227 of file AIEPlacer.h.
initialize()
void SequentialPlacer::initialize (const AIETargetModel & targetModel) override virtual
Reimplemented from xilinx::AIE::Placer.
Definition at line 95 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::availability, xilinx::AIE::col, xilinx::AIE::AIETargetModel::columns(), xilinx::AIE::TileAvailability::compTiles, xilinx::AIE::TileAvailability::compTilesSet, xilinx::AIE::Placer::initialize(), xilinx::AIE::TileAvailability::nonCompTiles, and xilinx::AIE::Placer::targetModel.
place()
LogicalResult SequentialPlacer::place (DeviceOp device) override virtual
Implements xilinx::AIE::Placer.
Definition at line 155 of file AIEPlacer.cpp.
References xilinx::AIE::Placer::buildCascadeAdjacency(), xilinx::AIE::Placer::buildComputePeerAdjacency(), xilinx::AIE::Placer::collectOperations(), DEBUG_TYPE, xilinx::AIE::AIETargetModel::isEast(), xilinx::AIE::AIETargetModel::isLegalMemAffinity(), xilinx::AIE::AIETargetModel::isSouth(), and xilinx::AIE::Placer::targetModel.
The documentation for this class was generated from the following files:
include/aie/Dialect/AIE/Transforms/AIEPlacer.h
lib/Dialect/AIE/Transforms/AIEPlacer.cpp