MLIR-AIE: xilinx::AIEX::TokenAnalysis Class Reference
xilinx::AIEX::TokenAnalysis Class Reference
#include "aie/Dialect/AIEX/AIETokenAnalysis.h"
Public Member Functions
TokenAnalysis (AIE::DeviceOp &d)
void runAnalysis ()
auto getTokenSymbols () const
auto getTokenChains () const
auto getTokenPairs () const
auto getTiles () const
mlir::Operation * getTokenUserOp (mlir::Operation *Op)
mlir::Operation * getShareableTileOp (mlir::Operation *Op1, mlir::Operation *Op2)
xilinx::AIE::TileID getCoord (mlir::Operation *Op)
void print (llvm::raw_ostream &os)
Detailed Description
Definition at line 30 of file AIETokenAnalysis.h.
Constructor & Destructor Documentation
TokenAnalysis()
xilinx::AIEX::TokenAnalysis::TokenAnalysis (AIE::DeviceOp & d) inline
Definition at line 44 of file AIETokenAnalysis.h.
Member Function Documentation
getCoord()
TileID xilinx::AIEX::TokenAnalysis::getCoord (mlir::Operation * Op)
Definition at line 159 of file AIETokenAnalysis.cpp.
Referenced by AIECreateLocksPass::runOnOperation().
getShareableTileOp()
Operation * xilinx::AIEX::TokenAnalysis::getShareableTileOp (mlir::Operation * Op1, mlir::Operation * Op2)
Definition at line 177 of file AIETokenAnalysis.cpp.
References xilinx::AIE::getTargetModel().
Referenced by AIECreateLocksPass::runOnOperation().
getTiles()
auto xilinx::AIEX::TokenAnalysis::getTiles () const inline
Definition at line 54 of file AIETokenAnalysis.h.
Referenced by AIECreateLocksPass::runOnOperation().
getTokenChains()
auto xilinx::AIEX::TokenAnalysis::getTokenChains () const inline
Definition at line 50 of file AIETokenAnalysis.h.
Referenced by AIECreateLocksPass::runOnOperation().
getTokenPairs()
auto xilinx::AIEX::TokenAnalysis::getTokenPairs () const inline
Definition at line 52 of file AIETokenAnalysis.h.
Referenced by AIECreateLocksPass::runOnOperation().
getTokenSymbols()
auto xilinx::AIEX::TokenAnalysis::getTokenSymbols () const inline
Definition at line 48 of file AIETokenAnalysis.h.
getTokenUserOp()
Operation * xilinx::AIEX::TokenAnalysis::getTokenUserOp (mlir::Operation * Op)
Definition at line 146 of file AIETokenAnalysis.cpp.
Referenced by AIECreateLocksPass::runOnOperation().
print()
void xilinx::AIEX::TokenAnalysis::print (llvm::raw_ostream & os)
Definition at line 224 of file AIETokenAnalysis.cpp.
References xilinx::AIE::os.
Referenced by AIECreateLocksPass::runOnOperation().
runAnalysis()
void xilinx::AIEX::TokenAnalysis::runAnalysis ()
Definition at line 36 of file AIETokenAnalysis.cpp.
Referenced by AIECreateLocksPass::runOnOperation().
The documentation for this class was generated from the following files:
include/aie/Dialect/AIEX/AIETokenAnalysis.h
lib/Dialect/AIEX/Utils/AIETokenAnalysis.cpp