MLIR-AIE: xilinx::aievec::AddElemOpAIE2pConversion Class Reference
xilinx::aievec::AddElemOpAIE2pConversion Class Reference
Classes
struct DecodedAddElemOp
Public Member Functions
LogicalResult matchAndRewrite (aievec::AddElemOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static DecodedAddElemOp decodeAddElemOp (OpAdaptor op)
Detailed Description
Definition at line 445 of file AIEVecToLLVM.cpp.
Member Function Documentation
decodeAddElemOp()
static DecodedAddElemOp xilinx::aievec::AddElemOpAIE2pConversion::decodeAddElemOp (OpAdaptor op) inline static
Definition at line 460 of file AIEVecToLLVM.cpp.
References xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::FP32_FP32_FP32_16x1x1x1, xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::FP32_FP32_FP32_32x1x1x1, xilinx::aievec::getVectorLaneSize(), and xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::UNSUPPORTED.
Referenced by matchAndRewrite().
matchAndRewrite()
LogicalResult xilinx::aievec::AddElemOpAIE2pConversion::matchAndRewrite (aievec::AddElemOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 485 of file AIEVecToLLVM.cpp.
References decodeAddElemOp(), xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::FP32_FP32_FP32_16x1x1x1, xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::FP32_FP32_FP32_32x1x1x1, and xilinx::aievec::AddElemOpAIE2pConversion::DecodedAddElemOp::UNSUPPORTED.
The documentation for this class was generated from the following file:
lib/Conversion/AIEVecToLLVM/AIEVecToLLVM.cpp