MLIR-AIE: lib/Dialect/AIE/Transforms/d_ary_heap.h File Reference
d_ary_heap.h File Reference
#include <vector>
#include <cstddef>
#include <algorithm>
#include <utility>
Classes
class d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >
Functions
template<class T , class K , class V >
void put (T &pa, K k, const V &val)
template<class K , class V >
const V & get (const std::map< K, V > &pa, K k)
Function Documentation
get()
template<class K , class V > const V& get (const std::map< K, V > & pa, K k) inline
Definition at line 69 of file d_ary_heap.h.
Referenced by xilinx::aievec::buildFMAOpSplatAttrForElemTy(), d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::contains(), xilinx::aievec::MulElemOpConversion::convertToEmulatedFP32MulElem(), xilinx::aievec::MulElemOpConversion::convertToEmulatedI32MulElem(), xilinx::xllvm::createExternalLLVMIntrinsicCall(), AIEObjectFifoStatefulTransformPass::createObjectFifoAllocationInfo(), AIEObjectFifoRegisterProcessPass::createPattern(), xilinx::aievec::createVectorType(), AIEObjectFifoStatefulTransformPass::dynamicGlobalObjectFifos(), AIEGenerateColumnControlOverlayPass::generatePacketFlowsForControl(), xilinx::AIE::AIEObjectFifoType::get(), xilinx::AIE::AIEObjectFifoSubviewType::get(), xilinx::aievec::getFlattenedVectorType(), ExtractTransposeFromContractionOp::getTransposedVectorType(), xilinx::aievec::getVectorOpDestType(), xilinx::aievec::FMAOpConversion::matchAndRewrite(), xilinx::aievec::MulOpConversion::matchAndRewrite(), xilinx::aievec::SelectOpConversion::matchAndRewrite(), xilinx::aievec::BroadcastScalarOpConversion::matchAndRewrite(), xilinx::aievec::ConcatOpConversion::matchAndRewrite(), xilinx::aievec::ExtOpConversion::matchAndRewrite(), xilinx::aievec::MaxOpConversion::matchAndRewrite(), xilinx::aievec::MinOpConversion::matchAndRewrite(), xilinx::aievec::MulElemOpConversion::matchAndRewrite(), xilinx::aievec::PackOpConversion::matchAndRewrite(), xilinx::aievec::ShiftOpConversion::matchAndRewrite(), xilinx::aievec::SRSOpConversion::matchAndRewrite(), xilinx::aievec::UPDOpConversion::matchAndRewrite(), ExpandUPDToUPDAndExtPattern::matchAndRewrite(), xilinx::aievec::UPSOpConversion::matchAndRewrite(), FoldMulAddChainToConvOpPattern::matchAndRewrite(), LowerVectorSelectOpToAIEVecSelOp::matchAndRewrite(), AIECoreToStandardFunc::matchAndRewrite(), AIEGetCascadeToStdLowering::matchAndRewrite(), ComputeCeilOpPattern::matchAndRewrite(), ComputeErfOpPattern::matchAndRewrite(), ComputeFloorOpPattern::matchAndRewrite(), ComputeRsqrtOpPattern::matchAndRewrite(), ComputeSqrtOpPattern::matchAndRewrite(), ComputeTanhOpByLUTPattern::matchAndRewrite(), HoistCastOpToDataSourcePattern::matchAndRewrite(), AIEPutCascadeToStdLowering::matchAndRewrite(), AIEPutStreamToStdLowering::matchAndRewrite(), ComputeAbsOpPattern< SrcOpTy >::matchAndRewrite(), LowerVectorCmpOpToAIEVecCmpOp< SrcOpTy, CmpTy >::matchAndRewrite(), AIEUseLockToStdLowering::matchAndRewrite(), ConvertVectorFMAOpToAIEVecFMAElemOpPattern::matchAndRewrite(), SplitUnalignedTransferReadPattern::matchAndRewrite(), ConvertSplatTransferReadToBroadcastPattern::matchAndRewrite(), FlattenMultDimTransferReadPattern::matchAndRewrite(), FlattenMultDimTransferWritePattern::matchAndRewrite(), LowerVectorTransposeOpToAIEVecShuffleOpPattern::matchAndRewrite(), memRefToDefaultAddressSpace(), orConsecutiveWritesOnSameAddr(), d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::push_or_update(), LowerVectorContractionOpToAIEVecMatMulPattern::reshapeLeadingUnitDims(), AIECanonicalizeDevicePass::runOnOperation(), AIEAssignTileCtrlIDsPass::runOnOperation(), AIEObjectFifoStatefulTransformPass::runOnOperation(), ReorderOperationsPass::runOnOperation(), AIECreateCoresPass::runOnOperation(), AIECtrlPacketInferTilesPass::runOnOperation(), AIECtrlPacketToDmaPass::runOnOperation(), xilinx::AIE::AIEPathfinderPass::runOnPacketFlow(), and d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::update().
put()
template<class T , class K , class V > void put (T & pa, K k, const V & val) inline
Definition at line 66 of file d_ary_heap.h.
Referenced by d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::pop(), d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::push(), and d_ary_heap_indirect< Value, Arity, IndexInHeapPropertyMap, DistanceMap, Compare, Container >::push_or_update().