MLIR-AIE: cxxopts::values::parser_tool Namespace Reference
cxxopts::values::parser_tool Namespace Reference
Classes
struct ArguDesc
struct IntegerDesc
Functions
IntegerDesc SplitInteger (const std::string &text)
bool IsTrueText (const std::string &text)
bool IsFalseText (const std::string &text)
OptionNames split_option_names (const std::string &text)
ArguDesc ParseArgument (const char *arg, bool &matched)
Function Documentation
IsFalseText()
bool cxxopts::values::parser_tool::IsFalseText (const std::string & text) inline
Definition at line 644 of file cxxopts.hpp.
Referenced by cxxopts::values::parse_value().
IsTrueText()
bool cxxopts::values::parser_tool::IsTrueText (const std::string & text) inline
Definition at line 637 of file cxxopts.hpp.
Referenced by cxxopts::values::parse_value().
ParseArgument()
ArguDesc cxxopts::values::parser_tool::ParseArgument (const char * arg, bool & matched) inline
Definition at line 674 of file cxxopts.hpp.
References cxxopts::values::parser_tool::ArguDesc::arg_name, cxxopts::values::parser_tool::ArguDesc::grouping, cxxopts::values::parser_tool::ArguDesc::set_value, and cxxopts::values::parser_tool::ArguDesc::value.
Referenced by cxxopts::OptionParser::parse().
split_option_names()
OptionNames cxxopts::values::parser_tool::split_option_names (const std::string & text) inline
Definition at line 654 of file cxxopts.hpp.
Referenced by cxxopts::OptionAdder::operator()().
SplitInteger()
IntegerDesc cxxopts::values::parser_tool::SplitInteger (const std::string & text) inline
Definition at line 613 of file cxxopts.hpp.
References cxxopts::values::parser_tool::IntegerDesc::base, cxxopts::values::parser_tool::IntegerDesc::negative, and cxxopts::values::parser_tool::IntegerDesc::value.
Referenced by cxxopts::values::integer_parser().