MLIR-AIE: xilinx::aievec Namespace Reference
xilinx::aievec Namespace Reference
Namespaces
namespace aie1
Classes
class AddElemOpAIE2Conversion
class AddElemOpAIE2pConversion
class AddOpConversion
struct AIEVecConvAnalysis
class AIEVecType
class BroadcastOpConversion
class BroadcastScalarOpAIE2pConversion
class BroadcastScalarOpConversion
struct BufferParams
struct CanonicalizeVectorForAIEVecOptions
Options for the "canonicalize-vector-for-aievec" pipeline.
class ConcatOpAIE2pConversion
class ConcatOpConversion
struct ConvertAIEVecToLLVMPass
struct ConvertVectorToAIEVecOptions
Options for the "convert-vector-to-aievec" pipeline.
class ExpOpAIE2pConversion
class ExtOpConversion
class ExtractElemOpAIE2pConversion
class ExtractElemOpConversion
class FMAElemOpConversion
class FMAOpConversion
class FoldAIECastOps
class IntervalReuse
struct LowerVectorToAIEVecOptions
Options for the "lower-vector-to-aievec" pipeline.
class MatMulOpAIE2pConversion
class MatMulOpConversion
class MaxOpAIE2pConversion
class MaxOpConversion
class MinOpAIE2pConversion
class MinOpConversion
class MulElemOpAIE2pConversion
class MulElemOpConversion
class MulOpConversion
struct OptimizeAIEVecOptions
Options for the "optimize-aievec" pipeline.
class PackOpConversion
class SelectOpConversion
class ShiftOpAIE2pConversion
class ShiftOpConversion
class ShuffleOpConversion
class SRSOpAIE2Conversion
class SRSOpAIE2pConversion
class SubElemOpAIE2Conversion
class SubElemOpAIE2pConversion
class SubOpConversion
class UnpackOpConversion
class UPDOpConversion
class UPSOpAIE2Conversion
class UPSOpAIE2pConversion
Enumerations
enum class AIEArch { AIE2 , AIE2p }
Functions
void populateAIEVecToLLVMConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns, Aie2Fp32Emulation aie2Fp32EmulationOption, llvm::StringRef aieTarget)
void populateAIEVecToLLVMCommonConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns)
void populateAIEVecToLLVMAIE2ConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns)
void populateAIEVecToLLVMAIE2pConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns)
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createConvertAIEVecToLLVMPass ()
char getHexValue (int val)
bool isPowerOfTwo (int32_t n)
mlir::VectorType createVectorType (unsigned lanes, mlir::Type elementType)
int32_t getElementSizeInBits (mlir::VectorType type)
unsigned getVectorLaneSize (mlir::VectorType type)
int32_t getVectorSizeInBits (mlir::VectorType type)
bool isAIEOp (mlir::Operation *op)
mlir::VectorType getVectorOpDestType (mlir::VectorType type, bool AIE2)
mlir::AffineExpr flattenedStridedExpr (llvm::ArrayRef< int64_t > sizes, llvm::ArrayRef< mlir::AffineExpr > exprs, mlir::MLIRContext *context)
mlir::AffineExpr constructLinearizedAffineExprForUPDOp (UPDOp updOp)
std::pair< mlir::AffineExpr, int32_t > extractBaseAndOffset (mlir::AffineExpr expr)
bool isAssumingNoImplicitBroadcastOfDynamicSizes (mlir::Block *block)
bool isAssumingNoImplicitBroadcastOfDynamicSizes (mlir::OpBuilder &builder)
std::unique_ptr< mlir::Pass > createAIEVecConvolutionAnalysisPass ()
void registerAIEVecToCppTranslation ()
void buildConvertVectorToAIEVec (mlir::OpPassManager &pm, const ConvertVectorToAIEVecOptions &options)
Adds the "convert-vector-to-aievec" pipeline to the OpPassManager.
void buildCanonicalizeVectorForAIEVec (mlir::OpPassManager &pm, const CanonicalizeVectorForAIEVecOptions &options)
void buildLowerVectorToAIEVec (mlir::OpPassManager &pm, const LowerVectorToAIEVecOptions &options)
void buildOptimizeAIEVec (mlir::OpPassManager &pm, const OptimizeAIEVecOptions &options)
void registerAIEVecPipelines ()
Register all pipelines for the AIE Vector dialect.
std::unique_ptr<::mlir::Pass > createCopyRemovalPass ()
Create a pass that removes unnecessary Copy operations.
std::unique_ptr<::mlir::Pass > createDynamicSizeNoImplicitBroadcastPass ()
void buildDynamicSizeNoImplicitBroadcastPass (mlir::OpPassManager &pm)
std::unique_ptr<::mlir::Pass > createSplitVectorLoadUpsChainsPass ()
Create a pass that splits vector.load + aievec.ups chains to reduce shuffle operations for AIE2p targets.
void registerTransformDialectExtension (mlir::DialectRegistry &registry)
std::unique_ptr< mlir::Pass > createAIEVectorizePass ()
template<typename TransferReadLikeOp , typename = std::enable_if_t< std::is_same_v<TransferReadLikeOp, mlir::vector::TransferReadOp> || std::is_same_v<TransferReadLikeOp, mlir::vector::TransferReadOp::Adaptor>>>
std::optional< int64_t > getTransferReadAlignmentOffset (TransferReadLikeOp readOp, mlir::VectorType vType, int64_t alignment)
mlir::VectorType getFlattenedVectorType (mlir::VectorType vecTy)
mlir::LogicalResult translateAIEVecToCpp (mlir::Operation *op, bool aie2, mlir::raw_ostream &os)
Translates the AIE vector dialect MLIR to C++ code.
std::string getVectorTypeString (VectorType type, bool abbrev=false, bool acc=false)
std::string getMulOrFMAIntrinsicName (Operation *op)
uint32_t encodeSquare (uint32_t square)
void encodeConf (uint32_t conf[2], const BufferParams &x, const BufferParams &z, bool sub)
void populateAIEVecToLLVMAIE2ConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns, Aie2Fp32Emulation aie2Fp32EmulationOption)
void populateAIEVecToLLVMConversionPatterns (mlir::LLVMTypeConverter &converter, mlir::RewritePatternSet &patterns, Aie2Fp32Emulation aie2Fp32EmulationOption, StringRef aieTarget)
SmallVector< NamedAttribute > buildFMAOpSplatAttrForElemTy (aievec::aie1::FMAOp fmaOp, int64_t bcastPos, int64_t step=1)
void configureAIEVecConvOpTransformationLegalizations (ConversionTarget &target, AnalysisManager &am, TargetBackend backend)
void populateAIEVecConvOpTransformationPatterns (RewritePatternSet &patterns, AnalysisManager &am, unsigned shiftParam, TargetBackend backend)
void configureAIEVecConvOpTransformationLegalizations (mlir::ConversionTarget &target, mlir::AnalysisManager &am, TargetBackend backend)
void populateAIEVecConvOpTransformationPatterns (mlir::RewritePatternSet &patterns, mlir::AnalysisManager &am, unsigned shiftParam, TargetBackend backend)
template<typename TransferReadLikeOp , typename >
std::optional< int64_t > getTransferReadAlignmentOffset (TransferReadLikeOp readOp, VectorType vType, int64_t alignment)
template std::optional< int64_t > getTransferReadAlignmentOffset (vector::TransferReadOp readOp, VectorType vType, int64_t alignment)
template std::optional< int64_t > getTransferReadAlignmentOffset (vector::TransferReadOp::Adaptor readOp, VectorType vType, int64_t alignment)
VectorType getFlattenedVectorType (VectorType vecTy)
Enumeration Type Documentation
AIEArch
enum class xilinx::aievec::AIEArch strong
Enumerator
AIE2
AIE2p
Definition at line 1322 of file AIEVecToLLVM.cpp.
Function Documentation
buildCanonicalizeVectorForAIEVec()
void xilinx::aievec::buildCanonicalizeVectorForAIEVec (mlir::OpPassManager & pm, const CanonicalizeVectorForAIEVecOptions & options)
Referenced by registerAIEVecPipelines().
buildConvertVectorToAIEVec()
void xilinx::aievec::buildConvertVectorToAIEVec (mlir::OpPassManager & pm, const ConvertVectorToAIEVecOptions & options)
Adds the "convert-vector-to-aievec" pipeline to the OpPassManager.
This pipeline takes Vector code, transforms it to make it compatible with the selected AIE target, lowers it to AIEVec dialect, and performs some optimizations based on the target AIE architecture.
Referenced by registerAIEVecPipelines().
buildDynamicSizeNoImplicitBroadcastPass()
void xilinx::aievec::buildDynamicSizeNoImplicitBroadcastPass (mlir::OpPassManager & pm)
Referenced by registerAIEVecPipelines().
buildFMAOpSplatAttrForElemTy()
SmallVector< NamedAttribute > xilinx::aievec::buildFMAOpSplatAttrForElemTy (aievec::aie1::FMAOp fmaOp, int64_t bcastPos, int64_t step = 1)
Definition at line 280 of file VectorToAIEVecConversions.cpp.
Referenced by MergeSingleColumnI16FMAOpPattern::matchAndRewrite(), and FoldSplatToFMAOp::matchAndRewrite().
buildLowerVectorToAIEVec()
void xilinx::aievec::buildLowerVectorToAIEVec (mlir::OpPassManager & pm, const LowerVectorToAIEVecOptions & options)
Referenced by registerAIEVecPipelines().
buildOptimizeAIEVec()
void xilinx::aievec::buildOptimizeAIEVec (mlir::OpPassManager & pm, const OptimizeAIEVecOptions & options)
Referenced by registerAIEVecPipelines().
configureAIEVecConvOpTransformationLegalizations() [1/2]
void xilinx::aievec::configureAIEVecConvOpTransformationLegalizations (ConversionTarget & target, AnalysisManager & am, TargetBackend backend)
Definition at line 518 of file FoldMulAddChainToConvOp.cpp.
References LongestConvMACChainAnalysis::am, and LongestConvMACChainAnalysis::canChainBeReplacedWithConvOps().
Referenced by AIEVecConvOpTransformationPass::runOnOperation().
configureAIEVecConvOpTransformationLegalizations() [2/2]
void xilinx::aievec::configureAIEVecConvOpTransformationLegalizations (mlir::ConversionTarget & target, mlir::AnalysisManager & am, TargetBackend backend)
constructLinearizedAffineExprForUPDOp()
mlir::AffineExpr xilinx::aievec::constructLinearizedAffineExprForUPDOp (UPDOp updOp) inline
Definition at line 151 of file AIEVecUtils.h.
References flattenedStridedExpr().
createAIEVecConvolutionAnalysisPass()
std::unique_ptr< Pass > xilinx::aievec::createAIEVecConvolutionAnalysisPass ()
Definition at line 612 of file FoldMulAddChainToConvOp.cpp.
createAIEVectorizePass()
std::unique_ptr< Pass > xilinx::aievec::createAIEVectorizePass ()
Definition at line 3063 of file AIEVectorize.cpp.
createConvertAIEVecToLLVMPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > xilinx::aievec::createConvertAIEVecToLLVMPass ()
Definition at line 4525 of file AIEVecToLLVM.cpp.
References createConvertAIEVecToLLVMPass().
Referenced by createConvertAIEVecToLLVMPass().
createCopyRemovalPass()
std::unique_ptr<::mlir::Pass > xilinx::aievec::createCopyRemovalPass ()
Create a pass that removes unnecessary Copy operations.
Definition at line 244 of file CopyRemoval.cpp.
createDynamicSizeNoImplicitBroadcastPass()
std::unique_ptr<::mlir::Pass > xilinx::aievec::createDynamicSizeNoImplicitBroadcastPass ()
Definition at line 121 of file DynamicSizeNoImplicitBroadcast.cpp.
createSplitVectorLoadUpsChainsPass()
std::unique_ptr<::mlir::Pass > xilinx::aievec::createSplitVectorLoadUpsChainsPass ()
Create a pass that splits vector.load + aievec.ups chains to reduce shuffle operations for AIE2p targets.
Definition at line 337 of file SplitVectorLoadUpsChains.cpp.
createVectorType()
mlir::VectorType xilinx::aievec::createVectorType (unsigned lanes, mlir::Type elementType) inline
Definition at line 42 of file AIEVecUtils.h.
Referenced by ConvertMulFToAIEVecMulElemOpPattern::matchAndRewrite(), ConvertMulIToAIEVecMulElemOpPattern::matchAndRewrite(), ComputeSignedIntRightShiftOpPattern::matchAndRewrite(), FoldVectorExtractAndSplatToAIEBroadcast::matchAndRewrite(), ConvertSplatToAIEBroadcast::matchAndRewrite(), ConvertSplatToAIEBroadcastAIE2p::matchAndRewrite(), LowerVectorReductionAddIntOp::matchAndRewrite(), and LowerVectorReductionAddBfloat16Op::matchAndRewrite().
encodeConf()
void xilinx::aievec::encodeConf (uint32_t conf[2], const BufferParams & x, const BufferParams & z, bool sub)
Definition at line 221 of file AIEVecToLLVM.cpp.
References encodeSquare(), xilinx::aievec::BufferParams::square, and xilinx::aievec::BufferParams::step.
Referenced by xilinx::aievec::FMAOpConversion::matchAndRewrite(), xilinx::aievec::MulOpConversion::matchAndRewrite(), and xilinx::aievec::SelectOpConversion::matchAndRewrite().
encodeSquare()
uint32_t xilinx::aievec::encodeSquare (uint32_t square)
Definition at line 210 of file AIEVecToLLVM.cpp.
Referenced by encodeConf(), and xilinx::aievec::SelectOpConversion::matchAndRewrite().
extractBaseAndOffset()
std::pair< mlir::AffineExpr, int32_t > xilinx::aievec::extractBaseAndOffset (mlir::AffineExpr expr) inline
Definition at line 206 of file AIEVecUtils.h.
flattenedStridedExpr()
mlir::AffineExpr xilinx::aievec::flattenedStridedExpr (llvm::ArrayRef< int64_t > sizes, llvm::ArrayRef< mlir::AffineExpr > exprs, mlir::MLIRContext * context) inline
Definition at line 111 of file AIEVecUtils.h.
Referenced by constructLinearizedAffineExprForUPDOp().
getElementSizeInBits()
int32_t xilinx::aievec::getElementSizeInBits (mlir::VectorType type) inline
Definition at line 49 of file AIEVecUtils.h.
Referenced by computeStartInAIEVec(), LongestConvMACChainAnalysis::getConvMacFromMulOp(), getVectorSizeInBits(), FoldMulAddChainToConvOpPattern::matchAndRewrite(), LowerVectorExtractStridedSliceOpAIEv1Pattern::matchAndRewrite(), LowerVectorExtractStridedSliceOpAIE2Pattern::matchAndRewrite(), and SplitUnalignedTransferReadPattern::matchAndRewrite().
getFlattenedVectorType() [1/2]
mlir::VectorType xilinx::aievec::getFlattenedVectorType (mlir::VectorType vecTy)
Referenced by xilinx::aievec::FMAElemOpConversion::matchAndRewrite(), xilinx::aievec::UPSOpAIE2Conversion::matchAndRewrite(), xilinx::aievec::UPSOpAIE2pConversion::matchAndRewrite(), ConvertSplatToAIEBroadcast::matchAndRewrite(), and ConvertSplatToAIEBroadcastAIE2p::matchAndRewrite().
getFlattenedVectorType() [2/2]
VectorType xilinx::aievec::getFlattenedVectorType (VectorType vecTy)
Definition at line 146 of file Utils.cpp.
getHexValue()
char xilinx::aievec::getHexValue (int val) inline
Definition at line 31 of file AIEVecUtils.h.
getMulOrFMAIntrinsicName()
std::string xilinx::aievec::getMulOrFMAIntrinsicName (Operation * op)
Definition at line 182 of file AIEVecToLLVM.cpp.
References getVectorLaneSize(), and getVectorTypeString().
Referenced by xilinx::aievec::FMAOpConversion::matchAndRewrite(), and xilinx::aievec::MulOpConversion::matchAndRewrite().
getTransferReadAlignmentOffset() [1/4]
template<typename TransferReadLikeOp , typename = std::enable_if_t< std::is_same_v<TransferReadLikeOp, mlir::vector::TransferReadOp> || std::is_same_v<TransferReadLikeOp, mlir::vector::TransferReadOp::Adaptor>>> std::optional< int64_t > xilinx::aievec::getTransferReadAlignmentOffset (TransferReadLikeOp readOp, mlir::VectorType vType, int64_t alignment)
Referenced by LowerVectorTransferReadToAIEUPD::matchAndRewrite(), and SplitUnalignedTransferReadPattern::matchAndRewrite().
getTransferReadAlignmentOffset() [2/4]
template<typename TransferReadLikeOp , typename > std::optional< int64_t > xilinx::aievec::getTransferReadAlignmentOffset (TransferReadLikeOp readOp, VectorType vType, int64_t alignment)
Definition at line 120 of file Utils.cpp.
getTransferReadAlignmentOffset() [3/4]
template std::optional< int64_t > xilinx::aievec::getTransferReadAlignmentOffset (vector::TransferReadOp readOp, VectorType vType, int64_t alignment)
getTransferReadAlignmentOffset() [4/4]
template std::optional< int64_t > xilinx::aievec::getTransferReadAlignmentOffset (vector::TransferReadOp::Adaptor readOp, VectorType vType, int64_t alignment)
getVectorLaneSize()
unsigned xilinx::aievec::getVectorLaneSize (mlir::VectorType type) inline
Definition at line 55 of file AIEVecUtils.h.
Referenced by xilinx::aievec::MulElemOpAIE2pConversion::decodeMulElemOp(), getMulOrFMAIntrinsicName(), getVectorSizeInBits(), getVectorTypeString(), xilinx::aievec::BroadcastScalarOpConversion::matchAndRewrite(), xilinx::aievec::BroadcastScalarOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::ConcatOpConversion::matchAndRewrite(), xilinx::aievec::ConcatOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::ExpOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::ExtractElemOpConversion::matchAndRewrite(), xilinx::aievec::ExtOpConversion::matchAndRewrite(), xilinx::aievec::MaxOpConversion::matchAndRewrite(), xilinx::aievec::MaxOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::MinOpConversion::matchAndRewrite(), xilinx::aievec::MinOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::ShiftOpConversion::matchAndRewrite(), xilinx::aievec::ShiftOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::SRSOpAIE2Conversion::matchAndRewrite(), xilinx::aievec::SRSOpAIE2pConversion::matchAndRewrite(), xilinx::aievec::UPDOpConversion::matchAndRewrite(), xilinx::aievec::UPSOpAIE2Conversion::matchAndRewrite(), xilinx::aievec::UPSOpAIE2pConversion::matchAndRewrite(), ConvertMulAddToAIEVecFMAElemOpPattern::matchAndRewrite(), ComputeSigmoidOpPattern::matchAndRewrite(), ConvertMulFToAIEVecMulElemOpPattern::matchAndRewrite(), ConvertMulIToAIEVecMulElemOpPattern::matchAndRewrite(), ComputeNegOpPattern::matchAndRewrite(), LowerVectorSelectOpToAIEVecSelOp::matchAndRewrite(), ComputeSignedIntRightShiftOpPattern::matchAndRewrite(), ComputeBxorAndBnegOpPattern::matchAndRewrite(), ComputeCeilOpPattern::matchAndRewrite(), ComputeErfOpPattern::matchAndRewrite(), ComputeFloorOpPattern::matchAndRewrite(), ComputeRsqrtOpPattern::matchAndRewrite(), ComputeSqrtOpPattern::matchAndRewrite(), ComputeTanhOpByLUTPattern::matchAndRewrite(), ComputeAbsOpPattern< SrcOpTy >::matchAndRewrite(), LowerVectorAddOrSubOpToAIEVecAddElemOrSubElemOp< SrcOpTy, DstOpTy >::matchAndRewrite(), LowerVectorMinMaxOpToAIEVecMinMaxOp< SrcOpTy, DstOpTy >::matchAndRewrite(), LowerVectorCmpOpToAIEVecCmpOp< SrcOpTy, CmpTy >::matchAndRewrite(), ComputeBandAndBorOpPattern< SrcOpTy, DstOpTy >::matchAndRewrite(), FoldVectorExtractAndSplatToAIEBroadcast::matchAndRewrite(), ConvertSplatToAIEBroadcast::matchAndRewrite(), ConvertSplatToAIEBroadcastAIE2p::matchAndRewrite(), ConvertVectorFMAOpToAIEVecFMAElemOpPattern::matchAndRewrite(), LowerVectorReductionMinOp::matchAndRewrite(), LowerVectorReductionMaxOp::matchAndRewrite(), LowerVectorReductionAddIntOp::matchAndRewrite(), LowerVectorReductionAddFloatOp::matchAndRewrite(), LowerVectorReductionAddBfloat16Op::matchAndRewrite(), verifyMulFMAConvOp(), verifyMulFMAElemOp(), xilinx::aievec::aie1::verifyMulFMAOp(), and verifyPackUnpackOp().
getVectorOpDestType()
mlir::VectorType xilinx::aievec::getVectorOpDestType (mlir::VectorType type, bool AIE2) inline
Definition at line 80 of file AIEVecUtils.h.
References AIE2.
Referenced by ConvertMulAddToAIEVecFMAOpPattern::matchAndRewrite(), ConvertMulAddToAIEVecFMAElemOpPattern::matchAndRewrite(), ConvertMulFToAIEVecMulElemOpPattern::matchAndRewrite(), ConvertMulIToAIEVecMulElemOpPattern::matchAndRewrite(), LowerVectorMulIOpToAIEVecMulOp::matchAndRewrite(), ComputeNegOpPattern::matchAndRewrite(), ComputeSignedIntRightShiftOpPattern::matchAndRewrite(), ComputeExpOpByLUTLLVMPattern::matchAndRewrite(), ComputeExpOpByLUTPattern::matchAndRewrite(), LowerExtOpPattern< SrcOpTy >::matchAndRewrite(), LowerVectorAddOrSubOpToAIEVecAddElemOrSubElemOp< SrcOpTy, DstOpTy >::matchAndRewrite(), LowerTruncOpPattern< SrcOpTy >::matchAndRewrite(), and LowerVectorReductionAddBfloat16Op::matchAndRewrite().
getVectorSizeInBits()
int32_t xilinx::aievec::getVectorSizeInBits (mlir::VectorType type) inline
Definition at line 66 of file AIEVecUtils.h.
References getElementSizeInBits(), and getVectorLaneSize().
Referenced by xilinx::aievec::UPDOpConversion::matchAndRewrite().
getVectorTypeString()
std::string xilinx::aievec::getVectorTypeString (VectorType type, bool abbrev = false, bool acc = false)
Definition at line 169 of file AIEVecToLLVM.cpp.
References getVectorLaneSize().
Referenced by xilinx::aievec::SelectOpConversion::getIntrinsicName(), xilinx::aievec::PackOpConversion::getIntrinsicName(), xilinx::aievec::UPDOpConversion::getIntrinsicName(), getMulOrFMAIntrinsicName(), and xilinx::aievec::UPDOpConversion::matchAndRewrite().
isAIEOp()
bool xilinx::aievec::isAIEOp (mlir::Operation * op) inline
Definition at line 73 of file AIEVecUtils.h.
isAssumingNoImplicitBroadcastOfDynamicSizes() [1/2]
bool xilinx::aievec::isAssumingNoImplicitBroadcastOfDynamicSizes (mlir::Block * block) inline
Definition at line 235 of file AIEVecUtils.h.
Referenced by isAssumingNoImplicitBroadcastOfDynamicSizes(), and DynamicSizeNoImplicitBroadcastPattern::matchAndRewrite().
isAssumingNoImplicitBroadcastOfDynamicSizes() [2/2]
bool xilinx::aievec::isAssumingNoImplicitBroadcastOfDynamicSizes (mlir::OpBuilder & builder) inline
Definition at line 246 of file AIEVecUtils.h.
References isAssumingNoImplicitBroadcastOfDynamicSizes().
isPowerOfTwo()
bool xilinx::aievec::isPowerOfTwo (int32_t n) inline
Definition at line 39 of file AIEVecUtils.h.
populateAIEVecConvOpTransformationPatterns() [1/2]
void xilinx::aievec::populateAIEVecConvOpTransformationPatterns (mlir::RewritePatternSet & patterns, mlir::AnalysisManager & am, unsigned shiftParam, TargetBackend backend)
populateAIEVecConvOpTransformationPatterns() [2/2]
void xilinx::aievec::populateAIEVecConvOpTransformationPatterns (RewritePatternSet & patterns, AnalysisManager & am, unsigned shiftParam, TargetBackend backend)
Definition at line 531 of file FoldMulAddChainToConvOp.cpp.
Referenced by AIEVecConvOpTransformationPass::runOnOperation().
populateAIEVecToLLVMAIE2ConversionPatterns() [1/2]
void xilinx::aievec::populateAIEVecToLLVMAIE2ConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns)
Referenced by populateAIEVecToLLVMAIE2ConversionPatterns(), and populateAIEVecToLLVMConversionPatterns().
populateAIEVecToLLVMAIE2ConversionPatterns() [2/2]
void xilinx::aievec::populateAIEVecToLLVMAIE2ConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns, Aie2Fp32Emulation aie2Fp32EmulationOption)
Definition at line 4379 of file AIEVecToLLVM.cpp.
References populateAIEVecToLLVMAIE2ConversionPatterns().
populateAIEVecToLLVMAIE2pConversionPatterns()
void xilinx::aievec::populateAIEVecToLLVMAIE2pConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns)
Definition at line 4473 of file AIEVecToLLVM.cpp.
References populateAIEVecToLLVMAIE2pConversionPatterns().
Referenced by populateAIEVecToLLVMAIE2pConversionPatterns(), and populateAIEVecToLLVMConversionPatterns().
populateAIEVecToLLVMCommonConversionPatterns()
void xilinx::aievec::populateAIEVecToLLVMCommonConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns)
Definition at line 4357 of file AIEVecToLLVM.cpp.
References populateAIEVecToLLVMCommonConversionPatterns().
Referenced by populateAIEVecToLLVMCommonConversionPatterns(), and populateAIEVecToLLVMConversionPatterns().
populateAIEVecToLLVMConversionPatterns() [1/2]
void xilinx::aievec::populateAIEVecToLLVMConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns, Aie2Fp32Emulation aie2Fp32EmulationOption, llvm::StringRef aieTarget)
Referenced by populateAIEVecToLLVMConversionPatterns(), and xilinx::aievec::ConvertAIEVecToLLVMPass::runOnOperation().
populateAIEVecToLLVMConversionPatterns() [2/2]
void xilinx::aievec::populateAIEVecToLLVMConversionPatterns (mlir::LLVMTypeConverter & converter, mlir::RewritePatternSet & patterns, Aie2Fp32Emulation aie2Fp32EmulationOption, StringRef aieTarget)
Definition at line 4488 of file AIEVecToLLVM.cpp.
References populateAIEVecToLLVMAIE2ConversionPatterns(), populateAIEVecToLLVMAIE2pConversionPatterns(), populateAIEVecToLLVMCommonConversionPatterns(), and populateAIEVecToLLVMConversionPatterns().
registerAIEVecPipelines()
void xilinx::aievec::registerAIEVecPipelines ()
Register all pipelines for the AIE Vector dialect.
Definition at line 146 of file ConvertVectorToAIEVec.cpp.
References buildCanonicalizeVectorForAIEVec(), buildConvertVectorToAIEVec(), buildDynamicSizeNoImplicitBroadcastPass(), buildLowerVectorToAIEVec(), and buildOptimizeAIEVec().
Referenced by aieRegisterAllPasses().
registerAIEVecToCppTranslation()
void xilinx::aievec::registerAIEVecToCppTranslation ()
Definition at line 43 of file TranslateRegistration.cpp.
References AIE2, and translateAIEVecToCpp().
registerTransformDialectExtension()
void xilinx::aievec::registerTransformDialectExtension (mlir::DialectRegistry & registry)
translateAIEVecToCpp()
mlir::LogicalResult xilinx::aievec::translateAIEVecToCpp (mlir::Operation * op, bool aie2, mlir::raw_ostream & os)
Translates the AIE vector dialect MLIR to C++ code.
Referenced by aieTranslateAIEVecToCpp(), and registerAIEVecToCppTranslation().