MLIR-AIE: xilinx::AIEX Namespace Reference
xilinx::AIEX Namespace Reference
Classes
class TokenAnalysis
Functions
memref::GlobalOp getOrCreateDataMemref (OpBuilder &builder, AIE::DeviceOp dev, mlir::Location loc, ArrayRef< uint32_t > words)
void getHardwareStridesWraps (const AIE::AIETargetModel &targetModel, mlir::Operation *op, mlir::BaseMemRefType referencedBufType, llvm::SmallVector< int64_t, 4 > inputSizes, llvm::SmallVector< int64_t, 4 > inputStrides, llvm::SmallVector< int64_t, 4 > &sizes, llvm::SmallVector< int64_t, 4 > &strides)
mlir::LogicalResult verifyStridesWraps (mlir::Operation *forOp, mlir::BaseMemRefType referencedBufType, int tileCol, int tileRow, llvm::SmallVector< int64_t, 4 > inputSizes, llvm::SmallVector< int64_t, 4 > inputStrides, llvm::SmallVector< int64_t, 4 > hardwareSizes, llvm::SmallVector< int64_t, 4 > hardwareStrides, bool skipTransformationChecks=false)
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIECreateCoresPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIECreateLocksPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEHerdRoutingPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIELowerMemcpyPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIELowerMulticastPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEBroadcastPacketPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEDmaToNpuPass ()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createAIEXToStandardPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEMaterializeBDChainsPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEAssignRuntimeSequenceBDIDsPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIEDMATasksToNPUPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIESubstituteShimDMAAllocationsPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIECtrlPacketToDmaPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIECtrlPacketInferTilesPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIELowerSetLockPass ()
std::unique_ptr< mlir::OperationPass< AIE::DeviceOp > > createAIETransformBfpTypesPass ()
Function Documentation
createAIEAssignRuntimeSequenceBDIDsPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIEAssignRuntimeSequenceBDIDsPass ()
Definition at line 169 of file AIEAssignRuntimeSequenceBDIDs.cpp.
createAIEBroadcastPacketPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIEBroadcastPacketPass ()
Definition at line 102 of file AIECreateBroadcastPacket.cpp.
createAIECreateCoresPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIECreateCoresPass ()
Definition at line 251 of file AIECreateCores.cpp.
createAIECreateLocksPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIECreateLocksPass ()
Definition at line 227 of file AIECreateLocks.cpp.
createAIECtrlPacketInferTilesPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIECtrlPacketInferTilesPass ()
Definition at line 192 of file AIECtrlPacketToDma.cpp.
createAIECtrlPacketToDmaPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIECtrlPacketToDmaPass ()
Definition at line 195 of file AIECtrlPacketToDma.cpp.
createAIEDMATasksToNPUPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIEDMATasksToNPUPass ()
Definition at line 560 of file AIEDMATasksToNPU.cpp.
createAIEDmaToNpuPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIEDmaToNpuPass ()
Definition at line 675 of file AIEDmaToNpu.cpp.
createAIEHerdRoutingPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIEHerdRoutingPass ()
Definition at line 333 of file AIEHerdRouting.cpp.
createAIELowerMemcpyPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIELowerMemcpyPass ()
Definition at line 144 of file AIELowerMemcpy.cpp.
createAIELowerMulticastPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIELowerMulticastPass ()
Definition at line 82 of file AIELowerMulticast.cpp.
createAIELowerSetLockPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIELowerSetLockPass ()
Definition at line 80 of file AIELowerSetLock.cpp.
createAIEMaterializeBDChainsPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIEMaterializeBDChainsPass ()
Definition at line 143 of file AIEMaterializeBDChains.cpp.
createAIESubstituteShimDMAAllocationsPass()
std::unique_ptr< OperationPass< AIE::DeviceOp > > xilinx::AIEX::createAIESubstituteShimDMAAllocationsPass ()
Definition at line 78 of file AIESubstituteShimDMAAllocations.cpp.
createAIETransformBfpTypesPass()
std::unique_ptr< OperationPass< DeviceOp > > xilinx::AIEX::createAIETransformBfpTypesPass ()
Definition at line 233 of file AIETransformBfpTypes.cpp.
createAIEXToStandardPass()
std::unique_ptr< OperationPass< ModuleOp > > xilinx::AIEX::createAIEXToStandardPass ()
Definition at line 65 of file AIEXToStandard.cpp.
getHardwareStridesWraps()
void xilinx::AIEX::getHardwareStridesWraps (const AIE::AIETargetModel & targetModel, mlir::Operation * op, mlir::BaseMemRefType referencedBufType, llvm::SmallVector< int64_t, 4 > inputSizes, llvm::SmallVector< int64_t, 4 > inputStrides, llvm::SmallVector< int64_t, 4 > & sizes, llvm::SmallVector< int64_t, 4 > & strides)
Definition at line 88 of file AIEXDialect.cpp.
References xilinx::AIE::AIETargetModel::getAddressGenGranularity().
Referenced by AIEDMATasksToNPUPass::rewriteSingleBD().
getOrCreateDataMemref()
memref::GlobalOp xilinx::AIEX::getOrCreateDataMemref (OpBuilder & builder, AIE::DeviceOp dev, mlir::Location loc, ArrayRef< uint32_t > words)
Definition at line 18 of file AIEUtils.cpp.
verifyStridesWraps()
mlir::LogicalResult xilinx::AIEX::verifyStridesWraps (mlir::Operation * forOp, mlir::BaseMemRefType referencedBufType, int tileCol, int tileRow, llvm::SmallVector< int64_t, 4 > inputSizes, llvm::SmallVector< int64_t, 4 > inputStrides, llvm::SmallVector< int64_t, 4 > hardwareSizes, llvm::SmallVector< int64_t, 4 > hardwareStrides, bool skipTransformationChecks = false)
Definition at line 172 of file AIEXDialect.cpp.
References xilinx::AIE::getTargetModel().
Referenced by AIEDMATasksToNPUPass::rewriteSingleBD().