MLIR-AIE: test_utils Namespace Reference
test_utils Namespace Reference
Functions
void check_arg_file_exists (const cxxopts::ParseResult &result, std::string name)
void add_default_options (cxxopts::Options &options)
void parse_options (int argc, const char *argv[], cxxopts::Options &options, cxxopts::ParseResult &result)
std::vector< uint32_t > load_instr_sequence (std::string instr_path)
std::vector< uint32_t > load_instr_binary (std::string instr_path)
void init_xrt_load_kernel (xrt::device &device, xrt::kernel &kernel, int verbosity, std::string xclbinFileName, std::string kernelNameInXclbin)
bool nearly_equal (float a, float b, float epsilon=128 *FLT_EPSILON, float abs_th=FLT_MIN)
template<typename T >
void print_matrix (const std::vector< T > matrix, int n_cols, int n_printable_rows=10, int n_printable_cols=10, std::ostream &ostream=std::cout, const char col_sep[]=" ", const char elide_sym[]=" ... ", int w=-1)
void write_out_trace (char *traceOutPtr, size_t trace_size, std::string path)
Function Documentation
add_default_options()
void test_utils::add_default_options (cxxopts::Options & options)
Definition at line 37 of file test_utils.cpp.
References cxxopts::Options::add_options().
Referenced by parse_args().
check_arg_file_exists()
void test_utils::check_arg_file_exists (const cxxopts::ParseResult & result, std::string name)
Definition at line 26 of file test_utils.cpp.
References cxxopts::ParseResult::count().
Referenced by parse_options().
init_xrt_load_kernel()
void test_utils::init_xrt_load_kernel (xrt::device & device, xrt::kernel & kernel, int verbosity, std::string xclbinFileName, std::string kernelNameInXclbin)
Referenced by setup_and_run_aie(), and setup_and_run_aie().
load_instr_binary()
std::vector< uint32_t > test_utils::load_instr_binary (std::string instr_path)
Definition at line 101 of file test_utils.cpp.
Referenced by setup_and_run_aie(), and setup_and_run_aie().
load_instr_sequence()
std::vector< uint32_t > test_utils::load_instr_sequence (std::string instr_path)
Definition at line 86 of file test_utils.cpp.
nearly_equal()
bool test_utils::nearly_equal (float a, float b, float epsilon = 128 * FLT_EPSILON, float abs_th = FLT_MIN)
Definition at line 186 of file test_utils.cpp.
parse_options()
void test_utils::parse_options (int argc, const char * argv[], cxxopts::Options & options, cxxopts::ParseResult & result)
Definition at line 58 of file test_utils.cpp.
References check_arg_file_exists(), cxxopts::ParseResult::count(), cxxopts::Options::help(), cxxopts::Options::parse(), and cxxopts::exceptions::exception::what().
Referenced by parse_args().
print_matrix()
template<typename T > void test_utils::print_matrix (const std::vector< T > matrix, int n_cols, int n_printable_rows = 10, int n_printable_cols = 10, std::ostream & ostream = std::cout, const char col_sep[] = " ", const char elide_sym[] = " ... ", int w = -1)
Definition at line 71 of file test_utils.h.
References print_row.
write_out_trace()
void test_utils::write_out_trace (char * traceOutPtr, size_t trace_size, std::string path)
Definition at line 207 of file test_utils.cpp.
Referenced by setup_and_run_aie(), and setup_and_run_aie().