MLIR-AIE: cxxopts::values Namespace Reference
cxxopts::values Namespace Reference
Namespaces
namespace detail
namespace parser_tool
Classes
class abstract_value
class standard_value
class standard_value< bool >
struct type_is_container
struct type_is_container< std::vector< T > >
Functions
template<typename R , typename T >
void checked_negate (R &r, T &&t, const std::string &, std::true_type)
template<typename R , typename T >
void checked_negate (R &, T &&, const std::string &text, std::false_type)
template<typename T >
void integer_parser (const std::string &text, T &value)
template<typename T >
void stringstream_parser (const std::string &text, T &value)
template<typename T , typename std::enable_if< std::is_integral< T >::value >::type * = nullptr>
void parse_value (const std::string &text, T &value)
void parse_value (const std::string &text, bool &value)
void parse_value (const std::string &text, std::string &value)
void parse_value (const std::string &text, char &c)
template<typename T >
void parse_value (const std::string &text, std::vector< T > &value)
template<typename T >
void add_value (const std::string &text, T &value)
template<typename T >
void add_value (const std::string &text, std::vector< T > &value)
Function Documentation
add_value() [1/2]
template<typename T > void cxxopts::values::add_value (const std::string & text, std::vector< T > & value)
Definition at line 887 of file cxxopts.hpp.
References add_value(), and cxxopts::value().
add_value() [2/2]
template<typename T > void cxxopts::values::add_value (const std::string & text, T & value)
Definition at line 882 of file cxxopts.hpp.
References parse_value(), and cxxopts::value().
Referenced by cxxopts::values::abstract_value< T >::add(), and add_value().
checked_negate() [1/2]
template<typename R , typename T > void cxxopts::values::checked_negate (R & , T && , const std::string & text, std::false_type)
Definition at line 741 of file cxxopts.hpp.
checked_negate() [2/2]
template<typename R , typename T > void cxxopts::values::checked_negate (R & r, T && t, const std::string & , std::true_type)
Definition at line 733 of file cxxopts.hpp.
integer_parser()
template<typename T > void cxxopts::values::integer_parser (const std::string & text, T & value)
Definition at line 746 of file cxxopts.hpp.
References cxxopts::values::parser_tool::IntegerDesc::base, cxxopts::values::parser_tool::IntegerDesc::negative, cxxopts::values::parser_tool::SplitInteger(), cxxopts::values::parser_tool::IntegerDesc::value, and cxxopts::value().
Referenced by parse_value().
parse_value() [1/5]
void cxxopts::values::parse_value (const std::string & text, bool & value) inline
Definition at line 814 of file cxxopts.hpp.
References cxxopts::values::parser_tool::IsFalseText(), cxxopts::values::parser_tool::IsTrueText(), and cxxopts::value().
parse_value() [2/5]
void cxxopts::values::parse_value (const std::string & text, char & c) inline
Definition at line 856 of file cxxopts.hpp.
parse_value() [3/5]
void cxxopts::values::parse_value (const std::string & text, std::string & value) inline
Definition at line 828 of file cxxopts.hpp.
References cxxopts::value().
parse_value() [4/5]
template<typename T > void cxxopts::values::parse_value (const std::string & text, std::vector< T > & value)
Definition at line 865 of file cxxopts.hpp.
References CXXOPTS_VECTOR_DELIMITER, parse_value(), and cxxopts::value().
parse_value() [5/5]
template<typename T , typename std::enable_if< std::is_integral< T >::value >::type * = nullptr> void cxxopts::values::parse_value (const std::string & text, T & value)
Definition at line 810 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
Referenced by add_value(), cxxopts::KeyValue::as(), cxxopts::values::abstract_value< T >::parse(), cxxopts::values::abstract_value< T >::parse(), and parse_value().
stringstream_parser()
template<typename T > void cxxopts::values::stringstream_parser (const std::string & text, T & value)
Definition at line 800 of file cxxopts.hpp.
References cxxopts::value().