MLIR-AIE: cxxopts Namespace Reference
cxxopts Namespace Reference
Namespaces
namespace exceptions
namespace values
Classes
struct HelpGroupDetails
struct HelpOptionDetails
class KeyValue
struct Option
class OptionAdder
class OptionDetails
class OptionParser
class Options
class OptionValue
class ParseResult
class Value
Typedefs
using String = std::string
using OptionNames = std::vector< std::string >
using ParsedHashMap = std::unordered_map< std::size_t, OptionValue >
using NameHashMap = std::unordered_map< std::string, std::size_t >
using OptionMap = std::unordered_map< std::string, std::shared_ptr< OptionDetails > >
using PositionalList = std::vector< std::string >
using PositionalListIterator = PositionalList::const_iterator
Functions
template<typename T >
T toLocalString (T &&t)
std::size_t stringLength (const String &s)
String & stringAppend (String &s, const String &a)
String & stringAppend (String &s, std::size_t n, char c)
template<typename Iterator >
String & stringAppend (String &s, Iterator begin, Iterator end)
template<typename T >
std::string toUTF8String (T &&t)
bool empty (const std::string &s)
template<typename T >
void throw_or_mimic (const std::string &text)
template<typename T >
std::shared_ptr< Value > value ()
template<typename T >
std::shared_ptr< Value > value (T &t)
CXXOPTS_NODISCARD const std::string & first_or_empty (const OptionNames &long_names)
Typedef Documentation
NameHashMap
using cxxopts::NameHashMap = typedef std::unordered_map<std::string, std::size_t>
Definition at line 1216 of file cxxopts.hpp.
OptionMap
using cxxopts::OptionMap = typedef std::unordered_map<std::string, std::shared_ptr<OptionDetails> >
Definition at line 1389 of file cxxopts.hpp.
OptionNames
using cxxopts::OptionNames = typedef std::vector<std::string>
Definition at line 443 of file cxxopts.hpp.
ParsedHashMap
using cxxopts::ParsedHashMap = typedef std::unordered_map<std::size_t, OptionValue>
Definition at line 1215 of file cxxopts.hpp.
PositionalList
using cxxopts::PositionalList = typedef std::vector<std::string>
Definition at line 1391 of file cxxopts.hpp.
PositionalListIterator
using cxxopts::PositionalListIterator = typedef PositionalList::const_iterator
Definition at line 1392 of file cxxopts.hpp.
String
using cxxopts::String = typedef std::string
Definition at line 250 of file cxxopts.hpp.
Function Documentation
empty()
bool cxxopts::empty (const std::string & s) inline
Definition at line 275 of file cxxopts.hpp.
Referenced by first_or_empty().
first_or_empty()
CXXOPTS_NODISCARD const std::string & cxxopts::first_or_empty (const OptionNames & long_names) inline
Definition at line 1038 of file cxxopts.hpp.
References empty().
Referenced by cxxopts::OptionValue::as(), and cxxopts::OptionDetails::first_long_name().
stringAppend() [1/3]
String & cxxopts::stringAppend (String & s, const String & a) inline
Definition at line 259 of file cxxopts.hpp.
stringAppend() [2/3]
template<typename Iterator > String & cxxopts::stringAppend (String & s, Iterator begin, Iterator end)
Definition at line 266 of file cxxopts.hpp.
stringAppend() [3/3]
String & cxxopts::stringAppend (String & s, std::size_t n, char c) inline
Definition at line 261 of file cxxopts.hpp.
stringLength()
std::size_t cxxopts::stringLength (const String & s) inline
Definition at line 257 of file cxxopts.hpp.
throw_or_mimic()
template<typename T > void cxxopts::throw_or_mimic (const std::string & text)
Definition at line 426 of file cxxopts.hpp.
References cxxopts::exceptions::exception::what().
toLocalString()
template<typename T > T cxxopts::toLocalString (T && t)
Definition at line 253 of file cxxopts.hpp.
Referenced by cxxopts::Options::add_option(), and cxxopts::Options::help().
toUTF8String()
template<typename T > std::string cxxopts::toUTF8String (T && t)
Definition at line 271 of file cxxopts.hpp.
Referenced by cxxopts::Options::help().
value() [1/2]
template<typename T > std::shared_ptr< Value > cxxopts::value ()
Definition at line 1026 of file cxxopts.hpp.
Referenced by cxxopts::Options::add_option(), cxxopts::Options::add_option(), cxxopts::OptionParser::add_to_option(), cxxopts::values::add_value(), cxxopts::values::add_value(), cxxopts::values::detail::check_signed_range(), cxxopts::OptionParser::checked_parse_arg(), cxxopts::values::abstract_value< T >::default_value(), cxxopts::values::abstract_value< T >::implicit_value(), cxxopts::values::integer_parser(), cxxopts::OptionAdder::operator()(), cxxopts::OptionParser::parse(), cxxopts::OptionParser::parse_option(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), and cxxopts::values::stringstream_parser().
value() [2/2]
template<typename T > std::shared_ptr< Value > cxxopts::value (T & t)
Definition at line 1031 of file cxxopts.hpp.
Variable Documentation
major
uint8_t cxxopts::major
Definition at line 131 of file cxxopts.hpp.
minor
uint8_t cxxopts::minor
Definition at line 131 of file cxxopts.hpp.
patch
uint8_t cxxopts::patch
Definition at line 131 of file cxxopts.hpp.