MLIR-AIE: ShiftClampTruncToSRSPattern Struct Reference
ShiftClampTruncToSRSPattern Struct Reference
Public Member Functions
ShiftClampTruncToSRSPattern (MLIRContext *context, PatternBenefit benefit=2)
LogicalResult matchAndRewrite (arith::TruncIOp truncOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static std::optional< int64_t > getConstantSplatValue (Value val)
static std::optional< Value > getShiftValue (Value rhs, ConversionPatternRewriter &rewriter, Location loc)
Detailed Description
Definition at line 3819 of file VectorToAIEVecConversions.cpp.
Constructor & Destructor Documentation
ShiftClampTruncToSRSPattern()
ShiftClampTruncToSRSPattern::ShiftClampTruncToSRSPattern (MLIRContext * context, PatternBenefit benefit = 2) inline
Definition at line 3822 of file VectorToAIEVecConversions.cpp.
Member Function Documentation
getConstantSplatValue()
static std::optional< int64_t > ShiftClampTruncToSRSPattern::getConstantSplatValue (Value val) inline static
Definition at line 3827 of file VectorToAIEVecConversions.cpp.
Referenced by matchAndRewrite().
getShiftValue()
static std::optional< Value > ShiftClampTruncToSRSPattern::getShiftValue (Value rhs, ConversionPatternRewriter & rewriter, Location loc) inline static
Definition at line 3841 of file VectorToAIEVecConversions.cpp.
Referenced by matchAndRewrite().
matchAndRewrite()
LogicalResult ShiftClampTruncToSRSPattern::matchAndRewrite (arith::TruncIOp truncOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 3866 of file VectorToAIEVecConversions.cpp.
References xilinx::aievec::createVectorType(), getConstantSplatValue(), getShiftValue(), xilinx::aievec::getVectorLaneSize(), and xilinx::aievec::getVectorOpDestType().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToAIEVecConversions.cpp