MLIR-AIE: LowerScalarShiftClampTruncToSRS Struct Reference
LowerScalarShiftClampTruncToSRS Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (arith::TruncIOp truncOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Static Public Member Functions
static std::optional< int64_t > getScalarConstantValue (Value val)
Detailed Description
Definition at line 4230 of file VectorToAIEVecConversions.cpp.
Member Function Documentation
getScalarConstantValue()
static std::optional< int64_t > LowerScalarShiftClampTruncToSRS::getScalarConstantValue (Value val) inline static
Definition at line 4234 of file VectorToAIEVecConversions.cpp.
Referenced by matchAndRewrite().
matchAndRewrite()
LogicalResult LowerScalarShiftClampTruncToSRS::matchAndRewrite (arith::TruncIOp truncOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 4245 of file VectorToAIEVecConversions.cpp.
References xilinx::aievec::createVectorType(), and getScalarConstantValue().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToAIEVecConversions.cpp