MLIR-AIE: GraphWriter Struct Reference
GraphWriter Struct Reference
Public Member Functions
GraphWriter (raw_ostream &output)
StringRef getCTypeString (const Type &type)
std::string getKernelTypeString (const std::string &direction, Type type)
std::string getConnectionTypeString (Type type)
std::string getTempNetName ()
void visitOpResultUsers (GraphInputOp driverOp)
void visitOpResultUsers (KernelOp source)
void writeKernelFunctions (ModuleOp module)
void writeClass (GraphOp graph)
Public Attributes
raw_ostream & output
std::unordered_map< Operation *, std::string > kernelOp2VarName
Detailed Description
Definition at line 45 of file ADFGenerateCppGraph.cpp.
Constructor & Destructor Documentation
GraphWriter()
GraphWriter::GraphWriter (raw_ostream & output) inline
Definition at line 47 of file ADFGenerateCppGraph.cpp.
Member Function Documentation
getConnectionTypeString()
std::string GraphWriter::getConnectionTypeString (Type type) inline
Definition at line 87 of file ADFGenerateCppGraph.cpp.
Referenced by visitOpResultUsers(), and visitOpResultUsers().
getCTypeString()
StringRef GraphWriter::getCTypeString (const Type & type) inline
Definition at line 52 of file ADFGenerateCppGraph.cpp.
Referenced by getKernelTypeString().
getKernelTypeString()
std::string GraphWriter::getKernelTypeString (const std::string & direction, Type type) inline
Definition at line 74 of file ADFGenerateCppGraph.cpp.
References getCTypeString().
Referenced by writeKernelFunctions().
getTempNetName()
std::string GraphWriter::getTempNetName () inline
Definition at line 98 of file ADFGenerateCppGraph.cpp.
Referenced by visitOpResultUsers(), and visitOpResultUsers().
visitOpResultUsers() [1/2]
void GraphWriter::visitOpResultUsers (GraphInputOp driverOp) inline
Definition at line 103 of file ADFGenerateCppGraph.cpp.
References getConnectionTypeString(), getTempNetName(), kernelOp2VarName, and output.
visitOpResultUsers() [2/2]
void GraphWriter::visitOpResultUsers (KernelOp source) inline
Definition at line 126 of file ADFGenerateCppGraph.cpp.
References getConnectionTypeString(), getTempNetName(), kernelOp2VarName, and output.
writeClass()
void GraphWriter::writeClass (GraphOp graph) inline
Definition at line 187 of file ADFGenerateCppGraph.cpp.
writeKernelFunctions()
void GraphWriter::writeKernelFunctions (ModuleOp module) inline
Definition at line 162 of file ADFGenerateCppGraph.cpp.
References getKernelTypeString(), and output.
Member Data Documentation
kernelOp2VarName
std::unordered_map<Operation *, std::string> GraphWriter::kernelOp2VarName
Definition at line 50 of file ADFGenerateCppGraph.cpp.
Referenced by visitOpResultUsers(), and visitOpResultUsers().
output
raw_ostream& GraphWriter::output
Definition at line 46 of file ADFGenerateCppGraph.cpp.
Referenced by visitOpResultUsers(), visitOpResultUsers(), and writeKernelFunctions().
The documentation for this struct was generated from the following file:
lib/Targets/ADFGenerateCppGraph.cpp