MLIR-AIE: BdIdGenerator Struct Reference
BdIdGenerator Struct Reference
#include "aie/Dialect/AIE/Transforms/AIEAssignBufferDescriptorIDs.h"
Public Member Functions
BdIdGenerator (int col, int row, const AIETargetModel &targetModel)
std::optional< uint32_t > nextBdId (int channelIndex)
void assignBdId (uint32_t bdId)
bool bdIdAlreadyAssigned (uint32_t bdId)
void freeBdId (uint32_t bdId)
Public Attributes
const int col
const int row
const AIETargetModel & targetModel
std::set< uint32_t > alreadyAssigned
Detailed Description
Definition at line 18 of file AIEAssignBufferDescriptorIDs.h.
Constructor & Destructor Documentation
BdIdGenerator()
BdIdGenerator::BdIdGenerator (int col, int row, const AIETargetModel & targetModel)
Definition at line 23 of file AIEAssignBufferDescriptorIDs.cpp.
Member Function Documentation
assignBdId()
void BdIdGenerator::assignBdId (uint32_t bdId)
Definition at line 43 of file AIEAssignBufferDescriptorIDs.cpp.
References alreadyAssigned.
Referenced by nextBdId(), AIEAssignRuntimeSequenceBDIDsPass::runOnConfigureBDs(), and AIEAssignBufferDescriptorIDsPass::runOnOperation().
bdIdAlreadyAssigned()
bool BdIdGenerator::bdIdAlreadyAssigned (uint32_t bdId)
Definition at line 48 of file AIEAssignBufferDescriptorIDs.cpp.
References alreadyAssigned.
Referenced by nextBdId(), AIEAssignRuntimeSequenceBDIDsPass::runOnConfigureBDs(), AIEAssignRuntimeSequenceBDIDsPass::runOnFreeBDs(), and AIEAssignBufferDescriptorIDsPass::runOnOperation().
freeBdId()
void BdIdGenerator::freeBdId (uint32_t bdId)
Definition at line 52 of file AIEAssignBufferDescriptorIDs.cpp.
References alreadyAssigned.
Referenced by AIEAssignRuntimeSequenceBDIDsPass::runOnFreeBDs().
nextBdId()
std::optional< uint32_t > BdIdGenerator::nextBdId (int channelIndex)
Definition at line 27 of file AIEAssignBufferDescriptorIDs.cpp.
References assignBdId(), bdIdAlreadyAssigned(), col, xilinx::AIE::AIETargetModel::getNumBDs(), xilinx::AIE::AIETargetModel::isBdChannelAccessible(), row, and targetModel.
Referenced by AIEAssignRuntimeSequenceBDIDsPass::runOnConfigureBDs(), and AIEAssignBufferDescriptorIDsPass::runOnOperation().
Member Data Documentation
alreadyAssigned
std::set<uint32_t> BdIdGenerator::alreadyAssigned
Definition at line 22 of file AIEAssignBufferDescriptorIDs.h.
Referenced by assignBdId(), bdIdAlreadyAssigned(), and freeBdId().
col
const int BdIdGenerator::col
Definition at line 19 of file AIEAssignBufferDescriptorIDs.h.
Referenced by nextBdId().
row
const int BdIdGenerator::row
Definition at line 20 of file AIEAssignBufferDescriptorIDs.h.
Referenced by nextBdId().
targetModel
const AIETargetModel& BdIdGenerator::targetModel
Definition at line 21 of file AIEAssignBufferDescriptorIDs.h.
Referenced by nextBdId().
The documentation for this struct was generated from the following files:
include/aie/Dialect/AIE/Transforms/AIEAssignBufferDescriptorIDs.h
lib/Dialect/AIE/Transforms/AIEAssignBufferDescriptorIDs.cpp