MLIR-AIE: AIEAssignRuntimeSequenceBDIDsPass Struct Reference
AIEAssignRuntimeSequenceBDIDsPass Struct Reference
Public Member Functions
BdIdGenerator & getGeneratorForTile (AIE::TileOp tile, std::map< AIE::TileOp, BdIdGenerator > &gens)
LogicalResult runOnConfigureBDs (DMAConfigureTaskOp op, std::map< AIE::TileOp, BdIdGenerator > &gens)
LogicalResult runOnFreeBDs (DMAFreeTaskOp op, std::map< AIE::TileOp, BdIdGenerator > &gens)
void runOnOperation () override
Detailed Description
Definition at line 23 of file AIEAssignRuntimeSequenceBDIDs.cpp.
Member Function Documentation
getGeneratorForTile()
BdIdGenerator & AIEAssignRuntimeSequenceBDIDsPass::getGeneratorForTile (AIE::TileOp tile, std::map< AIE::TileOp, BdIdGenerator > & gens) inline
Definition at line 27 of file AIEAssignRuntimeSequenceBDIDs.cpp.
References xilinx::AIE::getTargetModel().
Referenced by runOnConfigureBDs(), and runOnFreeBDs().
runOnConfigureBDs()
LogicalResult AIEAssignRuntimeSequenceBDIDsPass::runOnConfigureBDs (DMAConfigureTaskOp op, std::map< AIE::TileOp, BdIdGenerator > & gens) inline
Definition at line 40 of file AIEAssignRuntimeSequenceBDIDs.cpp.
References BdIdGenerator::assignBdId(), BdIdGenerator::bdIdAlreadyAssigned(), getGeneratorForTile(), and BdIdGenerator::nextBdId().
Referenced by runOnOperation().
runOnFreeBDs()
LogicalResult AIEAssignRuntimeSequenceBDIDsPass::runOnFreeBDs (DMAFreeTaskOp op, std::map< AIE::TileOp, BdIdGenerator > & gens) inline
Definition at line 86 of file AIEAssignRuntimeSequenceBDIDs.cpp.
References BdIdGenerator::bdIdAlreadyAssigned(), BdIdGenerator::freeBdId(), and getGeneratorForTile().
Referenced by runOnOperation().
runOnOperation()
void AIEAssignRuntimeSequenceBDIDsPass::runOnOperation () inline override
Definition at line 132 of file AIEAssignRuntimeSequenceBDIDs.cpp.
References runOnConfigureBDs(), and runOnFreeBDs().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEX/Transforms/AIEAssignRuntimeSequenceBDIDs.cpp