MLIR-AIE: AIECreateLocksPass Struct Reference
AIECreateLocksPass Struct Reference
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 134 of file AIECreateLocks.cpp.
Member Function Documentation
runOnOperation()
void AIECreateLocksPass::runOnOperation () inline override
Definition at line 135 of file AIECreateLocks.cpp.
References xilinx::AIEX::TokenAnalysis::getCoord(), xilinx::AIEX::TokenAnalysis::getShareableTileOp(), xilinx::AIEX::TokenAnalysis::getTiles(), xilinx::AIEX::TokenAnalysis::getTokenChains(), xilinx::AIEX::TokenAnalysis::getTokenPairs(), xilinx::AIEX::TokenAnalysis::getTokenUserOp(), xilinx::AIEX::TokenAnalysis::print(), and xilinx::AIEX::TokenAnalysis::runAnalysis().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEX/Transforms/AIECreateLocks.cpp