MLIR-AIE: AIEGenerateColumnControlOverlayPass Struct Reference
AIEGenerateColumnControlOverlayPass Struct Reference
Public Member Functions
void getDependentDialects (DialectRegistry &registry) const override
void runOnOperation () override
AIE::PacketFlowOp createPacketFlowOp (OpBuilder &builder, int &flowID, Value source, xilinx::AIE::WireBundle sourceBundle, uint32_t sourceChannel, Value dest, xilinx::AIE::WireBundle destBundle, uint32_t destChannel, mlir::BoolAttr keep_pkt_header=nullptr, mlir::BoolAttr ctrl_pkt_flow=nullptr)
SmallVector< int > getAvailableShimChans (DeviceOp device, TileOp shimTile, WireBundle shimWireBundle, bool isShimMM2S)
void generatePacketFlowsForControl (OpBuilder builder, DeviceOp device, TileOp shimTile, WireBundle shimWireBundle, SmallVector< AIE::TileOp > ctrlTiles, WireBundle ctrlWireBundle, int coreOrMemChanId, DenseMap< TileID, int > tileIDMap, bool isShimMM2S)
AIE::PacketFlowOp getPktFlowWithSameSrcOrDst (DeviceOp device, TileOp srcTile, WireBundle srcBundle, int srcChan, TileOp destTile, WireBundle destBundle, int destChan)
Detailed Description
Definition at line 181 of file AIEGenerateColumnControlOverlay.cpp.
Member Function Documentation
createPacketFlowOp()
AIE::PacketFlowOp AIEGenerateColumnControlOverlayPass::createPacketFlowOp (OpBuilder & builder, int & flowID, Value source, xilinx::AIE::WireBundle sourceBundle, uint32_t sourceChannel, Value dest, xilinx::AIE::WireBundle destBundle, uint32_t destChannel, mlir::BoolAttr keep_pkt_header = nullptr, mlir::BoolAttr ctrl_pkt_flow = nullptr) inline
Definition at line 242 of file AIEGenerateColumnControlOverlay.cpp.
Referenced by generatePacketFlowsForControl().
generatePacketFlowsForControl()
void AIEGenerateColumnControlOverlayPass::generatePacketFlowsForControl (OpBuilder builder, DeviceOp device, TileOp shimTile, WireBundle shimWireBundle, SmallVector< AIE::TileOp > ctrlTiles, WireBundle ctrlWireBundle, int coreOrMemChanId, DenseMap< TileID, int > tileIDMap, bool isShimMM2S) inline
Definition at line 303 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::col, createPacketFlowOp(), getAvailableShimChans(), and getRowToShimChanMap().
Referenced by runOnOperation().
getAvailableShimChans()
SmallVector< int > AIEGenerateColumnControlOverlayPass::getAvailableShimChans (DeviceOp device, TileOp shimTile, WireBundle shimWireBundle, bool isShimMM2S) inline
Definition at line 268 of file AIEGenerateColumnControlOverlay.cpp.
Referenced by generatePacketFlowsForControl().
getDependentDialects()
void AIEGenerateColumnControlOverlayPass::getDependentDialects (DialectRegistry & registry) const inline override
Definition at line 183 of file AIEGenerateColumnControlOverlay.cpp.
getPktFlowWithSameSrcOrDst()
AIE::PacketFlowOp AIEGenerateColumnControlOverlayPass::getPktFlowWithSameSrcOrDst (DeviceOp device, TileOp srcTile, WireBundle srcBundle, int srcChan, TileOp destTile, WireBundle destBundle, int destChan) inline
Definition at line 373 of file AIEGenerateColumnControlOverlay.cpp.
runOnOperation()
void AIEGenerateColumnControlOverlayPass::runOnOperation () inline override
Definition at line 187 of file AIEGenerateColumnControlOverlay.cpp.
References xilinx::AIE::col, generatePacketFlowsForControl(), and getTileToControllerIdMap().
The documentation for this struct was generated from the following file:
lib/Dialect/AIE/Transforms/AIEGenerateColumnControlOverlay.cpp