MLIR-AIE: LowerTruncOpPattern< SrcOpTy > Struct Template Reference
LowerTruncOpPattern< SrcOpTy > Struct Template Reference
Public Types
using OpAdaptor = typename SrcOpTy::Adaptor
Public Member Functions
LogicalResult matchAndRewrite (SrcOpTy truncOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Detailed Description
template<typename SrcOpTy>
struct LowerTruncOpPattern< SrcOpTy >
Definition at line 2390 of file VectorToAIEVecConversions.cpp.
Member Typedef Documentation
OpAdaptor
template<typename SrcOpTy > using LowerTruncOpPattern< SrcOpTy >::OpAdaptor = typename SrcOpTy::Adaptor
Definition at line 2392 of file VectorToAIEVecConversions.cpp.
Member Function Documentation
matchAndRewrite()
template<typename SrcOpTy > LogicalResult LowerTruncOpPattern< SrcOpTy >::matchAndRewrite (SrcOpTy truncOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 2395 of file VectorToAIEVecConversions.cpp.
References xilinx::aievec::createVectorType(), xilinx::aievec::getVectorLaneSize(), and xilinx::aievec::getVectorOpDestType().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToAIEVecConversions.cpp