MLIR-AIE: ConvertMulFToAIEVecMulElemOpPattern Struct Reference
ConvertMulFToAIEVecMulElemOpPattern Struct Reference
Public Member Functions
ConvertMulFToAIEVecMulElemOpPattern (MLIRContext *context, unsigned shiftParam=0)
LogicalResult matchAndRewrite (arith::MulFOp mulOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Public Attributes
unsigned shiftParam
Detailed Description
Definition at line 745 of file VectorToAIEVecConversions.cpp.
Constructor & Destructor Documentation
ConvertMulFToAIEVecMulElemOpPattern()
ConvertMulFToAIEVecMulElemOpPattern::ConvertMulFToAIEVecMulElemOpPattern (MLIRContext * context, unsigned shiftParam = 0) inline
Definition at line 749 of file VectorToAIEVecConversions.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult ConvertMulFToAIEVecMulElemOpPattern::matchAndRewrite (arith::MulFOp mulOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 754 of file VectorToAIEVecConversions.cpp.
References xilinx::aievec::createVectorType(), xilinx::aievec::getVectorLaneSize(), xilinx::aievec::getVectorOpDestType(), and shiftParam.
Member Data Documentation
shiftParam
unsigned ConvertMulFToAIEVecMulElemOpPattern::shiftParam
Definition at line 846 of file VectorToAIEVecConversions.cpp.
Referenced by matchAndRewrite().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToAIEVecConversions.cpp