MLIR-AIE: SplitUnalignedTransferReadPattern Struct Reference
SplitUnalignedTransferReadPattern Struct Reference
Public Member Functions
SplitUnalignedTransferReadPattern (MLIRContext *context, int64_t maxVectorSize, int64_t alignment)
LogicalResult matchAndRewrite (vector::TransferReadOp readOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Public Attributes
int64_t maxVectorSize
int64_t vectorAlignment
Detailed Description
Definition at line 123 of file VectorToVectorConversions.cpp.
Constructor & Destructor Documentation
SplitUnalignedTransferReadPattern()
SplitUnalignedTransferReadPattern::SplitUnalignedTransferReadPattern (MLIRContext * context, int64_t maxVectorSize, int64_t alignment) inline
Definition at line 127 of file VectorToVectorConversions.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult SplitUnalignedTransferReadPattern::matchAndRewrite (vector::TransferReadOp readOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 133 of file VectorToVectorConversions.cpp.
References get(), xilinx::aievec::getElementSizeInBits(), and xilinx::aievec::getTransferReadAlignmentOffset().
Member Data Documentation
maxVectorSize
int64_t SplitUnalignedTransferReadPattern::maxVectorSize
Definition at line 182 of file VectorToVectorConversions.cpp.
vectorAlignment
int64_t SplitUnalignedTransferReadPattern::vectorAlignment
Definition at line 183 of file VectorToVectorConversions.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToVectorConversions.cpp