MLIR-AIE: xilinx::aievec::AIEVecConvAnalysis Struct Reference
xilinx::aievec::AIEVecConvAnalysis Struct Reference
Public Types
using ConvMacChain = LongestConvMACChainAnalysis::ConvMacChain
using ConvMacChainGroupList = LongestConvMACChainAnalysis::ConvMacChainGroupList
Public Member Functions
AIEVecConvAnalysis ()=default
void runOnOperation () override
void listChain (const std::unique_ptr< ConvMacChain > &chain, const ConvMacChainGroupList &groups) const
Detailed Description
Definition at line 529 of file FoldMulAddChainToConvOp.cpp.
Member Typedef Documentation
ConvMacChain
using xilinx::aievec::AIEVecConvAnalysis::ConvMacChain = LongestConvMACChainAnalysis::ConvMacChain
Definition at line 531 of file FoldMulAddChainToConvOp.cpp.
ConvMacChainGroupList
using xilinx::aievec::AIEVecConvAnalysis::ConvMacChainGroupList = LongestConvMACChainAnalysis::ConvMacChainGroupList
Definition at line 532 of file FoldMulAddChainToConvOp.cpp.
Constructor & Destructor Documentation
AIEVecConvAnalysis()
xilinx::aievec::AIEVecConvAnalysis::AIEVecConvAnalysis () default
Member Function Documentation
listChain()
void xilinx::aievec::AIEVecConvAnalysis::listChain (const std::unique_ptr< ConvMacChain > & chain, const ConvMacChainGroupList & groups) const inline
Definition at line 573 of file FoldMulAddChainToConvOp.cpp.
Referenced by runOnOperation().
runOnOperation()
void xilinx::aievec::AIEVecConvAnalysis::runOnOperation () inline override
Definition at line 535 of file FoldMulAddChainToConvOp.cpp.
References LongestConvMACChainAnalysis::am, listChain(), and LongestConvMACChainAnalysis::sortChain().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/FoldMulAddChainToConvOp.cpp