MLIR-AIE: AIEObjectFifoRegisterProcessPass Struct Reference
AIEObjectFifoRegisterProcessPass Struct Reference
Public Member Functions
scf::ForOp createForLoop (OpBuilder &builder, int length)
void createPattern (OpBuilder &builder, DeviceOp &device, ObjectFifoRegisterProcessOp regOp, MemRefType elementType, IntegerAttr acqNumber, IntegerAttr relNumber, int length)
void runOnOperation () override
Detailed Description
Definition at line 36 of file AIEObjectFifoRegisterProcess.cpp.
Member Function Documentation
createForLoop()
scf::ForOp AIEObjectFifoRegisterProcessPass::createForLoop (OpBuilder & builder, int length) inline
Definition at line 39 of file AIEObjectFifoRegisterProcess.cpp.
Referenced by createPattern().
createPattern()
void AIEObjectFifoRegisterProcessPass::createPattern (OpBuilder & builder, DeviceOp & device, ObjectFifoRegisterProcessOp regOp, MemRefType elementType, IntegerAttr acqNumber, IntegerAttr relNumber, int length) inline
Definition at line 51 of file AIEObjectFifoRegisterProcess.cpp.
References createForLoop().
Referenced by runOnOperation().
runOnOperation()
void AIEObjectFifoRegisterProcessPass::runOnOperation () inline override
Definition at line 100 of file AIEObjectFifoRegisterProcess.cpp.
References createPattern().
The documentation for this struct was generated from the following file:
lib/Dialect/AIE/Transforms/AIEObjectFifoRegisterProcess.cpp