MLIR-AIE: ConvertMulIToAIEVecMulElemOpPattern Struct Reference
ConvertMulIToAIEVecMulElemOpPattern Struct Reference
Public Member Functions
ConvertMulIToAIEVecMulElemOpPattern (MLIRContext *context, unsigned shiftParam=0)
LogicalResult matchAndRewrite (arith::MulIOp mulOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Public Attributes
unsigned shiftParam
Detailed Description
Definition at line 972 of file VectorToAIEVecConversions.cpp.
Constructor & Destructor Documentation
ConvertMulIToAIEVecMulElemOpPattern()
ConvertMulIToAIEVecMulElemOpPattern::ConvertMulIToAIEVecMulElemOpPattern (MLIRContext * context, unsigned shiftParam = 0) inline
Definition at line 976 of file VectorToAIEVecConversions.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult ConvertMulIToAIEVecMulElemOpPattern::matchAndRewrite (arith::MulIOp mulOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 981 of file VectorToAIEVecConversions.cpp.
References xilinx::aievec::createVectorType(), xilinx::aievec::getVectorLaneSize(), xilinx::aievec::getVectorOpDestType(), and shiftParam.
Member Data Documentation
shiftParam
unsigned ConvertMulIToAIEVecMulElemOpPattern::shiftParam
Definition at line 1071 of file VectorToAIEVecConversions.cpp.
Referenced by matchAndRewrite().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEVec/Transforms/VectorToAIEVecConversions.cpp