MLIR-AIE: AIEAssignBufferAddressesPass Struct Reference
AIEAssignBufferAddressesPass Struct Reference
Public Member Functions
void getDependentDialects (DialectRegistry &registry) const override
void runOnOperation () override
Detailed Description
Definition at line 469 of file AIEAssignBuffers.cpp.
Member Function Documentation
getDependentDialects()
void AIEAssignBufferAddressesPass::getDependentDialects (DialectRegistry & registry) const inline override
Definition at line 472 of file AIEAssignBuffers.cpp.
runOnOperation()
void AIEAssignBufferAddressesPass::runOnOperation () inline override
Definition at line 477 of file AIEAssignBuffers.cpp.
References basicAllocation(), checkBufferScope(), and simpleBankAwareAllocation().
The documentation for this struct was generated from the following file:
lib/Dialect/AIE/Transforms/AIEAssignBuffers.cpp