MLIR-AIE: include/aie-c/TargetModel.h File Reference
TargetModel.h File Reference
#include "mlir-c/IR.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Functions
DEFINE_C_API_STRUCT (AieTargetModel, uint64_t)
MLIR_CAPI_EXPORTED AieTargetModel aieGetTargetModel (uint32_t device)
MLIR_CAPI_EXPORTED uint32_t aieGetTargetModelAddressGenGranularity (AieTargetModel targetModel)
Returns the data bus width for the target model.
MLIR_CAPI_EXPORTED int aieTargetModelColumns (AieTargetModel targetModel)
Returns the number of columns in the target model.
MLIR_CAPI_EXPORTED int aieTargetModelRows (AieTargetModel targetModel)
Returns the number of rows in the target model.
MLIR_CAPI_EXPORTED bool aieTargetModelIsNPU (AieTargetModel targetModel)
Returns true if this is an NPU target model.
MLIR_CAPI_EXPORTED bool aieTargetModelIsCoreTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimNOCTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimPLTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimNOCorPLTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsInternal (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED bool aieTargetModelIsLegalMemAffinity (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemSouthBaseAddress (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemNorthBaseAddress (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemEastBaseAddress (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemWestBaseAddress (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetLocalMemorySize (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumLocks (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumBDs (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumMemTileRows (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemTileSize (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumBanks (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMaxChannelNumForAdjacentTile (AieTargetModel targetModel, int col, int row)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumDestSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumSourceSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumDestShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumSourceShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetColumnShift (AieTargetModel targetModel)
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetRowShift (AieTargetModel targetModel)
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
  struct name {                                                                \
    storage d;                                                                 \
  };                                                                           \
  typedef struct name name
Definition at line 33 of file TargetModel.h.
Function Documentation
aieGetTargetModel()
MLIR_CAPI_EXPORTED AieTargetModel aieGetTargetModel (uint32_t device)
Definition at line 26 of file TargetModel.cpp.
References xilinx::AIE::getTargetModel().
aieGetTargetModelAddressGenGranularity()
MLIR_CAPI_EXPORTED uint32_t aieGetTargetModelAddressGenGranularity (AieTargetModel targetModel)
Returns the data bus width for the target model.
Definition at line 31 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getAddressGenGranularity().
aieTargetModelColumns()
MLIR_CAPI_EXPORTED int aieTargetModelColumns (AieTargetModel targetModel)
Returns the number of columns in the target model.
Definition at line 35 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::columns().
aieTargetModelGetColumnShift()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetColumnShift (AieTargetModel targetModel)
Definition at line 199 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getColumnShift().
aieTargetModelGetLocalMemorySize()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetLocalMemorySize (AieTargetModel targetModel)
Definition at line 131 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getLocalMemorySize().
aieTargetModelGetMaxChannelNumForAdjacentTile()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMaxChannelNumForAdjacentTile (AieTargetModel targetModel, int col, int row)
aieTargetModelGetMemEastBaseAddress()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemEastBaseAddress (AieTargetModel targetModel)
Definition at line 123 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemEastBaseAddress().
aieTargetModelGetMemNorthBaseAddress()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemNorthBaseAddress (AieTargetModel targetModel)
Definition at line 119 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemNorthBaseAddress().
aieTargetModelGetMemSouthBaseAddress()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemSouthBaseAddress (AieTargetModel targetModel)
Definition at line 115 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemSouthBaseAddress().
aieTargetModelGetMemTileSize()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemTileSize (AieTargetModel targetModel)
Definition at line 148 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemTileSize().
aieTargetModelGetMemWestBaseAddress()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetMemWestBaseAddress (AieTargetModel targetModel)
Definition at line 127 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemWestBaseAddress().
aieTargetModelGetNumBanks()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumBanks (AieTargetModel targetModel, int col, int row)
Definition at line 152 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumBanks().
aieTargetModelGetNumBDs()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumBDs (AieTargetModel targetModel, int col, int row)
Definition at line 140 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumBDs().
aieTargetModelGetNumDestShimMuxConnections()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumDestShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 179 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumDestShimMuxConnections().
aieTargetModelGetNumDestSwitchboxConnections()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumDestSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 163 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumDestSwitchboxConnections().
aieTargetModelGetNumLocks()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumLocks (AieTargetModel targetModel, int col, int row)
Definition at line 135 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumLocks().
aieTargetModelGetNumMemTileRows()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumMemTileRows (AieTargetModel targetModel)
Definition at line 144 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumMemTileRows().
aieTargetModelGetNumSourceShimMuxConnections()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumSourceShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 187 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumSourceShimMuxConnections().
aieTargetModelGetNumSourceSwitchboxConnections()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetNumSourceSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 171 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumSourceSwitchboxConnections().
aieTargetModelGetRowShift()
MLIR_CAPI_EXPORTED uint32_t aieTargetModelGetRowShift (AieTargetModel targetModel)
Definition at line 203 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getRowShift().
aieTargetModelIsCoreTile()
MLIR_CAPI_EXPORTED bool aieTargetModelIsCoreTile (AieTargetModel targetModel, int col, int row)
Definition at line 43 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isCoreTile().
aieTargetModelIsEast()
MLIR_CAPI_EXPORTED bool aieTargetModelIsEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 74 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isEast().
aieTargetModelIsInternal()
MLIR_CAPI_EXPORTED bool aieTargetModelIsInternal (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 64 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isInternal().
aieTargetModelIsLegalMemAffinity()
MLIR_CAPI_EXPORTED bool aieTargetModelIsLegalMemAffinity (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 109 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isLegalMemAffinity().
aieTargetModelIsMemEast()
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 94 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemEast().
aieTargetModelIsMemNorth()
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 99 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemNorth().
aieTargetModelIsMemSouth()
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 104 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemSouth().
aieTargetModelIsMemTile()
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemTile (AieTargetModel targetModel, int col, int row)
Definition at line 47 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemTile().
aieTargetModelIsMemWest()
MLIR_CAPI_EXPORTED bool aieTargetModelIsMemWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 89 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemWest().
aieTargetModelIsNorth()
MLIR_CAPI_EXPORTED bool aieTargetModelIsNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 79 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isNorth().
aieTargetModelIsNPU()
MLIR_CAPI_EXPORTED bool aieTargetModelIsNPU (AieTargetModel targetModel)
Returns true if this is an NPU target model.
Definition at line 195 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::hasProperty(), and xilinx::AIE::AIETargetModel::IsNPU.
aieTargetModelIsShimNOCorPLTile()
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimNOCorPLTile (AieTargetModel targetModel, int col, int row)
Definition at line 59 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimNOCorPLTile().
aieTargetModelIsShimNOCTile()
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimNOCTile (AieTargetModel targetModel, int col, int row)
Definition at line 51 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimNOCTile().
aieTargetModelIsShimPLTile()
MLIR_CAPI_EXPORTED bool aieTargetModelIsShimPLTile (AieTargetModel targetModel, int col, int row)
Definition at line 55 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimPLTile().
aieTargetModelIsSouth()
MLIR_CAPI_EXPORTED bool aieTargetModelIsSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 84 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isSouth().
aieTargetModelIsWest()
MLIR_CAPI_EXPORTED bool aieTargetModelIsWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 69 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isWest().
aieTargetModelRows()
MLIR_CAPI_EXPORTED int aieTargetModelRows (AieTargetModel targetModel)
Returns the number of rows in the target model.
Definition at line 39 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::rows().
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (AieTargetModel , uint64_t)