MLIR-AIE: lib/CAPI/TargetModel.cpp File Reference
TargetModel.cpp File Reference
#include "aie-c/TargetModel.h"
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIE/IR/AIETargetModel.h"
Functions
AieTargetModel aieGetTargetModel (uint32_t device)
uint32_t aieGetTargetModelAddressGenGranularity (AieTargetModel targetModel)
Returns the data bus width for the target model.
int aieTargetModelColumns (AieTargetModel targetModel)
Returns the number of columns in the target model.
int aieTargetModelRows (AieTargetModel targetModel)
Returns the number of rows in the target model.
bool aieTargetModelIsCoreTile (AieTargetModel targetModel, int col, int row)
bool aieTargetModelIsMemTile (AieTargetModel targetModel, int col, int row)
bool aieTargetModelIsShimNOCTile (AieTargetModel targetModel, int col, int row)
bool aieTargetModelIsShimPLTile (AieTargetModel targetModel, int col, int row)
bool aieTargetModelIsShimNOCorPLTile (AieTargetModel targetModel, int col, int row)
bool aieTargetModelIsInternal (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsMemWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsMemEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsMemNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsMemSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
bool aieTargetModelIsLegalMemAffinity (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
uint32_t aieTargetModelGetMemSouthBaseAddress (AieTargetModel targetModel)
uint32_t aieTargetModelGetMemNorthBaseAddress (AieTargetModel targetModel)
uint32_t aieTargetModelGetMemEastBaseAddress (AieTargetModel targetModel)
uint32_t aieTargetModelGetMemWestBaseAddress (AieTargetModel targetModel)
uint32_t aieTargetModelGetLocalMemorySize (AieTargetModel targetModel)
uint32_t aieTargetModelGetNumLocks (AieTargetModel targetModel, int col, int row)
uint32_t aieTargetModelGetNumBDs (AieTargetModel targetModel, int col, int row)
uint32_t aieTargetModelGetNumMemTileRows (AieTargetModel targetModel)
uint32_t aieTargetModelGetMemTileSize (AieTargetModel targetModel)
uint32_t aieTargetModelGetNumBanks (AieTargetModel targetModel, int col, int row)
uint32_t aieTargetModelGetMaxChannelNumForAdjacentMemTile (AieTargetModel targetModel, int col, int row)
uint32_t aieTargetModelGetNumDestSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
uint32_t aieTargetModelGetNumSourceSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
uint32_t aieTargetModelGetNumDestShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
uint32_t aieTargetModelGetNumSourceShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
bool aieTargetModelIsNPU (AieTargetModel targetModel)
Returns true if this is an NPU target model.
uint32_t aieTargetModelGetColumnShift (AieTargetModel targetModel)
uint32_t aieTargetModelGetRowShift (AieTargetModel targetModel)
Function Documentation
aieGetTargetModel()
AieTargetModel aieGetTargetModel (uint32_t device)
Definition at line 26 of file TargetModel.cpp.
References xilinx::AIE::getTargetModel().
aieGetTargetModelAddressGenGranularity()
uint32_t aieGetTargetModelAddressGenGranularity (AieTargetModel targetModel)
Returns the data bus width for the target model.
Definition at line 31 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getAddressGenGranularity().
aieTargetModelColumns()
int aieTargetModelColumns (AieTargetModel targetModel)
Returns the number of columns in the target model.
Definition at line 35 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::columns().
aieTargetModelGetColumnShift()
uint32_t aieTargetModelGetColumnShift (AieTargetModel targetModel)
Definition at line 199 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getColumnShift().
aieTargetModelGetLocalMemorySize()
uint32_t aieTargetModelGetLocalMemorySize (AieTargetModel targetModel)
Definition at line 131 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getLocalMemorySize().
aieTargetModelGetMaxChannelNumForAdjacentMemTile()
uint32_t aieTargetModelGetMaxChannelNumForAdjacentMemTile (AieTargetModel targetModel, int col, int row)
Definition at line 158 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMaxChannelNumForAdjacentMemTile().
aieTargetModelGetMemEastBaseAddress()
uint32_t aieTargetModelGetMemEastBaseAddress (AieTargetModel targetModel)
Definition at line 123 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemEastBaseAddress().
aieTargetModelGetMemNorthBaseAddress()
uint32_t aieTargetModelGetMemNorthBaseAddress (AieTargetModel targetModel)
Definition at line 119 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemNorthBaseAddress().
aieTargetModelGetMemSouthBaseAddress()
uint32_t aieTargetModelGetMemSouthBaseAddress (AieTargetModel targetModel)
Definition at line 115 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemSouthBaseAddress().
aieTargetModelGetMemTileSize()
uint32_t aieTargetModelGetMemTileSize (AieTargetModel targetModel)
Definition at line 148 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemTileSize().
aieTargetModelGetMemWestBaseAddress()
uint32_t aieTargetModelGetMemWestBaseAddress (AieTargetModel targetModel)
Definition at line 127 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getMemWestBaseAddress().
aieTargetModelGetNumBanks()
uint32_t aieTargetModelGetNumBanks (AieTargetModel targetModel, int col, int row)
Definition at line 152 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumBanks().
aieTargetModelGetNumBDs()
uint32_t aieTargetModelGetNumBDs (AieTargetModel targetModel, int col, int row)
Definition at line 140 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumBDs().
aieTargetModelGetNumDestShimMuxConnections()
uint32_t aieTargetModelGetNumDestShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 179 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumDestShimMuxConnections().
aieTargetModelGetNumDestSwitchboxConnections()
uint32_t aieTargetModelGetNumDestSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 163 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumDestSwitchboxConnections().
aieTargetModelGetNumLocks()
uint32_t aieTargetModelGetNumLocks (AieTargetModel targetModel, int col, int row)
Definition at line 135 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumLocks().
aieTargetModelGetNumMemTileRows()
uint32_t aieTargetModelGetNumMemTileRows (AieTargetModel targetModel)
Definition at line 144 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumMemTileRows().
aieTargetModelGetNumSourceShimMuxConnections()
uint32_t aieTargetModelGetNumSourceShimMuxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 187 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumSourceShimMuxConnections().
aieTargetModelGetNumSourceSwitchboxConnections()
uint32_t aieTargetModelGetNumSourceSwitchboxConnections (AieTargetModel targetModel, int col, int row, uint32_t bundle)
Definition at line 171 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getNumSourceSwitchboxConnections().
aieTargetModelGetRowShift()
uint32_t aieTargetModelGetRowShift (AieTargetModel targetModel)
Definition at line 203 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::getRowShift().
aieTargetModelIsCoreTile()
bool aieTargetModelIsCoreTile (AieTargetModel targetModel, int col, int row)
Definition at line 43 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isCoreTile().
aieTargetModelIsEast()
bool aieTargetModelIsEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 74 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isEast().
aieTargetModelIsInternal()
bool aieTargetModelIsInternal (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 64 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isInternal().
aieTargetModelIsLegalMemAffinity()
bool aieTargetModelIsLegalMemAffinity (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 109 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isLegalMemAffinity().
aieTargetModelIsMemEast()
bool aieTargetModelIsMemEast (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 94 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemEast().
aieTargetModelIsMemNorth()
bool aieTargetModelIsMemNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 99 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemNorth().
aieTargetModelIsMemSouth()
bool aieTargetModelIsMemSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 104 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemSouth().
aieTargetModelIsMemTile()
bool aieTargetModelIsMemTile (AieTargetModel targetModel, int col, int row)
Definition at line 47 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemTile().
aieTargetModelIsMemWest()
bool aieTargetModelIsMemWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 89 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isMemWest().
aieTargetModelIsNorth()
bool aieTargetModelIsNorth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 79 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isNorth().
aieTargetModelIsNPU()
bool aieTargetModelIsNPU (AieTargetModel targetModel)
Returns true if this is an NPU target model.
Definition at line 195 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::hasProperty(), and xilinx::AIE::AIETargetModel::IsNPU.
aieTargetModelIsShimNOCorPLTile()
bool aieTargetModelIsShimNOCorPLTile (AieTargetModel targetModel, int col, int row)
Definition at line 59 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimNOCorPLTile().
aieTargetModelIsShimNOCTile()
bool aieTargetModelIsShimNOCTile (AieTargetModel targetModel, int col, int row)
Definition at line 51 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimNOCTile().
aieTargetModelIsShimPLTile()
bool aieTargetModelIsShimPLTile (AieTargetModel targetModel, int col, int row)
Definition at line 55 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isShimPLTile().
aieTargetModelIsSouth()
bool aieTargetModelIsSouth (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 84 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isSouth().
aieTargetModelIsWest()
bool aieTargetModelIsWest (AieTargetModel targetModel, int src_col, int src_row, int dst_col, int dst_row)
Definition at line 69 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::isWest().
aieTargetModelRows()
int aieTargetModelRows (AieTargetModel targetModel)
Returns the number of rows in the target model.
Definition at line 39 of file TargetModel.cpp.
References xilinx::AIE::AIETargetModel::rows().