MLIR-AIE: include/aie-c/Translation.h File Reference
Translation.h File Reference
#include "aie-c/TargetModel.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Wrap.h"
Classes
struct AieRtControl
Typedefs
using AieRtControl = AieRtControl
Functions
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateAIEVecToCpp (MlirOperation op, bool aie2)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateModuleToLLVMIR (MlirOperation op)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateNpuToBinary (MlirOperation op, MlirStringRef deviceName, MlirStringRef sequenceName)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateControlPacketsToUI32Vec (MlirOperation op, MlirStringRef deviceName)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToXAIEV2 (MlirOperation op, MlirStringRef deviceName)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToHSA (MlirOperation op, MlirStringRef deviceName)
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToBCF (MlirOperation op, int col, int row, MlirStringRef deviceName)
MLIR_CAPI_EXPORTED MlirStringRef aieLLVMLink (MlirStringRef *modules, int nModules)
MLIR_CAPI_EXPORTED MlirLogicalResult aieTranslateToCDODirect (MlirOperation moduleOp, MlirStringRef workDirPath, MlirStringRef deviceName, bool bigEndian, bool emitUnified, bool cdoDebug, bool aieSim, bool xaieDebug, bool enableCores)
MLIR_CAPI_EXPORTED MlirOperation aieTranslateBinaryToTxn (MlirContext ctx, MlirStringRef binary)
MLIR_CAPI_EXPORTED AieRtControl getAieRtControl (AieTargetModel tm)
MLIR_CAPI_EXPORTED void freeAieRtControl (AieRtControl aieCtl)
MLIR_CAPI_EXPORTED void aieRtStartTransaction (AieRtControl aieCtl)
MLIR_CAPI_EXPORTED void aieRtDmaUpdateBdAddr (AieRtControl aieCtl, int col, int row, size_t addr, size_t bdId)
MLIR_CAPI_EXPORTED void aieRtExportSerializedTransaction (AieRtControl aieCtl)
Typedef Documentation
AieRtControl
using AieRtControl = AieRtControl
Definition at line 47 of file Translation.h.
Function Documentation
aieLLVMLink()
MLIR_CAPI_EXPORTED MlirStringRef aieLLVMLink (MlirStringRef * modules, int nModules)
Definition at line 165 of file Translation.cpp.
References xilinx::AIE::AIELLVMLink(), and xilinx::AIE::os.
aieRtDmaUpdateBdAddr()
MLIR_CAPI_EXPORTED void aieRtDmaUpdateBdAddr (AieRtControl aieCtl, int col, int row, size_t addr, size_t bdId)
Definition at line 194 of file Translation.cpp.
References xilinx::AIE::col, xilinx::AIE::AIERTControl::dmaUpdateBdAddr(), and xilinx::AIE::row.
aieRtExportSerializedTransaction()
MLIR_CAPI_EXPORTED void aieRtExportSerializedTransaction (AieRtControl aieCtl)
Definition at line 205 of file Translation.cpp.
References xilinx::AIE::AIERTControl::exportSerializedTransaction().
aieRtStartTransaction()
MLIR_CAPI_EXPORTED void aieRtStartTransaction (AieRtControl aieCtl)
Definition at line 200 of file Translation.cpp.
References xilinx::AIE::AIERTControl::startTransaction().
aieTranslateAIEVecToCpp()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateAIEVecToCpp (MlirOperation op, bool aie2)
Definition at line 41 of file Translation.cpp.
References xilinx::AIE::os, and xilinx::aievec::translateAIEVecToCpp().
aieTranslateBinaryToTxn()
MLIR_CAPI_EXPORTED MlirOperation aieTranslateBinaryToTxn (MlirContext ctx, MlirStringRef binary)
Definition at line 89 of file Translation.cpp.
References xilinx::AIE::convertTransactionBinaryToMLIR().
aieTranslateControlPacketsToUI32Vec()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateControlPacketsToUI32Vec (MlirOperation op, MlirStringRef deviceName)
Definition at line 112 of file Translation.cpp.
References xilinx::AIE::AIETranslateControlPacketsToUI32Vec().
aieTranslateModuleToLLVMIR()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateModuleToLLVMIR (MlirOperation op)
Definition at line 52 of file Translation.cpp.
References xilinx::AIE::os.
aieTranslateNpuToBinary()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateNpuToBinary (MlirOperation op, MlirStringRef deviceName, MlirStringRef sequenceName)
Definition at line 97 of file Translation.cpp.
References xilinx::AIE::AIETranslateNpuToBinary().
aieTranslateToBCF()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToBCF (MlirOperation op, int col, int row, MlirStringRef deviceName)
Definition at line 151 of file Translation.cpp.
References xilinx::AIE::AIETranslateToBCF(), xilinx::AIE::col, xilinx::AIE::os, and xilinx::AIE::row.
aieTranslateToCDODirect()
MLIR_CAPI_EXPORTED MlirLogicalResult aieTranslateToCDODirect (MlirOperation moduleOp, MlirStringRef workDirPath, MlirStringRef deviceName, bool bigEndian, bool emitUnified, bool cdoDebug, bool aieSim, bool xaieDebug, bool enableCores)
Definition at line 66 of file Translation.cpp.
References xilinx::AIE::AIETranslateToCDODirect().
aieTranslateToHSA()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToHSA (MlirOperation op, MlirStringRef deviceName)
Definition at line 138 of file Translation.cpp.
References xilinx::AIE::AIETranslateToHSA(), and xilinx::AIE::os.
aieTranslateToXAIEV2()
MLIR_CAPI_EXPORTED MlirStringRef aieTranslateToXAIEV2 (MlirOperation op, MlirStringRef deviceName)
Definition at line 125 of file Translation.cpp.
References xilinx::AIE::AIETranslateToXAIEV2(), and xilinx::AIE::os.
freeAieRtControl()
MLIR_CAPI_EXPORTED void freeAieRtControl (AieRtControl aieCtl)
Definition at line 189 of file Translation.cpp.
getAieRtControl()
MLIR_CAPI_EXPORTED AieRtControl getAieRtControl (AieTargetModel tm)
Definition at line 181 of file Translation.cpp.