MLIR-AIE: lib/CAPI/Translation.cpp File Reference
Translation.cpp File Reference
#include "aie-c/Translation.h"
#include "aie/Conversion/AIEToConfiguration/AIEToConfiguration.h"
#include "aie/Dialect/AIE/IR/AIETargetModel.h"
#include "aie/Targets/AIERT.h"
#include "aie/Targets/AIETargets.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/LLVMIR/Export.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
Functions
MlirStringRef aieTranslateAIEVecToCpp (MlirOperation moduleOp, bool aie2)
MlirStringRef aieTranslateModuleToLLVMIR (MlirOperation moduleOp)
MlirLogicalResult aieTranslateToCDODirect (MlirOperation moduleOp, MlirStringRef workDirPath, MlirStringRef deviceName, bool bigEndian, bool emitUnified, bool cdoDebug, bool aieSim, bool xaieDebug, bool enableCores)
MlirOperation aieTranslateBinaryToTxn (MlirContext ctx, MlirStringRef binary)
MlirStringRef aieTranslateNpuToBinary (MlirOperation moduleOp, MlirStringRef deviceNameMlir, MlirStringRef sequenceNameMlir)
MlirStringRef aieTranslateControlPacketsToUI32Vec (MlirOperation moduleOp, MlirStringRef deviceName)
MlirStringRef aieTranslateToXAIEV2 (MlirOperation moduleOp, MlirStringRef deviceName)
MlirStringRef aieTranslateToHSA (MlirOperation moduleOp, MlirStringRef deviceName)
MlirStringRef aieTranslateToBCF (MlirOperation moduleOp, int col, int row, MlirStringRef deviceName)
MlirStringRef aieLLVMLink (MlirStringRef *modules, int nModules)
AieRtControl getAieRtControl (AieTargetModel tm)
void freeAieRtControl (AieRtControl aieCtl)
void aieRtDmaUpdateBdAddr (AieRtControl aieCtl, int col, int row, size_t addr, size_t bdId)
void aieRtStartTransaction (AieRtControl aieCtl)
void aieRtExportSerializedTransaction (AieRtControl aieCtl)
Function Documentation
aieLLVMLink()
MlirStringRef aieLLVMLink (MlirStringRef * modules, int nModules)
Definition at line 165 of file Translation.cpp.
References xilinx::AIE::AIELLVMLink(), and xilinx::AIE::os.
aieRtDmaUpdateBdAddr()
void aieRtDmaUpdateBdAddr (AieRtControl aieCtl, int col, int row, size_t addr, size_t bdId)
Definition at line 194 of file Translation.cpp.
References xilinx::AIE::col, xilinx::AIE::AIERTControl::dmaUpdateBdAddr(), and xilinx::AIE::row.
aieRtExportSerializedTransaction()
void aieRtExportSerializedTransaction (AieRtControl aieCtl)
Definition at line 205 of file Translation.cpp.
References xilinx::AIE::AIERTControl::exportSerializedTransaction().
aieRtStartTransaction()
void aieRtStartTransaction (AieRtControl aieCtl)
Definition at line 200 of file Translation.cpp.
References xilinx::AIE::AIERTControl::startTransaction().
aieTranslateAIEVecToCpp()
MlirStringRef aieTranslateAIEVecToCpp (MlirOperation moduleOp, bool aie2)
Definition at line 41 of file Translation.cpp.
References xilinx::AIE::os, and xilinx::aievec::translateAIEVecToCpp().
aieTranslateBinaryToTxn()
MlirOperation aieTranslateBinaryToTxn (MlirContext ctx, MlirStringRef binary)
Definition at line 89 of file Translation.cpp.
References xilinx::AIE::convertTransactionBinaryToMLIR().
aieTranslateControlPacketsToUI32Vec()
MlirStringRef aieTranslateControlPacketsToUI32Vec (MlirOperation moduleOp, MlirStringRef deviceName)
Definition at line 112 of file Translation.cpp.
References xilinx::AIE::AIETranslateControlPacketsToUI32Vec().
aieTranslateModuleToLLVMIR()
MlirStringRef aieTranslateModuleToLLVMIR (MlirOperation moduleOp)
Definition at line 52 of file Translation.cpp.
References xilinx::AIE::os.
aieTranslateNpuToBinary()
MlirStringRef aieTranslateNpuToBinary (MlirOperation moduleOp, MlirStringRef deviceNameMlir, MlirStringRef sequenceNameMlir)
Definition at line 97 of file Translation.cpp.
References xilinx::AIE::AIETranslateNpuToBinary().
aieTranslateToBCF()
MlirStringRef aieTranslateToBCF (MlirOperation moduleOp, int col, int row, MlirStringRef deviceName)
Definition at line 151 of file Translation.cpp.
References xilinx::AIE::AIETranslateToBCF(), xilinx::AIE::col, xilinx::AIE::os, and xilinx::AIE::row.
aieTranslateToCDODirect()
MlirLogicalResult aieTranslateToCDODirect (MlirOperation moduleOp, MlirStringRef workDirPath, MlirStringRef deviceName, bool bigEndian, bool emitUnified, bool cdoDebug, bool aieSim, bool xaieDebug, bool enableCores)
Definition at line 66 of file Translation.cpp.
References xilinx::AIE::AIETranslateToCDODirect().
aieTranslateToHSA()
MlirStringRef aieTranslateToHSA (MlirOperation moduleOp, MlirStringRef deviceName)
Definition at line 138 of file Translation.cpp.
References xilinx::AIE::AIETranslateToHSA(), and xilinx::AIE::os.
aieTranslateToXAIEV2()
MlirStringRef aieTranslateToXAIEV2 (MlirOperation moduleOp, MlirStringRef deviceName)
Definition at line 125 of file Translation.cpp.
References xilinx::AIE::AIETranslateToXAIEV2(), and xilinx::AIE::os.
freeAieRtControl()
void freeAieRtControl (AieRtControl aieCtl)
Definition at line 189 of file Translation.cpp.
getAieRtControl()
AieRtControl getAieRtControl (AieTargetModel tm)
Definition at line 181 of file Translation.cpp.