MLIR-AIE: lib/Targets/AIEVecToCpp/TranslateAIEVecToCpp.cpp File Reference
TranslateAIEVecToCpp.cpp File Reference
#include "aie/Targets/AIETargets.h"
#include "aie/Dialect/AIE/IR/AIEDialect.h"
#include "aie/Dialect/AIEVec/AIE1/IR/AIEVecAIE1Ops.h"
#include "aie/Dialect/AIEVec/AIEVecUtils.h"
#include "aie/Dialect/AIEVec/IR/AIEVecOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Index/IR/IndexOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/IndentedOstream.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include <limits>
#include <numeric>
#include <optional>
#include <sstream>
#include <stack>
Macros
#define DEBUG_TYPE "aievec-to-cpp"
Functions
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Convenience functions to produce interleaved output with functions returning a LogicalResult.
template<typename Container , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (const Container &c, UnaryFunctor eachFn, NullaryFunctor betweenFn)
template<typename Container , typename UnaryFunctor >
LogicalResult interleaveCommaWithError (const Container &c, raw_ostream &os, UnaryFunctor eachFn)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aievec-to-cpp"
Definition at line 49 of file TranslateAIEVecToCpp.cpp.
Function Documentation
interleaveCommaWithError()
template<typename Container , typename UnaryFunctor > LogicalResult interleaveCommaWithError (const Container & c, raw_ostream & os, UnaryFunctor eachFn)
Definition at line 84 of file TranslateAIEVecToCpp.cpp.
References interleaveWithError().
interleaveWithError() [1/2]
template<typename Container , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (const Container & c, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Definition at line 78 of file TranslateAIEVecToCpp.cpp.
References interleaveWithError().
interleaveWithError() [2/2]
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Convenience functions to produce interleaved output with functions returning a LogicalResult.
This is different than those in STLExtras as functions used on each element doesn't return a string.
Definition at line 61 of file TranslateAIEVecToCpp.cpp.
Referenced by interleaveCommaWithError(), and interleaveWithError().