MLIR-AIE: runtime_lib/test_lib/xrt_test_wrapper.h File Reference
xrt_test_wrapper.h File Reference
#include "cxxopts.hpp"
#include "test_utils.h"
#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_hw_context.h"
#include "xrt/xrt_kernel.h"
#include <fstream>
#include <iostream>
#include <sstream>
Classes
struct args
Functions
struct args parse_args (int argc, const char *argv[])
uint32_t getParity (uint32_t n)
uint32_t create_ctrl_pkt (int operation, int beats, int addr, int ctrl_pkt_read_id=28)
template<typename T1 , typename T2 , typename T3 , void(*)(T1 *, int) init_bufIn1, void(*)(T2 *, int) init_bufIn2, void(*)(T3 *, int) init_bufOut, int(*)(T1 *, T2 *, T3 *, int, int) verify_results>
int setup_and_run_aie (int IN1_VOLUME, int IN2_VOLUME, int OUT_VOLUME, struct args myargs, bool enable_ctrl_pkts=false)
template<typename T1 , typename T3 , void(*)(T1 *, int) init_bufIn1, void(*)(T3 *, int) init_bufOut, int(*)(T1 *, T3 *, int, int) verify_results>
int setup_and_run_aie (int IN1_VOLUME, int OUT_VOLUME, struct args myargs, bool enable_ctrl_pkts=false)
Function Documentation
create_ctrl_pkt()
uint32_t create_ctrl_pkt (int operation, int beats, int addr, int ctrl_pkt_read_id = 28)
Definition at line 60 of file xrt_test_wrapper.h.
References getParity().
Referenced by setup_and_run_aie(), and setup_and_run_aie().
getParity()
uint32_t getParity (uint32_t n)
Definition at line 49 of file xrt_test_wrapper.h.
Referenced by create_ctrl_pkt().
parse_args()
struct args parse_args (int argc, const char * argv[])
Definition at line 25 of file xrt_test_wrapper.h.
References test_utils::add_default_options(), args::do_verify, args::instr, args::kernel, args::n_iterations, args::n_warmup_iterations, test_utils::parse_options(), args::trace_file, args::trace_size, args::verbosity, and args::xclbin.
setup_and_run_aie() [1/2]
template<typename T1 , typename T2 , typename T3 , void(*)(T1 *, int) init_bufIn1, void(*)(T2 *, int) init_bufIn2, void(*)(T3 *, int) init_bufOut, int(*)(T1 *, T2 *, T3 *, int, int) verify_results> int setup_and_run_aie (int IN1_VOLUME, int IN2_VOLUME, int OUT_VOLUME, struct args myargs, bool enable_ctrl_pkts = false)
Definition at line 77 of file xrt_test_wrapper.h.
References create_ctrl_pkt(), args::do_verify, test_utils::init_xrt_load_kernel(), args::instr, args::kernel, test_utils::load_instr_binary(), args::n_iterations, args::n_warmup_iterations, args::trace_file, args::trace_size, args::verbosity, test_utils::write_out_trace(), and args::xclbin.
setup_and_run_aie() [2/2]
template<typename T1 , typename T3 , void(*)(T1 *, int) init_bufIn1, void(*)(T3 *, int) init_bufOut, int(*)(T1 *, T3 *, int, int) verify_results> int setup_and_run_aie (int IN1_VOLUME, int OUT_VOLUME, struct args myargs, bool enable_ctrl_pkts = false)
Definition at line 296 of file xrt_test_wrapper.h.
References create_ctrl_pkt(), args::do_verify, test_utils::init_xrt_load_kernel(), args::instr, args::kernel, test_utils::load_instr_binary(), args::n_iterations, args::n_warmup_iterations, args::trace_file, args::trace_size, args::verbosity, test_utils::write_out_trace(), and args::xclbin.