# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Dummy overlay kernels of an exact size.

Two properties the tests need and real kernels cannot give:

*Exact size.* Padding is emitted as `SEL` blocks -- the idiom from
../../pm_write_while_running/ovl.cc -- each of which Peano compiles to exactly
32 branch-free bytes. `retain` (SHF_GNU_RETAIN) keeps them alive through the
overlay link's --gc-sections. So any size on a 32-byte grid is reachable, which
is what lets a test sit exactly on the slot boundary rather than near it.

*Distinct by construction.* Each overlay adds its own tag to every element, so
"the swap actually changed what ran" is guaranteed rather than checked. A
workload whose output happens to be constant makes a distinctness check vacuous,
and that is not hypothetical: an earlier version of this suite had two layers
emitting all-zero rows that compared equal to everything.

Note what the kernel does *not* do: a scalar byte-store loop. The pinned Peano
miscompiles those, dropping the last store of each unrolled iteration so three
bytes in four are written, silently. int32 stores are unaffected. See
../peano_scalar_store_canary.
"""

import os
import subprocess
import sys

from .elf import peano, text_size

SEL_BLOCK_BYTES = 32

# Kept out of any f-string or .format(): the macro body is mostly braces, and
# escaping them all is a good way to introduce a typo into every generated file.
_PRELUDE = """\
// Generated by pmlib/workload.py. Do not edit.
#include <cstdint>

// Exactly 32 branch-free bytes each, retained against --gc-sections. `weak`
// stops the caller constant-propagating the stored value; `noinline` alone
// does not.
#define SEL(name, val)                                                         \\
  extern "C" __attribute__((noinline, used, retain, weak)) void name(          \\
      int32_t *out) {                                                          \\
    *out = val;                                                                \\
  }
"""


def source(tag, n_elems, pad_blocks, entry="overlay_entry"):
    """C++ for one dummy overlay: adds `tag` to every element, padded to size."""
    padding = "\n".join(f"SEL(pad_{tag}_{i}, {i})" for i in range(pad_blocks))
    body = (
        "// int32 stores, deliberately: a byte loop here would be miscompiled.\n"
        f'extern "C" void {entry}(int32_t *in, int32_t *out) {{\n'
        f"  for (int i = 0; i < {n_elems}; i++)\n"
        f"    out[i] = in[i] + {tag};\n"
        "}\n"
    )
    return f"{_PRELUDE}\n{padding}\n\n{body}"


def compile_overlay(
    tag,
    n_elems,
    out_o,
    target="aie2p-none-unknown-elf",
    pad_blocks=0,
    workdir=".",
    entry="overlay_entry",
):
    """Compile one dummy overlay object, returning its .text size."""
    src = os.path.join(workdir, f"dummy_{tag}.cc")
    with open(src, "w") as f:
        f.write(source(tag, n_elems, pad_blocks, entry))
    cmd = [
        peano("clang++"),
        f"--target={target}",
        "-O2",
        "-std=c++20",
        # So iron.overlay's stack-budget guard (which needs .stack_sizes on
        # every overlay it checks) has something to read -- see
        # test/npu-xrt/program_memory_overlay/nohw/stack_budget.lit.
        "-fstack-size-section",
        "-c",
        src,
        "-o",
        out_o,
    ]
    if subprocess.run(cmd).returncode:
        sys.exit(f"compiling dummy overlay {tag} failed")
    return text_size(out_o)


def compile_overlay_of_size(tag, n_elems, out_o, want_bytes, **kw):
    """Compile a dummy overlay whose .text is exactly `want_bytes`.

    Measures the unpadded kernel, then pads the difference. The size is exact
    rather than approximate because every pad block is exactly 32 bytes -- and
    the residual is reported rather than rounded away, so a test asking for a
    size off the grid is told, not silently given something else.
    """
    base = compile_overlay(tag, n_elems, out_o, pad_blocks=0, **kw)
    if want_bytes is None:
        return base
    if want_bytes < base:
        sys.exit(
            f"overlay {tag}: asked for {want_bytes} bytes but the kernel alone is "
            f"{base}; padding cannot make an overlay smaller"
        )
    extra = want_bytes - base
    if extra % SEL_BLOCK_BYTES:
        sys.exit(
            f"overlay {tag}: {want_bytes} bytes is not reachable. The kernel is "
            f"{base} bytes and padding comes in {SEL_BLOCK_BYTES}-byte blocks, so "
            f"the nearest are {base + (extra // SEL_BLOCK_BYTES) * SEL_BLOCK_BYTES} "
            f"and {base + (extra // SEL_BLOCK_BYTES + 1) * SEL_BLOCK_BYTES}"
        )
    got = compile_overlay(
        tag, n_elems, out_o, pad_blocks=extra // SEL_BLOCK_BYTES, **kw
    )
    if got != want_bytes:
        sys.exit(
            f"overlay {tag}: wanted {want_bytes} bytes, got {got}. The padding "
            f"idiom is no longer emitting {SEL_BLOCK_BYTES} bytes per block."
        )
    return got
