MLIR-AIE: hrx_test::Context Class Reference
hrx_test::Context Class Reference
#include "/home/runner/work/mlir-aie/mlir-aie/runtime_lib/test_lib/hrx_test_wrapper.h"
Static Public Member Functions
static Context & get ()
Public Attributes
hrx_device_t device = nullptr
hrx_stream_t stream = nullptr
Detailed Description
Definition at line 78 of file hrx_test_wrapper.h.
Member Function Documentation
get()
static Context & hrx_test::Context::get () inline static
Definition at line 80 of file hrx_test_wrapper.h.
Referenced by hrx_test::dispatch_chain(), hrx_test::dispatch_once(), and hrx_test::load_kernel().
Member Data Documentation
device
hrx_device_t hrx_test::Context::device = nullptr
Definition at line 85 of file hrx_test_wrapper.h.
Referenced by hrx_test::load_kernel().
stream
hrx_stream_t hrx_test::Context::stream = nullptr
Definition at line 86 of file hrx_test_wrapper.h.
Referenced by hrx_test::dispatch_chain(), hrx_test::dispatch_once(), setup_and_run_aie(), setup_and_run_aie(), and setup_and_run_aie().
The documentation for this class was generated from the following file:
runtime_lib/test_lib/hrx_test_wrapper.h