MLIR-AIE: hrx_test::Buffer Class Reference
hrx_test::Buffer Class Reference
#include "/home/runner/work/mlir-aie/mlir-aie/runtime_lib/test_lib/hrx_test_wrapper.h"
Public Member Functions
Buffer (hrx_stream_t stream, size_t nbytes)
~Buffer ()
Buffer (const Buffer &)=delete
Buffer & operator= (const Buffer &)=delete
void flush ()
void invalidate ()
hrx_buffer_t handle () const
void * host_ptr () const
size_t nbytes () const
Detailed Description
Definition at line 100 of file hrx_test_wrapper.h.
Constructor & Destructor Documentation
Buffer() [1/2]
hrx_test::Buffer::Buffer (hrx_stream_t stream, size_t nbytes) inline
Definition at line 102 of file hrx_test_wrapper.h.
References hrx_test::hrx_check(), and nbytes().
~Buffer()
hrx_test::Buffer::~Buffer () inline
Definition at line 119 of file hrx_test_wrapper.h.
Buffer() [2/2]
hrx_test::Buffer::Buffer (const Buffer &) delete
Member Function Documentation
flush()
void hrx_test::Buffer::flush () inline
Definition at line 127 of file hrx_test_wrapper.h.
References hrx_test::hrx_check().
Referenced by setup_and_run_aie(), setup_and_run_aie(), and setup_and_run_aie().
handle()
hrx_buffer_t hrx_test::Buffer::handle () const inline
Definition at line 138 of file hrx_test_wrapper.h.
host_ptr()
void * hrx_test::Buffer::host_ptr () const inline
Definition at line 139 of file hrx_test_wrapper.h.
Referenced by setup_and_run_aie(), setup_and_run_aie(), and setup_and_run_aie().
invalidate()
void hrx_test::Buffer::invalidate () inline
Definition at line 132 of file hrx_test_wrapper.h.
References hrx_test::hrx_check().
Referenced by setup_and_run_aie(), setup_and_run_aie(), and setup_and_run_aie().
nbytes()
size_t hrx_test::Buffer::nbytes () const inline
Definition at line 140 of file hrx_test_wrapper.h.
Referenced by Buffer().
operator=()
Buffer & hrx_test::Buffer::operator= (const Buffer &) delete
The documentation for this class was generated from the following file:
runtime_lib/test_lib/hrx_test_wrapper.h