MLIR-AIE: hrx_test Namespace Reference
hrx_test Namespace Reference
Classes
class Buffer
struct ChainRun
class Context
struct LoadedKernel
Functions
void hrx_check (hrx_status_t status, const char *what)
std::vector< uint8_t > control_code_from_elf (const std::vector< uint8_t > &d)
std::vector< uint8_t > read_transaction (const std::string &insts_path)
LoadedKernel load_kernel (const std::string &xclbin_path, const std::string &insts_path, const std::string &kernel_name)
double dispatch_once (const LoadedKernel &lk, const std::vector< Buffer * > &bindings)
double dispatch_chain (const std::vector< ChainRun > &runs)
void reject_unsupported_features (int trace_size, bool enable_ctrl_pkts)
void report_timing (double total, double mn, double mx, int n_iters)
Function Documentation
control_code_from_elf()
std::vector< uint8_t > hrx_test::control_code_from_elf (const std::vector< uint8_t > & d) inline
Definition at line 153 of file hrx_test_wrapper.h.
Referenced by read_transaction().
dispatch_chain()
double hrx_test::dispatch_chain (const std::vector< ChainRun > & runs) inline
Definition at line 333 of file hrx_test_wrapper.h.
References hrx_test::Context::get(), hrx_check(), and hrx_test::Context::stream.
dispatch_once()
double hrx_test::dispatch_once (const LoadedKernel & lk, const std::vector< Buffer * > & bindings) inline
Definition at line 292 of file hrx_test_wrapper.h.
References hrx_test::LoadedKernel::exe, hrx_test::Context::get(), hrx_check(), hrx_test::LoadedKernel::ordinal, and hrx_test::Context::stream.
hrx_check()
void hrx_test::hrx_check (hrx_status_t status, const char * what) inline
Definition at line 59 of file hrx_test_wrapper.h.
Referenced by hrx_test::Buffer::Buffer(), dispatch_chain(), dispatch_once(), hrx_test::Buffer::flush(), hrx_test::Buffer::invalidate(), and load_kernel().
load_kernel()
LoadedKernel hrx_test::load_kernel (const std::string & xclbin_path, const std::string & insts_path, const std::string & kernel_name) inline
Definition at line 225 of file hrx_test_wrapper.h.
References hrx_test::Context::device, hrx_test::LoadedKernel::exe, hrx_test::Context::get(), hrx_check(), hrx_test::LoadedKernel::ordinal, and read_transaction().
read_transaction()
std::vector< uint8_t > hrx_test::read_transaction (const std::string & insts_path) inline
Definition at line 204 of file hrx_test_wrapper.h.
References control_code_from_elf().
Referenced by load_kernel().
reject_unsupported_features()
void hrx_test::reject_unsupported_features (int trace_size, bool enable_ctrl_pkts) inline
Definition at line 367 of file hrx_test_wrapper.h.
report_timing()
void hrx_test::report_timing (double total, double mn, double mx, int n_iters) inline
Definition at line 380 of file hrx_test_wrapper.h.