MLIR-AIE: AIEDMATasksToNPUPass Struct Reference
AIEDMATasksToNPUPass Struct Reference
Classes
struct BdTemplateFields
Public Member Functions
bool shouldSkipBlock (Block &block)
LogicalResult verifyBdInBlock (Block &block, bool hasRuntimeBdId=false)
LogicalResult verifyOptionalLocksInBlock (Block &block)
LogicalResult verifyNoUnsupportedOpsInBlock (Block &block)
AIE::DMABDOp getBdForBlock (Block &block)
std::optional< std::pair< AIE::UseLockOp, AIE::UseLockOp > > getOptionalLockOpsForBlock (Block &block)
LogicalResult setAddressForSingleBD (OpBuilder &builder, AIE::DMABDOp &bd_op, AIE::TileOp &tile, OpFoldResult bdId={})
FailureOr< BdTemplateFields > gatherBdTemplateFields (Block &block, AIE::DMABDOp bd_op, AIE::TileOp &tile, const AIE::AIETargetModel &target_model, std::optional< xilinx::AIE::PacketInfoAttr > packet)
LogicalResult rewriteSingleBDDynamic (OpBuilder &builder, Block &block, AIE::DMABDOp bd_op, AIE::TileOp &tile, std::optional< xilinx::AIE::PacketInfoAttr > packet, Value runtimeBdId=nullptr)
LogicalResult emitShimTemplateWordOverrides (OpBuilder &builder, Location loc, const AIE::AIETargetModel &target_model, int col, int row, OpFoldResult bdId, const BdTemplateFields &f, uint32_t burstLength)
LogicalResult rewriteSingleBD (OpBuilder &builder, Block &block, AIE::TileOp &tile, AIE::DMAChannelDir channelDir, std::optional< xilinx::AIE::PacketInfoAttr > packet, Value runtimeBdId=nullptr)
LogicalResult hoistNextBdOpsIntoAttrs (DMAConfigureTaskOp op)
LogicalResult rewriteSingleDMAConfigureTaskOp (DMAConfigureTaskOp op)
LogicalResult rewriteDMAConfigureTaskOp (AIE::DeviceOp device)
LogicalResult dropDeadTaskCarries (AIE::DeviceOp device)
void runOnOperation () override
Detailed Description
Definition at line 147 of file AIEDMATasksToNPU.cpp.
Member Function Documentation
dropDeadTaskCarries()
LogicalResult AIEDMATasksToNPUPass::dropDeadTaskCarries (AIE::DeviceOp device) inline
Definition at line 1004 of file AIEDMATasksToNPU.cpp.
Referenced by runOnOperation().
emitShimTemplateWordOverrides()
LogicalResult AIEDMATasksToNPUPass::emitShimTemplateWordOverrides (OpBuilder & builder, Location loc, const AIE::AIETargetModel & target_model, int col, int row, OpFoldResult bdId, const BdTemplateFields & f, uint32_t burstLength) inline
Definition at line 596 of file AIEDMATasksToNPU.cpp.
References xilinx::AIEX::createConstantI32(), AIEDMATasksToNPUPass::BdTemplateFields::enable_packet, xilinx::AIEX::getBdRegisterBase(), xilinx::AIE::getShimBurstLengthEncoding(), AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_enable, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_val, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_val, AIEDMATasksToNPUPass::BdTemplateFields::next_bd_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_type, and AIEDMATasksToNPUPass::BdTemplateFields::use_next_bd.
Referenced by rewriteSingleBDDynamic().
gatherBdTemplateFields()
FailureOr< BdTemplateFields > AIEDMATasksToNPUPass::gatherBdTemplateFields (Block & block, AIE::DMABDOp bd_op, AIE::TileOp & tile, const AIE::AIETargetModel & target_model, std::optional< xilinx::AIE::PacketInfoAttr > packet) inline
Definition at line 428 of file AIEDMATasksToNPU.cpp.
References AIEDMATasksToNPUPass::BdTemplateFields::enable_packet, xilinx::AIE::AIETargetModel::getLockLocalBaseIndex(), getOptionalLockOpsForBlock(), xilinx::AIE::AIETargetModel::isMemTile(), AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_enable, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_val, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_val, AIEDMATasksToNPUPass::BdTemplateFields::next_bd_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_type, and AIEDMATasksToNPUPass::BdTemplateFields::use_next_bd.
Referenced by rewriteSingleBD(), and rewriteSingleBDDynamic().
getBdForBlock()
AIE::DMABDOp AIEDMATasksToNPUPass::getBdForBlock (Block & block) inline
Definition at line 240 of file AIEDMATasksToNPU.cpp.
Referenced by hoistNextBdOpsIntoAttrs(), and rewriteSingleBD().
getOptionalLockOpsForBlock()
std::optional< std::pair< AIE::UseLockOp, AIE::UseLockOp > > AIEDMATasksToNPUPass::getOptionalLockOpsForBlock (Block & block) inline
Definition at line 249 of file AIEDMATasksToNPU.cpp.
Referenced by gatherBdTemplateFields().
hoistNextBdOpsIntoAttrs()
LogicalResult AIEDMATasksToNPUPass::hoistNextBdOpsIntoAttrs (DMAConfigureTaskOp op) inline
Definition at line 887 of file AIEDMATasksToNPU.cpp.
References getBdForBlock(), and shouldSkipBlock().
Referenced by rewriteSingleDMAConfigureTaskOp().
rewriteDMAConfigureTaskOp()
LogicalResult AIEDMATasksToNPUPass::rewriteDMAConfigureTaskOp (AIE::DeviceOp device) inline
Definition at line 982 of file AIEDMATasksToNPU.cpp.
References rewriteSingleDMAConfigureTaskOp().
Referenced by runOnOperation().
rewriteSingleBD()
LogicalResult AIEDMATasksToNPUPass::rewriteSingleBD (OpBuilder & builder, Block & block, AIE::TileOp & tile, AIE::DMAChannelDir channelDir, std::optional< xilinx::AIE::PacketInfoAttr > packet, Value runtimeBdId = nullptr) inline
Definition at line 635 of file AIEDMATasksToNPU.cpp.
References AIEDMATasksToNPUPass::BdTemplateFields::enable_packet, gatherBdTemplateFields(), xilinx::AIE::AIETargetModel::getAddressGenGranularity(), getBdForBlock(), xilinx::AIEX::getHardwareStridesWraps(), xilinx::AIE::getTargetModel(), xilinx::AIEX::isContiguousTransfer(), xilinx::AIEX::isLinearTransfer(), xilinx::AIE::AIETargetModel::isMemTile(), xilinx::AIE::AIETargetModel::isShimNOCTile(), AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_enable, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_val, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_val, AIEDMATasksToNPUPass::BdTemplateFields::next_bd_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_type, rewriteSingleBDDynamic(), setAddressForSingleBD(), AIEDMATasksToNPUPass::BdTemplateFields::use_next_bd, xilinx::AIEX::verifyConstBdRealizability(), and xilinx::AIEX::verifyStridesWraps().
Referenced by rewriteSingleDMAConfigureTaskOp().
rewriteSingleBDDynamic()
LogicalResult AIEDMATasksToNPUPass::rewriteSingleBDDynamic (OpBuilder & builder, Block & block, AIE::DMABDOp bd_op, AIE::TileOp & tile, std::optional< xilinx::AIE::PacketInfoAttr > packet, Value runtimeBdId = nullptr) inline
Definition at line 493 of file AIEDMATasksToNPU.cpp.
References xilinx::AIEX::createConstantI32(), xilinx::AIEX::emitDynamicShimBdWordOverrides(), emitShimTemplateWordOverrides(), AIEDMATasksToNPUPass::BdTemplateFields::enable_packet, gatherBdTemplateFields(), xilinx::AIE::AIETargetModel::getAddressGenGranularity(), xilinx::AIEX::getAsValue(), xilinx::AIE::getTargetModel(), AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_enable, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_acq_val, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_id, AIEDMATasksToNPUPass::BdTemplateFields::lock_rel_val, AIEDMATasksToNPUPass::BdTemplateFields::next_bd_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_id, AIEDMATasksToNPUPass::BdTemplateFields::packet_type, setAddressForSingleBD(), and AIEDMATasksToNPUPass::BdTemplateFields::use_next_bd.
Referenced by rewriteSingleBD().
rewriteSingleDMAConfigureTaskOp()
LogicalResult AIEDMATasksToNPUPass::rewriteSingleDMAConfigureTaskOp (DMAConfigureTaskOp op) inline
Definition at line 921 of file AIEDMATasksToNPU.cpp.
References hoistNextBdOpsIntoAttrs(), rewriteSingleBD(), shouldSkipBlock(), verifyBdInBlock(), verifyNoUnsupportedOpsInBlock(), and verifyOptionalLocksInBlock().
Referenced by rewriteDMAConfigureTaskOp().
runOnOperation()
void AIEDMATasksToNPUPass::runOnOperation () inline override
Definition at line 1013 of file AIEDMATasksToNPU.cpp.
References dropDeadTaskCarries(), and rewriteDMAConfigureTaskOp().
setAddressForSingleBD()
LogicalResult AIEDMATasksToNPUPass::setAddressForSingleBD (OpBuilder & builder, AIE::DMABDOp & bd_op, AIE::TileOp & tile, OpFoldResult bdId = {}) inline
Definition at line 273 of file AIEDMATasksToNPU.cpp.
Referenced by rewriteSingleBD(), and rewriteSingleBDDynamic().
shouldSkipBlock()
bool AIEDMATasksToNPUPass::shouldSkipBlock (Block & block) inline
Definition at line 150 of file AIEDMATasksToNPU.cpp.
Referenced by hoistNextBdOpsIntoAttrs(), and rewriteSingleDMAConfigureTaskOp().
verifyBdInBlock()
LogicalResult AIEDMATasksToNPUPass::verifyBdInBlock (Block & block, bool hasRuntimeBdId = false) inline
Definition at line 158 of file AIEDMATasksToNPU.cpp.
Referenced by rewriteSingleDMAConfigureTaskOp().
verifyNoUnsupportedOpsInBlock()
LogicalResult AIEDMATasksToNPUPass::verifyNoUnsupportedOpsInBlock (Block & block) inline
Definition at line 212 of file AIEDMATasksToNPU.cpp.
Referenced by rewriteSingleDMAConfigureTaskOp().
verifyOptionalLocksInBlock()
LogicalResult AIEDMATasksToNPUPass::verifyOptionalLocksInBlock (Block & block) inline
Definition at line 197 of file AIEDMATasksToNPU.cpp.
Referenced by rewriteSingleDMAConfigureTaskOp().
The documentation for this struct was generated from the following file:
lib/Dialect/AIEX/Transforms/AIEDMATasksToNPU.cpp