MLIR-AIE: xilinx::AIEX::SsaStridePolicy Struct Reference
xilinx::AIEX::SsaStridePolicy Struct Reference
#include "aie/Dialect/AIEX/Utils/BdLowering.h"
Public Types
using V = mlir::Value
Public Member Functions
SsaStridePolicy (mlir::OpBuilder &b, mlir::Location l)
V cst (int64_t c) const
V mul (V v, int64_t c) const
V div (V v, int64_t c) const
V sub (V v, int64_t c) const
V selectGT1 (V cond, V t, V e) const
V selectGT0 (V cond, V t, V e) const
V selectLt (V a, V b, V t, V e) const
Public Attributes
mlir::OpBuilder & builder
mlir::Location loc
Detailed Description
Definition at line 202 of file BdLowering.h.
Member Typedef Documentation
V
using xilinx::AIEX::SsaStridePolicy::V = mlir::Value
Definition at line 203 of file BdLowering.h.
Constructor & Destructor Documentation
SsaStridePolicy()
xilinx::AIEX::SsaStridePolicy::SsaStridePolicy (mlir::OpBuilder & b, mlir::Location l) inline
Definition at line 207 of file BdLowering.h.
Member Function Documentation
cst()
Value xilinx::AIEX::SsaStridePolicy::cst (int64_t c) const
Definition at line 30 of file BdLowering.cpp.
References builder, and loc.
Referenced by div(), mul(), selectGT0(), selectGT1(), and sub().
div()
Value xilinx::AIEX::SsaStridePolicy::div (V v, int64_t c) const
Definition at line 39 of file BdLowering.cpp.
References builder, cst(), and loc.
mul()
Value xilinx::AIEX::SsaStridePolicy::mul (V v, int64_t c) const
Definition at line 35 of file BdLowering.cpp.
References builder, cst(), and loc.
selectGT0()
Value xilinx::AIEX::SsaStridePolicy::selectGT0 (V cond, V t, V e) const
Definition at line 57 of file BdLowering.cpp.
References builder, cst(), and loc.
selectGT1()
Value xilinx::AIEX::SsaStridePolicy::selectGT1 (V cond, V t, V e) const
Definition at line 50 of file BdLowering.cpp.
References builder, cst(), and loc.
selectLt()
Value xilinx::AIEX::SsaStridePolicy::selectLt (V a, V b, V t, V e) const
Definition at line 64 of file BdLowering.cpp.
References builder, and loc.
sub()
Value xilinx::AIEX::SsaStridePolicy::sub (V v, int64_t c) const
Definition at line 46 of file BdLowering.cpp.
References builder, cst(), and loc.
Member Data Documentation
builder
mlir::OpBuilder& xilinx::AIEX::SsaStridePolicy::builder
Definition at line 204 of file BdLowering.h.
Referenced by cst(), div(), mul(), selectGT0(), selectGT1(), selectLt(), and sub().
loc
mlir::Location xilinx::AIEX::SsaStridePolicy::loc
Definition at line 205 of file BdLowering.h.
Referenced by cst(), div(), mul(), selectGT0(), selectGT1(), selectLt(), and sub().
The documentation for this struct was generated from the following files:
include/aie/Dialect/AIEX/Utils/BdLowering.h
lib/Dialect/AIEX/Utils/BdLowering.cpp