MLIR-AIE: xilinx::AIEX::ShimBdFieldWidths Struct Reference
xilinx::AIEX::ShimBdFieldWidths Struct Reference
#include "aie/Dialect/AIEX/Utils/BdLowering.h"
Static Public Member Functions
static constexpr int64_t d0WrapMax ()
static constexpr int64_t d1WrapMax ()
static constexpr int64_t iterWrapMax ()
Static Public Attributes
static constexpr int64_t kD0WrapBits = 10
static constexpr int64_t kD1WrapBits = 10
static constexpr int64_t kIterWrapBits = 6
Detailed Description
Definition at line 43 of file BdLowering.h.
Member Function Documentation
d0WrapMax()
static constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::d0WrapMax () inline static constexpr
Definition at line 47 of file BdLowering.h.
References kD0WrapBits.
Referenced by xilinx::AIEX::emitDynamicShimBdWordOverrides().
d1WrapMax()
static constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::d1WrapMax () inline static constexpr
Definition at line 48 of file BdLowering.h.
References kD1WrapBits.
Referenced by xilinx::AIEX::emitDynamicShimBdWordOverrides().
iterWrapMax()
static constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::iterWrapMax () inline static constexpr
Definition at line 49 of file BdLowering.h.
References kIterWrapBits.
Referenced by xilinx::AIEX::emitDynamicShimBdWordOverrides().
Member Data Documentation
kD0WrapBits
constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::kD0WrapBits = 10 static constexpr
Definition at line 44 of file BdLowering.h.
Referenced by d0WrapMax().
kD1WrapBits
constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::kD1WrapBits = 10 static constexpr
Definition at line 45 of file BdLowering.h.
Referenced by d1WrapMax().
kIterWrapBits
constexpr int64_t xilinx::AIEX::ShimBdFieldWidths::kIterWrapBits = 6 static constexpr
Definition at line 46 of file BdLowering.h.
Referenced by iterWrapMax().
The documentation for this struct was generated from the following file:
include/aie/Dialect/AIEX/Utils/BdLowering.h