#!/usr/bin/env python3

# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Write the compiler-rt stack frames that aiecc's stack analysis falls back on.

Peano builds libclang_rt.builtins without -fstack-size-section, so a core that
calls `__divsf3` or `__modsi3` links functions with no `.stack_sizes` entry, and
aiecc can only bound its stack from below. This reads each builtin's frame from
its disassembly (the `[sp]` adjustment in its prologue) and prints entries for
the `fallbackFrames` table in tools/aiecc/StackSizeAnalysis.cpp.

test/aiecc/compiler_rt_stack_frames.test regenerates the table from the
installed Peano and fails when it differs. After a Peano bump, run:

    python utils/generate_compiler_rt_stack_frames.py \\
        > tools/aiecc/CompilerRtStackFrames.inc
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

# ELF e_flags of each target, as StackSizeAnalysis.cpp matches them.
ELF_FLAGS = {"aie2": 2, "aie2p": 3}

MEMBER_RE = re.compile(r"^\S+\(([^)]+)\):\s+file format")
SECTION_RE = re.compile(r"^Disassembly of section (\S+):")
FUNCTION_RE = re.compile(r"^([0-9a-f]+) <([^>]+)>:")
FUNCTION_SYMBOL_RE = re.compile(r"^([0-9a-f]+)\s+[gw]\s+F (\S+)\s+[0-9a-f]+ (\S+)$")
SP_ADJUST_RE = re.compile(r"\bpadd\w*\s+\[sp\],\s*#(-?(?:0x[0-9a-f]+|\d+))")
SP_WRITE_RE = re.compile(r"\b[a-z.]+\s+\[?sp\]?,")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--clang",
        default="clang",
        help="Peano clang; llvm-objdump is taken from its directory",
    )
    parser.add_argument(
        "--arch",
        action="append",
        choices=sorted(ELF_FLAGS),
        help="target to read (repeatable; default: all)",
    )
    args = parser.parse_args()

    clang = shutil.which(args.clang)
    if clang is None:
        sys.exit(f"error: {args.clang} not found")
    objdump = Path(clang).resolve().parent / "llvm-objdump"

    print(
        "// Copyright (C) 2026 Advanced Micro Devices, Inc.\n"
        "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception\n"
        "//\n"
        "// Generated by utils/generate_compiler_rt_stack_frames.py. Do not edit."
    )
    for arch in args.arch or sorted(ELF_FLAGS):
        library = subprocess.run(
            [
                clang,
                f"--target={arch}-none-unknown-elf",
                "-rtlib=compiler-rt",
                "--print-libgcc-file-name",
            ],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        disassembly, symbols = (
            subprocess.run(
                [str(objdump), flag, library],
                capture_output=True,
                text=True,
                check=True,
            ).stdout
            for flag in ("-d", "-t")
        )

        # Keyed by (archive member, section, address): the disassembly names
        # one symbol per address, and the symbol table adds its aliases.
        frames_at = {}
        member = section = start = None
        for line in disassembly.splitlines():
            if match := MEMBER_RE.match(line):
                member = match.group(1)
            elif match := SECTION_RE.match(line):
                section = match.group(1)
            elif match := FUNCTION_RE.match(line):
                # A local label is a block inside the function above it.
                if not match.group(2).startswith(".L"):
                    start = (member, section, int(match.group(1), 16))
                    frames_at[start] = 0
            elif start is not None and SP_WRITE_RE.search(line):
                # Only a constant adjustment has a frame this script can read.
                adjust = SP_ADJUST_RE.search(line)
                if adjust is None:
                    sys.exit(f"error: {arch} {start} writes sp: {line.strip()}")
                frames_at[start] = max(frames_at[start], int(adjust.group(1), 0))

        frames = {}
        for line in symbols.splitlines():
            if match := MEMBER_RE.match(line):
                member = match.group(1)
            elif match := FUNCTION_SYMBOL_RE.match(line):
                key = (member, match.group(2), int(match.group(1), 16))
                name = match.group(3)
                if key not in frames_at:
                    sys.exit(f"error: {arch} {name} was not disassembled")
                if frames.setdefault(name, frames_at[key]) != frames_at[key]:
                    sys.exit(f"error: {arch} defines {name} with two frame sizes")

        print(f"// {arch}: {Path(library).name}")
        for function, frame in sorted(frames.items()):
            print(f'{{{ELF_FLAGS[arch]}, llvm::StringLiteral("{function}"), {frame}}},')


if __name__ == "__main__":
    main()
