#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""Derive exp64's constants with mpmath and render aie_kernels/sample/exp64_table.h.

exp64 (aie_kernels/sample/exp64.h) is exp(x) = 2^(k/N) * exp(r), with a
2^(j/N) table of N = 128 entries and a degree-5 Taylor polynomial for exp(r),
|r| <= ln2/(2N). The header is the one copy of every constant: the core
compiles it, and the numpy port (``aie.iron.kernels.sample.exp64_ref``) reads
it. ``--check`` verifies that the committed header is current.

Needs ``mpmath``, which nothing else in the build does; the header is
committed, so only a change to the derivation reruns this.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path

import mpmath
import numpy as np

HEADER = (
    Path(__file__).resolve().parents[1] / "aie_kernels" / "sample" / "exp64_table.h"
)

TABLE_BITS = 7
N = 1 << TABLE_BITS
# kd * NEG_LN2_HI_N must be exact for every |kd| < 2^18 (|x| < 1024 gives
# |kd| < 1024 * N / ln2 < 2^18), so the high part keeps 53 - 18 = 35 bits.
HI_BITS = 35

mpmath.mp.prec = 256


def round_to_double(x: mpmath.mpf) -> float:
    """x rounded to the nearest double, ties to even (Fraction -> float is exact RN)."""
    sign, man, exp, _ = mpmath.mpf(x)._mpf_
    value = Fraction(int(man)) * Fraction(2) ** int(exp)
    return float(-value if sign else value)


def round_to_bits(x: mpmath.mpf, bits: int) -> mpmath.mpf:
    """x rounded to ``bits`` significant bits."""
    e = int(mpmath.floor(mpmath.log(abs(x), 2)))
    quantum = mpmath.mpf(2) ** (e - bits + 1)
    return mpmath.nint(x / quantum) * quantum


def bits_of(x: float) -> int:
    return int(np.float64(x).view(np.uint64))


@dataclass(frozen=True)
class Exp64Constants:
    inv_ln2_n: float
    shift: float
    neg_ln2_hi_n: float
    neg_ln2_lo_n: float
    c2: float
    c3: float
    c4: float
    c5: float
    # table[2*i] = bits(tail_i); table[2*i + 1] = bits(T_i) - (i << (52 - TABLE_BITS)),
    # with 2^(i/N) ~= T_i * (1 + tail_i).
    table: tuple[int, ...]

    def scalars(self) -> dict[str, float]:
        return {
            "INV_LN2_N": self.inv_ln2_n,
            "SHIFT": self.shift,
            "NEG_LN2_HI_N": self.neg_ln2_hi_n,
            "NEG_LN2_LO_N": self.neg_ln2_lo_n,
            "C2": self.c2,
            "C3": self.c3,
            "C4": self.c4,
            "C5": self.c5,
        }


def derive() -> Exp64Constants:
    ln2 = mpmath.log(2)
    ln2_n = ln2 / N
    hi = round_to_bits(ln2_n, HI_BITS)
    assert round_to_double(hi) == hi, "the high part must be a double"
    table: list[int] = []
    for i in range(N):
        exact = mpmath.power(2, mpmath.mpf(i) / N)
        t = round_to_double(exact)
        tail = round_to_double((exact - mpmath.mpf(t)) / mpmath.mpf(t))
        table.append(bits_of(tail))
        table.append((bits_of(t) - (i << (52 - TABLE_BITS))) % (1 << 64))
    return Exp64Constants(
        inv_ln2_n=round_to_double(N / ln2),
        shift=float.fromhex("0x1.8p52"),
        neg_ln2_hi_n=-round_to_double(hi),
        neg_ln2_lo_n=-round_to_double(ln2_n - hi),
        c2=round_to_double(mpmath.mpf(1) / 2),
        c3=round_to_double(mpmath.mpf(1) / 6),
        c4=round_to_double(mpmath.mpf(1) / 24),
        c5=round_to_double(mpmath.mpf(1) / 120),
        table=tuple(table),
    )


def render_header(c: Exp64Constants) -> str:
    lines = [
        "//===- exp64_table.h --------------------------------------------*- C++ -*-===//",
        "//",
        "// Copyright (C) 2026 Advanced Micro Devices, Inc.",
        "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
        "// Generated by utils/generate_exp64_table.py; do not edit.",
        "",
        "#ifndef AIE_KERNELS_SAMPLE_EXP64_TABLE_H",
        "#define AIE_KERNELS_SAMPLE_EXP64_TABLE_H",
        "",
        "#include <stdint.h>",
        "",
        "// clang-format off",
        f"#define EXP64_TABLE_BITS {TABLE_BITS}",
        f"#define EXP64_N {N}",
        "",
    ]
    for name, value in c.scalars().items():
        lines.append(
            f"#define EXP64_{name} UINT64_C(0x{bits_of(value):016x}) // {value.hex()}"
        )
    lines += ["", "static const uint64_t exp64_table[2 * EXP64_N] = {"]
    for i in range(N):
        tail, t = c.table[2 * i], c.table[2 * i + 1]
        lines.append(f"    UINT64_C(0x{tail:016x}), UINT64_C(0x{t:016x}),")
    lines += ["};", "// clang-format on", "", "#endif", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write exp64_table.h")
    group.add_argument(
        "--check", action="store_true", help="check exp64_table.h is current"
    )
    args = parser.parse_args()
    text = render_header(derive())
    if args.write:
        HEADER.write_text(text)
        return 0
    if HEADER.read_text() != text:
        print(f"{HEADER} is stale; run with --write")
        return 1
    print(f"{HEADER} is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
