//===- LayoutPasses.td -------------------------------------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_PHY_DIALECT_LAYOUT_PASSES_TD
#define MLIR_PHY_DIALECT_LAYOUT_PASSES_TD

include "phy/Dialect/Layout/LayoutBase.td"

include "mlir/Pass/PassBase.td"

#endif  // MLIR_PHY_DIALECT_LAYOUT_PASSES_TD
