//===- dynamic_runtime_lock_scf_while.mlir --------------------*- MLIR -*-===//
//
// Copyright (C) 2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// Acquire/release inside an scf.while body. The runtime held-counter approach
// needs no loop peeling or trip-count reasoning: the counter lives across
// iterations, so the while body lowers directly with a value-carrying
// `AcquireGreaterEqual`. A post-loop release decrements the counter.

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=true" --canonicalize %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(npu2) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(0, 1)
// CHECK:           %[[VAL_1:.*]] = aie.tile(0, 2)
// CHECK:           %[[VAL_2:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo_cons_buff_0"} : memref<8xi8>
// CHECK:           %[[VAL_3:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo_cons_buff_1"} : memref<8xi8>
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo_cons_buff_2"} : memref<8xi8>
// CHECK:           %[[VAL_5:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "fifo_cons_buff_3"} : memref<8xi8>
// CHECK:           %[[VAL_6:.*]] = aie.lock(%[[VAL_1]], 0) {init = 4 : i32, sym_name = "fifo_cons_prod_lock_0"}
// CHECK:           %[[VAL_7:.*]] = aie.lock(%[[VAL_1]], 1) {init = 0 : i32, sym_name = "fifo_cons_cons_lock_0"}
// CHECK:           %[[VAL_8:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_0"} : memref<8xi8>
// CHECK:           %[[VAL_9:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_1"} : memref<8xi8>
// CHECK:           %[[VAL_10:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "fifo_buff_2"} : memref<8xi8>
// CHECK:           %[[VAL_11:.*]] = aie.lock(%[[VAL_0]], 0) {init = 3 : i32, sym_name = "fifo_prod_lock_0"}
// CHECK:           %[[VAL_12:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "fifo_cons_lock_0"}
// CHECK:           %[[VAL_13:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "buf"} : memref<1xindex>
// CHECK:           aie.flow(%[[VAL_0]], DMA : 0, %[[VAL_1]], DMA : 0)
// CHECK:           %[[VAL_14:.*]] = aie.core(%[[VAL_1]]) {
// CHECK:             %[[VAL_15:.*]] = arith.constant -3 : i32
// CHECK:             %[[VAL_16:.*]] = arith.constant 2 : i32
// CHECK:             %[[VAL_17:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_18:.*]] = arith.constant 3 : i32
// CHECK:             %[[VAL_19:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_20:.*]] = arith.constant 4 : i32
// CHECK:             %[[VAL_21:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_22:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_23:.*]] = arith.constant 14 : index
// CHECK:             %[[VAL_24:.*]]:3 = scf.while (%[[VAL_25:.*]] = %[[VAL_21]], %[[VAL_26:.*]] = %[[VAL_19]], %[[VAL_27:.*]] = %[[VAL_19]]) : (index, i32, i32) -> (index, i32, i32) {
// CHECK:               %[[VAL_28:.*]] = arith.cmpi slt, %[[VAL_25]], %[[VAL_23]] : index
// CHECK:               scf.condition(%[[VAL_28]]) %[[VAL_25]], %[[VAL_26]], %[[VAL_27]] : index, i32, i32
// CHECK:             } do {
// CHECK:             ^bb0(%[[VAL_29:.*]]: index, %[[VAL_30:.*]]: i32, %[[VAL_31:.*]]: i32):
// CHECK:               %[[VAL_32:.*]] = arith.subi %[[VAL_18]], %[[VAL_30]] : i32
// CHECK:               %[[VAL_33:.*]] = arith.maxsi %[[VAL_32]], %[[VAL_19]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_33]])
// CHECK:               %[[VAL_34:.*]] = arith.addi %[[VAL_30]], %[[VAL_33]] : i32
// CHECK:               aie.use_lock(%[[VAL_6]], Release, %[[VAL_17]])
// CHECK:               %[[VAL_35:.*]] = arith.subi %[[VAL_34]], %[[VAL_17]] : i32
// CHECK:               %[[VAL_36:.*]] = arith.addi %[[VAL_31]], %[[VAL_17]] : i32
// CHECK:               %[[VAL_37:.*]] = arith.cmpi sge, %[[VAL_36]], %[[VAL_20]] : i32
// CHECK:               %[[VAL_38:.*]] = arith.addi %[[VAL_31]], %[[VAL_15]] : i32
// CHECK:               %[[VAL_39:.*]] = arith.select %[[VAL_37]], %[[VAL_38]], %[[VAL_36]] : i32
// CHECK:               %[[VAL_40:.*]] = arith.addi %[[VAL_29]], %[[VAL_22]] : index
// CHECK:               scf.yield %[[VAL_40]], %[[VAL_35]], %[[VAL_39]] : index, i32, i32
// CHECK:             }
// CHECK:             memref.store %[[VAL_41:.*]]#0, %[[VAL_13]]{{\[}}%[[VAL_21]]] : memref<1xindex>
// CHECK:             aie.use_lock(%[[VAL_6]], Release, %[[VAL_16]])
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_42:.*]] = aie.memtile_dma(%[[VAL_0]]) {
// CHECK:             %[[VAL_43:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_44:.*]] = aie.dma_start(MM2S, 0, ^bb1, ^bb4)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_12]], AcquireGreaterEqual, %[[VAL_43]])
// CHECK:             aie.dma_bd(%[[VAL_8]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_11]], Release, %[[VAL_43]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_12]], AcquireGreaterEqual, %[[VAL_43]])
// CHECK:             aie.dma_bd(%[[VAL_9]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_11]], Release, %[[VAL_43]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_12]], AcquireGreaterEqual, %[[VAL_43]])
// CHECK:             aie.dma_bd(%[[VAL_10]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_11]], Release, %[[VAL_43]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb4:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_45:.*]] = aie.mem(%[[VAL_1]]) {
// CHECK:             %[[VAL_46:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_47:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb5)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_2]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_3]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_4]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb4:
// CHECK:             aie.use_lock(%[[VAL_6]], AcquireGreaterEqual, %[[VAL_46]])
// CHECK:             aie.dma_bd(%[[VAL_5]] : memref<8xi8>, 0, 8)
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_46]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb5:
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }

module {
  aie.device(npu2) {
    %tile_0_1 = aie.tile(0, 1)
    %tile_0_2 = aie.tile(0, 2)
    %buf = aie.buffer(%tile_0_2) {sym_name = "buf"} : memref<1xindex>

    aie.objectfifo @fifo(%tile_0_1, {%tile_0_2}, 3 : i32) : !aie.objectfifo<memref<8xi8>>

    %core_0_2 = aie.core(%tile_0_2) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %c14 = arith.constant 14 : index
      %r = scf.while (%arg0 = %c0) : (index) -> index {
        %cond = arith.cmpi slt, %arg0, %c14 : index
        scf.condition(%cond) %arg0 : index
      } do {
      ^bb0(%arg1: index):
        %x = aie.objectfifo.acquire @fifo(Consume, 3) : !aie.objectfifosubview<memref<8xi8>>
        aie.objectfifo.release @fifo(Consume, 1)
        %next = arith.addi %arg1, %c1 : index
        scf.yield %next : index
      }
      memref.store %r, %buf[%c0] : memref<1xindex>
      aie.objectfifo.release @fifo(Consume, 2)
      aie.end
    }
  }
}
