//===- repeat_count_test.mlir -----------------------------------*- MLIR -*-===//
//
// Copyright (C) 2024 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform %s | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(npu1) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(1, 1)
// CHECK:           %[[VAL_1:.*]] = aie.tile(1, 2)
// CHECK:           %[[VAL_2:.*]] = aie.tile(1, 3)
// CHECK:           %[[VAL_3:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "of1_cons_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_4:.*]] = aie.lock(%[[VAL_2]], 0) {init = 1 : i32, sym_name = "of1_cons_prod_lock_0"}
// CHECK:           %[[VAL_5:.*]] = aie.lock(%[[VAL_2]], 1) {init = 0 : i32, sym_name = "of1_cons_cons_lock_0"}
// CHECK:           %[[VAL_6:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "of1_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_7:.*]] = aie.lock(%[[VAL_1]], 2) {init = 3 : i32, sym_name = "of1_prod_lock_0"}
// CHECK:           %[[VAL_8:.*]] = aie.lock(%[[VAL_1]], 3) {init = 0 : i32, sym_name = "of1_cons_lock_0"}
// CHECK:           %[[VAL_9:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "of0_cons_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_10:.*]] = aie.lock(%[[VAL_1]], 0) {init = 1 : i32, sym_name = "of0_cons_prod_lock_0"}
// CHECK:           %[[VAL_11:.*]] = aie.lock(%[[VAL_1]], 1) {init = 0 : i32, sym_name = "of0_cons_cons_lock_0"}
// CHECK:           %[[VAL_12:.*]] = aie.buffer(%[[VAL_0]]) {sym_name = "of0_buff_0"} : memref<16xi32>
// CHECK:           %[[VAL_13:.*]] = aie.lock(%[[VAL_0]], 0) {init = 1 : i32, sym_name = "of0_prod_lock_0"}
// CHECK:           %[[VAL_14:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "of0_cons_lock_0"}
// CHECK:           aie.flow(%[[VAL_0]], DMA : 0, %[[VAL_1]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_1]], DMA : 0, %[[VAL_2]], DMA : 0)
// CHECK:           %[[VAL_15:.*]] = aie.core(%[[VAL_1]]) {
// CHECK:             %[[VAL_16:.*]] = arith.constant 0 : i32
// CHECK:             %[[VAL_17:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_18:.*]] = arith.constant 1 : index
// CHECK:             %[[VAL_19:.*]] = arith.constant 12 : index
// CHECK:             %[[VAL_20:.*]]:4 = scf.for %[[VAL_21:.*]] = %[[VAL_17]] to %[[VAL_19]] step %[[VAL_18]] iter_args(%[[VAL_22:.*]] = %[[VAL_16]], %[[VAL_23:.*]] = %[[VAL_16]], %[[VAL_24:.*]] = %[[VAL_16]], %[[VAL_25:.*]] = %[[VAL_16]]) -> (i32, i32, i32, i32) {
// CHECK:               %[[VAL_26:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_27:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_28:.*]] = arith.subi %[[VAL_26]], %[[VAL_24]] : i32
// CHECK:               %[[VAL_29:.*]] = arith.maxsi %[[VAL_28]], %[[VAL_27]] : i32
// CHECK:               aie.use_lock(%[[VAL_11]], AcquireGreaterEqual, %[[VAL_29]])
// CHECK:               %[[VAL_30:.*]] = arith.addi %[[VAL_24]], %[[VAL_29]] : i32
// CHECK:               %[[VAL_31:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_32:.*]] = arith.constant 0 : i32
// CHECK:               %[[VAL_33:.*]] = arith.subi %[[VAL_31]], %[[VAL_25]] : i32
// CHECK:               %[[VAL_34:.*]] = arith.maxsi %[[VAL_33]], %[[VAL_32]] : i32
// CHECK:               %[[VAL_35:.*]] = arith.constant 3 : i32
// CHECK:               %[[VAL_36:.*]] = arith.muli %[[VAL_34]], %[[VAL_35]] : i32
// CHECK:               aie.use_lock(%[[VAL_7]], AcquireGreaterEqual, %[[VAL_36]])
// CHECK:               %[[VAL_37:.*]] = arith.addi %[[VAL_25]], %[[VAL_36]] : i32
// CHECK:               %[[VAL_38:.*]] = arith.constant 3 : i32
// CHECK:               aie.use_lock(%[[VAL_8]], Release, %[[VAL_38]])
// CHECK:               %[[VAL_39:.*]] = arith.subi %[[VAL_37]], %[[VAL_38]] : i32
// CHECK:               %[[VAL_40:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_41:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_42:.*]] = arith.addi %[[VAL_23]], %[[VAL_41]] : i32
// CHECK:               %[[VAL_43:.*]] = arith.cmpi sge, %[[VAL_42]], %[[VAL_40]] : i32
// CHECK:               %[[VAL_44:.*]] = arith.subi %[[VAL_42]], %[[VAL_40]] : i32
// CHECK:               %[[VAL_45:.*]] = arith.select %[[VAL_43]], %[[VAL_44]], %[[VAL_42]] : i32
// CHECK:               %[[VAL_46:.*]] = arith.constant 1 : i32
// CHECK:               aie.use_lock(%[[VAL_10]], Release, %[[VAL_46]])
// CHECK:               %[[VAL_47:.*]] = arith.subi %[[VAL_30]], %[[VAL_46]] : i32
// CHECK:               %[[VAL_48:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_49:.*]] = arith.constant 1 : i32
// CHECK:               %[[VAL_50:.*]] = arith.addi %[[VAL_22]], %[[VAL_49]] : i32
// CHECK:               %[[VAL_51:.*]] = arith.cmpi sge, %[[VAL_50]], %[[VAL_48]] : i32
// CHECK:               %[[VAL_52:.*]] = arith.subi %[[VAL_50]], %[[VAL_48]] : i32
// CHECK:               %[[VAL_53:.*]] = arith.select %[[VAL_51]], %[[VAL_52]], %[[VAL_50]] : i32
// CHECK:               scf.yield %[[VAL_53]], %[[VAL_45]], %[[VAL_47]], %[[VAL_39]] : i32, i32, i32, i32
// CHECK:             } {aie.unroll_hint = 1 : i64}
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_54:.*]] = aie.memtile_dma(%[[VAL_0]]) {
// CHECK:             %[[VAL_55:.*]] = aie.dma_start(MM2S, 0, ^bb1, ^bb2)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_56:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_14]], AcquireGreaterEqual, %[[VAL_56]])
// CHECK:             aie.dma_bd(%[[VAL_12]] : memref<16xi32> offset = 0 len = 16)
// CHECK:             %[[VAL_57:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_57]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb2:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_58:.*]] = aie.mem(%[[VAL_1]]) {
// CHECK:             %[[VAL_59:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb2)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_60:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_10]], AcquireGreaterEqual, %[[VAL_60]])
// CHECK:             aie.dma_bd(%[[VAL_9]] : memref<16xi32> offset = 0 len = 16)
// CHECK:             %[[VAL_61:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_11]], Release, %[[VAL_61]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb2:
// CHECK:             %[[VAL_62:.*]] = aie.dma_start(MM2S, 0, ^bb3, ^bb4, repeat_count = 2)
// CHECK:           ^bb3:
// CHECK:             %[[VAL_63:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_63]])
// CHECK:             aie.dma_bd(%[[VAL_6]] : memref<16xi32> offset = 0 len = 16)
// CHECK:             %[[VAL_64:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_7]], Release, %[[VAL_64]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb4:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_65:.*]] = aie.mem(%[[VAL_2]]) {
// CHECK:             %[[VAL_66:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb2)
// CHECK:           ^bb1:
// CHECK:             %[[VAL_67:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_4]], AcquireGreaterEqual, %[[VAL_67]])
// CHECK:             aie.dma_bd(%[[VAL_3]] : memref<16xi32> offset = 0 len = 16)
// CHECK:             %[[VAL_68:.*]] = arith.constant 1 : i32
// CHECK:             aie.use_lock(%[[VAL_5]], Release, %[[VAL_68]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb2:
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }


module @repeatCount {
 aie.device(npu1) {
    %tile11 = aie.tile(1, 1)
    %tile12 = aie.tile(1, 2)
    %tile13 = aie.tile(1, 3)

    aie.objectfifo @of0 (%tile11, {%tile12}, 1 : i32) : !aie.objectfifo<memref<16xi32>>
    aie.objectfifo @of1 (%tile12, {%tile13}, 1 : i32) {repeat_count = 3 : i32} : !aie.objectfifo<memref<16xi32>>

    %core33 = aie.core(%tile12) {
      %c0 = arith.constant 0 : index
      %c1 = arith.constant 1 : index
      %height = arith.constant 12 : index

      scf.for %indexInHeight = %c0 to %height step %c1 {
         %subview0 = aie.objectfifo.acquire @of0 (Consume, 1) : !aie.objectfifosubview<memref<16xi32>>
         %subview1 = aie.objectfifo.acquire @of1 (Produce, 1) : !aie.objectfifosubview<memref<16xi32>>
         aie.objectfifo.release @of1 (Produce, 1)
         aie.objectfifo.release @of0 (Consume, 1)
      }

      aie.end
   }
 }
}
