//===- link_test_broadcast.mlir --------------------------------*- MLIR -*-===//
//
// Copyright (C) 2023 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Date: July 31st 2023
//
//===----------------------------------------------------------------------===//

// RUN: aie-opt --aie-objectFifo-stateful-transform="dynamic-objFifos=false" --aie-objectFifo-unroll %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK-LABEL:   aie.device(xcve2302) {
// CHECK:           %[[VAL_0:.*]] = aie.tile(0, 0)
// CHECK:           %[[VAL_1:.*]] = aie.tile(0, 1)
// CHECK:           %[[VAL_2:.*]] = aie.tile(0, 2)
// CHECK:           %[[VAL_3:.*]] = aie.tile(0, 3)
// CHECK:           %[[VAL_4:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "mem_out_cons_buff_0"} : memref<3000xi32>
// CHECK:           %[[VAL_5:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "mem_out_cons_buff_1"} : memref<3000xi32>
// CHECK:           %[[VAL_6:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "mem_out_cons_buff_2"} : memref<3000xi32>
// CHECK:           %[[VAL_7:.*]] = aie.buffer(%[[VAL_3]]) {sym_name = "mem_out_cons_buff_3"} : memref<3000xi32>
// CHECK:           %[[VAL_8:.*]] = aie.lock(%[[VAL_3]], 0) {init = 4 : i32, sym_name = "mem_out_cons_prod_lock_0"}
// CHECK:           %[[VAL_9:.*]] = aie.lock(%[[VAL_3]], 1) {init = 0 : i32, sym_name = "mem_out_cons_cons_lock_0"}
// CHECK:           %[[VAL_10:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "mem_in_0_cons_buff_0"} : memref<3000xi32>
// CHECK:           %[[VAL_11:.*]] = aie.buffer(%[[VAL_2]]) {sym_name = "mem_in_0_cons_buff_1"} : memref<3000xi32>
// CHECK:           %[[VAL_12:.*]] = aie.lock(%[[VAL_2]], 0) {init = 2 : i32, sym_name = "mem_in_0_cons_prod_lock_0"}
// CHECK:           %[[VAL_13:.*]] = aie.lock(%[[VAL_2]], 1) {init = 0 : i32, sym_name = "mem_in_0_cons_cons_lock_0"}
// CHECK:           %[[VAL_14:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_0"} : memref<3000xi32>
// CHECK:           %[[VAL_15:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_1"} : memref<3000xi32>
// CHECK:           %[[VAL_16:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_2"} : memref<3000xi32>
// CHECK:           %[[VAL_17:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_3"} : memref<3000xi32>
// CHECK:           %[[VAL_18:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_4"} : memref<3000xi32>
// CHECK:           %[[VAL_19:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_5"} : memref<3000xi32>
// CHECK:           %[[VAL_20:.*]] = aie.buffer(%[[VAL_1]]) {sym_name = "mem_in_1_cons_buff_6"} : memref<3000xi32>
// CHECK:           %[[VAL_21:.*]] = aie.lock(%[[VAL_1]], 0) {init = 7 : i32, sym_name = "mem_in_1_cons_prod_lock_0"}
// CHECK:           %[[VAL_22:.*]] = aie.lock(%[[VAL_1]], 1) {init = 0 : i32, sym_name = "mem_in_1_cons_cons_lock_0"}
// CHECK:           %[[VAL_23:.*]] = aie.lock(%[[VAL_0]], 0) {init = 0 : i32, sym_name = "mem_in_prod_lock_0"}
// CHECK:           %[[VAL_24:.*]] = aie.lock(%[[VAL_0]], 1) {init = 0 : i32, sym_name = "mem_in_cons_lock_0"}
// CHECK:           aie.flow(%[[VAL_0]], DMA : 0, %[[VAL_1]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_0]], DMA : 0, %[[VAL_2]], DMA : 0)
// CHECK:           aie.flow(%[[VAL_1]], DMA : 0, %[[VAL_3]], DMA : 0)
// CHECK:           %[[VAL_25:.*]] = aie.core(%[[VAL_2]]) {
// CHECK:             %[[VAL_26:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_27:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_28:.*]] = arith.constant 11 : i32
// CHECK:             aie.use_lock(%[[VAL_13]], AcquireGreaterEqual, %[[VAL_26]])
// CHECK:             memref.store %[[VAL_28]], %[[VAL_10]]{{\[}}%[[VAL_27]]] : memref<3000xi32>
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_29:.*]] = aie.core(%[[VAL_3]]) {
// CHECK:             %[[VAL_30:.*]] = arith.constant 3 : i32
// CHECK:             %[[VAL_31:.*]] = arith.constant 0 : index
// CHECK:             %[[VAL_32:.*]] = arith.constant 11 : i32
// CHECK:             aie.use_lock(%[[VAL_9]], AcquireGreaterEqual, %[[VAL_30]])
// CHECK:             memref.store %[[VAL_32]], %[[VAL_4]]{{\[}}%[[VAL_31]]] : memref<3000xi32>
// CHECK:             aie.end
// CHECK:           }
// CHECK:           aie.shim_dma_allocation @mem_in_shim_alloc(%[[VAL_0]], MM2S, 0)
// CHECK:           %[[VAL_33:.*]] = aie.mem(%[[VAL_2]]) {
// CHECK:             %[[VAL_34:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_35:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb3)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_12]], AcquireGreaterEqual, %[[VAL_34]])
// CHECK:             aie.dma_bd(%[[VAL_10]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_34]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_12]], AcquireGreaterEqual, %[[VAL_34]])
// CHECK:             aie.dma_bd(%[[VAL_11]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_13]], Release, %[[VAL_34]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb3:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_36:.*]] = aie.memtile_dma(%[[VAL_1]]) {
// CHECK:             %[[VAL_37:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_38:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb8)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_14]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_15]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_16]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb4:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_17]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb5
// CHECK:           ^bb5:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_18]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb6
// CHECK:           ^bb6:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_19]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb7
// CHECK:           ^bb7:
// CHECK:             aie.use_lock(%[[VAL_21]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_20]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_22]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb8:
// CHECK:             %[[VAL_39:.*]] = aie.dma_start(MM2S, 0, ^bb9, ^bb16)
// CHECK:           ^bb9:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_14]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb10
// CHECK:           ^bb10:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_15]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb11
// CHECK:           ^bb11:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_16]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb12
// CHECK:           ^bb12:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_17]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb13
// CHECK:           ^bb13:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_18]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb14
// CHECK:           ^bb14:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_19]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb15
// CHECK:           ^bb15:
// CHECK:             aie.use_lock(%[[VAL_22]], AcquireGreaterEqual, %[[VAL_37]])
// CHECK:             aie.dma_bd(%[[VAL_20]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_21]], Release, %[[VAL_37]])
// CHECK:             aie.next_bd ^bb9
// CHECK:           ^bb16:
// CHECK:             aie.end
// CHECK:           }
// CHECK:           %[[VAL_40:.*]] = aie.mem(%[[VAL_3]]) {
// CHECK:             %[[VAL_41:.*]] = arith.constant 1 : i32
// CHECK:             %[[VAL_42:.*]] = aie.dma_start(S2MM, 0, ^bb1, ^bb5)
// CHECK:           ^bb1:
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_41]])
// CHECK:             aie.dma_bd(%[[VAL_4]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_41]])
// CHECK:             aie.next_bd ^bb2
// CHECK:           ^bb2:
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_41]])
// CHECK:             aie.dma_bd(%[[VAL_5]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_41]])
// CHECK:             aie.next_bd ^bb3
// CHECK:           ^bb3:
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_41]])
// CHECK:             aie.dma_bd(%[[VAL_6]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_41]])
// CHECK:             aie.next_bd ^bb4
// CHECK:           ^bb4:
// CHECK:             aie.use_lock(%[[VAL_8]], AcquireGreaterEqual, %[[VAL_41]])
// CHECK:             aie.dma_bd(%[[VAL_7]] : memref<3000xi32> offset = 0 len = 3000)
// CHECK:             aie.use_lock(%[[VAL_9]], Release, %[[VAL_41]])
// CHECK:             aie.next_bd ^bb1
// CHECK:           ^bb5:
// CHECK:             aie.end
// CHECK:           }
// CHECK:         }


module @link_test_broadcast {
    aie.device(xcve2302) {
        %tile00 = aie.tile(0, 0)
        %tile01 = aie.tile(0, 1)
        %tile02 = aie.tile(0, 2)
        %tile03 = aie.tile(0, 3)

        aie.objectfifo @mem_in (%tile00, {%tile02, %tile01}, [2,2,7]) : !aie.objectfifo<memref<3000xi32>>
        aie.objectfifo @mem_out (%tile01, {%tile03}, 7 : i32) : !aie.objectfifo<memref<3000xi32>>
        aie.objectfifo.link [@mem_in] -> [@mem_out] ([] [])

        %core02 = aie.core(%tile02) {
            %v11 = arith.constant 11 : i32
            %c0 = arith.constant 0 : index

            %subview = aie.objectfifo.acquire @mem_in (Consume, 1) : !aie.objectfifosubview<memref<3000xi32>>
            %subview_obj = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<3000xi32>> -> memref<3000xi32>
            memref.store %v11, %subview_obj[%c0] : memref<3000xi32>
            aie.end
        }

        %core03 = aie.core(%tile03) {
            %v11 = arith.constant 11 : i32
            %c0 = arith.constant 0 : index

            %subview = aie.objectfifo.acquire @mem_out (Consume, 3) : !aie.objectfifosubview<memref<3000xi32>>
            %subview_obj = aie.objectfifo.subview.access %subview[0] : !aie.objectfifosubview<memref<3000xi32>> -> memref<3000xi32>
            memref.store %v11, %subview_obj[%c0] : memref<3000xi32>
            aie.end
        }
    }
}
