# dma_slice_memcpy/objectfifo.py -*- Python -*-
#
# Copyright (C) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
"""Slice-addressed DDR -> tile -> DDR, via ObjectFifo.

The same dataflow as tile_dma.py, one level up. The slice is said the same way;
what differs is that the staging tile's buffers, locks, DMA channels and routes
are generated by `forward()` rather than written out.

Placement stays the caller's: the same tile, and every hardware DMA channel
pinned, so both designs put the same things in the same places. What ObjectFifo
does not expose is lock identity -- the generated locks take whatever ids the
lowering assigns -- and buffer bank/address, which `iron.Buffer` can pin and an
ObjectFifo's buffer pool cannot.
"""

import aie.iron as iron
import numpy as np
from aie.iron import CompileTime, In, ObjectFifo, Out, Program, Runtime
from aie.iron.device import Tile
from harness import main


@iron.jit
def dma_slice_memcpy(a_in: In, c_out: Out, *, col: CompileTime[int] = 0):
    tile = Tile(col, 5)
    shim = Tile(col, 0)

    # One innermost run of the slice at a time, double-buffered: a chunk can
    # arrive while the previous one leaves. tile_dma.py's single buffer
    # serializes the two, and depth is the knob that buys the overlap.
    chunk = np.ndarray[(512,), np.dtype[np.int8]]
    into_tile = ObjectFifo(chunk, depth=2, name="into_tile")
    out_of_tile = into_tile.cons(channel=0).forward(
        tile=tile, channel=0, name="out_of_tile"
    )

    def sequence(a, c, fill_from, drain_to):
        fill_from.fill(a, tap=a[0::2, 1::2, ...])
        drain_to.drain(c, tap=c[...], wait=True)

    rt = Runtime(
        sequence,
        [
            np.ndarray[(16, 16, 512), np.dtype[np.int8]],
            np.ndarray[(8, 8, 512), np.dtype[np.int8]],
            # The Runtime discovers fifos from fn_args, not from the fill/drain
            # verbs -- the body runs after fifo collection -- so the handles
            # have to be passed through. The shim end is pinned here too.
            into_tile.prod(tile=shim, channel=0),
            out_of_tile.cons(tile=shim, channel=0),
        ],
    )

    return Program(iron.get_current_device(), rt).resolve_program()


if __name__ == "__main__":
    main(
        "AIE DMA Slice Memcpy (ObjectFifo)",
        dma_slice_memcpy,
        shape=(16, 16, 512),
        dtype=np.int8,
        key=np.s_[0::2, 1::2, ...],
    )
